### ISSUE TITLE
Support changed files outside editor on `didChangeWatchedFiles` (especially git branch switch)

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#1002]
LSP method `didChangeWatchedFiles` has 3 types: `created`, `changed` and `deleted`, warning on a file was changed outside editor, for example on git branch changes.

We already support `created` and `deleted`, removing/adding from db when a file is deleted/created outside the editor, but we don't support the `changed` state on purpose. I tried to add support for that some time ago and found multiple performance issues which caused lots of issues on multiple editors, especially related to the unused-public-var linter, so I disabled that since then.

I think clojure-lsp is way stable now and I'd like to re-introduce this feature under a feature flag.

https://github.com/clojure-lsp/clojure-lsp/blob/master/lib/src/clojure_lsp/feature/file_management.clj#L222

**Comment by ericdallo** [comment]
FYI @snoe @mainej

**Comment by mainej** [comment]
I agree, this is an important fix. Just today I switched branches and noticed that the analysis and diagnostics for several files was out-of-date. I think turning `changed` back on might fix that. I still worry about performance problems, but I think it's worth finding out. If there are problems we can research why and at worst engineer some sort of batching. I say go for it!

**Comment by ericdallo** [comment]
I did some tests and it seems to be working nice, still I have some concerns regarding different clients, since I saw that some of them send a bunch of changed files notifications (Emacs) while others send a single batch (Vscode), this is probably not a issue, but since we had performance/outdated analysis issues in the past, it'd be nice to others validate as well.

Pinging people that may be interested in testing this new feature @mainej @PEZ @bpringe @Cyrik @borkdude, it's possible to test it via #clojure-lsp-builds
