### ISSUE TITLE
feat: Remove `:async-custom-lint?`

### ISSUE THREAD

**Issue by mainej** [clojure-lsp/clojure-lsp#1017]
I propose that the `:async-custom-lint?` setting be removed.

## History

In November '21, an optional featured dubbed "async custom linting" was introduced to address performance problems with custom linting (for unused-public-var). If the feature was turned on, custom linting happened in the background after analysis, so that other features like semantic tokens and symbol highlight could run before the custom lint was finished.

When the feature was introduced it defaulted to off. It was defaulted to on in December '21.

Performance improvements in #861 in mid March '22 meant that custom linting became much faster. 

Following this, in late March '22 the async lint of the full project was removed 76c1bf59d79cc4ade0377e855df39eb2ea67e06f. Async lint remained as a feature for individual files, though it was defaulted to off 45cb47aa17194a9d9df8ff8053bbab5c9c9e8861. (`doc/settings.md` still reports otherwise.)

#892 and #895 in late March and early April improved performance further.

## Problems

This feature has caused a few problems over its life. It introduced a scenario where clojure-lsp could get caught in an infinite loop #796. It's also been implicated in situations where the lint gets out of sync with the analysis, e.g. 45cb47aa17194a9d9df8ff8053bbab5c9c9e8861. I believe both of these are evidence of a common thread—it's hard to get async code right.

Further work on this feature is difficult because it doesn't have tests. Personally, I find it very tricky to reason about.

## Impact

A search of GitHub turns up only [one](https://github.com/yqrashawn/yqdotfiles/blob/6a07f2fc0b896fc2fb3281ab0eea03a316585d1a/modules/yqrashawn/home-manager/dotfiles/lsp.edn#L11) public repository which uses async custom linting, in a user's dotfiles. 

The only other public usage I see is [here](https://github.com/NoahTheDuke/coc-clojure/blob/cd4905187387bbae3631a9c0795dd9b99d6ea6c4/package.json#L157-L160) in COC. /cc @NoahTheDuke I'm not sure how removing this setting would impact COC.

## Proposal

Remove the async path from custom linting. Remove the setting. Update the docs.

**Comment by NoahTheDuke** [comment]
I don't think it would impact Coc-clojure. I only included that setting to allow for full configuration of clojure-lsp within coc.nvim's built-in configuration system.

**Comment by mainej** [comment]
I don't want to open a separate bug if we're going to remove async-custom-lint, but I'll add a note here... If we decide to keep async-custom-lint for some reason, it should be researched for a potential bug:

It's passed file analysis by clj-kondo. It merges that analysis with the rest of the analysis from the db, names it `updated-analysis`, and then starts sleeping. It sleeps until it gets notification that that file's analysis has successfully been merged into the db. For linting it uses the `updated-analysis`. But that ignores the possibility that while it was sleeping other analysis was also merged into the db. So, it's using potentially outdated analysis. It should instead deref the db after it finishes sleeping and use its analysis. That analysis is supposed to contain the file's analysis, but will also contain any other analysis and findings that have been merged in the meantime.

This is an example of a fix that's hard to check because there aren't any tests.

**Comment by ericdallo** [comment]
Looks good, I'm ok on removing it

> A search of GitHub turns up only [one](https://github.com/yqrashawn/yqdotfiles/blob/6a07f2fc0b896fc2fb3281ab0eea03a316585d1a/modules/yqrashawn/home-manager/dotfiles/lsp.edn#L11) public repository which uses async custom linting, in a user's dotfiles.

FYI @yqrashawn

**Comment by mainej** [comment]
🎉
