### ISSUE TITLE
performance: `notify-references` could skip analysis

### ISSUE THREAD

**Issue by mainej** [clojure-lsp/clojure-lsp#1027]
**Describe the bug**
When we call `notify-references`, we don't expect that the reference files' contents have changed, only that their lint may have changed. This needs verification. It's possible that the analysis _does_ actually change, even if the contents don't change. And it needs confirmation that it improves performance. If either assumption is wrong, we can leave it as is.

**Comment by ericdallo** [comment]
@mainej I remembered something that will be outdated but not sure it should be relevant.
`var-usages` have a `:fixed-arities` that could be outdated if changed the arity of the var-definition, although quick grepping I don't see we using that from a var-usage anywhere.

**Comment by mainej** [comment]
Closing in favor of #1028
