### ISSUE TITLE
On shutdown request, client receives {} instead of expected null

### ISSUE THREAD

**Issue by Ekopalypse** [clojure-lsp/clojure-lsp#1031]
I am creating an lsp client for Notepad++ and found an issue(?) when exiting the Clojure lsp server.
The response from clojure-lsp is

~~~
{"jsonrpc":"2.0","id":9,"result":{}}
~~~

where I would have expected

~~~
{"jsonrpc":"2.0","id":9,"result":null}
~~~

Using the native binary (clojure-lsp-native-windows-amd64.zip) from 2022.05.31-17.35.50

Am I wrong in my assumption?

**Comment by ericdallo** [comment]
Oh, not really. I think we can fix it on clojure-lsp side

**Comment by ericdallo** [comment]
Fixed on master b911b673

**Comment by Ekopalypse** [comment]
@ericdallo - thanks for the quick fix. You're right, my client doesn't really care, it's just logged. It's more that I think ... hmm ... did I misunderstand something? :-)

**Comment by ericdallo** [comment]
It's probably ok so
