### ISSUE TITLE
refactor: drag should emit two edits

### ISSUE THREAD

**Issue by mainej** [clojure-lsp/clojure-lsp#1043]
Currently when you drag, clojure-lsp sends the editors a single edit, which includes the swapped clauses and their intervening whitespace.

There's a chance that editors would be able to preserve semantic tokens, preventing flicker, if the change was returned as two edits, one for each clause, leaving the intervening whitespace alone. I don't think it's very likely to help, but it wouldn't hurt to try and it might make the code slightly clearer.

**Comment by ericdallo** [comment]
Yes, I think it's worth the try, but not sure how to compare semantic tokens change other than visually

**Comment by mainej** [comment]
> not sure how to compare semantic tokens change other than visually

Yeah, I think that's the only way. And it'll be different in different editors. But even if it doesn't help flicker at all, the change will make the code a little easier to follow, so I think it's a good fix anyway.
