### ISSUE TITLE
clean-ns sorts reader conditionals in an odd way

### ISSUE THREAD

**Issue by lassemaatta** [clojure-lsp/clojure-lsp#1057]
**Describe the bug**
If the `:require` form of a `:ns` declaration contains libraries wrapped in a reader conditional, `lsp-clojure-clean-ns` (or the corresponding Code Action, or the CLI command) sort the `:require` contents in an odd way.

**To Reproduce**

Given a mock namespace

```clojure
(ns some-namespace
  ;; Imagine a-z are some random libraries we need to require
  ;; Run `lsp-clojure-clean-ns` or the corresponding code action to sort this
  (:require #?(:clj [some-clojure-ns])
            #?(:cljs [some-cljs-ns])
            #?@(:clj [[foo bar]]
                :cljs [[quuz zed]])
            [a]
            [b]
            [c]
            [d]
            [e]
            [f]
            [g]
            [h]
            [i]
            [j]
            [k]
            [l]
            [m]
            [n]
            [o]
            [p]
            [q]
            [r]
            [s]
            [t]
            [u]
            [x]
            [y]
            [z]))
```
Run `clean-ns`, which results in:

```clojure
(ns some-namespace
  ;; Imagine a-z are some random libraries we need to require
  ;; Run `lsp-clojure-clean-ns` or the corresponding code action to sort this
  (:require [a]
            [b]
            [c]
            [d]
            [e]
            [f]
            [g]
            [h]
            [i]
            [j]
            [k]
            [l]
            [m]
            [n]
            [o]
            [p]
            [q]
            [r]
            #?(:clj [some-clojure-ns])
            #?(:cljs [some-cljs-ns])
            #?@(:clj [[foo bar]]
                :cljs [[quuz zed]])
            [s]
            [t]
            [u]
            [x]
            [y]
            [z]))

```
**Expected behavior**

I would expect that the entries with reader conditionals would be at the top. At least in most projects I've seen those entries are first, then followed by the non-reader conditional entries. 

I'm not sure if the sorting should look within the conditionals, as it might be difficult to decide which entry comes first (should `#?(:cljs [foo.a])` come before  `#?(:clj [foo.b])` and what about `#?@(:clj [[foo.d foo.f]] :cljs [[foo.c foo.e]])` etc). Perhaps it's easier and better to just retain their original order with respect to each other.

**User details (please complete the following information):**
 - OS: Arch linux
 - Editor: `GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6) of 2022-04-28`
 - Version: `clojure-lsp 2022.06.17-15.19.25-nightly clj-kondo 2022.05.31`

**Comment by lassemaatta** [comment]
Related [discussion](https://clojurians.slack.com/archives/CPABC1H61/p1654235241117589) from clojurians slack.

**Comment by ericdallo** [comment]
The issue is that we are soring the requires inside reader conditionals as if they were not in reader conditionals, I think we can move then before normal requires and that would be enough

**Comment by ericdallo** [comment]
@lassemaatta, I made we move reader conditionals before normal requires without sorting what is inside it since there are too many cases to handle, we can wait to see if that is an issue for most people.
