### ISSUE TITLE
clojure-lsp silently stops working in calva after a while

### ISSUE THREAD

**Issue by calherries** [clojure-lsp/clojure-lsp#1080]
Note: duplicated issue in calva repo: https://github.com/BetterThanTomorrow/calva/issues/1782

**Describe the bug**
After about 10 minutes after starting clojure-lsp and using the editor, it’s functionality in the editor stops. I can solve it temporarily by restarting clojure-lsp, but it soon fails again.

The issue persists after disconnecting with the REPL.

Things that stop working:
- Any new syntax errors I create in the editor aren’t underlined with linting errors (existing ones before it stops working persist)
- Any new errors I create aren’t showing in the “Problems” tab (but existing ones persist)
- Go to definition
- All code navigation and refactoring commands

Things that are still working:

The clojure-lsp log file still logs handlers, publishing diagnostics, etc. If I intentionally create a syntax error I can see the logs update with a correctly updated “Publishing X diagnostics” message
```
2022-06-24T09:45:14.936Z DEBUG [clojure-lsp.server:82] - Publishing 11 diagnostics for file:///Users/callumherries/meta/metabase/src/metabase/query_processor/card.clj
```
VS code still shows clojure-lsp as working, and when I click the button, it shows the relevant quick actions.

**To Reproduce**
It happens reliably on my machine after jumping between files, definitions, etc., so I don’t know the specific cause. I haven’t tried with a minimal example but it happens while I’ve been working on https://github.com/metabase/metabase, which is open source.

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
[Trace - 10:23:59 PM] Sending notification '$/cancelRequest'.
Params: {
    "id": 808
}

Jun 24, 2022 10:23:59 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 808
[Trace - 10:23:59 PM] Sending request 'textDocument/codeAction - (809)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/callumherries/meta/metabase/src/metabase/query_processor/card.clj"
    },
    "range": {
        "start": {
            "line": 249,
            "character": 23
        },
        "end": {
            "line": 249,
            "character": 23
        }
    },
    "context": {
        "diagnostics": []
    }
}

[Trace - 10:23:59 PM] Sending notification '$/cancelRequest'.
Params: {
    "id": 807
}

Jun 24, 2022 10:23:59 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 807
[Trace - 10:24:16 PM] Sending request 'textDocument/codeAction - (810)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/callumherries/meta/metabase/src/metabase/query_processor/card.clj"
    },
    "range": {
        "start": {
            "line": 249,
            "character": 19
        },
        "end": {
            "line": 249,
            "character": 19
        }
    },
    "context": {
        "diagnostics": []
    }
}

[Trace - 10:24:16 PM] Sending notification '$/cancelRequest'.
Params: {
    "id": 809
}

Jun 24, 2022 10:24:16 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 809
[Trace - 10:24:16 PM] Sending notification '$/cancelRequest'.
Params: {
    "id": 805
}

[Trace - 10:24:16 PM] Sending request 'textDocument/documentHighlight - (811)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/callumherries/meta/metabase/src/metabase/query_processor/card.clj"
    },
    "position": {
        "line": 248,
        "character": 19
    }
}

Jun 24, 2022 10:24:16 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 805
[Trace - 10:24:16 PM] Sending request 'textDocument/codeAction - (812)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/callumherries/meta/metabase/src/metabase/query_processor/card.clj"
    },
    "range": {
        "start": {
            "line": 248,
            "character": 19
        },
        "end": {
            "line": 248,
            "character": 19
        }
    },
    "context": {
        "diagnostics": []
    }
}

[Trace - 10:24:16 PM] Sending notification '$/cancelRequest'.
Params: {
    "id": 810
}

Jun 24, 2022 10:24:16 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 810
[Trace - 10:24:16 PM] Sending request 'textDocument/definition - (813)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/callumherries/meta/metabase/src/metabase/query_processor/card.clj"
    },
    "position": {
        "line": 248,
        "character": 19
    }
}

</pre>
</details>

**User details (please complete the following information):**
 - OS: MacOS
 - Editor VSCode (Calva) (version from 13/6/2022, 17:40:41)
 - Version: 2022.06.22-14.09.50

**Comment by ericdallo** [comment]
Probably related with #1058 c/c @mainej, it seems we indeed have some freezing somewhere, we should prioritize this fix

**Comment by ericdallo** [comment]
@calherries it seems your client<->server logs are cropped, could you try getting full logs since `initialize` request?
