### ISSUE TITLE
"Resolve macro as" does not work in this particular case (at least in Calva)

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#1084]
**Describe the bug**
In Calva, with the cursor inside `deftest` but after the `t`, when "resolve macro as" is run, an error occurs: `No macro was found at cursor to resolve as 'clojure.core/def'.`

**Expected behavior**
The chosen config file should be updated according to the choice made about which macro to resolve the macro at cursor as.

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
[Trace - 1:57:12 PM] Sending request 'workspace/executeCommand - (31)'.
Params: {
    "command": "resolve-macro-as",
    "arguments": [
        "file:///Users/brandon/development/clojure-test/test/core_test.clj",
        4,
        6
    ]
}

[Trace - 1:57:12 PM] Received response 'workspace/executeCommand - (31)' in 1ms.
No result returned.

[Trace - 1:57:12 PM] Received request 'window/showMessageRequest - (4)'.
Params: {
    "actions": [
        {
            "title": "clojure.core/def"
        },
        {
            "title": "clojure.core/defn"
        },
        {
            "title": "clojure.core/let"
        },
        {
            "title": "clojure.core/for"
        },
        {
            "title": "clojure.core/->"
        },
        {
            "title": "clojure.core/->>"
        },
        {
            "title": "clj-kondo.lint-as/def-catch-all"
        }
    ],
    "type": 3,
    "message": "Select how LSP should resolve this macro:"
}

[Trace - 1:57:13 PM] Sending response 'window/showMessageRequest - (4)'. Processing request took 986ms
Result: {
    "title": "clojure.core/def"
}

[Trace - 1:57:13 PM] Received request 'window/showMessageRequest - (5)'.
Params: {
    "actions": [
        {
            "title": "/Users/brandon/development/clojure-test/.clj-kondo/config.edn"
        },
        {
            "title": "/Users/brandon/.config/clj-kondo/config.edn"
        }
    ],
    "type": 3,
    "message": "Select where LSP should save this setting:"
}

[Trace - 1:57:14 PM] Sending response 'window/showMessageRequest - (5)'. Processing request took 987ms
Result: {
    "title": "/Users/brandon/development/clojure-test/.clj-kondo/config.edn"
}
</pre>
</details>

<details>
 <summary><b>Log - clojure-lsp</b></summary>
<pre>
2022-06-29T21:01:16.509Z  INFO [clojure-lsp.handlers:252] - :document-highlight 0ms
2022-06-29T21:01:16.511Z  INFO [clojure-lsp.handlers:405] - :code-actions 2ms
2022-06-29T21:01:16.750Z  INFO [clojure-lsp.handlers:405] - :code-actions 19ms
2022-06-29T21:01:22.287Z  ERROR [clojure-lsp.feature.resolve-macro:85] - Could not resolve macro at cursor to be resolved as 'clojure.core/def' for path '/Users/brandon/development/clojure-test/.clj-kondo/config.edn'
2022-06-29T21:01:22.289Z  INFO [lsp4clj.core:445] - {:message "No macro was found at cursor to resolve as 'clojure.core/def'.", :type :error, :extra nil}
2022-06-29T21:01:22.292Z  INFO [clojure-lsp.handlers:356] - :execute-command 2639ms
</pre>
</details>

**User details (please complete the following information):**
 - OS: MacOS
 - Editor: VSCode (Calva)
 - Version: [2022.05.31-17.35.50](https://github.com/clojure-lsp/clojure-lsp/releases/tag/2022.05.31-17.35.50)

**Additional context**
Slack conversation: https://clojurians.slack.com/archives/CBE668G4R/p1656262855445719

**Comment by ericdallo** [comment]
We should improve this refactor to find the macro a little bit more smart than getting current point

**Comment by jgracin** [comment]
Hi! I think the following PR should fix the problem: https://github.com/clojure-lsp/clojure-lsp/pull/1179.

**Comment by ericdallo** [comment]
@jgracin I don't think #1179 is the correct fix, this will only solve for this case:
```clojure
(deftest| my-macro
```

But not for 
```clojure
(deftest my-m|acro
```

We should get the function caller in this row and not the cursor at row and col

**Comment by ericdallo** [comment]
Actually you were right @jgracin :)
Merged, thanks for the help!
