### ISSUE TITLE
Add new command to turn a keyword alias its expanded keyword form

### ISSUE THREAD

**Issue by mpenet** [clojure-lsp/clojure-lsp#1128]
This proposal is to add a command that turns `::baz` type keyword aliases to their expanded form, as in `:foo.bar/baz`. 

That could also be considered as a code action. 
An extra command that does that for an entire namespace might also make sense.

**Comment by ericdallo** [comment]
@mpenet I'm considering some options:
- a command called `cycle-keyword-namespace-alias` (`c k` for the mnemonic), which would cycle between aliased namespaced keywords to namespaced keywords
- The command could ask to user after executed if they want to change all namespaced places that is using that notation to changed as well
- or we do the same question but only for that namespace

WDYT?

**Comment by mpenet** [comment]
That sounds good. 

There are multiple possible scopes: 

* change only the instance of keyword at point
* change all occurences in current namespace
* change all occurences in whole project
(* change all keywords in whole project) - I'd love that, but that might be overkill for most people.

**Comment by ericdallo** [comment]
yeah, I think we can start with the first 2

**Comment by ericdallo** [comment]
Done!
![cycle-keyword-auto-resolve](https://user-images.githubusercontent.com/7820865/204365409-7dd657c5-0bc9-4754-9fdf-5127dfac40f1.gif)
