### ISSUE TITLE
Classpath lookup failure error with Calva on MS-Windows

### ISSUE THREAD

**Issue by ikappaki** [clojure-lsp/clojure-lsp#1132]
**Describe the bug**
Calva throws an error message when loading Clojure-lsp up on MS-Windows:

```
Classpath lookup failed when running `push -NoProfile -Command ...`
```

**To Reproduce**
On a stock Windows environment that comes with standard PowerShell 5.1 version and does not have any newer PowerShell version installed.

1. Open Calva in Visual Studio Code.
2. Open a workspace with an empty deps.edn file (or any other type of Clojure project file).
3. The above error will popup in Visual Studio Code.

**Expected behavior**
There should be no error message popping up.

**User details (please complete the following information):**
 - OS: Windows 10
 - Editor VSCode (Calva)
 - Version: latest calva update

**Additional context**
There has been a recent change with #976 that appears to have forced all external program invocations on MS-Windows to go via the `pwsh` command which is only available with the latest version of PowerShell, but does not come with any MS-Windows version preinstalled.

The error is thrown when trying to scan the class path.

This is likely to occur with any editor, but I do not know how to run clojure-lsp standalone.

PR to follow.

**Comment by ericdallo** [comment]
Thanks @ikappaki, I'm no windows users but if you know a better way to handle that the PR is welcome
