### ISSUE TITLE
Adjust percent done indicator for uncached startup

### ISSUE THREAD

**Issue by mainej** [clojure-lsp/clojure-lsp#1134]
**Is your feature request related to a problem? Please describe.**
The "percent done" indicator doesn't feel very smooth when running uncached startup. It quickly gets to 80%, but then slows down while clojure-lsp does its internal analysis.

The reason is that the percent done values weren't adjusted after #950, which reduced the time analyzing dependencies by 60-70%. We still allocate 50% of uncached startup to dependency analysis, and only 20% to project analysis:

```
0   clojure-lsp
5   Finding kondo config
10  Finding cache
15  Discovering classpath
20  Copying kondo configs
25  Analyzing external classpath
75  Resolving config paths
80  Analyzing project files
100 Project analyzed
```

**Describe the solution you'd like**
I propose we swap the allocations—giving 20% to external analysis and 50% to project analysis.
```
0   clojure-lsp
5   Finding kondo config
10  Finding cache
15  Discovering classpath
20  Copying kondo configs
25  Analyzing external classpath
45  Resolving config paths
50  Analyzing project files
100 Project analyzed
```

**Describe alternatives you've considered**
Other percentages are possible. We could do a more detailed analysis of how long each step takes. If we did, I suspect we'd discover that analysis takes closer to 95% of uncached startup, rather than the 70% we give it now. This may not always have been the case, but it is now. For example, in metabase on my machine the logs report that external analysis takes 19s, project analysis takes 61s, and overall initialize takes 83s, or 3s outside of analysis.

Cached startup might spend more time proportionally outside of analysis (reading the transit file, etc.) but I think analysis still dominates.

**Additional context**
While we're changing this, we might want to consider a minor fix to the percentages of cached startup. Here's what they are now:
```
0   clojure-lsp
5   Finding kondo config
10  Finding cache
15  Copying kondo configs
15  Resolving config paths
20  Analyzing project files
100 Project analyzed
```

We have two entries for 15%. We could adjust that, or, since neither of those things take much time, we could leave them as is.

**Comment by mainej** [comment]
Also I just noticed that the un-cached timing always jumps from 70% at the [end](https://github.com/clojure-lsp/clojure-lsp/blob/master/lib/src/clojure_lsp/crawler.clj#L49-L50) of "Analyzing external classpath" to 75% when "Resolving config paths" [starts](https://github.com/clojure-lsp/clojure-lsp/blob/aa46e433e9642c1368336130d1dd99cfc68402a8/lib/src/clojure_lsp/crawler.clj#L180). To be consistent with internal analysis, the end of external analysis should be [one percentage point less](https://github.com/clojure-lsp/clojure-lsp/blob/aa46e433e9642c1368336130d1dd99cfc68402a8/lib/src/clojure_lsp/crawler.clj#L195) than the start of the next task.

**Comment by ericdallo** [comment]
Yeah, we can fix the 15% to 12 or something but both are pretty fast most of the time.
The reason I left more time to external is because usually it's what takes most time on most projects... Metabase is a huge project that I consider as an outlier, but I don't see any problem spending a little bit more percents on internal analysis
