### ISSUE TITLE
Clean-ns with :keep indent introduces an extra new line.

### ISSUE THREAD

**Issue by snoe** [clojure-lsp/clojure-lsp#1141]
**Describe the bug**
When a namespace is on the same line as `:require`, and :keep indentation is set, the namespace will be placed on the line below the `:require` after clean-ns is called. This also happens with other actions that trigger the clean-ns code like add-missing.

**To Reproduce**
1.  `:clean {:ns-inner-blocks-indentation :keep}` setting
2. have name space like
```
(ns foo
  (:require [foo.a :as a]
            [foo.b :as b])
```
3. clean-ns
4. See that foo.a has moved
```
(ns foo
  (:require 
            [foo.a :as a]
            [foo.b :as b])
```

**Expected behavior**
The ns shouldn't change

**User details (please complete the following information):**
on clojure-lsp master

I'll work on this PR

**Comment by ericdallo** [comment]
I think this was a regression introduced recently, thanks for reporting
