### ISSUE TITLE
textDocument/hover makes wrong assumptions around def/defn 

### ISSUE THREAD

**Issue by agzam** [clojure-lsp/clojure-lsp#1159]
I've noticed something weird, and I'm not sure (yet) if this is a bug in lsp-mode, or in clojure-lsp, or it's a bug in Emacs (I'm using Emacs 29).

### To reproduce:

- Find a piece of code with `def` or `defn`, e.g., `(defn foo [])`
- Place the cursor at `foo`
- Evaluate the following elisp snippet:
```
(-some-> 
    "textDocument/hover"
  (lsp--make-request
   (lsp--text-document-position-params))
  (lsp--send-request)
  (lsp:hover-contents))
  ```
#### Expected:
 hover information for namespace/function, i.e., `user/foo` 
#### Actual: 
it gets hover information for `clojure.core/def(n)`

Interestingly, it properly works around `(defmethod foo`

**Comment by ericdallo** [comment]
It's a bug on clojure-lsp, we improved hover for multiple other cases bug caused this bug

**Comment by ericdallo** [comment]
Closing as duplicated of #1157
