### ISSUE TITLE
Provide namespace docstrings for eg. lsp-ui

### ISSUE THREAD

**Issue by lassemaatta** [clojure-lsp/clojure-lsp#1171]
**Is your feature request related to a problem? Please describe.**

When using `lsp-mode` as the client and `clojure-lsp` as the server, there doesn't seem to be a way to display or browse namespace docstrings (like docstrings for vars).

**Describe the solution you'd like**

Given the namespace declaration below, and the cursor in the position represented with `|` => `lsp-ui` (or some other similar tool) should show the namespace [docstring](https://github.com/clojure/clojure/blob/master/src/clj/clojure/test.clj#L20) for `clojure.test`.

```
(ns some.namespace
  (:require [cloju|re.test :refer [deftest testing is]]))
```

**Comment by ericdallo** [comment]
@lassemaatta I can see that working with `hover` LSP feature, similar to when you ask for docs for a symbol, I think lsp-ui has features to show popups somewhere for that so maybe it'd work out of the box for you, I don't use lsp-ui anymore though so not sure
