### ISSUE TITLE
working with shadow-cljs projects

### ISSUE THREAD

**Issue by Wonko7** [clojure-lsp/clojure-lsp#118]
Hi!

I'm using neovim, LanguageClient-neovim & clojure-lsp release-20200314.
I'm trying to setup clojure-lsp with this project: https://github.com/PEZ/rn-rf-shadow

I added `.lsp/config.edn` with:
```
{"project-specs" [{:project-path "shadow-cljs.edn"
                   :classpath-cmd ["./node_modules/.bin/shadow-cljs" "classpath"]}]}
```

And clojure-lsp seems to choke trying to parse the source. See:
[lsp.txt](https://github.com/snoe/clojure-lsp/files/4344833/lsp.txt)

What am I missing?

**Comment by ericdallo** [comment]
We already support shadow-cljs by default if you have npx installed, also test it with latest clojure-lsp and feel free to reopen if does not work
