### ISSUE TITLE
URIs vs Filenames

### ISSUE THREAD

**Issue by mainej** [clojure-lsp/clojure-lsp#1207]
### History

The LSP spec uses URIs to identify files. clj-kondo uses filenames. clojure-lsp uses both—URIs most of the time, but filenames when running queries on the analysis and findings. At the moment there are over 100 places in the code where we convert a URI to a filename, or vice versa, as we switch between paradigms.

### Proposal

I propose that we use URIs everywhere, except on the boundary with clj-kondo.

1. Convert URIs to filenames as we're sending data off to clj-kondo.
2. Convert filenames to URIs in the kondo normalization. Index analysis and findings by URI.
3. Convert the rest of the code to rely on URIs exclusively.

### Context

I recall seeing a discussion about teaching clj-kondo to take and return URIs, which I can't find now. I believe the rational at that point was the possibility of using clojure-lsp across a network, for example for remote pairing. Even if those changes are done in clj-kondo someday, we'd still have to update clojure-lsp as described here to take advantage of it.

### Concerns

I'm writing this Issue primarily to collect concerns. @ericdallo, @snoe and perhaps @borkdude, I assume you've thought about this at some point. Do you know of any roadblocks to doing this work? Or has it just been a low priority?

I haven't done an exhaustive analysis of the ways we use filenames. There may be other places besides our interaction with clj-kondo where we use filenames. Are you aware of any such places?

**Comment by snoe** [comment]
This sounds like a good thing. I'm probably responsible for the varied mix, and know that it was always a struggle to convert between the two, but can't remember any specific reasons except maybe apis that forced one or the other (even pre-kondo). We also had a discussion around `move-form` (that I can't find) and my reasons why that should take a filename instead of a namespace, I don't think that should be changed to a uri either.

File watching and cross OS testing (windows especially) would be the other things I'd keep in mind.

**Comment by ericdallo** [comment]
@mainej yeah, @borkdude is aware of that, I think if we want we could try opening PRs on clj-kondo to make it use uris too, but that would increase the complexity of this task indeed.

Even so, I agree we could turn everything to URIs and leave clj-kondo with filenames for now

**Comment by mainej** [comment]
Thanks for the additional context. This gives me confidence it's possible. Also, I won't be disappointed if we can't remove _every_ uri/filename conversion, I'd just like to do fewer. I think that means starting with using URIs in the analysis, and seeing how far that gets us.

> move-form should take a filename instead of a namespace, I don't think that should be changed to a uri either.

It wouldn't be a big deal to leave this as filename, but still, I'm curious. I vaguely remember the discussion and the conclusion, but not the rationale. Maybe it was that namespace is ambiguous—you can have the same namespace defined in two files, which happens regularly when you have both a .clj and .cljs version of a file. Technically filename is ambiguous too—you can have two namespaces defined in the same file—but that's very rare. Anyway, why wouldn't a URI be appropriate? (Aside from the obvious fact that we've already established filename as our API.)

> File watching

[didChangeWatchedFiles](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWatchedFiles) uses URIs to notify us of changes. Is that what you were referring to, or is there some other form of file watching I should be aware of?

> cross OS testing

That always makes me nervous... but, if the current conversions work cross-OS, and apparently they do, I feel pretty confident using them at the borders with kondo. Let me know if I'm oversimplifying.

> borkdude is aware of that

OK, good to know—I'll see how this work goes, and maybe we can work on a clj-kondo PR someday.

**Comment by snoe** [comment]
>> move-form should take a filename instead of a namespace, I don't think that should be changed to a uri either.

> It wouldn't be a big deal to leave this as filename, but still, I'm curious. I vaguely remember the discussion and the conclusion, but not the rationale.  Maybe it was that namespace is ambiguous

I think the namespace ambiguity was the rationale that resonated. But also editors know how to tab complete filenames from user input but not namespaces (and I doubt they'd be as good at uris)

> [didChangeWatchedFiles](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWatchedFiles) uses URIs to notify us of changes. Is that what you were referring to, or is there some other form of file watching I should be aware of?

That's what I was referring to.
