### ISSUE TITLE
First class dev/test support for MS-Windows

### ISSUE THREAD

**Issue by ikappaki** [clojure-lsp/clojure-lsp#1211]
**Is your feature request related to a problem? Please describe.**

At the moment, the lib/cli test and cli integration-test command fail with a lot of errors on MS-Windows.

In addition it is impossible to create debug/prod cli builds because the jar to binary conversion is not compatible with MS-Windows.

This means that the MS-Windows builds are likely to be dysfunctional and makes the release verification and the development cycle very difficult to manage.

**Describe the solution you'd like**

Fix all the test errors and make the development and CI integration on MS-Windows the same or very close to what is provided for Linux.

**Describe alternatives you've considered**

Can't think of any.

**Additional context**

The following is a non-exhaustive list that is likely to need addressing on MS-Windows
- Fix tests
- Fix integration tests
- Support for jar to executable conversion.
- Migrate makefile to bb.edn
- Update Github actions to run the same tests on MS-Windows.

Happy to have a look at all of the above.

Thanks

**Comment by ericdallo** [comment]
Totally agree with that! I'm no windows user but LMK if need any support or context, your help is appreciated

**Comment by ericdallo** [comment]
@ikappaki is this done after all your recent improvements?

**Comment by ikappaki** [comment]
> @ikappaki is this done after all your recent improvements?

Hi @ericdallo, the only thing left is to correct the formatting of the writing tests section of the documentation here, which some how comes back garbled: https://clojure-lsp.io/development sorry haven't figured out yet how this page is generated and how to "debug" it ... :(

**Comment by ericdallo** [comment]
No problem, I can take a look, usually running `make local-webpage` should build the docs locally

**Comment by ikappaki** [comment]
> No problem, I can take a look, usually running `make local-webpage` should build the docs locally

yeah, it asks me for a password and I don't have a docker account ...

(btw it is `bb local-webpage` now :) )

**Comment by ericdallo** [comment]
Oh, I think that's because the docker image comes from [here](https://github.com/clojure-lsp/docs-image), I should make it public somehow

yeah haha, just fixed on master

**Comment by ericdallo** [comment]
The image is public, but you need to make your docker login on github to download images from github :/

**Comment by ikappaki** [comment]
> The image is public, but you need to make your docker login on github to download images from github :/
> https://github.com/clojure-lsp/docs-image/pkgs/container/docs-image%2Fdocs-image

... :)

**Comment by ikappaki** [comment]
btw, if you don't mind me asking, why bother with docker images for this simple task, i.e. converting an md file to an html page? I'm not sure where the complexity is coming from

**Comment by ikappaki** [comment]
Great thanks, I can see it is now formatted correctly, I'm closing this as completed!

**Comment by ericdallo** [comment]
We use [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) for the webpage, and we have specific plugins [here](https://github.com/clojure-lsp/docs-image/blob/master/Dockerfile#L3-L6), if we don't use docker, we would need to install mkdocs-magerial on each machine along with those python plugins in specific versions, having it in a docker image is way easier to manage and update IMO.

I think it'd be nice to add to the docs-image readme how to login and download the image, IIRC are just 2 commands

**Comment by ikappaki** [comment]
> We use [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) for the webpage, and we have specific plugins [here](https://github.com/clojure-lsp/docs-image/blob/master/Dockerfile#L3-L6), if we don't use docker, we would need to install mkdocs-magerial on each machine along with those python plugins in specific versions, having it in a docker image is way easier to manage and update IMO.
> 
> I think it'd be nice to add to the docs-image readme how to login and download the image, IIRC are just 2 commands

or a couple of bb tasks, one to install the tools + packages, the other to run it to convert the files. Though I haven't looked into the details of the workflow, so I could be missing a lot :)
