### ISSUE TITLE
2022.09.01-15.27.31: `clojure-lsp.api` source links are broken in cljdoc

### ISSUE THREAD

**Issue by sheluchin** [clojure-lsp/clojure-lsp#1225]
https://cljdoc.org/d/com.github.clojure-lsp/clojure-lsp/2022.09.01-15.27.31/api/clojure-lsp.api

`source` links for each function here are currently broken, all pointing to something like `https://github.com/clojure-lsp/clojure-lsp/blob/2022.09.01-15.27.31/#L128`. I checked just a small number of other pages and they all seem to be okay, but I didn't test every page.

**Comment by ericdallo** [comment]
I tested and It seems to be a bug on cljdocs itself, maybe @lread can help here? 😅

**Comment by lread** [comment]
Huh! Happy to take a peek today.

**Comment by lread** [comment]
Should be all good now! Thanks very much for the report and lemme know if you find any further issues with cljdoc.

**Comment by ericdallo** [comment]
Awesome! thank you very much for the quick fix!
