### ISSUE TITLE
unused-public-var can't be ignored on protocols

### ISSUE THREAD

**Issue by Cyrik** [clojure-lsp/clojure-lsp#1226]
**Describe the bug**
When I have a `defprotocol` with functions that aren't called adding `#_{:clj-kondo/ignore [:clojure-lsp/unused-public-var]}` does not "solve" it.

**To Reproduce**
```clojure
(defprotocol IProducer
  #_{:clj-kondo/ignore [:clojure-lsp/unused-public-var]}
  (refresh-code-lens [this]))
```
`refres-code-lens` shows a warning.

**Expected behavior**
Should not show a warning.

**Comment by ericdallo** [comment]
Thanks, as an alternative for now you can add the ignore to the defprotocol itself, but that will ignore all usages of the protocol indeed

**Comment by ericdallo** [comment]
After some debugging, it seems that clj-kondo is not checking if the function var-definition inside the protocol has the ignore comment when we call `reg-finding!` from custom-lint-fn, does that makes sense for you @borkdude ?

**Comment by borkdude** [comment]
Issue + clj-kondo repro e.g. as failing test welcome

**Comment by ericdallo** [comment]
Thanks, done [here](https://github.com/clj-kondo/clj-kondo/issues/1815)

**Comment by ericdallo** [comment]
Fixed on master, thanks for the help @borkdude !
