### ISSUE TITLE
Restructure keys action creates shadowed locals

### ISSUE THREAD

**Issue by lassemaatta** [clojure-lsp/clojure-lsp#1229]
**Describe the bug**

Running the "Restructure keys" code action for a complex destructuring form several times creates duplicate locals. 

Assuming of course I'm using this as intended. It looked like a really cool refactoring so naturally I had to break it immediately :)

**To Reproduce**
1. Given

```clojure
(def data {:top-a {:a 1}
           :top-b {:b 2}})

(defn foobar
  [{{:keys [a]} :top-a
    {:keys [b]} :top-b}]
  (+ a b))
```

2. Move cursor before the first `{:keys [a]}` and run the code action:

```clojure
(defn foobar
  [{element :top-a
    {:keys [b]} :top-b}]
  (+ (:a element) b))
```

3. Move cursor before the `{:keys [b]}` and run the code action again:

```clojure
(defn foobar
  [{element :top-a
    element :top-b}]
  (+ (:a element) (:b element)))
```

**Expected behavior**
It would be nice if the refactoring could detect it's about to create a duplicate local and name it `element-2` or whatever. 

**User details (please complete the following information):**
 - OS: arch
 - Editor emacs
 - Version: `clojure-lsp 2022.09.01-15.27.31`

**Additional context**

A simple workaround is to immediately rename the `element` local before running the code action again.

**Comment by ericdallo** [comment]
Maybe we should append a sufix for the created elements like `element-1`, `element-2` etc c/c @mainej

**Comment by mainej** [comment]
I've been using your workaround @lassemaatta—renaming  the first`element` before restructuring the next—and it's been working ok. But I agree, something smarter would be a nice addition. Thanks for the suggestion 👍
