### ISSUE TITLE
[LSP] Semantic tokens support

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#124]
LSP recently added a new semantic highlighting feature where server send to client the regions to color/highlight.
Check https://github.com/emacs-lsp/lsp-mode/issues/1482 for emacs discussion support and [here](https://github.com/microsoft/vscode-languageserver-node/issues/368#issue-336150366) explaining the feature

**Comment by scotts777** [comment]
This would be a great feature.   LSP is getting very good.

**Comment by ericdallo** [comment]
https://github.com/eclipse/lsp4j/issues/430

**Comment by ericdallo** [comment]
Finally I Implemented a first basic support for that :tada: 
https://github.com/snoe/clojure-lsp/pull/216

I intend improving it by adding other tokens and tracking bugs since it's a hard new feature

**Comment by ericdallo** [comment]
Closing as this is already implemented even with basic support that we can easily improve in the future
