### ISSUE TITLE
Errors when file starts with a comment

### ISSUE THREAD

**Issue by mainej** [clojure-lsp/clojure-lsp#1252]
**Problem**
clojure-lsp assumes that after parsing a zloc from a syntactically correct file, it will be able to navigate to any cursor position using `parser/to-pos`. There's one case though where it fails.

In the following file `(-> (parser/safe-zloc-of-file db uri) (parser/to-pos 1 1))` will return nil:
```clojure
;; foo
(def foo)
```

In my opinion, we should navigate to the comment node.

The reason this bug exists is because of [these lines](https://github.com/clj-commons/rewrite-clj/blob/6027fa616552c4c395bba39cd1c2c7ad12099509/src/rewrite_clj/zip/base.cljc#L41-L42). In `z/of-string`, rewrite-clj calls `z/edn`, which skips past whitespace and comment nodes at the top of files. So, in the example, `parser/safe-zloc-of-file` navigates to `(def foo)`, which is on line 2. And since `parser/to-pos` searches forward, `(parser/to-pos zloc 1 1)` doesn't reach the comment on line 1.

**Solution**
I propose we create a function `z-of-string*` that uses [`z/edn*`](https://github.com/clj-commons/rewrite-clj/blob/v1.1.45/src/rewrite_clj/zip/base.cljc#L14) instead of `z/edn`, so that we always start at the root node. I haven't explored the implications of this—there may be code that expects that we'll never start at the `:forms` node, and instead will always be on one of its children.

**Alternatives**
* We can continue to work around [bugs](https://github.com/clojure-lsp/clojure-lsp/pull/1251) that arise from this, by checking whether the zloc is nil.
* Before calling `parser/to-pos` and when strategically appropriate, we can call `z/up` to get to the root node. (This is difficult to do correctly though, because if a file contains _only_ whitespace and comments, `z/edn` will already return the root node, in which case `z/up` will return nil. So the safe way would be `(or (z/up zloc) zloc)`.)

**Comment by ericdallo** [comment]
@mainej I see, should we "fix" this on rewrite-clj or at least provide a function that uses `z/edn*`?
Even so, sounds good fixing the root cause instead of doing workarounds like checking nil or using `or`s, WDYT?

**Comment by mainej** [comment]
@ericdallo, yeah, submitting a PR to rewrite-clj for `of-string*` is a good idea. I'll plan to do that. In the meantime, what do you want to do with #1251? Does https://github.com/clojure-lsp/clojure-lsp/commit/7ac822d3efe3dd51db4fef8959b8708ad7fb2e16 fix the same bug?

**Comment by ericdallo** [comment]
No, they fix different bugs, I think it's ok to merge #1251 and when we have that on rewrite-clj we change that.

**Comment by mainej** [comment]
#1286 navs to the root `:forms` node, so this is fixed. As noted in that PR, we still have to be careful about empty files, but files that start with comments are no longer a problem.
