### ISSUE TITLE
Generated cache files warnings

### ISSUE THREAD

**Issue by isacjunior** [clojure-lsp/clojure-lsp#1279]
**Describe the bug**
The generated cached files are being validated by clojure-lsp and I see some warnings on VSCode editor.

Cached file: `.lsp/.cache/stubs/datomic/api.clj` 

**Expected behavior**
As these are only cached files, they shouldn't display the errors.

**Screenshots**

![Screen Shot 2022-09-13 at 15 03 50](https://user-images.githubusercontent.com/12630335/192612876-e9c2a83a-d7ac-4c82-8227-66fb3fe52e97.png)

**User details (please complete the following information):**
 - OS: MacOS
 - Editor VSCode
 - Version: 
 clojure-lsp 2022.09.01-15.27.31
 clj-kondo 2022.08.03

**Comment by ericdallo** [comment]
We should on didClose ignore drop diagnostics of those files as we do for external opened files.

**Comment by ericdallo** [comment]
I confirmed clojure-lsp already disconsider the file diagnostics when closing it, tested on both emacs and vscode so I'm closing this, LMK if otherwise
