### ISSUE TITLE
In a multi-arity function, "move to let" is incorrect within arity-0 form

### ISSUE THREAD

**Issue by kdchabuk** [clojure-lsp/clojure-lsp#1283]
**Describe the bug**
In a multi-arity function, "move to let" is incorrect within 0-arity form; the new binding is placed outside the 0-arity form.

**To Reproduce**
Consider this code in VSCodium with Calva and clojure-lsp extensions:
```
(defn foo
  ([]
   (+ 0))
  ([x]
   (reduce + x)))
```
Highlight `0`, push Ctrl+., and choose "move to let". You will get:
```
(defn foo
  (let [new-binding 0]
   ([]
   (+ new-binding)))
  ([x]
   (reduce + x)))
```
This results in an error because the `let` is outside the 0-arity definition.

**Expected behavior**
```
(defn foo
  ([]
   (let [new-binding 0]
     (+ new-binding)))
  ([x]
   (reduce + x)))
```

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
[Trace - 12:55:11 PM] Sending request 'textDocument/codeAction - (3307)'.
Params: {
    "textDocument": {
        "uri": "file:///home/kdc/pe/tools/src/tools/foo.clj"
    },
    "range": {
        "start": {
            "line": 2,
            "character": 6
        },
        "end": {
            "line": 2,
            "character": 7
        }
    },
    "context": {
        "diagnostics": [],
        "triggerKind": 1
    }
}

[Trace - 12:55:11 PM] Received response 'textDocument/codeAction - (3307)' in 7ms.
Result: [
    {
        "title": "Move to let",
        "kind": "refactor.extract",
        "command": {
            "title": "Move to let",
            "command": "move-to-let",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6,
                "new-binding"
            ]
        }
    },
    {
        "title": "Cycle privacy",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Cycle privacy",
            "command": "cycle-privacy",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6
            ]
        }
    },
    {
        "title": "Extract function",
        "kind": "refactor.extract",
        "command": {
            "title": "Extract function",
            "command": "extract-function",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6,
                "new-function"
            ]
        }
    },
    {
        "title": "Extract to def",
        "kind": "refactor.extract",
        "command": {
            "title": "Extract to def",
            "command": "extract-to-def",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6,
                null
            ]
        }
    },
    {
        "title": "Thread first all",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Thread first all",
            "command": "thread-first-all",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6
            ]
        }
    },
    {
        "title": "Thread last all",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Thread last all",
            "command": "thread-last-all",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6
            ]
        }
    },
    {
        "title": "Drag backward",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Drag backward",
            "command": "drag-backward",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6
            ]
        }
    },
    {
        "title": "Introduce let",
        "kind": "refactor.extract",
        "command": {
            "title": "Introduce let",
            "command": "introduce-let",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6,
                "new-binding"
            ]
        }
    },
    {
        "title": "Create test for 'foo'",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Create test",
            "command": "create-test",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6
            ]
        }
    },
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "command": {
            "title": "Clean namespace",
            "command": "clean-ns",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6
            ]
        }
    }
]

[Trace - 12:55:15 PM] Sending request 'workspace/executeCommand - (3308)'.
Params: {
    "command": "move-to-let",
    "arguments": [
        "file:///home/kdc/pe/tools/src/tools/foo.clj",
        2,
        6,
        "new-binding"
    ]
}

[Trace - 12:55:15 PM] Received response 'workspace/executeCommand - (3308)' in 2ms.
No result returned.

[Trace - 12:55:15 PM] Sending request 'textDocument/codeAction - (3309)'.
Params: {
    "textDocument": {
        "uri": "file:///home/kdc/pe/tools/src/tools/foo.clj"
    },
    "range": {
        "start": {
            "line": 2,
            "character": 6
        },
        "end": {
            "line": 2,
            "character": 7
        }
    },
    "context": {
        "diagnostics": [],
        "triggerKind": 2
    }
}

[Trace - 12:55:15 PM] Received request 'workspace/applyEdit - (41)'.
Params: {
    "edit": {
        "documentChanges": [
            {
                "textDocument": {
                    "uri": "file:///home/kdc/pe/tools/src/tools/foo.clj",
                    "version": 4
                },
                "edits": [
                    {
                        "range": {
                            "start": {
                                "line": 1,
                                "character": 2
                            },
                            "end": {
                                "line": 2,
                                "character": 9
                            }
                        },
                        "newText": "(let [new-binding 0]\n   ([]\n   (+ new-binding)))"
                    }
                ]
            }
        ]
    }
}

[Trace - 12:55:15 PM] Received response 'textDocument/codeAction - (3309)' in 9ms.
Result: [
    {
        "title": "Move to let",
        "kind": "refactor.extract",
        "command": {
            "title": "Move to let",
            "command": "move-to-let",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6,
                "new-binding"
            ]
        }
    },
    {
        "title": "Cycle privacy",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Cycle privacy",
            "command": "cycle-privacy",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6
            ]
        }
    },
    {
        "title": "Extract function",
        "kind": "refactor.extract",
        "command": {
            "title": "Extract function",
            "command": "extract-function",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6,
                "new-function"
            ]
        }
    },
    {
        "title": "Extract to def",
        "kind": "refactor.extract",
        "command": {
            "title": "Extract to def",
            "command": "extract-to-def",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6,
                null
            ]
        }
    },
    {
        "title": "Thread first all",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Thread first all",
            "command": "thread-first-all",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6
            ]
        }
    },
    {
        "title": "Thread last all",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Thread last all",
            "command": "thread-last-all",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6
            ]
        }
    },
    {
        "title": "Drag backward",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Drag backward",
            "command": "drag-backward",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6
            ]
        }
    },
    {
        "title": "Introduce let",
        "kind": "refactor.extract",
        "command": {
            "title": "Introduce let",
            "command": "introduce-let",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6,
                "new-binding"
            ]
        }
    },
    {
        "title": "Create test for 'foo'",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Create test",
            "command": "create-test",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6
            ]
        }
    },
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "command": {
            "title": "Clean namespace",
            "command": "clean-ns",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                2,
                6
            ]
        }
    }
]

[Trace - 12:55:15 PM] Sending response 'workspace/applyEdit - (41)'. Processing request took 64ms
Result: {
    "applied": true
}

[Trace - 12:55:15 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///home/kdc/pe/tools/src/tools/foo.clj",
        "version": 5
    },
    "contentChanges": [
        {
            "text": "(defn foo\n  (let [new-binding 0]\n   ([]\n   (+ new-binding)))\n  ([x]\n   (reduce + x)))"
        }
    ]
}

[Trace - 12:55:15 PM] Sending request 'textDocument/semanticTokens/full - (3310)'.
Params: {
    "textDocument": {
        "uri": "file:///home/kdc/pe/tools/src/tools/foo.clj"
    }
}

[Trace - 12:55:15 PM] Sending request 'textDocument/documentSymbol - (3311)'.
Params: {
    "textDocument": {
        "uri": "file:///home/kdc/pe/tools/src/tools/foo.clj"
    }
}

[Trace - 12:55:16 PM] Sending request 'textDocument/codeAction - (3312)'.
Params: {
    "textDocument": {
        "uri": "file:///home/kdc/pe/tools/src/tools/foo.clj"
    },
    "range": {
        "start": {
            "line": 3,
            "character": 18
        },
        "end": {
            "line": 3,
            "character": 18
        }
    },
    "context": {
        "diagnostics": [],
        "triggerKind": 2
    }
}

[Trace - 12:55:16 PM] Received response 'textDocument/semanticTokens/full - (3310)' in 240ms.
Result: {
    "data": [
        0,
        1,
        4,
        3,
        0,
        0,
        5,
        3,
        2,
        1,
        3,
        4,
        1,
        2,
        0,
        1,
        4,
        1,
        6,
        0,
        1,
        4,
        6,
        2,
        0,
        0,
        7,
        1,
        2,
        0,
        0,
        2,
        1,
        6,
        0
    ]
}

[Trace - 12:55:16 PM] Received response 'textDocument/documentSymbol - (3311)' in 187ms.
Result: [
    {
        "name": "/home/kdc/pe/tools/src/tools/foo.clj",
        "kind": 21,
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 999999,
                "character": 999999
            }
        },
        "selectionRange": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 999999,
                "character": 999999
            }
        },
        "children": [
            {
                "name": "foo",
                "kind": 12,
                "range": {
                    "start": {
                        "line": 0,
                        "character": 0
                    },
                    "end": {
                        "line": 5,
                        "character": 17
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 0,
                        "character": 6
                    },
                    "end": {
                        "line": 0,
                        "character": 9
                    }
                },
                "tags": []
            }
        ]
    }
]

[Trace - 12:55:16 PM] Received response 'textDocument/codeAction - (3312)' in 54ms.
Result: [
    {
        "title": "Change coll to vector",
        "kind": "refactor",
        "command": {
            "title": "Change coll",
            "command": "change-coll",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18,
                "vector"
            ]
        }
    },
    {
        "title": "Change coll to set",
        "kind": "refactor",
        "command": {
            "title": "Change coll",
            "command": "change-coll",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18,
                "set"
            ]
        }
    },
    {
        "title": "Change coll to map",
        "kind": "refactor",
        "command": {
            "title": "Change coll",
            "command": "change-coll",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18,
                "map"
            ]
        }
    },
    {
        "title": "Move to let",
        "kind": "refactor.extract",
        "command": {
            "title": "Move to let",
            "command": "move-to-let",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18,
                "new-binding"
            ]
        }
    },
    {
        "title": "Cycle privacy",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Cycle privacy",
            "command": "cycle-privacy",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    },
    {
        "title": "Extract function",
        "kind": "refactor.extract",
        "command": {
            "title": "Extract function",
            "command": "extract-function",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18,
                "new-function"
            ]
        }
    },
    {
        "title": "Extract to def",
        "kind": "refactor.extract",
        "command": {
            "title": "Extract to def",
            "command": "extract-to-def",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18,
                null
            ]
        }
    },
    {
        "title": "Thread first all",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Thread first all",
            "command": "thread-first-all",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    },
    {
        "title": "Thread last all",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Thread last all",
            "command": "thread-last-all",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    },
    {
        "title": "Move another expression to get/get-in",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Move another expression to get/get-in",
            "command": "get-in-more",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    },
    {
        "title": "Move all expressions to get/get-in",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Move all expressions to get/get-in",
            "command": "get-in-all",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    },
    {
        "title": "Drag backward",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Drag backward",
            "command": "drag-backward",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    },
    {
        "title": "Introduce let",
        "kind": "refactor.extract",
        "command": {
            "title": "Introduce let",
            "command": "introduce-let",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18,
                "new-binding"
            ]
        }
    },
    {
        "title": "Create test for 'foo'",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Create test",
            "command": "create-test",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    },
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "command": {
            "title": "Clean namespace",
            "command": "clean-ns",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    }
]

[Trace - 12:55:16 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///home/kdc/pe/tools/src/tools/foo.clj",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 6
                },
                "end": {
                    "line": 0,
                    "character": 9
                }
            },
            "tags": [
                1
            ],
            "message": "Unused public var 'user/foo'",
            "code": "clojure-lsp/unused-public-var",
            "severity": 3,
            "source": "clojure-lsp"
        },
        {
            "range": {
                "start": {
                    "line": 1,
                    "character": 2
                },
                "end": {
                    "line": 1,
                    "character": 2
                }
            },
            "tags": [],
            "message": "Function arguments should be wrapped in vector.",
            "code": "syntax",
            "severity": 1,
            "source": "clj-kondo"
        },
        {
            "range": {
                "start": {
                    "line": 1,
                    "character": 8
                },
                "end": {
                    "line": 1,
                    "character": 19
                }
            },
            "tags": [],
            "message": "Unresolved symbol: new-binding",
            "code": "unresolved-symbol",
            "severity": 1,
            "source": "clj-kondo"
        },
        {
            "range": {
                "start": {
                    "line": 3,
                    "character": 6
                },
                "end": {
                    "line": 3,
                    "character": 17
                }
            },
            "tags": [],
            "message": "Unresolved symbol: new-binding",
            "code": "unresolved-symbol",
            "severity": 1,
            "source": "clj-kondo"
        }
    ]
}

[Trace - 12:55:16 PM] Sending request 'textDocument/codeAction - (3313)'.
Params: {
    "textDocument": {
        "uri": "file:///home/kdc/pe/tools/src/tools/foo.clj"
    },
    "range": {
        "start": {
            "line": 3,
            "character": 18
        },
        "end": {
            "line": 3,
            "character": 18
        }
    },
    "context": {
        "diagnostics": [],
        "triggerKind": 2
    }
}

[Trace - 12:55:16 PM] Received response 'textDocument/codeAction - (3313)' in 9ms.
Result: [
    {
        "title": "Change coll to vector",
        "kind": "refactor",
        "command": {
            "title": "Change coll",
            "command": "change-coll",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18,
                "vector"
            ]
        }
    },
    {
        "title": "Change coll to set",
        "kind": "refactor",
        "command": {
            "title": "Change coll",
            "command": "change-coll",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18,
                "set"
            ]
        }
    },
    {
        "title": "Change coll to map",
        "kind": "refactor",
        "command": {
            "title": "Change coll",
            "command": "change-coll",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18,
                "map"
            ]
        }
    },
    {
        "title": "Move to let",
        "kind": "refactor.extract",
        "command": {
            "title": "Move to let",
            "command": "move-to-let",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18,
                "new-binding"
            ]
        }
    },
    {
        "title": "Cycle privacy",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Cycle privacy",
            "command": "cycle-privacy",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    },
    {
        "title": "Extract function",
        "kind": "refactor.extract",
        "command": {
            "title": "Extract function",
            "command": "extract-function",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18,
                "new-function"
            ]
        }
    },
    {
        "title": "Extract to def",
        "kind": "refactor.extract",
        "command": {
            "title": "Extract to def",
            "command": "extract-to-def",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18,
                null
            ]
        }
    },
    {
        "title": "Thread first all",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Thread first all",
            "command": "thread-first-all",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    },
    {
        "title": "Thread last all",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Thread last all",
            "command": "thread-last-all",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    },
    {
        "title": "Move another expression to get/get-in",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Move another expression to get/get-in",
            "command": "get-in-more",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    },
    {
        "title": "Move all expressions to get/get-in",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Move all expressions to get/get-in",
            "command": "get-in-all",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    },
    {
        "title": "Drag backward",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Drag backward",
            "command": "drag-backward",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    },
    {
        "title": "Introduce let",
        "kind": "refactor.extract",
        "command": {
            "title": "Introduce let",
            "command": "introduce-let",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18,
                "new-binding"
            ]
        }
    },
    {
        "title": "Create test for 'foo'",
        "kind": "refactor.rewrite",
        "command": {
            "title": "Create test",
            "command": "create-test",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    },
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "command": {
            "title": "Clean namespace",
            "command": "clean-ns",
            "arguments": [
                "file:///home/kdc/pe/tools/src/tools/foo.clj",
                3,
                18
            ]
        }
    }
]
</pre>
</details>

**User details (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Editor: VSCodium
 - Version:  2022.09.01-15.27.31

**Additional context**

**Comment by janosmeszaros** [comment]
Hi @ericdallo 
I've looked into this issue and it seems it is also a problem for the `expand let` feature (and as `move to let` also uses that feature the issue surfaces there too). BTW the issue is also present for the higher arity versions of the multi-arity fns if the inputs are not used in the body.
`expand let` does not consider the possibility of multi-arity fns so it would just raise the `let` until it reaches the top level.
My suggestion would be to introduce an additional check [here](https://github.com/clojure-lsp/clojure-lsp/blob/3d5ed698354567b8bef2f31780a2026429b9b80a/lib/src/clojure_lsp/refactor/transform.clj#L310) to `expand let` which would stop the further expansion when the first element of the parent node is an array (indicating that the node is a multi-arity fn definition).
What are your thoughts?

**Comment by ericdallo** [comment]
sounds good to me @janosmeszaros !
Willing to open a PR?

**Comment by janosmeszaros** [comment]
@ericdallo just did, although it's a draft as there is an open question.

**Comment by ericdallo** [comment]
@janosmeszaros looks pretty good to me, LMK if it's ok in your side to do the merge

**Comment by janosmeszaros** [comment]
@ericdallo it's good to go on my side, thanks for taking a look.
