### ISSUE TITLE
ClojureScript interop using the .. operator

### ISSUE THREAD

**Issue by QikLiang** [clojure-lsp/clojure-lsp#131]
In the following code: `(.. e -target -value)` where `e` is meant to be a JavaScript object, I get the errors `Unknown symbol: -target` and `Unknown symbol: -value`.

**Comment by FongHou** [comment]
@QikLiang, here is a workaround.

$cat .lsp/config.edn

`{ "macro-defs" {cljs.core/.. [:elements]`

**Comment by QikLiang** [comment]
After learning about how `macro-defs` work, I don't think it's a proper solution. The `-target` symbol is still not being recognized because it has never been defined previously. I see two ways around this issue: treat symbols starting with `-` within interop macros as literals or have an alternative to `elements` for `macro-defs` that have the semantics of "don't try to check the macro beyond this point".

**Comment by ericdallo** [comment]
@QikLiang could you confirm if this happens yet? I'll close this since is not clj-kondo responsibility to handles these things after #261
