### ISSUE TITLE
Cannot Complete Java Classes

### ISSUE THREAD

**Issue by stevemolitor** [clojure-lsp/clojure-lsp#1329]
**Describe the bug**

I cannot complete Java classes in clojure-lsp in Emacs. Regular clojure (ie `map`, `filter`, etc) completes just fine.

**To Reproduce**

Type `java.io.F` and trigger completion. You will not see any candidates.

**Expected behavior**

If I type `java.io.F` and trigger completion, I should see candidates.

**Screenshots**

Trying to trigger completion of Java classes in Emacs using clojure-lsp:

![](https://cdn.zappy.app/0f4e781644d795dc7140d801c99f9f08.gif)

With cider it works as expected:

![](https://cdn.zappy.app/9ee674cb2f358d055a8248c824a52f32.gif)

**User details (please complete the following information):**
 - OS: MacOs
 - Editor: Emacs 29
 - Version: clojure-lsp 2022.10.05-16.48.26-nightly, clj-kondo 2022.10.05

**Additional context**

I have an empty `deps.edn` file:

```clojure
{}
```

I assumed that Java standard library stuff would be picked up by clojure-lsp automatically, as it is with cider. But maybe I have a classpath issue, with clojure-lsp?

Great project btw - amazing stuff.

**Comment by ericdallo** [comment]
We never had this feature because until recently we didn't have java analysis from clj-kondo, I think we can add this kind of completion now, but need to double check

**Comment by ericdallo** [comment]
This is a possible fix: https://github.com/clojure-lsp/clojure-lsp/pull/1331

**Comment by ericdallo** [comment]
This should be fixed, you can try a nightly build or wait for next release
