### ISSUE TITLE
Cannot parse clojure.core.protocols

### ISSUE THREAD

**Issue by pesterhazy** [clojure-lsp/clojure-lsp#134]
```
WARN  clojure-lsp.parser: Cannot parse jar:file:///Users/user/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core/protocols.clj
 nil
 (defprotocol Datafiable
  :extend-via-metadata true

  (datafy [o] "return a representation of o as data (default identity)"))
```

This is because of the unusual `:extend-via-metadata true` syntax. This option was added [a while back](https://github.com/clojure/clojure/commit/2cc37bb56a9125a1829c73c505e32995e663059a).

**Comment by ericdallo** [comment]
Hey @pesterhazy this already works since we merged #261 :)
