### ISSUE TITLE
Autocomplete of ns doesn't work when there's no alias to it

### ISSUE THREAD

**Issue by ericliou** [clojure-lsp/clojure-lsp#1352]
**Describe the bug**
In Emacs, when requiring a ns without an alias, autocomplete doesn't seem to work.
Even with an alias, it still fails at some weird cases.

I also tried with the same clojure-lsp server in nvim and it works every time <3. So it looks like the problem is isolated around integration with emacs.

**To Reproduce**
1. Use the suggested init.el from https://emacs-lsp.github.io/lsp-mode/tutorials/clojure-guide/#basic-configuration
2. Create a ns foo.car
3. Create a second ns requiring the first one without alias. e.g.
```
(ns foo.bar
  (:require [foo.car]))
  ```
4. Try autocompleting with part of the ns "foo.c"
5. Result: No relevant candidates come back from foo.car. Sometimes it works, when deleting enough characters.

**Expected behavior**
The relevant autocomplete candidates are shown with or without alias.

**Screenshots**

https://user-images.githubusercontent.com/46451142/198919797-64c7eed4-3f51-48b3-8b74-50a7de4a247c.mp4

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
[Trace - 02:01:23 am] Received response 'textDocument/completion - (16)' in 25ms.
Result: [
  {
    "label": "foo.bar",
    "kind": 9,
    "data": {
      "unresolved": [
        [
          "documentation",
          {
            "name": "foo.bar",
            "uri": "file:///home/eric/dev/lsp-debug/src/foo/bar.clj",
            "name-row": 1,
            "name-col": 5
          }
        ]
      ]
    }
  }
]
</pre>
</details>

<details>
 <summary><b>Log - clojure-lsp</b></summary>
<pre>
No relevant logs
</pre>
</details>

**User details (please complete the following information):**
 - OS: ArchLinux
 - Editor: emacs
 - Version: clojure-lsp 2022.10.05-16.39.51
clj-kondo 2022.10.05

**Additional context**

New Emacs user here, it could be some configuration issue. But the issue was reproduced with a minimal init.el.

**Comment by ericdallo** [comment]
@ericliou I suspect this is a clojure-lsp bug pretty specific to not being able to complete a invalid code `foo/` at the end of the file like:

```clojure
(my-ns)

clojure.string/
```
The `/` ☝🏻 is the last char in the file and clojure-lsp doesn't understand that well

```clojure
(my-ns)

(clojure.string/)
```
Auto completing after `/` here works because `/` is not the last char.

I know is pretty weird, but could you try both and LMK?

**Comment by ericliou** [comment]
Tried with the case where the file ends with closing paren and it didn't work.

With an alias, `(:require [foo.car :as c])`: 
`c/` this works reliably, so it makes me believe that `/` isn't the issue.

So.. I tried something else and it changed the problem a bit.
`(setq lsp-completion-no-cache t)`

These cases started to autocomplete functions reliably:
- `foo.car`
- `(foo.car)

The only issues that are still left are:
- Without aliasing the ns, `(:require [foo.car])`
  - I expected `fo` to autocomplete `foo.car`, it doesn't

(With an alias, `(:require [foo.car :as c])`, it DOES work.)

These are weird but minor issues that I can live with :)

**Comment by ericdallo** [comment]
That's weird, this seems to work properly to me, I also have lsp-completion-no-cache enabled but for development purposes.

![Peek 2022-10-31 15-32](https://user-images.githubusercontent.com/7820865/199083605-70320513-75e6-472e-a80f-1f9992ab7b26.gif)

**Comment by ericdallo** [comment]
Uh, I do notice that we doesn't suggest `foo.bar` on that gif, that would be something to fix on server side, nothing more besides that as I can see

**Comment by ericdallo** [comment]
Fixed on master, available on next release (a couple of days probably)!
