### ISSUE TITLE
Extending a protocol does not clear `unused-public-var` warning

### ISSUE THREAD

**Issue by bhlieberman** [clojure-lsp/clojure-lsp#1368]
**Describe the bug**
When extending a protocol with `extend-protocol`, the method signatures in the corresponding `defprotocol` still show the warning `unused-public-var`. 

**To Reproduce**
1. Recreate this code:

````
(ns foo)

(defprotocol Stats
  (get-stats [this profile])
  (compute-advanced-stats [this]))

(defrecord PlayerStats [name])

(extend-protocol Stats
  PlayerStats
  (get-stats [this profile] (assoc profile :stats this))
  (compute-advanced-stats [this] this))

````

**Expected behavior**
Extending the protocol should clear the warning. 

**Screenshots**

````

"context": {
        "diagnostics": [
            {
                "range": {
                    "start": {
                        "line": 5,
                        "character": 3
                    },
                    "end": {
                        "line": 5,
                        "character": 12
                    }
                },
                "message": "Unused public var 'player.profile/get-stats'",
                "code": "clojure-lsp/unused-public-var",
                "severity": 3,
                "tags": [
                    1
                ],
                "source": "clojure-lsp"
            },
            {
                "range": {
                    "start": {
                        "line": 6,
                        "character": 3
                    },
                    "end": {
                        "line": 6,
                        "character": 25
                    }
                },
                "message": "Unused public var 'player.profile/compute-advanced-stats'",
                "code": "clojure-lsp/unused-public-var",
                "severity": 3,
                "tags": [
                    1
                ],
                "source": "clojure-lsp"
            }
        ],
        "triggerKind": 2
    }

````

**User details (please complete the following information):**
 - OS: Windows 11
 - Editor: VSCode w/ Calva
 - Version: clojure-lsp version used: 2022.11.03-00.14.57
clj-kondo version used: 2022.11.02

**Comment by ericdallo** [comment]
WIP [here](https://github.com/clojure-lsp/clojure-lsp/pull/new/fix-unused-public-var-for-protocols)

**Comment by ericdallo** [comment]
@bhlieberman re-checking this, I'm wondering if current behaviour is not already correct since this happen for defrecords as well:
```clojure
(defprotocol Stats
  (get-stats [this profile]) ;; gives unused
  (compute-advanced-stats [this]))

(defrecord PlayerStats [name]
  Stats
  (get-stats [this profile] (assoc profile :stats this))
  (compute-advanced-stats [this] this))
```
And it's truly unused since there is no place calling `get-stats` anywhere, only implementing it, but not calling it, WDYT?

**Comment by bhlieberman** [comment]
Hey @ericdallo sorry, I completely forgot to check in on this. If you think it's the behavior that should be expected, I'll defer to you. I'm probably reworking the code where I first noticed this anyhow, so it at least won't be an issue in this particular respect.

**Comment by ericdallo** [comment]
Thanks, I'll close this for now, LMK if you find any issues
