### ISSUE TITLE
Add a `clojure-lsp dump` flag like `--ignore-libs` or `--project-only` to ignore external libs

### ISSUE THREAD

**Issue by sheluchin** [clojure-lsp/clojure-lsp#1383]
**Is your feature request related to a problem? Please describe.**
I want to be able to use clojure-lsp's analysis data on different Clojure projects, but without installing and analyzing all of their dependencies. My understanding is that, at present, LSP follows and runs analysis on all classpath entries.

**Describe the solution you'd like**
Add a flag to allow dumping lightweight LSP analysis data _without_ analyzing the project's external libs. This kind of behaviour is already used in `clojure-lsp clean-ns` and `clojure-lsp format`. 

**Additional context**
There is a bit of discussion about this idea in this Slack [thread](https://clojurians.slack.com/archives/CPABC1H61/p1668960512798619).

**Comment by ericdallo** [comment]
I wonder if we should as default bring project analysis, and add a flag to include external as well, not sure what is the more common usage

**Comment by ericdallo** [comment]
@sheluchin this should be fixed, by default now the dump command will analyze only project and not external deps, for change that you need to `clojure-lsp dump --analysis '{:type :project-and-dependencies}'`
