### ISSUE TITLE
`dump` function should include data as EDN when passed `:format :edn`

### ISSUE THREAD

**Issue by sheluchin** [clojure-lsp/clojure-lsp#1390]
When called as the [example](https://github.com/clojure-lsp/clojure-lsp/blob/2022.11.03-00.14.57/lib/src/clojure_lsp/api.clj#L275-L279) in the docs shows (specifying `:output {:format :edn}`), the expectation that the dump data is included as EDN somewhere in the return value. The actual shape of the return value is `{:result-code 0 :message "..."}`, where the `:message` value is the EDN as a string.

**Expected behavior**
When asked for EDN output, `dump` should include the output as EDN.

**User details (please complete the following information):**
 - Version: `2022.11.03-00.14.57`

**Additional context**
@ericdallo mentions that other commands already do this, adding custom fields to the returned map, but this detail was simply forgotten for the new `dump` functionality.

**Comment by ericdallo** [comment]
Done! now there is a :result in the output
