### ISSUE TITLE
Allow clj-kondo config merge/override from `$XDG_CONFIG_HOME/clojure-lsp/config.edn`

### ISSUE THREAD

**Issue by staifa** [clojure-lsp/clojure-lsp#1393]
**Is your feature request related to a problem? Please describe.**
Currently I have no means to override clj-kondo project config (or I wasn't able to find out how). This bugs me for following reasons:

- I'd like to have an editor specific config - for example disabling conjure's log buffer linting is easy, robust and elegant with `:output {:exclude-files ["conjure-log*"]}`
- Our project config is quite benevolent. It's ok to not force certain coding habits/philosophies on others, but I'd like to use as many linters as possible. Brainfarts happen.

**Describe the solution you'd like**
Add possibility to pass a config override to clj-kondo config in `$XDG_CONFIG_HOME/clojure-lsp/config.edn`. It would use deep merge to preserve project/personal settings. It would use the same data structure as `.clj-kondo/config.edn`.

Example:

`$XDG_CONFIG_HOME/clojure-lsp/config.edn`
```clojure
{:linters {:clj-kondo {:level :on
                       :report-duplicates true
                       :ns-exclude-regex "some-ns.*"
                       :config {:linters {:unused-public-var {:level :off}}}}}}
```

**Describe alternatives you've considered**
Only namespace level and command line input configs merge over project config. Both of these possibilities are problematic, especially when using clojure-lsp. 

**Additional context**
PR following shortly.

**Comment by ericdallo** [comment]
@staifa I understand your problem but I wonder if it's not possible to fix it using an already existing solution: IIRC clj-kondo already supports custom config in `$XDG_CONFIG_HOME`, wouldn't adding your custom editor config there would be enough?

**Comment by staifa** [comment]
> @staifa I understand your problem but I wonder if it's not possible to fix it using an already existing solution: IIRC clj-kondo already supports custom config in `$XDG_CONFIG_HOME`, wouldn't adding your custom editor config there would be enough?

I tried that not too long ago, but home config didn't override the project config, I spent several hours trying to make it work. The problem is that when this stuff doesn't work, you're usually up for a deep dive into the sources and not everyone has time or patience to do so. The solution I proposed here is foolproof and just works. I can give the home config another shot later today though, just to be sure.

**Comment by ericdallo** [comment]
@staifa my concern is having a config hell, ATM clojure-lsp doesn't change clj-kondo config or allow any overrides because clj-kondo config management is pretty good, so it seems that for your case you want that clj-kondo allow a generic home config override a project specific config, so I wonder if clj-kondo should support that instead of clojure-lsp allow a custom config to override kondo config.

I'm not saying your suggestion is not an alternative, it's just that if we could still have each lib managing its own configs without other libs overriding, would be best for sanity, issues debugging and documentation IMO.

Maybe @borkdude can give his opinion here

**Comment by staifa** [comment]
@ericdallo Yes, your points are definitely valid and I'm well aware of them. I just opted for the easiest way here after weeks/months of waiting for a solution to come around and trying to make it work in some more or less hacky way...

**Comment by borkdude** [comment]
clj-kondo supports this by allowing `:config-paths ["your-extra-config"]` which will merge the config from the your-extra-config dir, and it ignores this when it doesn't exist.

**Comment by ericdallo** [comment]
@staifa is that enough for your case?

**Comment by staifa** [comment]
@borkdude Just verified. `:config-paths ["your-extra-config"]` doesn't override the project config. Only keys that are not present in the project config are merged in. It's stated in clj-kondo docs as well.

```
The configurations are merged in the following order, where a later config overrides an earlier config:

home dir config
:config-paths in project config
project config
command line config
namespace local config
```

I'm running latest clj-kondo. Am I missing something here?

**Comment by borkdude** [comment]
Try `:config-paths ^:replace [...]`

**Comment by staifa** [comment]
@borkdude That would mean adding the command line config when starting clj-kondo from clojure-lsp, which is messier than my proposed solution imo...

**Comment by ericdallo** [comment]
@staifa not really, I think borkdude just mentioned this is already possible via the 2 existing entrypoints: `CLI`, via the `--config` and `JVM` via the `:config` that clojure-lsp passes, and your proposed PR uses the latter one which is really the solution.

**Comment by ericdallo** [comment]
As I said, it's a solution indeed, my only concern is that we would have clojure-lsp configs with clj-kondo configs inside, not sure how bad it's is, but it's certainly a little bit confusing for users

**Comment by staifa** [comment]
@ericdallo I actually came up with this solution when I was checking how I could pass the command line config via clojure-lsp and noticed that the code already manipulates the kondo config. But the more I think about it, the more it makes sense to change this in clj-kondo. Just by quickly looking into the code, I could more or less easily implement another metadata hint for `:config-paths`, something like `:config-paths ^:override [...]`, that would just switch the order in which the configs are merged, what do you think @borkdude ?

**Comment by borkdude** [comment]
`:config-paths` was invented for library configurations that you can opt-in to, while still being able to override them in your project.

But sometimes it's convenient for contributors to override the common project configuration for their local development.

Maybe we can have `:extra-config-paths` which get merged after the project config is merged.

**Comment by ericdallo** [comment]
Yeah, I like the idea of supporting that on kondo side as well.
`:extra-config-paths` doesn't make clear the difference between :config-paths, so maybe `override-config-paths` ? not sure, naming is hard indeed

**Comment by borkdude** [comment]
In deps.edn, the name `:extra-` is used when you want to add more stuff on top of what's in the project configuration.

**Comment by ericdallo** [comment]
I see, @staifa what do you think about that? if agreed, we could open a issue on clj-kondo with a possible follow-up PR if you want

**Comment by staifa** [comment]
This makes more sense in my opinion https://github.com/clj-kondo/clj-kondo/issues/1891
Ok to close @ericdallo ?

**Comment by staifa** [comment]
This makes more sense in my opinion https://github.com/clj-kondo/clj-kondo/issues/1891
Ok to close @ericdallo ?

**Comment by ericdallo** [comment]
Thank you both!
