### ISSUE TITLE
clojure-lsp didn't support single file, is it made by design or my LSP client's problem?

### ISSUE THREAD

**Issue by suliveevil** [clojure-lsp/clojure-lsp#1402]
**Describe the bug**

My LSP client says that clojure-lsp didn't support single file.

<img width="832" alt="截屏2022-12-02 15 10 51" src="https://user-images.githubusercontent.com/35763237/205236408-56e6a12c-9948-4696-b09a-04c16488e6d8.png">

**To Reproduce**

1. install Emacs
2. install clojure-mode lsp-bridge clojure-lsp
3. open a single EDN file which is not under a git repo

**Expected behavior**

support EDN file format

**User details (please complete the following information):**
 - OS: macOS 13.0.1
 - Version: clojure-lsp 2022.11.03-00.16.44-nightly    clj-kondo 2022.11.02

**Additional context**

I'm Emacs newbie, and know nothing about clojure, just want to format my EDN file.

**Comment by ericdallo** [comment]
It does supports single files with some limitations, so we need to understand why your lsp client is saying that

**Comment by ericdallo** [comment]
We probably need to change [here](https://github.com/manateelazycat/lsp-bridge/blob/master/langserver/clojure-lsp.json#L6)

**Comment by suliveevil** [comment]
Thank you very much, I will change it and PR to lsp-bridge.
