### ISSUE TITLE
Does clojure-lsp implement progress endpoints ?

### ISSUE THREAD

**Issue by thecontinium** [clojure-lsp/clojure-lsp#1409]
Please see [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#progress)

**Comment by ericdallo** [comment]
Yes, currently we use this for startup and only there, but I do know vscode doesn't show that, only Emacs, not sure about vim too

![2022-12-07_11-19](https://user-images.githubusercontent.com/7820865/206203596-51c43a2b-d4d6-4975-88ed-9dda55e35d4c.png)

**Comment by thecontinium** [comment]
Ah I see only on startup.

FYI: In Neovim you can see it using [Fidget](https://www.lovegardenbirds.co.uk/garden-bird-suet-food/suet-blocks-cakes)

Thanks

**Comment by andreiox** [comment]
Did you managed to make it work, @thecontinium? tsserver works with fidget but clojure-lsp doesn´t.
