### ISSUE TITLE
latest release crashes with GLIBC not found error 

### ISSUE THREAD

**Issue by robertfw** [clojure-lsp/clojure-lsp#1415]
**Describe the bug**
After updating `clojure-lsp`, it crashes with an error about specific versions of GLIBC not being found

```
robertfw@orion:~$ clojure-lsp --version
clojure-lsp 2022.05.03-12.35.40
clj-kondo 2022.04.26-SNAPSHOT

robertfw@orion:~$ sudo bash < <(curl -s https://raw.githubusercontent.com/clojure-lsp/clojure-lsp/master/install)
Downloading https://github.com/clojure-lsp/clojure-lsp/releases/download/2022.12.09-15.51.10/clojure-lsp-native-linux-amd64.zip to /tmp/tmp.IfoNRy4tk4
Moving /usr/local/bin/clojure-lsp to /usr/local/bin/clojure-lsp.old
Successfully installed clojure-lsp in /usr/local/bin

robertfw@orion:~$ clojure-lsp --version
clojure-lsp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by clojure-lsp)
clojure-lsp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by clojure-lsp)
```

**To Reproduce**

1. Update `clojure-lsp` to latest version (both master and nightly were triggering the issue)
2. run `clojure-lsp --version`
3. See error

**Expected behavior**
no error :)

**Additional context**
[Slack thread with details from Borkdude about similar issue in clj-kondo due to build environment using too new version of glibc](https://clojurians.slack.com/archives/CPABC1H61/p1670788653853229)

**Comment by borkdude** [comment]
Workaround: add `--static`.

**Comment by ericdallo** [comment]
@robertfw I [fixed](https://github.com/clojure-lsp/clojure-lsp/commit/0895a3d836a5fddcc2a59b1091252b16a1de738f) the script to always install static binaries and fixed the CI for next release use a stable ubuntu image, your install command should be fixed, I'm not sure if a new release is necessary just to fix the non static one, but will close this for now, LMK if any more issues
