### ISSUE TITLE
Quick typing leads to inaccurate completion suggestions

### ISSUE THREAD

**Issue by orestis** [clojure-lsp/clojure-lsp#1425]
**Describe the bug**

Typing fast, in the context of creating a new local scope with restructuring (defn/let/etc.) results in giving misleading completions. Video shows the issue:

https://user-images.githubusercontent.com/9217/209626202-3692f19e-e267-44ae-9867-6ec5fa4f384f.mov

Link to Slack discussion: https://clojurians.slack.com/archives/CBE668G4R/p1670878025727979

**To Reproduce**

Quickly type:

```
(defn foo [{:keys [bar baz]}]
  (let [v {:bar ba|}]) ; <- cursor here
```

**Expected behavior**

I would expect to be offered completions `bar`, `baz`.

Instead I see only `:bar`.

**Screenshots**

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
ADD JSON HERE
</pre>
</details>

<details>
 <summary><b>Log - clojure-lsp</b></summary>
<pre>
ADD HERE
</pre>
</details>

**User details (please complete the following information):**
 - OS: macOS
 - Editor VSCode (Calva)
 - Version: `2022.12.09-16.00.34-nightly`

**Additional context**

**Comment by ericdallo** [comment]
It should be fixed on master!

**Comment by ericdallo** [comment]
@orestis we changed the default behavior again on master giving the performance issue introduced, check [here ](https://github.com/clojure-lsp/clojure-lsp/issues/1487)for more details.

To fix this issue you should add a setting `:completion :analysis-type` with the value of `:slow-but-accurate`

**Comment by orestis** [comment]
Personalised heads-up, love it! Thank you so much @ericdallo !
