### ISSUE TITLE
Include referred vars in completion items

### ISSUE THREAD

**Issue by borkdude** [clojure-lsp/clojure-lsp#1440]
Example:

```
(require '[clojure.set :refer [intersection]])

i<TAB>
```

A quote from @ericdallo on Slack:

> indeed we don't include in completion var-usages, but we could include var-usages with :refer true , so please create a issue for that

**Comment by ericdallo** [comment]
Done!
![image](https://user-images.githubusercontent.com/7820865/210670666-db5126e1-84e3-45de-9f9a-753c0c84964c.png)

**Comment by borkdude** [comment]
Awesome!
