### ISSUE TITLE
Support navigation of quoted symbols

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#1446]
https://github.com/clj-kondo/clj-kondo/issues/1902#issuecomment-1378529454

**Comment by borkdude** [comment]
Made a PR here: https://github.com/clojure-lsp/clojure-lsp/pull/1447

This makes the following navigation work:

![viewer-fn-nav](https://user-images.githubusercontent.com/284934/211887915-99a445af-af21-4bff-bd3f-ae90aa00af22.gif)
![exec-fn-nav](https://user-images.githubusercontent.com/284934/211887920-26bc20a5-5102-4f7b-81f1-0db37f278513.gif)

cc @mk
