### ISSUE TITLE
Not linting files without a namespace or with extension .edn

### ISSUE THREAD

**Issue by pedroserigatto** [clojure-lsp/clojure-lsp#1452]
**Describe the bug**
`clojure-lsp` doesn't consider files in the source-path that don't have a namespace
Also doesn't consider `.edn` files

**To Reproduce**

1. Create a `.clj` file in your project, write some unformatted clojure code in it but don't declare the `namespace`
2. Create a `.edn` file in your project, write some unformatted clojure code in it
3. Assert that these files belong to the `source-path`
4. Run `clojure-lsp clean-ns`
5. Notice your files weren't linted

**Expected behavior**
I expected that `clojure-lsp` would lint all files (clojure and `edn`) belonging to the `source-path`, regardless of it having a declared namespace

**User details (please complete the following information):**
 - OS: MacOS 13.1
 - Version: 
```
clojure-lsp 2022.12.09-15.51.10
clj-kondo 2022.12.08
```

**Additional context**
It might be worth mentioning that I use the Lein version of clojure-lsp:
`[com.github.clojure-lsp/lein-clojure-lsp "1.3.17"]`

**Comment by ericdallo** [comment]
Fixed on master/nighly build!
