### ISSUE TITLE
cli diagnostics report 0-indexed line numbers on errorformat string

### ISSUE THREAD

**Issue by brobsc** [clojure-lsp/clojure-lsp#1459]
**Describe the bug**
`clojure-lsp diagnostics` reports line/column numbers are 0-indexed on its `errorformat`-formatted output.

**To Reproduce**

1. Run `clojure-lsp diagnostics --raw`
2. See output
3. Compare against `clj-kondo --lint` against same files

**Expected behavior**
As a CLI tool, should report line and column numbers as expected by editors (vim) and other external tools (or at least provide an appropriate `-o` option).

clj-kondo (expected):
```
./src/report.clj:3:16: warning: unused binding args
```

clojure-lsp (got):
```
src/report.clj:0:4: error: [namespace-name-mismatch] Namespace name does not match file name: reporta
src/report.clj:2:15: warning: [unused-binding] unused binding args
```

<details>
 <summary><b>clojure-lsp output</b></summary>
<pre>
src/report.clj:2:15: warning: [unused-binding] unused binding args
</pre>
</details>

**User details (please complete the following information):**
 - OS: macOS (-irrelevant)
 - Version: clojure-lsp 2022.12.09-16.00.34-nightly

**Additional context**
Some other tools work with errorformat output, and they expect line numbers to count from 1.. as a standard (clj-kondo output is correct for instance) 

minor: while at it, probably a good idea to also preserve the relative path `./` on the filepath (see outputs)

**Comment by ericdallo** [comment]
Thanks for the report, I thing makes sense to output the same a kondo outputs.

> minor: while at it, probably a good idea to also preserve the relative path ./ on the filepath (see outputs)

Hum, makes sense, will take a look how hard would be to improve that

**Comment by ericdallo** [comment]
I couldn't find a way to improve the `./` the way we are already relativing the paths, but this issue should be fixed

**Comment by brobsc** [comment]
awesome, many thanks!

> I couldn't find a way to improve the ./ the way we are already relativing the paths, but this issue should be fixed

not *currently* causing any issues. Just a suggestion to stick with the standard (some other tool might expect it, I don't know...)
