### ISSUE TITLE
Typo in `clean-ns` summary line

### ISSUE THREAD

**Issue by dpsutton** [clojure-lsp/clojure-lsp#1467]
**Describe the bug**
Super trivial, but the summary for `clean-ns` is "Cleared N namespaces" as opposed to "Cleaned"

**To Reproduce**
```
# in java.jdbc
❯ clojure-lsp clean-ns
[100%] Project analyzed
Checking namespaces...
Cleaned clojure.java.jdbc-test
Cleaned clojure.java.jdbc.spec
Cleaned clojure.java.jdbc.utilities-test
Cleaned clojure.java.jdbc
Cleaned clojure.java.jdbc.datafy
Cleared 5 namespaces
```

1. Clone project XXX
2. Run clojure-lsp clean-ns --flags... 
3. See error

https://github.com/clojure-lsp/clojure-lsp/blob/master/lib/src/clojure_lsp/internal_api.clj#L300

**Expected behavior**
Just a typo "Cleared 5 namespaces" -> "Cleaned 5 namespaces"

**Comment by ericdallo** [comment]
My bad, not a native speaker 😛 
Fixed!
