### ISSUE TITLE
Populating the LSP cache from the command line causes issues with lsp-mode in Emacs

### ISSUE THREAD

**Issue by lassemaatta** [clojure-lsp/clojure-lsp#1473]
**Describe the bug**
If the `.lsp/.cache` cache is populated by running `clojure-lsp` from the command line, the cache contents will cause problems with `lsp-mode` in emacs. See [this](https://github.com/emacs-lsp/lsp-mode/issues/3930) issue for the original symptoms (TLDR: emacs doesn't like `zipfile://` URIs.).

**To Reproduce**

1. Clone the [clojure-sample](https://github.com/ericdallo/clojure-sample) project
2. Make sure the `.lsp/.cache` folder does not exist
3. Make sure you DO NOT open the project in emacs
4. Run `clojure-lsp diagnostics` from the command line, which will populate the cache
5. Open project in emacs
6. Try to apply `lsp-find-definition` to a function call, which refers to a library function. For example the `testing` macro in the `clojure-sample.core-test` namespace
7. See error

**Expected behavior**
Populating the cache from the command line should not break `lsp-mode` in emacs due to `zipfile://` URIs to libraries..

**User details (please complete the following information):**
 - OS: Arch Linux
 - Version: `clojure-lsp 2023.01.26-11.08.16` + `clj-kondo 2023.01.20`

**Additional context**

**Comment by ericdallo** [comment]
thanks, I'll fix it including the dependency-scheme setting into the db, so if they don't match we invalidate the cache and re-analyze

**Comment by ericdallo** [comment]
@lassemaatta it should be fixed on master/nightly builds, LMK if any issues!
