### ISSUE TITLE
Enhance hover to search clojuredocs on CLJS 

### ISSUE THREAD

**Issue by RCmerci** [clojure-lsp/clojure-lsp#1506]
**Is your feature request related to a problem? Please describe.**
when writing cljs codes, hovering on fn, and the returned doc doesn't contain clojuredocs.

**Describe the solution you'd like**
when file-type is :cljs, replace(ns-sym "cljs" "clojure")

**Describe alternatives you've considered**
nil

**Additional context**
nil

**Comment by ericdallo** [comment]
Fixed on #1507
