### ISSUE TITLE
diagnostics: support different ranges

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#1530]
As mentioned [here](https://clojurians.slack.com/archives/CPABC1H61/p1679240936214769?thread_ts=1678981815.810429&cid=CPABC1H61), we only support showing diagnostics ranges for the whole expr, but there are users that prefer showing only the start of each expr, the trade-off is less intrusive visual but less noticeable.

We should add a option to support both behaviors defaulting to current one

**Comment by borkdude** [comment]
This is how I implemented it for clj-kondo.lsp:

https://github.com/clj-kondo/clj-kondo.lsp/blob/9db9ec3be0d5aeca8b76097010eeee4b2c4e2fe3/server/src/clj_kondo/lsp_server/impl/server.clj#L82-L88

and this is what it looks like:

<img width="264" alt="Screenshot 2023-03-19 at 16 48 05" src="https://user-images.githubusercontent.com/284934/226188152-5211ba70-8262-4bcf-969e-5b0468ad3485.png">

**Comment by ericdallo** [comment]
Done, the new setting is `:diagnostics :range-type`, which supports `:full` or `:simple` with default value of `:full`

**Comment by borkdude** [comment]
Thanks, works like a charm
