### ISSUE TITLE
clojure.repl/doc support

### ISSUE THREAD

**Issue by paltom** [clojure-lsp/clojure-lsp#154]
Does `clojure-lsp` support documentation from built-in functions/macros?

I have setup basic project with `lein new app test`.  `clojure-lsp` starts correctly (I think), provides diagnostics, completions, etc.
However, it does not provide documentation for clojure's functions and macros, e.g. `println`. As you can see below, server returns empty documentation string. It does provide documentation for newly created functions, e.g. `-main`. Am I missing something in configuration?

I'm using `clojure-lsp` with coc.nvim and Neovim on Windows.

Source file:
```clojure
(ns test.core
  (:gen-class))

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (println "Hello, World!"))
```

Response for `-main`:
```
[Trace - 18:55:19] Received response 'textDocument/hover - (4)' in 2ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```clojure\ntest.core/-main \n```\n```clojure\n[& args]\n```\nI don't do a whole lot ... yet.\n\n----\nlsp: :declare :public"
    },
    "range": {
        "start": {
            "line": 3,
            "character": 6
        },
        "end": {
            "line": 3,
            "character": 11
        }
    }
}
```

Response for `println`:
```
[Trace - 18:56:08] Received response 'textDocument/hover - (5)' in 2ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```clojure\n \n```\n"
    },
    "range": {
        "start": {
            "line": 8,
            "character": 1
        },
        "end": {
            "line": 8,
            "character": 6
        }
    }
}
```

**Comment by snoe** [comment]
We don't use repl/doc but we do expect docs to come in, make sure you have your project classpaths setup but as long as clojure jar is in the path it should find it.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/105012/86167243-698dfc00-bad3-11ea-8842-5994c4fec98d.png">

**Comment by paltom** [comment]
Thanks, @snoe for quick response. This is weird, all I did was to reboot my laptop and it now seems to (mostly) work. Perhaps some global $PATH settings were not updated, although I'm pretty sure that I rebooted system after installing lein etc.

It still doesn't work in some cases, see below
![image](https://user-images.githubusercontent.com/38882604/86169280-ab419580-bb19-11ea-8550-fa21e32f80fd.png)
![image](https://user-images.githubusercontent.com/38882604/86169350-c57b7380-bb19-11ea-89ff-59b1d2ca5e7b.png)

**Comment by snoe** [comment]
yeah, map is weird, clojure.core does `(def map)` then later `(defn map <docs> ...)`... so we should take the last found declaration instead of the first. `do` is a special form and might need hardcoding or something else.

**Comment by paltom** [comment]
Wouldn't using the output from `clojure.repl/doc` be a solution? I don't know if it's easy to use `doc` in clojure-lsp, but it seems to handle all above cases.

**Comment by divs1210** [comment]
@paltom All the code will have to be evaluated in order for `clojure.repl/doc`.

clojure-lsp is supposed to be static, not repl-based like CIDER.

I will raise a PR to fix [this](https://github.com/clojure-lsp/clojure-lsp/issues/154#issuecomment-652065976).

**Comment by ericdallo** [comment]
This does not depends on clojure-lsp anymore, after #261 we removed all parsing logic from clojure-lsp replaced by `clj-kondo`, it should fix a lot of bugs and issues, but it does not get the `map` docs still, if you think this is should clj-kondo should provide, you can open a PR there
