### ISSUE TITLE
LSP-based highlighting of keyword namespace's `:` sign isn't consistent with how CIDER formats it

### ISSUE THREAD

**Issue by Invertisment** [clojure-lsp/clojure-lsp#1550]
When I highlight my keyword using Emacs (CIDER and no LSP) then `:` sign is different from what the namespace color is.
When I do it on clojure-lsp-based highlighting mode then color of `:` is the same as namespace's color of that keyword.

CIDER on my Spacemacs:
![image](https://user-images.githubusercontent.com/1641263/232251268-7bdfcc43-1b8d-405a-b1b3-01b2f13cd5b0.png)

With current LSP implementation (my nvim that uses clojure-lsp server):
![image](https://user-images.githubusercontent.com/1641263/232251254-cd2f5b0c-29a8-4aaa-b54c-cc61910e374e.png)

**Describe the solution you'd like**
I think that `:` should be excluded from highlighting so that the editor's highlighting plugin would highlight it instead.

**Describe alternatives you've considered**
I used the https://github.com/clojure-vim/clojure.vim/ where I implemented the same `:` highlighting and it worked. But as nvim updated to 0.9.0 they now force the LSP highlighting and I don't yet know how to opt-out.

**Additional context**
```
> clojure-lsp --version
clojure-lsp 2023.02.27-13.12.12
clj-kondo 2023.02.17
```
```
> nvim --version
NVIM v0.9.0
```

**Comment by ericdallo** [comment]
we should probably not exclude `:`, but color it as something else, otherwise the `:` color may differ from editor to editor

**Comment by Invertisment** [comment]
If you don't exclude `:` then you probably would need to color `/` because currently it's not colored too.
I suggested including because it would be less moving parts overall.

**Comment by Invertisment** [comment]
> color may differ from editor to editor

If you configure your editors the same way then they won't be different. Is this even a good goal to try to achieve?

And from what I understand it's probably a good idea to think that editors won't add any highlighting of their own when LSP server is used. But this doesn't solve the question of whether you want to color some part of a token or not.

**Comment by ericdallo** [comment]
I double checked and you are correct, we should exclude the `:` or color it differently from the namespace, I think excluding it is an easier approach for now.
@victorpigmeo maybe you would like to work on that since you touched on that part recently?

**Comment by victorpigmeo** [comment]
I'll take a look
