### ISSUE TITLE
Full qualified symbol's namespace doesn't have a separate color

### ISSUE THREAD

**Issue by Invertisment** [clojure-lsp/clojure-lsp#1551]
**Is your feature request related to a problem? Please describe.**
When I use LSP highlighting (I disabled other highlighting for this screenshot) and import a symbol with an alias `subs` then this alias has a color.
When I don't use the alias but instead use full namespace name then it doesn't have a separate color and it's colored as function:
![image](https://user-images.githubusercontent.com/1641263/232252114-1454ef9c-69c2-4f77-8896-bf87bade587f.png)

**Describe the solution you'd like**
Fully qualified symbol (line 5) should have the same namespace and `/` handling as aliased reference (line 4).

**Describe alternatives you've considered**
-

**Additional context**
```
> clojure-lsp --version
clojure-lsp 2023.02.27-13.12.12
clj-kondo 2023.02.17
```
```
> nvim --version
NVIM v0.9.0
```

**Comment by victorpigmeo** [comment]
https://github.com/clojure-lsp/clojure-lsp/pull/1591
