### ISSUE TITLE
Support auto-gensym on syntax-quote

### ISSUE THREAD

**Issue by daniel-quintoandar** [clojure-lsp/clojure-lsp#156]
I'm not sure if I've misconfigured something or if it doesn't work at all...
![Screenshot from 2020-07-15 23-17-00](https://user-images.githubusercontent.com/65167584/87619163-efc05a00-c6f1-11ea-8f6e-21c75ae317fb.png)

I'm using NeoVim with coc.nvim and built clojure-lsp with `lein bin` from master using java 8

**Comment by ericdallo** [comment]
This should work now after #261 since clj-kondo takes care of that logic :)
