### ISSUE TITLE
Formatting ignores {:style/indent} macro

### ISSUE THREAD

**Issue by zikajk** [clojure-lsp/clojure-lsp#1561]
**Describe the bug**
- When running `eglot-format-buffer` from Emacs, macros aren't formatted according to their` {:style/indent} `macro.
- It is related to this feature https://github.com/clojure-lsp/clojure-lsp/pull/1471

**To Reproduce**
1. Require some library with a macro that has mentioned metadata (for example https://github.com/metosin/compojure-api/blob/master/src/compojure/api/core.clj)
2. Use `c/context` in your code and reformat the buffer with LSP
3. It gets formatted with _indent 1_ but it has `{:style/indent 2}`

**Expected behavior**
Metadata should be respected and `c/context` should have indent 2.

**User details (please complete the following information):**
 - OS: [MacOS]
 - Editor: Emacs
 - Version: clojure-lsp 2023.04.19-12.49.36-nightly
clj-kondo 2023.04.15-SNAPSHOT

**Comment by ericdallo** [comment]
I tested and this seems to be working on latest clojure-lsp, I created [this sample](https://github.com/ericdallo/clojure-sample/blob/style-indent/src/clojure_sample/client.clj#L6), could you test if that works for you? I'm closing the issue unless we find it's a problem

**Comment by zikajk** [comment]
I tested as well, the problem is not there anymore.
