### ISSUE TITLE
Support external (non-custom) linters like kibit

### ISSUE THREAD

**Issue by port19x** [clojure-lsp/clojure-lsp#1563]
**Is your feature request related to a problem? Please describe.**
It's pretty annoying to configure flycheck in emacs.
It's also pretty annoying to only lint before a commit with the very manual `clj -M:kibit`.

**Describe the solution you'd like**
I'm not sure how these would integrate.
Perhaps they should be disabled by default and enabled via some easy launch flag.
I explicitly want a non-generic solution: custom linter rules are already supported, as are clj-kondo hooks, I'm aware.
This should enable some agreed upon set of additional linters.
I'm proposing kibit, eastwood and antq.

**Describe alternatives you've considered**
I guess I can use flycheck-clojure if I really have to, tho in my limited testing that's not the best experience.

**Additional context**
Nice talk!

**Comment by ericdallo** [comment]
thank you!
So, the issue adding more integrations is the need to add more dependencies to clojure-lsp, if we could add that in a optional-way would be great, also, I wonder what features those libs provide that are not already available via clojure-lsp built-in, clj-kondo and cljfmt. Kibit for example, I can see clj-kondo doing that, actually clj-kondo already has some checks related to code idiomatic.

**Comment by port19x** [comment]
I haven't run into many things that kibit warns me about that clj-kondo lints.
My usecase for kibit is mostly to be made aware of built-in composite functions such as `(fnext x)` over `(first (next x))` or `(not= a b)` over `(not (= a b))`.
`eastwood` is less necessary, as most of it's rules are covered by clj-kondo.
`antq` is neat to check for dependency updates, but I can imagine there are alternative ways to introduce equivalent functionality.

**Comment by ericdallo** [comment]
Yeah, I'm wondering if we can support those missing kibitz cool features in clj-kondo that would avoid add kibitz as another dep WDYT @borkdude ?

about antq, we can probably discuss having it in the future indeed, I can see how convenient it is but it's not entirely related to linting, but upgrade deps

**Comment by borkdude** [comment]
@ericdallo I think https://github.com/noahtheduke/splint is the spiritual successor to kibit. It's much faster since it doesn't rely on core.logic and it also works with babashka. There are some things that it detects like `(= true x)` => `(true? x)` that I want to have in clj-kondo as well. I'd say let's just port the most popular ones. A feature that splint has is that you can define your own linters in terms of matching DSL which is quite neat. Not sure about the performance impact of that if we'd support something like that in clj-kondo.

**Comment by ericdallo** [comment]
Sounds great, we can start discussing in clj-kondo

**Comment by port19x** [comment]
> Yeah, I'm wondering if we can support those missing kibitz cool features in clj-kondo that would avoid add kibitz as another dep WDYT @borkdude ?
> 
> about antq, we can probably discuss having it in the future indeed, I can see how convenient it is but it's not entirely related to linting, but upgrade deps

No need for `antq` just figured out that `cljr-update-project-dependencies` exists
