### ISSUE TITLE
CLI find-all-references

### ISSUE THREAD

**Issue by shaunlebron** [clojure-lsp/clojure-lsp#1572]
For those of us who have trouble setting up clojure-lsp in an editor, it would be nice to be able query all references to a symbol from the command line.  Thanks

**Comment by ericdallo** [comment]
Done @shaunlebron !
Now clojure-lsp has the `references` feature available both on API and CLI (probably more useful via API than CLI), LMK if any issues

**Comment by shaunlebron** [comment]
Thank you! 🙌
