### ISSUE TITLE
File renames changing src files when renaming a test file

### ISSUE THREAD

**Issue by victorpigmeo** [clojure-lsp/clojure-lsp#1574]
**Describe the bug**
When I rename a `test` file, all the imports on my `src` files are changed

**To Reproduce**
1. Clone or open a [project](https://github.com/ericdallo/clojure-sample)
2. Create a file on the `test` directory that has the same `ns` as any `src` file. (ex: `clojure-sample.lsp.call-hierarchy.a`)
3. Rename the file (SPC + f + R on doom-emacs)
4. All the imports of that `ns` will change on `src` files.

**Expected behavior**
Rename only the `test` files if I change a test file.

**User details (please complete the following information):**
 - OS: Debian 11
 - Editor emacs (doom-emacs)
 - Version: clojure-lsp 2023.01.26-11.08.16 / clj-kondo 2023.01.20

**Additional context**
It is not a critical bug but could lead to some errors if we don't pay attention.

**Comment by ericdallo** [comment]
The issue should be fixed [here](https://github.com/clojure-lsp/clojure-lsp/blob/5e3584014f2ac9c13a877dfd7984383346d81609/lib/src/clojure_lsp/feature/file_management.clj#L381-L383), if we can't find reliable the namespace we should at least fail with a message to client saying we can't really apply those changes and let user rename it manually.

**Comment by ericdallo** [comment]
@janosmeszaros will work on that
