### ISSUE TITLE
Support JS lib names in completion ns-to-add results and add-require-suggestion command

### ISSUE THREAD

**Issue by Deraen** [clojure-lsp/clojure-lsp#1586]
**Is your feature request related to a problem? Please describe.**

Clojure-lsp can provide require/alias suggestions on completion based on existing requires in the workspace.

For example, if `(:require ["@mui/material/Box$default" :as Box])` is already used, completion on `Box` in another namespace will suggest `Box` alias, with detail field `alias to: @mui/material/Box$default`. But `ns-to-add` data will be `material/Box$default` because(?) the value is coerced to a Clojure symbol at some point?

It is also probable that when the completion item is selected, and the edit is applied (`completionItem/resolve` if I understand correctly), the values are handled as symbols.

Additionally, the same suggestions are available as Code actions, in this case, the code action will have `add-require-suggestion` command the `arguments` has the correct full JS lib require. However, when the action is executed, clojure-lsp will throw error about Invalid symbol.

**Describe the solution you'd like**

If the completion suggestion is created from an existing require form where the namespace is a string, the completion item, and the edit should use the correct (and full) value and keep it as a string.

If I'm using `(:require ["react" :as react])` I'd prefer if `react/` completion also kept using the string as it is common to use strings with all JS libs to separate them from Clojure namespaces.

`add-require-suggestion` command selected from Code actions should work with these JS lib suggestions.

**Describe alternatives you've considered**

-

**Additional context**

Related: https://github.com/clojure-lsp/clojure-lsp/issues/327, but this is just using existing aliases on the project, so there is no need to inspect the JS libs.

**Comment by ericdallo** [comment]
Thanks, I think we never went deep to support cljs requires like that, I suspect we would need some changes in clj-kondo as well, as for kondo analysis `"@mui/material/Box$default" ` is just a string, not a namespace-usage like a clj symbol require.

**Comment by ericdallo** [comment]
Tests like you did in your draft PR is a good start for that, well done

**Comment by ericdallo** [comment]
Fixed by #1587
