### ISSUE TITLE
Does hover work with clojure.core functions?

### ISSUE THREAD

**Issue by knubie** [clojure-lsp/clojure-lsp#159]
I'm using clojure-lsp with `LanguageClient-neovim` and when I call hover on any clojure.core function, nothing happens. It seems to work fine with functions I've defined however.

**Comment by snoe** [comment]
Most core functions should have hover work, you might need to look at `project-specs` options to make sure your classpath is read in.

**Comment by knubie** [comment]
Thanks for the tip @snoe. I'm using shadow-cljs, so I added this `.lsp/config.edn` file:
```clj
{"project-specs" [{:project-path "shadow-cljs.edn"
                   :classpath-cmd ["yarn" "--silent" "shadow-cljs" "classpath"]}]}
```

But I'm still seeing the same behavior. Is there some log file, or debug mode I can use to get more info?

**Comment by ericdallo** [comment]
@knubie could you test it again and re open the issue if not working? 
We had a huge refactor which made us use clj-kondo for almost everything, so this should work properly

**Comment by eccentric-j** [comment]
Hitting this myself with latest clojure-lsp and neovim. 

I get signatures for custom functions, but only name for core functions. Also a shadow-cljs project.
