### ISSUE TITLE
Completion for qualified keywords

### ISSUE THREAD

**Issue by lassemaatta** [clojure-lsp/clojure-lsp#1599]
**Is your feature request related to a problem? Please describe.**

At the moment completion for keywords only considers keywords present in the current file (see [discussion](https://clojurians.slack.com/archives/CPABC1H61/p1687521708133669)). In some use cases (e.g. datomic attributes), the same qualified keywords (e.g. `:user/first-name`, `:user/email`..)  appear in many files and it would be really nice if `clojure-lsp` could complete `:user/|` (or maybe even just `:us|` )with the possible choices (`|` is the cursor).

**Describe the solution you'd like**

Perhaps `clojure-lsp` could try to keep track of such qualified keywords and suggest them when completing a matching prefix? There might be a lot of such keywords in a large program which might negatively affect the completion candidate calculations. Thus it might be a good idea to provide a configuration setting for controlling this behaviour. 

**Additional context**

I haven't really thought about namespaced keywords (`::quuz`, `::some-ns/bar`) and how they should be handled. It would certainly be nice if you have an alias `[my-project.some-ns :as foo]` and try to complete `::foo/|` then `clojure-lsp` could find the relevant candidates.

**Comment by ericdallo** [comment]
@lassemaatta I reworked most keyword completion support, now we support completion of namespaced keywords across all project, it should work both completing the namespace and the value of the namespaced keyword

**Comment by lassemaatta** [comment]
Awesome! I tested with the nightly and it seemed to work quite nicely.
