### ISSUE TITLE
understand `reagent/with-let` bindings

### ISSUE THREAD

**Issue by dpsutton** [clojure-lsp/clojure-lsp#160]
```
(r/with-let [edit-raw? (r/atom false)]
 ...
  (finally ....))
```

and in config.edn macrodefs:
`reagent.core/with-let [:bindings :bound-elements]`

also verify that it understands the `finally` form?

**Comment by ericdallo** [comment]
Sorry for the late response, we now rely on clj-kondo to parse/analysis, this should be handle by clj-kondo now anod probably will work, feel free to reopen otherwise.

**Comment by AjBreidenbach** [comment]
This resolved the issue for me https://github.com/clj-kondo/clj-kondo/issues/904#issuecomment-664638850
