### ISSUE TITLE
clean-ns returns error when there's nothing to change

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#1603]
**Describe the bug**
An error occurs when the clean-ns command is run but there's nothing to change.

In VS Code, this causes a pop up message.

Slack convos:
- https://clojurians.slack.com/archives/CBE668G4R/p1687911269838849
- https://clojurians.slack.com/archives/CPABC1H61/p1687979890280189

**To Reproduce**
A Calva users says they think they caused this with these VS Code settings:

```json
"editor.codeActionsOnSave": {

    "source.organizeImports": true,
    "source.fixAll": true
  },
```

I'm guessing if you try to run clean-ns in a file with no ns form (like in the example - that's the Calva output file), that error will happen. It _might_ also happen when there's an ns form but no changes are required, but I'm 

**Expected behavior**
No error occurs.

**Screenshots**

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
[Trace - 5:12:30 PM] Sending request 'workspace/executeCommand - (365)'.
Params: {
    "command": "clean-ns",
    "arguments": [
        "file:///Users/def/src/abc/.calva/output-window/output.calva-repl",
        0,
        0
    ]
}
[Trace - 5:12:30 PM] Received response 'workspace/executeCommand - (365)' in 2ms. Request failed: Nothing to change. (-32600).
[Error - 5:12:30 PM] Request workspace/executeCommand failed.
  Message: Nothing to change.
  Code: -32600 
</pre>
</details>

**User details (please complete the following information):**
Note: This was not experienced by me - I'm just reporting it.
 - OS: [e.g. ArchLinux, MacOS, Windows 10]
 - Editor [e.g. emacs, nvim, VSCode (Calva)]
 - Version: (post the result of `clojure-lsp --version`)

**Comment by mrkam2** [comment]
OS: MacOS
Editor: VSCode (Calva)
Version: as reported by Calva:
```
Calva is utilizing cider-nrepl and clojure-lsp to create this VS Code experience.
  nREPL dependencies configured:
    nrepl: 0.8.3
    cider-nrepl: 0.28.5
    cider/piggieback: 0.5.2
  clojure-lsp version configured: latest

If you are new to Calva, please see: https://calva.io/getting-started/
  And please consider the command: **Calva: Fire up the Getting Started REPL**

Calva version used: v2.0.372
clojure-lsp version used: 2023.05.04-19.38.01
clj-kondo version used: 2023.04.15-SNAPSHOT
```

**Comment by mrkam2** [comment]
Screenshot:
![image](https://github.com/clojure-lsp/clojure-lsp/assets/28267638/d71f7e26-052b-4301-90f9-84db64079608)

**Comment by ericdallo** [comment]
That only happens for files without ns indeed, fixed in nightly/master
