### ISSUE TITLE
:exclude-when-defined-by option doesn't work in CLI and Calva

### ISSUE THREAD

**Issue by mrkam2** [clojure-lsp/clojure-lsp#1604]
**Describe the bug**
As discussed in [slack](https://clojurians.slack.com/archives/CPABC1H61/p1688074746584709?thread_ts=1688068718.797849&cid=CPABC1H61), the following clj-kondo config doesn't silence unused public var info warnings for the macro:
```
 :linters {:clojure-lsp/unused-public-var
           {:exclude-when-defined-by #{clojure-sample.client/defabctest}}}}
```

**To Reproduce**

1. Clone [clojure_sample](https://github.com/ericdallo/clojure-sample/blob/lsp-unused-public-var-test/src/clojure_sample/client.clj).
2. Run `clojure-lsp diagnostics`.
3. See `src/clojure_sample/client.clj:11:13: info: [clojure-lsp/unused-public-var] Unused public var 'clojure-sample.client/my-test'` which should be suppressed.

**Expected behavior**
The warning shown above shouldn't appear.

<details>
 <summary><b>clojure-lsp output</b></summary>
<pre>
$ clojure-lsp --verbose diagnostics
[ 10%] Finding cache               [INFO] [DB] Reading transit analysis cache from /Users/akouznetsov/src/clojure-sample/clojure-sample/.lsp/.cache/db.transit.json db took 822ms
[INFO] :maintain-dep-graph 86ms
[ 15%] Discovering classpath       [INFO] Finding classpath via `/Users/akouznetsov/src/liftoff/tools/bin/clojure -A:test:dev -Spath`
[DEBUG] Classpath found, paths:  ["test" "src" "resources" "/Users/akouznetsov/.m2/repository/com/fulcrologic/guardrails/1.1.10/guardrails-1.1.10.jar" "/Users/akouznetsov/.m2/repository/nubank/matcher-combinators/3.3.1/matcher-combinators-3.3.1.jar" "/Users/akouznetsov/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar" "/Users/akouznetsov/.m2/repository/org/clojure/clojurescript/1.10.758/clojurescript-1.10.758.jar" "/Users/akouznetsov/.m2/repository/potemkin/potemkin/0.4.5/potemkin-0.4.5.jar" "/Users/akouznetsov/.m2/repository/expound/expound/0.8.7/expound-0.8.7.jar" "/Users/akouznetsov/.m2/repository/org/clojure/core.async/1.3.618/core.async-1.3.618.jar" "/Users/akouznetsov/.m2/repository/midje/midje/1.10.4/midje-1.10.4.jar" "/Users/akouznetsov/.m2/repository/org/clojure/math.combinatorics/0.1.6/math.combinatorics-0.1.6.jar" "/Users/akouznetsov/.m2/repository/org/clojure/core.specs.alpha/0.2.56/core.specs.alpha-0.2.56.jar" "/Users/akouznetsov/.m2/repository/org/clojure/spec.alpha/0.2.194/spec.alpha-0.2.194.jar" "/Users/akouznetsov/.m2/repository/com/cognitect/transit-clj/0.8.309/transit-clj-0.8.309.jar" "/Users/akouznetsov/.m2/repository/com/google/javascript/closure-compiler-unshaded/v20200315/closure-compiler-unshaded-v20200315.jar" "/Users/akouznetsov/.m2/repository/org/clojure/data.json/0.2.6/data.json-0.2.6.jar" "/Users/akouznetsov/.m2/repository/org/clojure/google-closure-library/0.0-20191016-6ae1f72f/google-closure-library-0.0-20191016-6ae1f72f.jar" "/Users/akouznetsov/.m2/repository/org/clojure/tools.reader/1.3.2/tools.reader-1.3.2.jar" "/Users/akouznetsov/.m2/repository/clj-tuple/clj-tuple/0.2.2/clj-tuple-0.2.2.jar" "/Users/akouznetsov/.m2/repository/riddley/riddley/0.1.12/riddley-0.1.12.jar" "/Users/akouznetsov/.m2/repository/org/clojure/tools.analyzer.jvm/1.1.0/tools.analyzer.jvm-1.1.0.jar" "/Users/akouznetsov/.m2/repository/clj-time/clj-time/0.15.1/clj-time-0.15.1.jar" "/Users/akouznetsov/.m2/repository/colorize/colorize/0.1.1/colorize-0.1.1.jar" "/Users/akouznetsov/.m2/repository/flare/flare/0.2.9/flare-0.2.9.jar" "/Users/akouznetsov/.m2/repository/io/aviso/pretty/0.1.37/pretty-0.1.37.jar" "/Users/akouznetsov/.m2/repository/marick/suchwow/6.0.2/suchwow-6.0.2.jar" "/Users/akouznetsov/.m2/repository/mvxcvi/puget/1.1.2/puget-1.1.2.jar" "/Users/akouznetsov/.m2/repository/org/clojure/core.unify/0.5.7/core.unify-0.5.7.jar" "/Users/akouznetsov/.m2/repository/org/clojure/test.check/0.10.0-alpha3/test.check-0.10.0-alpha3.jar" "/Users/akouznetsov/.m2/repository/org/clojure/tools.macro/0.1.5/tools.macro-0.1.5.jar" "/Users/akouznetsov/.m2/repository/org/clojure/tools.namespace/0.3.0/tools.namespace-0.3.0.jar" "/Users/akouznetsov/.m2/repository/org/tcrawley/dynapath/1.0.0/dynapath-1.0.0.jar" "/Users/akouznetsov/.m2/repository/slingshot/slingshot/0.12.2/slingshot-0.12.2.jar" "/Users/akouznetsov/.m2/repository/com/cognitect/transit-java/0.8.332/transit-java-0.8.332.jar" "/Users/akouznetsov/.m2/repository/args4j/args4j/2.0.26/args4j-2.0.26.jar" "/Users/akouznetsov/.m2/repository/com/google/code/gson/gson/2.7/gson-2.7.jar" "/Users/akouznetsov/.m2/repository/com/google/elemental2/elemental2-core/1.0.0-RC1/elemental2-core-1.0.0-RC1.jar" "/Users/akouznetsov/.m2/repository/com/google/errorprone/error_prone_annotations/2.3.1/error_prone_annotations-2.3.1.jar" "/Users/akouznetsov/.m2/repository/com/google/guava/guava/25.1-jre/guava-25.1-jre.jar" "/Users/akouznetsov/.m2/repository/com/google/javascript/closure-compiler-externs/v20200315/closure-compiler-externs-v20200315.jar" "/Users/akouznetsov/.m2/repository/com/google/jsinterop/base/1.0.0/base-1.0.0.jar" "/Users/akouznetsov/.m2/repository/com/google/jsinterop/jsinterop-annotations/1.0.2/jsinterop-annotations-1.0.2.jar" "/Users/akouznetsov/.m2/repository/com/google/protobuf/protobuf-java/3.11.1/protobuf-java-3.11.1.jar" "/Users/akouznetsov/.m2/repository/com/google/re2j/re2j/1.3/re2j-1.3.jar" "/Users/akouznetsov/.m2/repository/org/clojure/google-closure-library-third-party/0.0-20191016-6ae1f72f/google-closure-library-third-party-0.0-20191016-6ae1f72f.jar" "/Users/akouznetsov/.m2/repository/org/clojure/core.memoize/1.0.236/core.memoize-1.0.236.jar" "/Users/akouznetsov/.m2/repository/org/clojure/tools.analyzer/1.0.0/tools.analyzer-1.0.0.jar" "/Users/akouznetsov/.m2/repository/org/ow2/asm/asm/5.2/asm-5.2.jar" "/Users/akouznetsov/.m2/repository/joda-time/joda-time/2.10/joda-time-2.10.jar" "/Users/akouznetsov/.m2/repository/org/clojars/brenton/google-diff-match-patch/0.1/google-diff-match-patch-0.1.jar" "/Users/akouznetsov/.m2/repository/com/rpl/specter/1.0.5/specter-1.0.5.jar" "/Users/akouznetsov/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar" "/Users/akouznetsov/.m2/repository/environ/environ/1.1.0/environ-1.1.0.jar" "/Users/akouznetsov/.m2/repository/fipp/fipp/0.6.17/fipp-0.6.17.jar" "/Users/akouznetsov/.m2/repository/mvxcvi/arrangement/1.2.0/arrangement-1.2.0.jar" "/Users/akouznetsov/.m2/repository/org/clojure/java.classpath/0.2.3/java.classpath-0.2.3.jar" "/Users/akouznetsov/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.7/jackson-core-2.8.7.jar" "/Users/akouznetsov/.m2/repository/org/msgpack/msgpack/0.6.12/msgpack-0.6.12.jar" "/Users/akouznetsov/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar" "/Users/akouznetsov/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar" "/Users/akouznetsov/.m2/repository/org/checkerframework/checker-qual/2.0.0/checker-qual-2.0.0.jar" "/Users/akouznetsov/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar" "/Users/akouznetsov/.m2/repository/org/clojure/core.cache/1.0.207/core.cache-1.0.207.jar" "/Users/akouznetsov/.m2/repository/org/clojure/core.rrb-vector/0.0.14/core.rrb-vector-0.0.14.jar" "/Users/akouznetsov/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar" "/Users/akouznetsov/.m2/repository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar" "/Users/akouznetsov/.m2/repository/org/clojure/data.priority-map/1.0.0/data.priority-map-1.0.0.jar"]
[INFO] [Startup] Using source-paths from classpath: ["/Users/akouznetsov/src/clojure-sample/clojure-sample/test" "/Users/akouznetsov/src/clojure-sample/clojure-sample/resources" "/Users/akouznetsov/src/clojure-sample/clojure-sample/src"]
[ 20%] Copying kondo configs       [INFO] Copying kondo configs from classpath to project if any...
[WARN] Non-fatal error from clj-kondo: Configs copied:
- .clj-kondo/marick/midje

[INFO] Copied kondo configs, took 239ms secs.
[ 25%] Analyzing external classpath[INFO] Analyzing classpath for project root /Users/akouznetsov/src/clojure-sample/clojure-sample
[INFO] Analyzing 65 paths with clj-kondo
[ 44%] Analyzing external classpathConfigs copied:
- .clj-kondo/marick/midje

[INFO] External classpath paths analyzed, took 6095ms
[INFO] :maintain-dep-graph 13ms
[INFO] Manual GC after classpath scan took 78ms
[INFO] Caching db for next startup...
[INFO] [DB] Upserting transit analysis to /Users/akouznetsov/src/clojure-sample/clojure-sample/.lsp/.cache/db.transit.json cache took 809ms
[ 50%] Analyzing project files     [INFO] [Startup] Analyzing source paths for project root /Users/akouznetsov/src/clojure-sample/clojure-sample
[INFO] [Startup] Project only paths analyzed by clj-depend, took 0ms
[ 99%] Analyzing project files     No configs copied.
[INFO] :maintain-dep-graph 0ms
[INFO] Linting whole project for unused-public-var took 3ms

[INFO] [Startup] Project only paths analyzed by clj-kondo, took 19ms
[INFO] :maintain-dep-graph 0ms
[100%] Project analyzed            
Finding diagnostics...
test/clojure_sample/core_test.clj:11:1: warning: [redefined-var] redefined var #'clojure-sample.core-test/a-test
src/clojure_sample/client.clj:11:13: info: [clojure-lsp/unused-public-var] Unused public var 'clojure-sample.client/my-test'
</pre>
</details>

**User details (please complete the following information):**
 - OS: MacOS
 - Version: clojure-lsp 2023.05.04-19.38.01
clj-kondo 2023.04.15-SNAPSHOT

**Comment by ericdallo** [comment]
@mrkam2 I just tested with latest clojure-lsp and this should be fixed, closing this, let me know if otherwise
