### ISSUE TITLE
clojure-lsp does not use cljfmt 0.10.x

### ISSUE THREAD

**Issue by Garmelon** [clojure-lsp/clojure-lsp#1605]
**Describe the bug**
When running `clojure-lsp format` with custom `:indent`s in my `.cljfmt.edn`, code is being formatted incorrectly. cljfmt 0.9.2 exhibits the same formatting issue, while cljfmt 0.10.1 and newer versions format the code correctly.

**To Reproduce**

1. Clone project https://github.com/Garmelon/clojure-lsp-misformat-example
2. Run `clojure-lsp format`
3. Observe that no files are changed

**Expected behavior**
The bottom call to `foo` in `example2.clj` should be formatted the same as the top call and the call in `example.clj`.

<details>
 <summary><b>clojure-lsp output</b></summary>
<pre>
[ 10%] Finding cache               [INFO] [DB] Reading transit analysis cache from /home/username/tmp/clojure-lsp-misformat-example/.lsp/.cache/db.transit.json db took 1ms
[INFO] :maintain-dep-graph 0ms
[INFO] [Startup] Using cached classpath #{"src" "/home/username/.m2/repository/org/clojure/spec.alpha/0.3.218/spec.alpha-0.3.218.jar" "/home/username/.m2/repository/org/clojure/clojure/1.11.1/clojure-1.11.1.jar" "/home/username/.m2/repository/org/clojure/core.specs.alpha/0.2.62/core.specs.alpha-0.2.62.jar" "test"}
[INFO] [Startup] Using source-paths from classpath: ["/home/username/tmp/clojure-lsp-misformat-example/test" "/home/username/tmp/clojure-lsp-misformat-example/src"]
[ 15%] Copying kondo configs       [INFO] Copying kondo configs from classpath to project if any...
[WARN] Non-fatal error from clj-kondo: No configs copied.

[INFO] Copied kondo configs, took 27ms secs.
[ 20%] Analyzing project files     [INFO] [Startup] Analyzing source paths for project root /home/username/tmp/clojure-lsp-misformat-example
[INFO] [Startup] Project only paths analyzed by clj-depend, took 0ms
[ 99%] Analyzing project files     No configs copied.
[INFO] :maintain-dep-graph 0ms
[INFO] Linting whole project for unused-public-var took 1ms

[INFO] [Startup] Project only paths analyzed by clj-kondo, took 13ms
[INFO] :maintain-dep-graph 0ms
[100%] Project analyzed            
Formatting namespaces...
[INFO] :formatting 9ms
[INFO] :formatting 12ms
Nothing to format!
</pre>
</details>

**User details (please complete the following information):**
 - OS: NixOS (unstable)
 - Version:
   - clojure-lsp 2023.05.04-19.38.01
   - clj-kondo 2023.04.15-SNAPSHOT

**Comment by ericdallo** [comment]
@Garmelon the reason I didn't bump is that there is no 0.10.X jar in clojars, only the 0.9.2, maybe @weavejester changed the CI or something?

**Comment by Garmelon** [comment]
It appears to have moved here since 0.10: https://clojars.org/dev.weavejester/cljfmt

**Comment by ericdallo** [comment]
ah thanks, will update then!

**Comment by weavejester** [comment]
Apologies for the move! In retrospect it wasn't a great idea; I wanted to adhere to the new guidelines for Clojar artifact groups, and at the time didn't fully consider the consequences.

**Comment by weavejester** [comment]
It's also worth noting that the latest versions of cljfmt include `cljfmt.config/load-config`, for loading the configuration from the classpath. I notice that clojure-lsp adds some extra features like a `#re` tag for edn configurations.

Would you be opposed to merging our efforts in this regard so the command-line cljfmt tool uses the same configuration as the version used in clojure-lsp?

**Comment by ericdallo** [comment]
@weavejester I'd be glad to help make things follow the same standard/convention, but not sure what exactly you think we can change in clojure-lsp or cljfmt, Do you mean move the `#re` logic to cljfmt? or something else?

**Comment by weavejester** [comment]
Currently cljfmt has a `load-config` function that looks for a file: `.cljfmt.edn`, `.cljfmt.clj`, `cljfmt.edn` and `cljfmt.clj`. It looks in the current directory and any parent directory, and reads the first one it finds.

From my reading of the source it looks like clojure-lsp looks for `.cljfmt.edn` and `.cljfmt.clj` but not `cljfmt.edn` or `cljfmt.clj`. It also looks like it searches the current directory, but not any parent directories. Is that right?

My suggestion would be to add the `#re` tag to the cljfmt's `load-config`, and then to use `load-config` in clojure-lsp, so it uses the same configuration logic as the cljfmt CLI application. Do you foresee any issues or incompatibilities with that approach?

**Comment by ericdallo** [comment]
> From my reading of the source it looks like clojure-lsp looks for .cljfmt.edn and .cljfmt.clj but not cljfmt.edn or cljfmt.clj. It also looks like it searches the current directory, but not any parent directories. Is that right?

Almost, not the current file dir, but the project root, I agree we should use `load-config` since now cljfmt provides a way to make this lookup, will create a issue for that

> My suggestion would be to add the #re tag to the cljfmt's load-config, and then to use load-config in clojure-lsp, so it uses the same configuration logic as the cljfmt CLI application. Do you foresee any issues or incompatibilities with that approach?

Nope, sounds good to me! I can create a issue and work later in a PR for cljfmt to support `#re`, and then change clojure-lsp to use `load-config`, does that works for you?

**Comment by weavejester** [comment]
Sounds good! I believe there's already a PR for the `#re` tag on cljfmt - it just needs some tests.

**Comment by weavejester** [comment]
The `#re` tag has been added to `cljfmt.config/load-config` in cljfmt 0.11.0.
