### ISSUE TITLE
Cache classpath

### ISSUE THREAD

**Issue by technomancy** [clojure-lsp/clojure-lsp#1627]
Sometimes calculating a classpath can take a long time. Certain large projects at work exceed the 30-second time limit of my LSP client even when all the dependencies are present, and I've read that timeouts of 10 seconds are not uncommon.

Caching the classpath and expiring it when the project-path file is modified would allow boot time to be greatly improved and make it work out of the box on older hardware for clients with a lower default connection timeout setting.

**Comment by ericdallo** [comment]
We have the classpath string cached already [here](https://github.com/clojure-lsp/clojure-lsp/blob/5285b3db79f68bef3b13281687b770da80916745/lib/src/clojure_lsp/startup.clj#L232), so the next usages/start of clojure-lsp should already use that.

**Comment by technomancy** [comment]
I see; my bad--I thought that this was the culprit for the long load times I've been seeing but it must be something else. Thanks.
