### ISSUE TITLE
Namespaced aliases seems to be ignored

### ISSUE THREAD

**Issue by mathieuroblin** [clojure-lsp/clojure-lsp#1637]
**Describe the bug**
It seems that if an alias defined in `deps.edn` contains a namespace, only the name part of the keyword is picked up in the classpath resolution.

Since there is a bit of setup, please have a look at: https://github.com/mathieuroblin/cljfmt-aliases
This repo contains 3 libs to be loaded differently, two of them are only loaded via an alias and thus are added to the `.lsp/config`.
The project contains two aliases:
1. `:ns/keyword`
2. `:name-keyword`

When starting the LSP (full logs below), it shows that the aliases used for the classpath are: `-A:keyword:name-keyword -Spath`. This is not just a logging issue, the LSP's result shows that all the errors in `lib/3` have been ignored, and I can confirm in various text editors that all the features (like goto) are not working.

*After renaming `:ns/keyword` to `:ns-keyword` everything works as intended.*

**To Reproduce**
Just start the LSP at the root of the provided repo.

**Expected behavior**
The aliases shouldn't be changed by the LSP, the command to resolved the classpath should be: `-A:ns/keyword:name-keyword -Spath`.

<details>
 <summary><b>clojure-lsp output</b></summary>
<pre>
[ 10%] Finding cache               [ERROR] [DB] No cache DB file found
[INFO] [DB] Reading transit analysis cache from /Users/mathieu/Programming/oss/cljlsp-aliases/.lsp/.cache/db.transit.json db took 0ms
[ 15%] Discovering classpath       [INFO] Finding classpath via `/opt/homebrew/bin/clojure -A:keyword:name-keyword -Spath`
[DEBUG] Classpath found, paths:  ["lib2" "lib1" "/Users/mathieu/.m2/repository/org/clojure/clojure/1.11.1/clojure-1.11.1.jar" "/Users/mathieu/.m2/repository/org/clojure/core.specs.alpha/0.2.62/core.specs.alpha-0.2.62.jar" "/Users/mathieu/.m2/repository/org/clojure/spec.alpha/0.3.218/spec.alpha-0.3.218.jar"]
[INFO] [Startup] Using source-paths from classpath: ["/Users/mathieu/Programming/oss/cljlsp-aliases/lib2" "/Users/mathieu/Programming/oss/cljlsp-aliases/lib1"]
[ 20%] Copying kondo configs       [INFO] Copying kondo configs from classpath to project if any...
[WARN] Non-fatal error from clj-kondo: No configs copied.

[INFO] Copied kondo configs, took 12ms secs.
[ 25%] Analyzing external classpath[INFO] Analyzing classpath for project root /Users/mathieu/Programming/oss/cljlsp-aliases
[INFO] Analyzing 3 paths with clj-kondo
[ 44%] Analyzing external classpathNo configs copied.

[INFO] External classpath paths analyzed, took 593ms
[INFO] :maintain-dep-graph 1ms
[INFO] Manual GC after classpath scan took 32ms
[INFO] Caching db for next startup...
[INFO] Manual GC before upsert db took 29ms
[INFO] [DB] Upserting transit analysis to /Users/mathieu/Programming/oss/cljlsp-aliases/.lsp/.cache/db.transit.json cache took 37ms
[ 50%] Analyzing project files     [INFO] [Startup] Analyzing source paths for project root /Users/mathieu/Programming/oss/cljlsp-aliases
[INFO] [Startup] Project only paths analyzed by clj-depend, took 1ms
[ 98%] Analyzing project files     No configs copied.
[INFO] :maintain-dep-graph 0ms
[INFO] Linting whole project for unused-public-var took 1ms

[INFO] [Startup] Project only paths analyzed by clj-kondo, took 5ms
[INFO] :maintain-dep-graph 0ms
[ 99%] Project analyzed            Finding diagnostics...
lib2/file2.clj:3:1: error: [syntax] Invalid function body.
lib2/file2.clj:3:7: info: [clojure-lsp/unused-public-var] Unused public var 'file2/fn-2'
lib1/file1.clj:3:1: error: [syntax] Invalid function body.
lib1/file1.clj:3:7: info: [clojure-lsp/unused-public-var] Unused public var 'file1/fn-1'
</pre>
</details>

**User details (please complete the following information):**
 - OS: `MacOS`
 - Version: `2023.07.01-22.45.58-nightly`

----

I am keen to have a look at it myself when I have a bit of free time. I must have missed the part of the documentation about contributing, could you point me to it? Any other relevant information you think would help me get the ball rolling would be appreciated.

**Comment by ericdallo** [comment]
@mathieuroblin thanks, [this](https://clojure-lsp.io/development/) should be enough but we should create a CONTRIBUTING.md file indeed
