### ISSUE TITLE
Configure custom linters via ns metadata

### ISSUE THREAD

**Issue by simonacca** [clojure-lsp/clojure-lsp#1652]
**Is your feature request related to a problem? Please describe.**

Clj-kondo supports config changes while linting a namespace [via namespace metadata](https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#metadata-config).
This seems not to be supported for clojure-lsp's custom linters, such as `:clojure-lsp/unused-public-var`.

The `unused-public-var` linter happens to be a particularly useful one to control on a per-ns basis, especially when one starts gradually adopting linting on a legacy codebase.

**Describe the solution you'd like**
Ideally one would be able control clojure-lsp's custom linters with ns metadata, for example with
```clojure
(ns my-ns
  {:clj-kondo/config '{:linters {:clojure-lsp/unused-public-var {:level :off}}}})

```

**Describe alternatives you've considered**
Of course, one can already toggle such linting on a per-ns basis via the clj-kondo config, and this works just fine. The proposed feature is just an ergonomic enhancement :)

Thank you for your consideration,
Simon

**Comment by ericdallo** [comment]
I think that should work but there is a bug in clj-kondo where custom-lint-fn is not considererd for those config, WDYT @borkdude ?

**Comment by borkdude** [comment]
I think it's better to use `:config-in-ns {my.namespace {:linters {....}}}`

**Comment by ericdallo** [comment]
AFACS this would move the config from the ns to the config file, right?
@simonacca is that enough for you?

**Comment by borkdude** [comment]
Yes, and this should be the more robust way which is also visible for clojure-lsp if I'm not mistaking.

**Comment by borkdude** [comment]
I think it's better to just use config-in-ns in this case.

**Comment by borkdude** [comment]
Yeah some extra docs would be in order.

**Comment by ericdallo** [comment]
Thank you for the help @simonacca.
I agree would be ideal to clj-kondo be consistent with custom-lint-fn but I suppose it's hard to support it, having a note meanwhile sounds good to me!
