### ISSUE TITLE
JDK source go-to-definition works unreliably 

### ISSUE THREAD

**Issue by sg-qwt** [clojure-lsp/clojure-lsp#1656]
**Describe the bug**
Hi there,

I found a pretty weird issue with my clojure-lsp+eglot setup, not sure if this is by eglot or clojure-lsp side though.

What I found is JDK source jump to definition does not work reliably, if I type in a new class, on first try, it will usually go to the source correctly. 

But if I quit the source and try again, eglot will just complain `xref--not-found-error: No definitions found for: LSP identifier at point`. I can repeat the same with different new classes, they all behave the same, first time jump works, then  `No definitions found`. 

Note this only happens on JDK source, for other java library source, jump to definition works reliably no matter how many times back and forth.

[jdkjump.webm](https://github.com/clojure-lsp/clojure-lsp/assets/115715554/6a735019-d371-48d7-ad9f-b9ca09e524f4)

JDK source is deduced from JAVA_HOME, I don't have anything special setup for clojure-lsp.

[clojure-lsp.15979514708496532991.out.txt](https://github.com/clojure-lsp/clojure-lsp/files/12371641/clojure-lsp.15979514708496532991.out.txt)

From eglot client, for the unsuccessfully jump, it just get nil result:
```
[client-request] (id:408) Fri Aug 18 00:32:40 2023:
(:jsonrpc "2.0" :id 408 :method "textDocument/definition" :params
	  (:textDocument
	   (:uri "file:///home/me/nixos/pulumi/src/infralab/infralab.clj")
	   :position
	   (:line 7 :character 19)))
[server-reply] (id:408) Fri Aug 18 00:32:40 2023:
(:jsonrpc "2.0" :id 408 :result nil)

``` 

**User details (please complete the following information):**
 - OS: nixos
 - Editor: emacs29
 - Version:
clojure-lsp 2023.08.06-00.28.06
clj-kondo 2023.07.14-SNAPSHOT

**Comment by ericdallo** [comment]
There is a known issue that if you delete the java file after going to it, next definitions won't work indeed, @sg-qwt, could you elaborate what you do after you exit the file?
With lsp-mode at least, if I go to definition and just kill the buffer (not delete the java cache file), next definitions work as expected.

**Comment by ericdallo** [comment]
No problem, glad you found, I'm not sure clojure-lsp is the right place to document eglot peculiarities, but I do think it should go somewhere more LSP generic like eglot docs.
