### ISSUE TITLE
Windows 11 - Clojure Language Client client: couldn't create connection to server.  Message: Internal error   Code: -32603 

### ISSUE THREAD

**Issue by uhlikosaurus** [clojure-lsp/clojure-lsp#1679]
Hello,
I've been struggling for a few days with turning on clojure-lsp via Calva extension in VSCode. I also tried the option that Calva download the lsp itself, but I had the exact same problem.

It always writes this error:

> [Error - 6:18:41 PM] Server initialization failed.
  Message: Internal error
  Code: -32603 
[object Object]
[Error - 6:18:41 PM] Clojure Language Client client: couldn't create connection to server.
  Message: Internal error
  Code: -32603 
[object Object]
[Error - 6:18:43 PM] Connection to server got closed. Server will not be restarted.

OS: Windows 11
Arch: x64

Java:
> openjdk 17.0.8 2023-07-18
OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)
OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)

ClojureLSP version:

> clojure-lsp 2023.08.06-00.28.06
clj-kondo 2023.07.14-SNAPSHOT

VSC settings:

`{
    "calva.showDocstringInParameterHelp": true,
    "calva.clojureLspPath": "C:\\Users\\uhlik\\bin\\clojure\\bin\\clojure-lsp.exe",
    "editor.fontLigatures": true,
    "editor.formatOnSave": true,
    "calva.paredit.defaultKeyMap": "original",
    "calva.autoOpenJackInTerminal": false,
"calva.fmt.configPath": "CLOJURE-LSP",
    "calva.enableClojureLspOnStart": "never",
"calva.prettyPrintingOptions": {
        "printEngine": "pprint",
        "enabled": true,
        "width": 120,
        "maxLength": 50
    }}`

<img width="958" alt="image" src="https://github.com/clojure-lsp/clojure-lsp/assets/89848892/e3f03cd5-6a2e-45ed-8c74-5aff38b6914a">

<img width="704" alt="image" src="https://github.com/clojure-lsp/clojure-lsp/assets/89848892/d220f86f-127e-46b2-a552-0c2cf92a83cd">

I hope this helps.

Regards
Martin Strnad

**Comment by uhlikosaurus** [comment]
attached here

**Comment by PEZ** [comment]
Not sure why this was closed?

**Comment by hkjels** [comment]
Same happening on windows 10 with clean installation of Visual Studio Code, Calva extension, and Clojure-lsp.

**Comment by uhlikosaurus** [comment]
I closed this ticket because it looks like a Calva extension error, LSP with Kate worked fine.
