### ISSUE TITLE
Errors while trying to rename parameters of defprotocol function declarations

### ISSUE THREAD

**Issue by aisamu** [clojure-lsp/clojure-lsp#1691]
Per [@ericdallo's request on clojurians](https://clojurians.slack.com/archives/CPABC1H61/p1697746211451579)

**Describe the bug**

When I try to rename protocol parameters, I get an `Internal Error` as the response.
I couldn't determine whether that's unsupported or if there's something wonky with my setup!

<details>
 <summary><b>clojure-lsp log output</b></summary>
<pre>
```
2023-10-19T20:05:38.833Z  ERROR [clojure-lsp.server:55] - Error receiving message: Internal error (-32603)
{:id 988, :method "textDocument/prepareRename"}
com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine  PosixPlatformThreads.java:  203
            com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine       PlatformThreads.java:  775
                            java.util.concurrent.ForkJoinWorkerThread.run  ForkJoinWorkerThread.java:  183
                              java.util.concurrent.ForkJoinPool.runWorker          ForkJoinPool.java: 1594
                                   java.util.concurrent.ForkJoinPool.scan          ForkJoinPool.java: 1656
                 java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec          ForkJoinPool.java: 1020
                                 java.util.concurrent.ForkJoinTask.doExec          ForkJoinTask.java:  290
                  java.util.concurrent.CompletableFuture$AsyncSupply.exec     CompletableFuture.java: 1692
                   java.util.concurrent.CompletableFuture$AsyncSupply.run     CompletableFuture.java: 1700
                                                promesa.util.Supplier/get                  util.cljc:   34
                                            promesa.exec/wrap-bindings/fn                  exec.cljc:  163
                                                 clojure-lsp.server/fn/fn                 server.clj:  256
                                      clojure-lsp.handlers/prepare-rename               handlers.clj:  252
                                clojure-lsp.feature.rename/prepare-rename                 rename.clj:  268
                                 clojure-lsp.feature.rename/rename-status                 rename.clj:  224
                                      clojure-lsp.shared/uri->source-path                 shared.clj:  259
                                     clojure-lsp.shared/uri->source-paths                 shared.clj:  256
                                         clojure-lsp.shared/uri->filename                 shared.clj:  207
                                              clojure.string/starts-with?                 string.clj:  365
```
</pre>
</details>

**To Reproduce**

1. Given 

```clojure
(ns report)

(defprotocol Buggable
  (-fail [with-tpyo]))

(extend-protocol Buggable
  nil
  (-fail [with-tpyo] true))

(-fail nil)
```

2. Attempt to rename the protocol's parameter `with-tpyo`
3. See error

> NB: Attempting to rename the implementation's parameter works

**Expected behavior**

If not implemented, a message saying so.
If implemented, all the known implementation parameters should be renamed accordingly.  

**User details (please complete the following information):**
 - OS: MacOS `23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020 arm64 arm Darwin`
 - Editor: `GNU Emacs 29.1 (build 1, aarch64-apple-darwin22.6.0, Carbon Version 169 AppKit 2299.7)`
 - Version: `clojure-lsp 2023.08.06-00.33.37-nightly, clj-kondo 2023.07.14-SNAPSHOT`

 Thanks for clojure-lsp! 🥳

**Comment by ericdallo** [comment]
@aisamu I improved clojure-lsp to show a proper message instead of a crash, but the reason for this not work is that we don't support rename arity of functions/protocol/records methods and rename all other places, I'll close this issue, but feel free to create a feature request to allow renaming function args

**Comment by aisamu** [comment]
Thank you, will do!

Tangent: it looks like you've added the faulty scenario, but I couldn't find a test exercising it
(find it on the diff, that is)

**Comment by ericdallo** [comment]
yeah, I was meaning to add that on the new feature, but makes more sense to add right now indeed
