### ISSUE TITLE
Performance: allow disable keyword analysis for better memory usage

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#1700]
https://clojurians.slack.com/archives/CBE668G4R/p1698416057409289

from that thread we could:

- allow disable all keyword analysis for external or external+internal analysis, this should remove find references features and rename in keywords but should be a good option for huge projects for performance and memory improvement
- Maybe we should not save in memory keyword usages for external dependencies, I can't see why that is useful since no one cares about keyword usages in external deps, and rename doesn't work for deps.

**Comment by hugoduncan** [comment]
Thank you for this - turning off keyword analysis took the clojue-lsp process on a large project from 20Gb memory usage to 10Gb!
