### ISSUE TITLE
find-ns function

### ISSUE THREAD

**Issue by agzam** [clojure-lsp/clojure-lsp#171]
_Not an issue_

I'd like to write a small `find-ns` utility function that does exactly what `cider-find-ns` does, but without having to be jacked-in, only using tools provided in lsp. Can someone suggest where should I look, how to start it? Thanks.

**Comment by ericdallo** [comment]
Hey @agzam, cool, it seems a good idea.
Well, as this is a specific feature that is not in the [lsp protocol](https://microsoft.github.io/language-server-protocol/), you can write a new handler for the `executeCommand` method like we do for server-info [here](https://github.com/snoe/clojure-lsp/blob/master/src/clojure_lsp/main.clj#L334-L335), returning all namespaces available.

For finding all namespaces, you can try to move [this code](https://github.com/snoe/clojure-lsp/blob/master/src/clojure_lsp/handlers.clj#L169-L187) to a common function where you can call it from your handler.

After that, you can open a PR on your favorite client, like [lsp-mode](https://emacs-lsp.github.io/lsp-mode) for emacs calling this new command like we did [here](https://github.com/emacs-lsp/lsp-mode/commit/4145a70ce1d4bfb2463606ba34c5965080b080d9).

Feel free to ask anything here or in the [clojurians lsp channel](https://clojurians.slack.com/archives/CPABC1H61) :)

**Comment by agzam** [comment]
Thank you @ericdallo, looks like it requires more thought than I expected. Thank you for the pointers, I will try to play around, maybe something useful comes out of that.

**Comment by snoe** [comment]
You might be interested in lsp's workspace symbols (in coc.nvim it's `:CocList symbols`) you can start typing in a namespace and it will jump you there.

**Comment by ericdallo** [comment]
Closing this since this is already present in some clients like snoe explained above
