### ISSUE TITLE
Exclude keys that are already included in the function call from auto-completion suggestions

### ISSUE THREAD

**Issue by anonimitoraf** [clojure-lsp/clojure-lsp#1720]
Just wanted to preface this with: I love this auto-completion of map keys when calling functions!

https://github.com/clojure-lsp/clojure-lsp/assets/15933322/d98f9d8d-700d-4e49-9f50-796d164a9edf

For context:
```clojure
(defn send-email
  [{:keys [from to subject html text]}]
  (let [payload {:html-body html :text-body text}]
    (ses/send-email client-opts from to subject payload)))
```

**Is your feature request related to a problem? Please describe.**
It would be great if the auto-completion excluded keys that are already part of the function call

**Describe the solution you'd like**
In my video recording above, only `:subject` and `:text` would be suggested

**Comment by ericdallo** [comment]
Yeah, I use that a lot as well and noticed that too, I think it should not be that hard, will take a loot at this soon

**Comment by ericdallo** [comment]
Done! available on nightly and next release
