### ISSUE TITLE
Launch performance is too slow to use as a pre-commit hook

### ISSUE THREAD

**Issue by markbastian** [clojure-lsp/clojure-lsp#1723]
It would be great to use `clojure-lsp` as a git pre-commit hook, but it would need to be very fast to not be a burden for developers as a hook.

Here's a simple comparison script of running plain `cljfmt` vs. `clojure-lsp` to reformat a single file:

```
start_time=`date +%s`
clojure -T:cljfmt fix '{:paths ["src/metabase/lib/metadata/protocols.cljc"]}'
end_time=`date +%s`
echo execution time was `expr $end_time - $start_time` s.

start_time=`date +%s`
clojure-lsp format --filenames src/metabase/lib/metadata/protocols.cljc
end_time=`date +%s`
echo execution time was `expr $end_time - $start_time` s.
```
Here are the results:

```
➜  metabase ./bin/timed_cljfmt.sh                                                  
Reformatted src/metabase/lib/metadata/protocols.cljc
execution time was 1 s.
[ 99%] Project analyzed            Formatting namespaces...
Nothing to format!
execution time was 59 s.
```

Note that the "Nothing to format!" message is just because `cljfmt` ran first. The specific file being formatted can be found [here](https://github.com/metabase/metabase/blob/master/src/metabase/lib/metadata/protocols.cljc) if you want to reproduce. The primary issue is the analysis that happens up front.

See [this slack thread](https://clojurians.slack.com/archives/CPABC1H61/p1699554342728299) for reference. The original idea was to just export the `clojure-lsp` format config and use `cljfmt` here, but ideally `clojure-lsp` would execute very quickly.

**Comment by ericdallo** [comment]
@markbastian That worked smoothly, please try and let me know, but now the format task should be way faster, LMK if you benchmark anything
