### ISSUE TITLE
Eglot receives non-sensical urls for external deps

### ISSUE THREAD

**Issue by LiGoldragon** [clojure-lsp/clojure-lsp#1744]
Quick report before I punch out. I have scoured the web and spent lots of time hunting down how I get such nonsensical urls as this one:
 `/home/li/git/lojix/src/lojix/jar:file:/home/li/.m2/repository/org/clojure/clojure/1.11.1/clojure-1.11.1.jar!/clojure/`
 
 As you can see, the source's location was prepended to the url (In this case a jar url, as I tried switching schemes to see what happened).
 
 Any pointer is appreciated, and I have more energy to fix this. On Nixos near-master with clojure-lsp from the maste flake or directly from nixpkgs (august version). Thank you :pray:

**Comment by ericdallo** [comment]
@LiGoldragon, yeah that URL is wrong, but I can't understand how to repro that (I'm a NixOS user as well, but I doubt it's related to the derivation)

**Comment by LiGoldragon** [comment]
Moved out of clojure. Never found out. Good luck
