### ISSUE TITLE
clojure-lsp fails to run on Ahasi Linux

### ISSUE THREAD

**Issue by lasselinkola-yle** [clojure-lsp/clojure-lsp#1748]
**Describe the bug**
When I try to run the lsp on ahasi linux I get an error 
`Fatal error: Failed to create the main Isolate. (code 24)`

**To Reproduce**
run the binary frome the CLI

**User details (please complete the following information):**
 - OS: Ahasi Linux, M2 Macbook Pro
 - Version: latest

Possible similar issues in other projects:
https://github.com/coursier/coursier/issues/2636
https://github.com/VirtusLab/scala-cli/issues/1714

Maybe setting page size to 64k would help?

**Comment by ericdallo** [comment]
Thanks for the report, I think we can try [the same approach](https://github.com/coursier/coursier/pull/2641/files) on these other projects

**Comment by ericdallo** [comment]
We just need to add a conditional when it's aarch [here](https://github.com/clojure-lsp/clojure-lsp/blob/ede6be7323d0257d9fd178ff65183d8c2672bede/cli/build.clj#L120)

**Comment by lasselinkola-yle** [comment]
Sounds good! Any estimate when this would be released? I Would like to start using clojure-lsp as soon as possible

**Comment by ericdallo** [comment]
@lasselinkola-yle good news, I think I have it fixed, I'm building a native binary which you can test it [here](https://github.com/clojure-lsp/clojure-lsp/actions/runs/7513758038/job/20455896527), I let you know

**Comment by ericdallo** [comment]
@lasselinkola-yle the binary was sucessfully built, you can download it from [here](https://github.com/clojure-lsp/clojure-lsp/actions/runs/7513758038), or if you don't have access I can try to send to you somehow, it has 36MB

**Comment by ericdallo** [comment]
Next release should include the fix, LMK if not fixed

**Comment by lasselinkola-yle** [comment]
Seems to be working! Thank you!
