### ISSUE TITLE
lsp-rename incorrectly changing require ns when changed to longer text and changing current namespace

### ISSUE THREAD

**Issue by Kaspazza** [clojure-lsp/clojure-lsp#1751]
**Describe the bug**
When lsp-rename is run on required namespace in a way that the new name is longer it results in some weird combination of letters at the end of the replaced ns.

**To Reproduce**
1. Go to [this line](https://github.com/hephaistox/automaton-core/blob/feat/mati/compilation/src/cljc/automaton_core/configuration.cljc#L14)
2. Run lsp-rename on `automaton-core.configuration.files` to `automaton-core.configuration.new-files`
3. On that line the text will be messed up, the namespace in which we are `automaton-core.configuration` will be renamed also to automaton-core.configuration.new-files and the file will be moved accordingly.

**Expected behavior**
Only that required ns is renamed on that line and the namespace that it's pointing to, not the current ns

** Testing env ** 
I'm using mac aarch 
I've tested this on the newest version of lsp-clojure to 2022.06.22 (first one with aarch). 
And on all of them it is not working, it was definitely at one point before that date, but can't tell which one.

**Comment by Kaspazza** [comment]
It seems it is more messed up, because also when I tried renaming defrecord (in ns automaton-core.configuration.files), it renamed the ns reference instead of the defrecord name.

So [SimpleFiles](https://github.com/hephaistox/automaton-core/blob/feat/mati/compilation/src/cljc/automaton_core/configuration/files.cljc#L58)
when running lsp-rename,->SimpleConf renamed to ->FilesConf
It renamed it in automaton-core.configuration 
From core-conf-files/->SimpleConf to ->FilesConf/->SimpleConf

**Comment by ericdallo** [comment]
Found the bug, it seems it exists since 2022/05, introduced [here](https://github.com/clojure-lsp/clojure-lsp/commit/3c13ba27ad72fcae085b6eeaeac814e541aaef8b), I'll fix it, but meanwhile, just renaming the file instead of the ns, should rename the ns and its references and not cause this bug

**Comment by ericdallo** [comment]
Should be fixed on nightly/next release
