### ISSUE TITLE
External libraries explorer

### ISSUE THREAD

**Issue by gasilveira** [clojure-lsp/clojure-lsp#1752]
**Is your feature request related to a problem? Please describe.**

In some vs code languages (like gon or java) the developer has the option to see and explore external libraries included in the project using a tab in _explorer_.
And today for calva the only option is navigating throw the imports of the function or running a cmd: 
`lein deps :tree`

My suggestion is to include a plugin or feature that includes an "External Libraries" explorer available for calva users
Bellow is an explample from intellij available for cursive users:
![image](https://github.com/clojure-lsp/clojure-lsp/assets/102158732/ee571575-d619-4b10-9237-af8f5945f171)

**Comment by ericdallo** [comment]
Thanks, I think we can provide a custom method providing this info, so clients can integrate

**Comment by ericdallo** [comment]
@gasilveira Done! Also, I implemented support for emacs-lsp as the first candidate 
![image](https://github.com/clojure-lsp/clojure-lsp/assets/7820865/83ac3134-d473-4f97-9c33-f9f217233862)

https://clojure-lsp.io/features/#project-tree

**Comment by ericdallo** [comment]
@gasilveira I implemented support for Calva as well :)
https://github.com/BetterThanTomorrow/calva/pull/2407
