### ISSUE TITLE
[Regression] Renaming defrecord results in renaming alias instead of the name

### ISSUE THREAD

**Issue by Kaspazza** [clojure-lsp/clojure-lsp#1756]
**Describe the bug**
When I run lsp-rename on defrecord, the places where defrecord is references are replaced in the alias part of the name instead of the changed name.
E.g.
a. We have defrecord Files
b. We have it references somewhere as namespace-a/Files

Run lsp-rename on defrecord Files to FilesC
It changes defrecord name (a.) in that place to FilesC
It changes the reference (b.) from namespace-a/Files to -> FilesCace-a/Files
^ so it replaced the beginning of the reference, instead of the part after the alias.

**To Reproduce**
1. Go to [FilesConf](https://github.com/hephaistox/automaton-core/blob/feat/mati/compilation/src/cljc/automaton_core/configuration/files.cljc#L57)
2. run lsp-rename to `FilesConfig`
3. Go to [where it's referenced](https://github.com/hephaistox/automaton-core/blob/feat/mati/compilation/src/cljc/automaton_core/configuration.cljc#L24)
4. It will be renamed at that point from (core-conf-files/->FilesConf) to (->FilesConfigiles/->FilesConf)

**Expected behavior**
At point 4. It should be renamed from (core-conf-files/->FilesConf) to (core-conf-files/->FilesConfig)
Changing only what's after the alias.

**User details (please complete the following information):**
 - OS: MacOS M2
 - Editor emacs doom
 - Version:  2024.01.15-12.02.49-nightly mac aarch 
 (It was working at version 2022.06.22)

**Comment by ericdallo** [comment]
Minimal repro:
```clojure
(ns foo)

(defrecord MyRecord [])

(ns bar
  (:require [foo :as f]))

(f/MyRecord)

```
