### ISSUE TITLE
False positive: reports definterface methods as unused

### ISSUE THREAD

**Issue by mrkam2** [clojure-lsp/clojure-lsp#1762]
**Describe the bug**
clojure-lsp incorrectly identifies `definterface` methods as unused.

**To Reproduce**

Create `foo_test.clj`:
```clojure
(ns foo-test)

(definterface Foo
  (bar [x]))

(let [f (reify Foo (bar [_ x] x))]
  (.bar f 5))
```

It can be evaluated to verify that `bar` was defined and used in the snippet.
`clojure-lsp diagnostics` would show that `(bar [x])` is unused.

**Expected behavior**
It should not report these methods as unused.

**Comment by ericdallo** [comment]
@borkdude do you see anything that clj-kondo could help here? the problem is that the only analysis for `.bar` is a `instance-invocation`:
```clojure
   {:method-name "bar",
    :uri "...",
    :bucket :instance-invocations}
```

So I can't find a way to relate that bar with the bar from the definterface 🤔

**Comment by ericdallo** [comment]
hum, good point, I think it makes sense to ignore all methods in the unused-public-var linter and consider only the `Foo` if it's being used or not
