### ISSUE TITLE
Help to consistently apply namespace aliases.

### ISSUE THREAD

**Issue by acamargo** [clojure-lsp/clojure-lsp#1770]
This feature was first proposed on https://github.com/clj-kondo/clj-kondo/issues/2195

I agree it makes more sense to be part of `clojure-lsp` because it requires a project-wide analysis to be done.

There is a working implementation proposal on https://github.com/clojure-lsp/clojure-lsp/pull/1768

**Comment by ericdallo** [comment]
Thanks, that makes sense, I think we should keep an eye on performance since custom linters should be fast, so a profiler would be a good idea.

**Comment by ericdallo** [comment]
Fixed by #1768
