### ISSUE TITLE
Add keyword definitions (reg-...) to :clojure/workspace/projectTree/nodes

### ISSUE THREAD

**Issue by zikajk** [clojure-lsp/clojure-lsp#1789]
**Is your feature request related to a problem? Please describe.**
I can get all fns and vars for a namespace by  `:clojure/workspace/projectTree/nodes` which is used to build a project-tree.
I built a project-tree for Eglot and I would like to extend CLJS namespace node by 'keyword definitions' of re-frame subscriptions or events like:
```
(rf/reg-sub
 ::spinner-count ...)

(reg-event-db
 ::set ...)
 ```
 
 Clojure-lsp already supports find definition / references on them. It would be useful to see them in project-tree as well.

**Describe the solution you'd like**
Having them inside a response from` :clojure/workspace/projectTree/nodes` as an another type would be useful when building a tree. 

**Alternative solutions you'd like**
- new type of request that will return all `reg-...` for a node (namespace).
  - maybe the request can be customized by clj-kondo configuration so it is not limited to  `reg-...` only

**Comment by zikajk** [comment]
Do you think it is a good idea to have re-frames as part of project-nodes permanently, or would it be possible to define clj-custom hooks to be used?

**Comment by ericdallo** [comment]
@zikajk the idea is to consider keyword definition which should include anything from custom hooks that is tagged as keyword definition, including re-frame macros

**Comment by zikajk** [comment]
@ericdallo If the user will be able to configure what he wants to analyze within the new type, that sounds good. I would work on it, but where to start?

**Comment by ericdallo** [comment]
@zikajk it was pretty simple to add ;)
![image](https://github.com/clojure-lsp/clojure-lsp/assets/7820865/6b2d095d-96af-4270-a121-79e692447574)

**Comment by zikajk** [comment]
That is great. So it will be a new, 10th type called `function`?

**Comment by ericdallo** [comment]
I used the same function type to avoid the need to change all clients to support a new one, and I think it's enough given the detail mentioning the keyword reg definition
