### ISSUE TITLE
Adding require command fails for requires without alias

### ISSUE THREAD

**Issue by blnote** [clojure-lsp/clojure-lsp#1791]
**Describe the bug**
the code action to add a namespace results in error when it is an unqualified namespace (like tmp, user).

**To Reproduce**
1. create namespace 
```
(ns tmp)
(def f inc)
```
2. execute code action to require from another namespace, eg for line `(tmp/f 2)`

**Expected behavior**
no error

This seems to occur only after the recent code change supporting js-requires [PR](https://github.com/clojure-lsp/clojure-lsp/pull/1587)

culprit seems to be a change in the `add-require-suggestion` function of `add_missing_libspec.clj` that transforms `chosen-ns` to a symbol (line 608). No error occurs when removing this line, but probably it was needed for the new functionality. I don't have the time to look into this in detail right now.

**Comment by ericdallo** [comment]
This happens for any code action without alias like:
```clojure
"Add require [foo.bar]"
```
