### ISSUE TITLE
Enable "find references" for quoted qualified symbols

### ISSUE THREAD

**Issue by lassemaatta** [clojure-lsp/clojure-lsp#1804]
**Is your feature request related to a problem? Please describe.**

We sometimes use a combination of a datastructure + `requiring-resolve` to lazy-load and invoke functions/vars. The datastructures might look like

```clojure
(def operations {"foo" 'some.namespace/foo-fn
                 "bar" 'some.other-namespace/bar-fn
                  ...})
```

With https://github.com/clojure-lsp/clojure-lsp/issues/1446 we can navigate from the datastructure to the var. But not the other way around:
- cannot navigate from `some.namespace/foo-fn` back to the datastructure ("No references") and
- `clojure-lsp` will report that `some.namespace/foo-fn` is an "Unused public var"

The latter can be quite problematic, as you might accidentally be tempted in removing the var as it's "unused code". 

**Describe the solution you'd like**

Quoted qualified symbols should work like var-quote (`#'some.namespace/foo-fn`). Assuming of course the symbol points to an actual var somewhere.

**Comment by lassemaatta** [comment]
Thanks a lot for implementing this!

FYI: I was testing with the latest release and the fix did not quite work the way I expected for our particular use case. After experimenting with this briefly, I think the feature works as expected _when you require the corresponding namespace_ which contains the var when you want to refer to it with a symbol. For example, here in the [test](https://github.com/clojure-lsp/clojure-lsp/blob/eca423d71e08f232e35525a57b96c972691e5619/lib/test/clojure_lsp/queries_test.clj#L323). 

Our use case looks more like (pseudo-code, might not compile):

```clojure
(ns some-ns.with-vars
  (:require [... a bunch of stuff ...])

(defn some-function []
  "I do something")

;; elsewhere..

(ns some-ns.program
 ;; No require for `some-ns.with-vars` here!
 (:gen-class))

(def operations {"foo" 'some-ns.with-vars/some-function})

(defn main- [& args]
  (when-let [s (get operations (first args))]
   ((requiring-resolve s)))  
```

**Comment by ericdallo** [comment]
Hum, indeed we will only consider if the symbol was required, I'll take a look but I think it's not trivial to support that

**Comment by lassemaatta** [comment]
Thanks! And don’t worry about it, this is most likely a niche use case anyways :)
