### ISSUE TITLE
Clojure LSP incorrectly marks `[\!\@]` as an error `<form> expected, got '\!\@'`

### ISSUE THREAD

**Issue by devurandom** [clojure-lsp/clojure-lsp#1816]
**Describe the bug**

When I write in a `*.clj` file:
```clj
 [\!\@]
```
Clojure LSP IntelliJ marks `\!\@` as an error: `<form> expected, got '\!\@'`

This appears to be independent of the actual values (`\!` and `\@` in this case; e.g. `\a\b` or `\.\:` behaves the same way).

The vector `[]` is not necessary either. Given a file containing:
```clj
\a\b
```
Clojure LSP IntellJ will mark `\a\b` as an error: `'\a\b' unexpected`

**Expected behavior**

`\a\b` is valid syntax. `[\a\b]` is a vector containing char values `\a` and `\b`.

**User details**

 - OS: Fedora Linux 40
 - Editor: IntelliJ 2024.1.1 with Clojure LSP plugin 2.4.5
 - Version: clojure-lsp 2024.04.22-11.50.26, clj-kondo 2024.03.13

**Comment by ericdallo** [comment]
That's a bug in clojure-lsp-intellij only as it works in other editors using clojure-lsp, that happens because of the Clojure language parser that clojure-lsp-intellij uses for Intellij, it's hot easy to fix it, but please open a issue there

**Comment by devurandom** [comment]
> That's a bug in clojure-lsp-intellij

Sorry, I might have opened it here accidentally, mixing up the two repos.

> please open a issue there

https://github.com/clojure-lsp/clojure-lsp-intellij/issues/54
