### ISSUE TITLE
Add `deftest` to resolve-macro-as list

### ISSUE THREAD

**Issue by PEZ** [clojure-lsp/clojure-lsp#1850]
**Is your feature request related to a problem? Please describe.**

When I use `defspec` from `clojure.test.check.clojure-test`, I get a linter message about that the defined symbol is undefined. Using the resolve-macro-as command I get a list of macros that I can resolve as. The closest one I see in that list is `def`. But that leaves me with an *Unused public var* message. Resolving as `deftest` gets rid of both messages, but it is not part of the list.

**Describe the solution you'd like**

I'd love it if `deftest` was included in the list of suggested macros.

**Describe alternatives you've considered**

I can manually edit clj-kondo's config.

**Additional context**

In this [streamed session](https://www.youtube.com/live/3IAWBbhZH6I?si=DGTrB_RZ_m1jaFv3&t=917) Eric Normand uses Calva and we can see him wonder about why the red squiggle on the `defspec`ed symbbol. He never tries to quick-fix it, but if he had he would have ran into a blue squiggle. 😄

**Comment by ericdallo** [comment]
I already thought about that but forgot about the issue, it should be easy and straightforward

**Comment by PEZ** [comment]
Seriously if I had a dime for each nice little thing I have thought of with Calva and then forgotten about, I'd be filthy rich! 😄
