### ISSUE TITLE
Autocomplete namespace aliases

### ISSUE THREAD

**Issue by iGEL** [clojure-lsp/clojure-lsp#1857]
**Is your feature request related to a problem? Please describe.**

I hope it's not my setup with neovim, but I think it'd be great to autocomplete the namespaces aliases.

**Describe the solution you'd like**

It's possible to refer public functions from other namespaces:

```clj
(require '[backend.integration.s3.client :as s3.client])

(s3.client/cl|) ; <- Bar is the cursor, autocompletes all functions of the namespace starting with `cl` 👍
```
But I cannot autocomplete the namespace alias, which is sometimes quite long:
```clj
(require '[backend.integration.s3.client :as s3.client])

(s3.|) ;; <- Bar is the cursor, should autocomplete `s3.client`, but doesn't
```

**Describe alternatives you've considered**

\-

**Additional context**

Thank you for the awesome project :heart:

**Comment by ericdallo** [comment]
@iGEL it looks like something with your vim LSP client, maybe check client <-> server logs

![image](https://github.com/user-attachments/assets/e7450128-e0b8-442c-9195-0f29196851af)

**Comment by iGEL** [comment]
@ericdallo Sorry for the late reply, I'll have a look at that & close the issue for now.

But one question: Why is `f.rename` a suggestion? It's not aliased in your `require`. 🤔
