### ISSUE TITLE
Homebrew error: bad CPU type in executable

### ISSUE THREAD

**Issue by TiLogic** [clojure-lsp/clojure-lsp#1859]
**Describe the bug**

**To Reproduce**

1. `brew install clojure-lsp/brew/clojure-lsp-native`
2. `/usr/local/bin/clojure-lsp --help`

**Expected behavior**
List of available commands and options.

<details>
 <summary><b>clojure-lsp output</b></summary>
<pre>
zsh: bad CPU type in executable: /usr/local/bin/clojure-lsp
</pre>
</details>

**User details (please complete the following information):**
 - OS: macOS 14.5 (Intel)
 - Version: 2024.08.03-15.28.27

**Additional context**
zsh 5.9 (x86_64-apple-darwin23.0)

**Comment by ericdallo** [comment]
I manually editted the binary on latest release as a workaround.
I'm working on understand what CI did wrong

**Comment by ericdallo** [comment]
Got it, github changed the `macos-latest` to be a aarch64 machine, we should use a specific version, I'll fix it

**Comment by ericdallo** [comment]
I'll do a new release fixing this
