### ISSUE TITLE
[LSP] - Support for semantic tokens

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#188]
If this PR merged https://github.com/eclipse/lsp4j/pull/446, we now can start adding support for semantic tokens :)

**Comment by ericdallo** [comment]
@snoe how complicated do you think this would be?

**Comment by snoe** [comment]
It might be a bit difficult to make fast, you'd probably have to go the definition to figure out what it is.
And then we're also pretty vague, we have declarations, which could be a def or defn or macro and don't really give clojure.core stuff special treatment. Might be worth trying a naive implementation of it and see if it's useful tho.

**Comment by ericdallo** [comment]
Yeah, it would be great if we could achieve something like CIDER [syntax highlight](https://docs.cider.mx/cider/config/syntax_highlighting.html).

**Comment by ericdallo** [comment]
Closing as we already implemented that support :)
