### ISSUE TITLE
CI action for nightly build should not pass if binaries cannot be built

### ISSUE THREAD

**Issue by seancorfield** [clojure-lsp/clojure-lsp#1881]
Since the nightly build "succeeds" even if the binaries are not built, anyone trying to use the `nightly` build from Calva will get a broken LSP: it sees there is a new build, but it fails to download the binary (and this breaks, rather than just continuing to use the old version -- which is a separate issue).

Currently, binaries do not build because Actions is rejecting the older artifact downloader:

[linux-amd64](https://github.com/clojure-lsp/clojure-lsp/actions/runs/10818582925/job/30014602806#step:1:36)
This request has been automatically failed because it uses a deprecated version of `actions/download-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

**Comment by ericdallo** [comment]
@seancorfield sorryu for the late reponse, is this still a issue? I fixed all download-actions to use v4

**Comment by ericdallo** [comment]
Closing this as I understand it's fixed given nigthly builds are now passing, LMK otherwise

**Comment by seancorfield** [comment]
I've seen broken nightly downloads in the past but didn't investigate the cause. Nightlies seem to be working right now. If it breaks again, I'll do some investigation and open a new issue. Thanks.
