### ISSUE TITLE
`clojure-lsp` cannot find the definition of `slurp`?

### ISSUE THREAD

**Issue by eval-exec** [clojure-lsp/clojure-lsp#1928]
**Describe the bug**
I have a clojure project, and I have 
```clj
(ns eval-exec.day6
  (:gen-class))

(defn parse-input
  [filename]
  (let [lines (slurp filename)]
    (map #(clojure.string/split % #",") (clojure.string/split lines #"\n"))))

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (println
   (parse-input "input.txt")))
```
When I put cursor on `slurp`, and execute "find definition", but clojure-lsp failed to find the definition of `slurp`.

**Expected behavior**
clojure-lsp should find the definition of slurp, it's should be in clojure.core.

**Screenshots**
no
<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
[Trace - 05:19:04 PM] Sending request 'textDocument/definition - (1113)'.
Params: {
  "textDocument": {
    "uri": "file:///home/exec/Projects/github.com/eval-exec/AdventOfCode/2024/day6/src/eval_exec/day6.clj"
  },
  "position": {
    "line": 5,
    "character": 15
  }
}

[Trace - 05:19:04 PM] Received response 'textDocument/definition - (1113)' in 2ms.
Result: null

</pre>
</details>

<details>
 <summary><b>Log - clojure-lsp</b></summary>
<pre>
no log
</pre>
</details>

**User details (please complete the following information):**
 - OS: NixOs
 - Editor: emacs
 - Version:  clojure-lsp 2024.11.08-17.49.29 clj-kondo 2024.09.28-SNAPSHOT

**Additional context**
No

**Comment by ericdallo** [comment]
I can't repro that, looks like a bad classpath lookup, could you try removing `rm -r .lsp/.cache`, and restarting your editor?

**Comment by eval-exec** [comment]
Thank you, I `rm -rf .lsp` and restart lsp, it worked.
