### ISSUE TITLE
Declarations reported as unused when usage is syntax quoted

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#203]
If I have a function called `login` and I refer to it somewhere by syntax quoting, like:

```clojure
`login
```

then clojure-lsp reports login as being unused.

**Comment by ericdallo** [comment]
Do you have a concrete sample file? 
Just tested with this code, it works, but I'm not sure I understands the issue:
```clojure
(defn bar
  []
  1)

(defn foo []
  (let [a 1]
    `bar))
```

**Comment by bpringe** [comment]
Sorry if I was unclear. This is regarding diagnostics. See in the below image, `sample` is syntax quoted in the `comment` form, but clojure-lsp reports it as unused at the declaration.

![image](https://user-images.githubusercontent.com/12722744/103158140-91eb7000-476f-11eb-8edc-f506208aad2d.png)

**Comment by ericdallo** [comment]
Oh, got it, `clojure-lsp` doesn't add-references for quoted symbols indeed... I'm not sure how hard would it be to implement that support though
Thanks, I'll take a look at this soon

**Comment by ericdallo** [comment]
@bpringe could you check if this issue is solved with latest release? This should be handled by clj-kondo now

**Comment by bpringe** [comment]
Adding it to my list! Will report back.

**Comment by bpringe** [comment]
Works!
