### ISSUE TITLE
Inline-symbol doesn't remove let if symbol was only binding in let

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#210]
Expected:

* Running inline-symbol on a symbol in a `let`, which is the only binding in the `let`, removes the `let`.

Actual:

* When I run inline-symbol and the symbol is from the only binding in a let, the let is left with an empty binding vector.

  ![inline-symbol-let](https://user-images.githubusercontent.com/12722744/102677503-a0c29900-4157-11eb-9509-3e14d61fb20d.gif)

**Comment by ericdallo** [comment]
This is not quite easy since we need to check some corner cases like 

```clojure
(defn ii []
  (let [x 1]
    (+ 2 x)
    (+ 2 4)))
```
should be:
```clojure
(defn ii []
  (+ 2 1)
  (+ 2 4))
```
`rewrite-clj`, the lib we heavily rely on changing/analyzing Clojure code, doesn't allow replace a form with multiple forms like `(+ 2 1) (+ 2 4)`, is not a correct Clojure form so I'm not sure how to fix that, replacing the `let` by a `do` form would help implement too:
```clojure
(defn ii []
  (do
    (+ 2 1)
    (+ 2 4)))
```

**Comment by bpringe** [comment]
I see. I saw the let removal in this gif, which is what made me expect it: https://github.com/clojure-emacs/clj-refactor.el/blob/master/examples/inline-symbol.gif

I realize that is not rewrite-clj, but I arrived there from the readme link pointing to those examples as a reference for what the refactor commands do.

**Comment by ericdallo** [comment]
Yes, maybe we can check how they do, but we may need rewrite-clj anyway

**Comment by snoe** [comment]
You should be able to do this with rewrite-clj by taking the children of the let and adding them to the defn node.

One day we'll switch to rewrite-cljc and leaning more heavily on its paredit API (and expanding) would make this code so much easier.

**Comment by ericdallo** [comment]
@snoe what is needed to switch to rewrite-cljc ? I can help with that

**Comment by snoe** [comment]
@ericdallo this pr https://github.com/clojure-lsp/clojure-lsp/pull/150 
but on clojurians yesterday I saw this from @lread so this is is some progress that means we can switch to the clj-commons version asap and then just double check things work with the cljc playground merges (which I believe lread already tested clojure-lsp)

> Great news, xsc/rewrite-clj has been transferred to clj-commons/rewrite-clj!
> Much thanks to @xsc and @slipset!
> 
> So rewrite-cljc-playground will be merged into rewrite-clj proper.
> This will give a nice continuity for existing rewrite-clj users as @xsc also kindly transfered exisiting clojars xsc/rewrite-clj deploy coordinates.

**Comment by slipset** [comment]
As soon as @lread has done his merging magic, I'll publish a new version of rewrite-clj

**Comment by lread** [comment]
Hey ho!  Yup, I'll be working on this soon! 

It'll be a bit of work, but a 1.0.x-alpha release will happen!

**Comment by ericdallo** [comment]
Gentle ping @lread, any issue on rewrite-clj to track that work :) ?

**Comment by lread** [comment]
> Gentle ping @lread, any issue on rewrite-clj to track that work :) ?

Sure! I'm steadily working on the [v1 branch](https://github.com/clj-commons/rewrite-clj/tree/v1). 
When it is ready, I will merge to the main branch.
I am [tracking progress here](https://github.com/clj-commons/rewrite-clj/projects/1).

**Comment by mainej** [comment]
I think this is low-hanging fruit, made somewhat easier by `rewrite-clj`'s [`splice-killing-backward`](https://cljdoc.org/d/rewrite-clj/rewrite-clj/1.0.767-alpha/api/rewrite-clj.paredit#splice-killing-backward).

The main question is—when is it safe to omit a `do` wrapper?

A quick search through clojure.core turns up the following list. Does anyone see any obvious omissions? Does anyone have a systematic way of finding these?

```
binding
comment
defn
delay
doseq
dosync
dotimes
fn
for
future
io!
let
letfn
locking
loop
sync
when
when-first
when-let
when-not
when-some
while
with-bindings
with-in-str
with-local-vars
with-open
with-out-str
```

**Comment by snoe** [comment]
It would be nice if kondo could tell us, then lint-as and hooks would be able to participate too.

**Comment by mainej** [comment]
clj-kondo does have lint for this, which it calls `:redundant-do`. We could consider adding a `do`, running an extra lint to see if clj-kondo would complain, then removing the `do`. Or we could duplicate [the logic](https://github.com/clj-kondo/clj-kondo/blob/4bd9cca90b235e9e4553d980644cc41d1614a2e3/src/clj_kondo/impl/analyzer.clj#L790-L805) it uses. Comparing its list of expressions where a do is redundant to the list I created above:

| originally proposed | clj-kondo  |
|:--------------------|:-----------|
| binding             | binding    |
| comment             |            |
| defn                | defn       |
|                     | defn-      |
| delay               |            |
|                     | do         |
| doseq               | doseq      |
| dosync              |            |
| dotimes             |            |
| fn                  | fn         |
| for                 |            |
| future              | future     |
| io!                 |            |
| let                 | let        |
| letfn               |            |
| locking             |            |
| loop                | loop       |
| sync                |            |
|                     | try        |
| when                | when       |
| when-first          | when-first |
| when-let            | when-let   |
| when-not            | when-not   |
| when-some           | when-some  |
| while               |            |
| with-bindings       |            |
| with-in-str         |            |
| with-local-vars     |            |
| with-open           | with-open  |
| with-out-str        |            |

My list definitely should have included `defn-`, `do` and `try`. The others I proposed but which clj-kondo doesn't warn about (`comment`, `delay`, etc.) should be double-checked. Whichever we decide actually introduce an implicit `do` could be submitted back to clj-kondo for inclusion in `:redundant-do`.

**Comment by mainej** [comment]
`for` expects 2 arguments, so it shouldn't be a candidate. Revised list:

```
binding
comment
defn
defn-
delay
do
doseq
dosync
dotimes
fn
future
io!
let
letfn
locking
loop
sync
try
when
when-first
when-let
when-not
when-some
while
with-bindings
with-in-str
with-local-vars
with-open
with-out-str
```
