### ISSUE TITLE
clean-ns refactoring only works if cursor inside top level form

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#221]
Here's a gif from Calva. We are sending the line and character values for the current cursor position. If this isn't reproduced by you easily I can provide a more concrete repro case from our side.

![clean-ns](https://user-images.githubusercontent.com/12722744/103178468-d8a49d00-4837-11eb-8169-e0d4e111c4a1.gif)

**Comment by ericdallo** [comment]
I could reproduce the issue indeed using Emacs `lsp-mode`, I'll take a look. (I use this feature all the time, it's odd I never noticed that issue :sweat_smile: )

**Comment by ericdallo** [comment]
Fixed on latest release @bpringe :)

**Comment by bpringe** [comment]
Awesome! :tada:
