### ISSUE TITLE
Can I haz clojure-lsp version together with the `server-info`?

### ISSUE THREAD

**Issue by PEZ** [clojure-lsp/clojure-lsp#228]
I just added the `server-info` in my dev branch of Calva. It would be nice to see the version of `cojure-lsp` there.

If you agree, I'd also like to issue a PR with this. It's time I start contributing to this awesome project. ❤️

**Comment by ericdallo** [comment]
Sure!
I added the server-info for debugging purposes some months ago, the version inside makes sense indeed :)
you can get it from [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/main.clj#L522)
