### ISSUE TITLE
/tmp/lsp.out or /tmp/clojure-lsp.out

### ISSUE THREAD

**Issue by yatesco** [clojure-lsp/clojure-lsp#232]
Hi, in https://github.com/clojure-lsp/clojure-lsp/blob/master/docs/troubleshooting.md it suggests logging is done to `/tmp/clojure-lsp.out` but I only get a `/tmp/lsp.out`.

I'm not sure if this is client specific, and I am using:
 - macOS
 - neovim
 - coc 

Should I do a PR for https://github.com/clojure-lsp/clojure-lsp/blob/master/docs/troubleshooting.md or is this a result of my specific environment?

Thanks!

**Comment by ericdallo** [comment]
We renamed `lsp.out` -> `clojure-lsp.out` a few releases ago, since it's more clear that file is related to clojure-lsp and not any other LSP server.
You probably have an outdated release

**Comment by yatesco** [comment]
Thanks @ericdallo  - I only just installed it via `brew` - I'll install the master version. Thanks!
