### ISSUE TITLE
Clean NS doesn't handle special symbols.

### ISSUE THREAD

**Issue by FongHou** [clojure-lsp/clojure-lsp#236]
com.fulcrologic.guarddrails.core uses a few special symbols in their macros (>defn => | ?). clojure-lsp seems missing spaces when put them back after Clean NS action.

I'm using latest clojure-lsp with coc.nvim. 

![image](https://user-images.githubusercontent.com/13973254/103801337-9b03f900-501b-11eb-96dd-b3f8293ae74a.png)

![image](https://user-images.githubusercontent.com/13973254/103801436-ba9b2180-501b-11eb-8b03-21557144a221.png)

**Comment by ericdallo** [comment]
Hum, good catch, kind of weird macros 😆 does that arrow is a `=>`?

**Comment by FongHou** [comment]
Yes, the arrow is two ascii characters. Fira code render them like one :-)

**Comment by ericdallo** [comment]
Got it, I can take a look at this later today, thanks for the report!

**Comment by ericdallo** [comment]
One last question, @FongHou in your case which `refers` are used? `=>` and `>defn`

**Comment by FongHou** [comment]
Yes, both >defn and => are used. | and ? are not, so clean ns did occur.

**Comment by FongHou** [comment]
One more thing, if | is used. It looks like this after clean NS.

![image](https://user-images.githubusercontent.com/13973254/103805687-ec16eb80-5021-11eb-9e72-c94f4f7745f0.png)

**Comment by ericdallo** [comment]
I don't get this last issue, how would be the correct?

**Comment by FongHou** [comment]
I meant it's the same issue, missing space between | and >defn. In addition, symbols are sorted in different order than original, which is fine.

**Comment by ericdallo** [comment]
Fixed by https://github.com/clojure-lsp/clojure-lsp/commit/3a34e84d600a6830601348a7f2bea86a502bcfbf, @FongHou any issue, feel free to reopen the issue, thank you!
