### ISSUE TITLE
Handle classpath-cmd on Windows without config change

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#237]
In order to make clojure-lsp work on Windows for a typical project, the `:classpath-cmd` in `.lsp/config.edn` (`:project-specs`) needs to be set to `["powershell.exe" <command+args for clj or lein>]`.

It seems that using `lein.bat` as the command is not necessary, so long as the first command is `powershell.exe`. Therefore, I think if clojure-lsp would change its default classpath command to add `powershell.exe` to the beginning if the OS is Windows, this would remove the requirement for people to add a custom classpath cmd in their config (for typical projects).

I think this would improve the out-of-the-box experience. The alternative (for us) would be Calva modifying the `.lsp/config.edn`, but I don't think this is a good route.

**Comment by ericdallo** [comment]
It makes total sense to improve the out-of-the-box experience, but AFAIK we don't know which OS user is using.
I found [these default settings](https://github.com/clojure-lsp/clojure-lsp/blob/0efbc42acdf92e4d9de3980f87c31fe71ab91af7/src/clojure_lsp/crawler.clj#L123-L131), I think adding to it maybe fix the issue?

**Comment by bpringe** [comment]
We can tell which OS the user is using via `(System/getProperty "os.name")`.

Thanks for pointing me to those settings. Another thing I noticed is that with shadow-cljs it assumes they have `shadow-cljs` installed, but this is true also with the other commands.

In addition to adding `powershell.exe` as the first command if the OS is Windows, I think in any case, clojure-lsp should send a message to the client informing when there is an error looking up classpath info (as it logs in clojure-lsp.out). This way, at least when their is an error, they will know immediately.

**Comment by ericdallo** [comment]
Ok, I think we can check the OS that way and add it if it is Windows, I just not sure how it'd looks like the config for Windows:
```clojure
  {:project-path "?"
    :classpath-cmd ["powershell.exe" "?"]}
```

> In addition to adding powershell.exe as the first command if the OS is Windows, I think in any case, clojure-lsp should send a message to the client informing when there is an error looking up classpath info (as it logs in clojure-lsp.out). This way, at least when their is an error, they will know immediately.

We can send a message using `windows/message` LSP method with `error` type, then the client shows to user automatically :)

**Comment by bpringe** [comment]
>We could send a message using windows/message LSP method with error type, then the client shows to user automatically :)

Yes, that's what I was meaning. :smiley:

**Comment by ericdallo** [comment]
@bpringe Could you check if it was fixed by https://github.com/clojure-lsp/clojure-lsp/commit/1d8a0fb065cd44be14d3d169892df9aaed614459 ? I added the `powershell.exe` prefix for default `classpath-cmd` when OS is Windows

**Comment by bpringe** [comment]
I'll check this tomorrow, thanks!

**Comment by bpringe** [comment]
@ericdallo I'm getting this issue on Windows with no `.lsp/config.edn`:

```
ERROR clojure-lsp.crawler: Error while looking up classpath info in c:\Users\brand\development\clojure-test Cannot run program "c:\Users\brand\development\clojure-test" (in directory "powershell.exe"): CreateProcess error=5, Access is denied
java.io.IOException: Cannot run program "c:\Users\brand\development\clojure-test" (in directory "powershell.exe"): CreateProcess error=5, Access is denied
```

As you can see it looks like some args are out of order somewhere, as it's trying to use the directory as the command and the command as the directory.

I'm looking at fixing this now myself, but if you have some useful info or want to take over, please let me know here.

**Comment by ericdallo** [comment]
Yeah 🤦🏻‍♂️ , LMK if need any help with this
The code to be fixed should be [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/crawler.clj#L125-L129)
