### ISSUE TITLE
Move file path in hovers to bottom, under separator

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#240]
Currently it looks like this in VS Code:

![image](https://user-images.githubusercontent.com/12722744/103928758-27242800-50d1-11eb-803b-fbdb7368fadc.png)

And this in Emacs:

![image](https://user-images.githubusercontent.com/12722744/103928924-59358a00-50d1-11eb-8178-f1234ed77014.png)

We should see how it looks on both editors before merging a change.

**Comment by bpringe** [comment]
I plan to make this change myself soon.

**Comment by ericdallo** [comment]
@bpringe the #261 will fix that already

**Comment by ericdallo** [comment]
Fixed on https://github.com/clojure-lsp/clojure-lsp/releases/tag/2021.01.22-13.04.28
