### ISSUE TITLE
Repeated automatic require

### ISSUE THREAD

**Issue by lucasdf** [clojure-lsp/clojure-lsp#247]
Hello,

It seems that since version [2021.01.07-02.38.39](https://github.com/clojure-lsp/clojure-lsp/compare/2021.01.07-00.58.26...2021.01.07-02.38.39) `clojure-lsp` started adding duplicated requires when triggering autocomplete with `coc-nvim`.

**Comment by ericdallo** [comment]
Hi @lucasdf, could you provide a sample code, I could not reproduce it on Emacs lsp-mode

**Comment by lucasdf** [comment]
Hey @ericdallo , pretty much any autocomplete here is triggering a new require (even if one already exists) starting on that version. I couldn't see anything weird on the logs.

**Comment by ericdallo** [comment]
@lucasdf I found the issue :) I'll fix it ASAP, thanks!

**Comment by ericdallo** [comment]
It should be fixed now on latest release @lucasdf, LMK if any issues!

**Comment by lucasdf** [comment]
awesome! I tested it here and it is all good now. thanks!
