### ISSUE TITLE
Windows release support

### ISSUE THREAD

**Issue by snoe** [clojure-lsp/clojure-lsp#25]
Thanks to @sparkofreason for trying clojure-lsp in windows:

1) At first glance, it looks like there are at least a few places that ought to use path joins instead of `str` and  `"/"` 
https://github.com/snoe/clojure-lsp/blob/e1d892a13ef23f130009e0058bbdd0157d885d0e/src/clojure_lsp/handlers.clj#L26
https://github.com/snoe/clojure-lsp/blob/e1d892a13ef23f130009e0058bbdd0157d885d0e/src/clojure_lsp/handlers.clj#L146

2) Does the classpath lookup using `shell/sh` work in windows? I'm splitting the result with `path.separator` so maybe that's correct (iirc windows puts `:` vs `;` to separate classpath).

3) My understanding is that the org.xerial/sqlite-jdbc jar provides sqlite but that needs to be confirmed or else installed separately.

4) @sparkofreason says: 
> Took a bit of hacking, but I got something to happen with `clojure-lsp` on windows. I updated to https://github.com/BrunoBonacci/lein-binplus, and had to rename the output with a `.bat` extension.

We should switch the bin generation and produce these files in CI.

**Comment by snoe** [comment]
with 9b035767e5464, 4a580859 and 49702e717316 I was able to get it working pretty well in windows and vscode.

I had to install `lein` through chocolatey (otherwise using the self installer bat file only worked if I changed the classpath lookup to `lein.bat`).

I also had to rename `clojure-lsp` to `clojure-lsp.bat` and change `extension.js` to point to the .bat file. I hope https://github.com/snoe/clojure-lsp/issues/28 will fix this as it did with lein.

Zipfile links (any definition inside a jar) predictably failed to open in vscode - raising this issue to track it separately: https://github.com/snoe/clojure-lsp/issues/27

Other than that, I *think* things are working ok. Keeping this open until https://github.com/snoe/clojure-lsp/issues/28 is done

**Comment by ericdallo** [comment]
I think only adding to the CI a `clojure-lsp.bat` would be enough to close this issue

**Comment by ericdallo** [comment]
BTW we now include `clojure-lsp.bar` in our release:
https://github.com/clojure-lsp/clojure-lsp/releases/edit/2020.12.29-20.42.24

**Comment by ericdallo** [comment]
Closing this since we now have `clojure-lsp.bat` and GraalVM compiled Windows binaries
