### ISSUE TITLE
Add setting for exlcuding files from linting

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#255]
Calva uses the file  `.calva/output-window/output.calva-repl` as it's output/repl window. This file is sent to clj-kondo for linting by clojure-lsp, which results in a parsing error by clj-kondo.

![image](https://user-images.githubusercontent.com/12722744/104497098-b5dfeb80-558e-11eb-904d-0e360ada6740.png)

As Eric said in slack, maybe a setting for files to exclude would be ideal. I'm not sure yet if it should be a set/vector of paths, glob patterns, or something else.

**Comment by bpringe** [comment]
I'm exploring this now, just FYI.

**Comment by ericdallo** [comment]
I forget to mention that If I'm not mistaken there is an option to avoid LSP watch some file changes... but If you open the file manually it'll still lint it.

**Comment by bpringe** [comment]
So... I've found a solution on Calva's side. I can check the uri in the `handleDiagnostics` middleware and return nothing if it's the .calva-repl file. I'm not sure if this is the best solution since clojure-lsp will still run the file through clj-kondo each time it's opened, however:

1. The process of linting the file and getting the error is virtually instant from what I've seen.
2. This will only happen when the .calva-repl file is opened, which won't occur very often (users either work with it open or closed most of the time).

My perfectionist side wants to make the linting not even happen in clojure-lsp, but my practical side says it may not be worth the added setting, code, and complexity. Thoughts?

**Comment by ericdallo** [comment]
> My perfectionist side wants to make the linting not even happen in clojure-lsp, but my practical side says it may not be worth the added setting, code, and complexity. Thoughts?

Super agree with that 😅, I still think that it may have some way to suppress the diagnostics for a file following the spec.
Anyway, feel free to implement that in clojure-lsp if you think that worth it, LMK if need any help.

**Comment by ericdallo** [comment]
Well I asked lsp-mode folks for some help and it seems it doesn't have that kind of feature in protocol level indeed

**Comment by bpringe** [comment]
Going to close this since I think my current solution is fine. Even clj-kondo offers a way to filter output, which doesn't help in this case, but aligns with what I did. I don't think an unnecessary parse/error here and there is something to be concerned about.

If this need comes up for something else in the future maybe it can be revisited.
