### ISSUE TITLE
Duplicate reference location returned when finding references

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#260]
See [this comment here](https://github.com/clojure-lsp/clojure-lsp/issues/257#issuecomment-761277649) for details, as this occurred after that fix.

It seems with the `includeDeclaration` param set to `true`, clojure-lsp is considering the location that the references request was made from as being the declaration. :thinking:

**Comment by ericdallo** [comment]
@PEZ It should be fixed on latest release, could you confirm, please?

**Comment by bpringe** [comment]
Works! Thanks!
