### ISSUE TITLE
Clj-kondo config not being respected by clojure-lsp

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#262]
If I place some config in `.clj-kondo/config.edn` in my project directory, it doesn't seem to be respected by clojure-lsp, which contradicts what the docs say.

For example, content of `^:replace {:linters {}}` in that file I believe should disable all linting in the project, but it does not.

This was brought up by @svdo regarding usage with Calva. https://github.com/BetterThanTomorrow/calva/issues/961

I know #261 may fix this, but how far off is that PR? In the meantime it seems clj-kondo config via clojure-lsp is broken. Should a fix be implemented prior to that PR being merged?

**Comment by ericdallo** [comment]
@snoe and I are putting all the efforts ATM to fix that PR, but a PR with few changes to avoid conflicts just fixing the issue could help :)
The issue may be here: https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/feature/diagnostics.clj#L81-L98

**Comment by bpringe** [comment]
I just realized config of kondo still works through .lsp/config.edn (:clj-kondo) so I'm fine with leaving this as-is until the PR is merged. Thanks!

**Comment by bpringe** [comment]
@ericdallo This is actually an issue related to monorepos and was fixed in clj-kondo. An update to clj-kondo as well as maybe a small change to how `run!` is called should fix it, see here: https://github.com/BetterThanTomorrow/calva/issues/961#issuecomment-762772554

If again you think this will be fixed with that PR maybe it should wait.

**Comment by ericdallo** [comment]
Before that PR merge, we will use latest clj-kondo so it probably fix it, after the merge I'll iterate over each PR related and ask to test again ;)

**Comment by ericdallo** [comment]
Closing this since there is no way to configure `clj-kondo` settings via `.lsp/config.edn` anymore, all clj-kondo config should be done via the canonical way (`.clj-kondo/config.edn` for example)
