### ISSUE TITLE
Use npx for shadow-cljs classpath lookup instead of globally installed shadow-cljs

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#271]
It seems like the classpath lookup failure happens most often with shadow-cljs. Currently clojure-lsp tries to run a globally installed `shadow-cljs`, but some users don't have this installed. If instead clojure-lsp used `npx shadow-cljs` this would cover a broader range of cases and result in fewer failures.

Calva uses `npx shadow-cljs` for its jack-in command for shadow-cljs projects.

**Comment by bpringe** [comment]
Related issue: https://github.com/BetterThanTomorrow/calva/issues/984 (though we aren't positive the cause here). I've seen this issue elsewhere too, in which case the user didn't have `shadow-cljs` globally installed.

**Comment by ericdallo** [comment]
Got it, I think we can try to use first `npx shadow-cljs` and fallback to `shadow-cljs` if doesn't work. WDYT? 
Not sure how we can check if npx is available  or not though

**Comment by bpringe** [comment]
`shadow-cljs` is an npm package. `npx` comes with npm and allows you to run npm packages without installing them. So if `npx shadow-cljs` doesn't work, I think almost certainly `shadow-cljs` won't work, so I don't think the fallback is appropriate.

**Comment by ericdallo** [comment]
I was thinking in something like this:
```clojure
(defn ^:private classpath-cmd->windows-safe-classpath-cmd
  [classpath]
  (if shared/windows-os?
    (into ["powershell.exe"] classpath)
    classpath))

(defn ^:private command-exists?
  [command]
  (let [check-command (if shared/windows-os? "where.exe" "which")]
    (try
      (= (:exit (apply shell/sh check-command [command])) 0)
      (catch Exception _
        false))))

(defn ^:private with-shadow-cljs-project-spec
  [specs]
  (cond
    (command-exists? "npx")
    (conj specs {:project-path "shadow-cljs.edn"
                 :classpath-cmd ["npx" "shadow-cljs" "classpath"]})

    :else
    (conj specs {:project-path "shadow-cljs.edn"
                 :classpath-cmd ["shadow-cljs" "classpath"]})))

(defn ^:private default-project-specs []
  (->> [{:project-path "project.clj"
         :classpath-cmd ["lein" "classpath"]}
        {:project-path "deps.edn"
         :classpath-cmd ["clj" "-Spath"]}
        {:project-path "build.boot"
         :classpath-cmd ["boot" "show" "--fake-classpath"]}]
       with-shadow-cljs-project-spec
       (map #(update % :classpath-cmd classpath-cmd->windows-safe-classpath-cmd))))

```

If you think it's too much we can just add `npx` before `shadow-cljs`

**Comment by bpringe** [comment]
Yeah, I think if `npx` is not found, `shadow-cljs` will not be found, in most or all cases, since shadow-cljs is an npm package, and npx comes with npm. Maybe @PEZ can confirm this, but I'm pretty certain.

**Comment by ericdallo** [comment]
I see, I thought user could just `npm install -g shadow-cljs`

**Comment by bpringe** [comment]
They can, but they don't have to install shadow-cljs when using `npx`. So using `npx` covers a much wider group of users. I was just watching a stream recording earlier of a guy using Calva with a shadow project, and he got the classpath lookup failure warning, likely because he didn't have `shadow-cljs` installed. But if `npx` would have been used it would have worked. I know this because he used Calva's jack-in which worked and used `npx`.

**Comment by bpringe** [comment]
Some people work on shadow projects without having `shadow-cljs` installed globally.

**Comment by ericdallo** [comment]
Oh, sorry I was not clear, I agree there are more users using `npx shadow-cljs` and it's the recommended AFAIK, but if we just add `npx` it'll probably stop working for few users that have shadow-cljs globally installed, right?
I know it's a trade-off and probably is the best to do here, but I'm just checking the 2 sides of the issue 😅

**Comment by bpringe** [comment]
> but if we just add npx prefix it'll probably stop working for few users that have shadow-cljs globally installed, right?

No, I don't think so. Maybe I was the one not clear. I meant that in order to install it globally they _must_ have used `npm` which means they _must_ have had `npx`. This is what I want @pez to verify. There could be some small set of cases in which this isn't totally, like maybe they uninstalled npm/npx after installed shadow-cljs globally, but then I'm not sure if shadow-cljs would still work, and even if so, that's probably a very unlikely scenario, and not something to be accounted for.

**Comment by ericdallo** [comment]
Oh got it, I think we can go with the `npx` prefix only, if @PEZ agree, I can merge the PR: https://github.com/clojure-lsp/clojure-lsp/pull/272

**Comment by PEZ** [comment]
I think `npx shadow-cljs` is a safe bet. Maybe if the user hasn't run `npm install` in the project, that it would fail, but then everything fails. I don't think I have never seen a report of Calva jack-in failing because of this, and we don't have fallback.

**Comment by ericdallo** [comment]
Thank you both!

**Comment by dpsutton** [comment]
> Maybe if the user hasn't run npm install in the project, that it would fail, but then everything fails.

just went to an empty directory in tmp and ran `npx shadow-cljs --help` and it runs fine with no errors. `npx` does not seem to require a local one to be installed. So this sounds like 100% safe unless the person does not have npm installed. Probably rare but could happen if they only use `yarn`.

**Comment by ericdallo** [comment]
Thank you for the test @dpsutton!
