### ISSUE TITLE
Using/persisting only last kondo batch analysis 

### ISSUE THREAD

**Issue by FongHou** [clojure-lsp/clojure-lsp#284]
Hi @ericdallo, reporting more issues :-)

Hover doc and goto definition do not work for external dep jars. I noticed size of clojure-lsp/.lsp/sqlite.db (recreated fresh by latest release) is much smaller than before (clj-kondo rewrite). It used to be 5-7 MBs, now it's only 0.8 MB. Do you see the same in your local repo?

```
❯ ll .lsp/
total 868
drwxr-xr-x  2 haskeller haskeller   4096 Jan 27 17:28 ./
drwxr-xr-x 15 haskeller haskeller   4096 Jan 27 17:23 ../
-rw-r--r--  1 haskeller haskeller    337 Jan  8 15:55 config.edn
-rw-r--r--  1 haskeller haskeller 876544 Jan 27 17:28 sqlite.db
```
![image](https://user-images.githubusercontent.com/13973254/106069265-3135b700-60d0-11eb-85e0-48b44dff82ca.png)

**Comment by ericdallo** [comment]
Not actually, this should work, but we completely rely on clj-kondo (`.clj-kondo/.cache`), so coult you test it removing `.clj-kondo/.cache` and `.lsp/sqlite.db` and restart the server and test it again?

**Comment by FongHou** [comment]
Did that.  .clj-kondo/.cache contains 1263 files. sqlite.db is recreated as shown in clojure-lsp.out

[clojure-lsp.txt](https://github.com/clojure-lsp/clojure-lsp/files/5883952/clojure-lsp.txt)

Here are hover request/response. Not sure all expected metadata were returned?

```
[Trace - 7:23:29 PM] Sending request 'textDocument/hover - (6)'.
Params: {
    "textDocument": {
        "uri": "file:///home/haskeller/github/clojure-lsp/src/clojure_lsp/crawler.clj"
    },
    "position": {
        "line": 17,
        "character": 1
    }
}


[Trace - 7:23:29 PM] Received response 'textDocument/hover - (6)' in 22ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```clojure\ndefn\n```\n\n----\n*/home/haskeller/github/clojure-lsp/src/clojure_lsp/crawler.clj*"
    },
    "range": {
        "start": {
            "line": 17,
            "character": 1
        },
        "end": {
            "line": 17,
            "character": 5
        }
    }
}

```

**Comment by FongHou** [comment]
goto-definition request/response

```
[Trace - 7:35:47 PM] Sending request 'textDocument/definition - (17)'.
   1 Params: {
   2     "textDocument": {
   3         "uri": "file:///home/haskeller/github/clojure-lsp/src/clojure_lsp/crawler.clj"
   4     },
   5     "position": {
   6         "line": 17,
   7         "character": 3
   8     }
   9 }
  10
  11
  12 [Trace - 7:35:47 PM] Received response 'textDocument/definition - (17)' in 9ms.
  13 No result returned.
  14
  15                                                                                                                                                                        
```

**Comment by ericdallo** [comment]
Ok, I'll check that soon, thanks for the detailed test :)

**Comment by ericdallo** [comment]
Hey @FongHou this is actually a huge bug, we are only using/persisting the last clj-kondo batch analysis, I'm fixing it

**Comment by ericdallo** [comment]
Fixed on latest release, thank you very much for the report ;)
