### ISSUE TITLE
Re-add support for keywords

### ISSUE THREAD

**Issue by snoe** [clojure-lsp/clojure-lsp#288]
We lost this functionality with the kondo analysis, kondo will now support it (see commented out analysis/README.md: https://github.com/clj-kondo/clj-kondo/issues/1129)

We should be able to bring back the old behavior
- go to def if a keyword has a `:def` on it
- rename - only rename the keyword if the cursor is on a raw keyword (i.e. not also a local destructuring binding)
  - `(let [{:keys [:f|oo]} stuff] foo)` should only rename the local, not the keyword. 
  - rename the alias of an aliased keyword (`::alias/kw`) if you rename with the cursor on the alias in the require. Renaming with a cursor on an aliased keyword would just be changing the kw `name`. (This should follow the behaviour when renaming vars)
- find usages, completion, hover, etc

**Comment by ericdallo** [comment]
Some doubts:
- About the `:def`, do you have an example of the first one?
- About the rename, in this case renaming `:foo` should rename the `foo` local-usage but not he `:foo`? I don't get it.

**Comment by snoe** [comment]
- goto def on the `|` in `(s/def ::my-spec string?) ::|my-spec` should go to col 7
- yes, it is very dangerous and surprising to rename keywords from bindings. so renaming foo to bar in `(let [{:keys [:f|oo]} stuff] foo) :foo` should result in `(let [{:keys [:bar]} stuff] bar) :foo`
  - in cursive it asks if you want to rename the keyword too, but I don't think lsp has that ability so it's better to not. (maybe a client setting can change that but for now let's just get back to where we were.

**Comment by ericdallo** [comment]
Oh got it, so it should rename the local-usage of that let scope but not the :foo from outsize, ok it makes sense now
