### ISSUE TITLE
Add binary test (Integration test)

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#289]
With the GraalVM build, we can break the build with any reflection code or non type hinting in some cases, so it'd be great to start with a simple test that it'd load the binary and send the initialize request and receive the response.

**Comment by FongHou** [comment]
@ericdallo, is graal-vm binary build ready to use? I tried it, but it seems clojure-lsp stuck in-progress forever, again from coc.nvim...

**Comment by ericdallo** [comment]
Yeah not ready yet, I removed the latest bugged release since I'm still WIP on the CI, sorry for that

**Comment by ericdallo** [comment]
It's ready now @FongHou :)

**Comment by ericdallo** [comment]
Related to #285

**Comment by FongHou** [comment]
@ericdallo, linux static link binary segfault. 

https://github.com/clojure-lsp/clojure-lsp/releases/download/2021.02.02-14.02.23/clojure-lsp-native-static-linux-amd64.zip

**Comment by ericdallo** [comment]
Yes, Linux static binary will not work until sqlite fix it's deps, I'll try to open an issue there

**Comment by ericdallo** [comment]
I created this issue to track that: https://github.com/clojure-lsp/clojure-lsp/issues/296
