### ISSUE TITLE
Improving clojure-lsp completion 

### ISSUE THREAD

**Issue by FongHou** [clojure-lsp/clojure-lsp#292]
@ericdallo, link the issue from
Auto completion does not work in clojure-lsp only mode (no repl connection). #996.

**Comment by ericdallo** [comment]
https://github.com/BetterThanTomorrow/calva/issues/996#issuecomment-771320467

**Comment by ericdallo** [comment]
About https://github.com/BetterThanTomorrow/calva/issues/996#issuecomment-771320467, yeah, that's the idea, but is not that easy have a ID for the completion item, we would need to persist it somewhere, so IMO we could drop the resolveItem method and just calculate the documentation content on textDocument/completion, clojure-lsp already don't return a lot of symbols/we don't have a history of bad performance on completion.

**Comment by ericdallo** [comment]
Fixed on master to return documentation on the `textDocument/completion`, we don't have/require anymore `completion/resolveItem` since it's not necessary for clojure-lsp anymore.
Completion on Calva should work as expected now
