### ISSUE TITLE
re-create `install_clojure_lsp` downloading the correct GraalVM binary

### ISSUE THREAD

**Issue by barkanido** [clojure-lsp/clojure-lsp#298]
After resurrecting it from Git, it still works. Any reason for removing it?

**Comment by ericdallo** [comment]
Hi @barkanido , we are using the releases to distribute the binaries, also in the future, probably we will just release the jar and the graalvm native compiled binaries, so the embedded jar will be deprecated, is there any reason for you to use the embedded jar instead of using it from releases?

**Comment by barkanido** [comment]
Wdym by the "embedded jar"? Is this the executable from the releases page? Iiuc the download script, it just downloads it  amd copies it to a proper place in my Path. I use vim and so COC uses the executable.

**Comment by ericdallo** [comment]
yes, that executable should be removed soon, replaced by the graalvm native images (windows, linux or macos).
That executable is a embedded jar, it uses the `lein bin-plus` plugin that has some bugs with jars with some dependencies, it's a matter of time to stop working...
You probably need some script that checks the OS and download the correct binary, right?

**Comment by barkanido** [comment]
Well, it is just a convenience I got used to. While it is not critical, it would be good to keep it updated. I do also understand the hassle in maintain an Ubuntu ppo.
A better option (but it might be just for me) would be to teach COC to do it (like the rust lsp client checks for a new version on rust-analizer when it starts).

**Comment by ericdallo** [comment]
yes, lsp-mode for emacs do that too, I think this would be the better approach, we also can re-create the script but change the logic to check the OS and download the correct binary, WDYT?
But I still think this should be logic from the clients

**Comment by barkanido** [comment]
Just fixing the script would be an easy work around. COC clojure should be be improved, but agreed.

**Comment by ericdallo** [comment]
Ok, I'll add this as a implement so

**Comment by ericdallo** [comment]
Done @barkanido, I create the `install-latest-clojure-lsp.sh` that download the latest graalvm compiled binary checking your OS
