### ISSUE TITLE
Allow require unknown namespaces guessing the alias

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#302]
Using version 2021.02.05-03.05.34 with Calva, if I run this command on `clojure.set/union` below, the require is not added (nothing changes). Shouldn't it add the missing require?

```clojure
(ns windows
  (:require [hiccup.core :as h]))

(clojure.set/union)
```

Request and response:

```
[Trace - 1:37:32 PM] Sending request 'workspace/executeCommand - (229)'.
Params: {
    "command": "add-missing-libspec",
    "arguments": [
        "file:///home/brandon/development/clojure-test/src/windows.clj",
        3,
        16
    ]
}


[Trace - 1:37:32 PM] Received response 'workspace/executeCommand - (229)' in 1ms.
No result returned.
```

/tmp/clojure-lsp.out says:

```
2021-02-05T21:37:32.195Z brandon-desktop WARN [clojure-lsp.feature.refactor:94] - :add-missing-libspec made no changes clojure.set/union
```

**Comment by bpringe** [comment]
This is on linux ^

**Comment by snoe** [comment]
I think it's been mostly aliased based in the past, so if you've never required it before it doesn't come in. It's not great when you run into it tho, so this would be a good change

What should the behaviour here be?
What does cider/refactor do? (I think it adds the require as `[clojure.set :as set]` and modifies the call to `set/union`)
What would happen for user-libs like 'medley.core' or 'clj-http.client' that haven't been required yet?

**Comment by bpringe** [comment]
Oh I see.

> What would happen for user-libs like 'medley.core' or 'clj-http.client' that haven't been required yet?

I'm not sure what all is possible, but I'll just say what "would be nice" and then maybe that will lead somewhere.

It would be nice if when I ran the command in my editor for something like `clj-http.client` it would a require like `clj-http.client :as client`, all usages are changed to `client`, but then the alias in the require and all usages are selected with cursors for editing, so I can immediately change them all at once, or decide to leave them.

I know this may not be an option, but that would be nice :smile:.

**Comment by ericdallo** [comment]
Any reason why not using the code actions? clojure-lsp already check if it supports the add require for that line col and suggest you, but @snoe is correct, ATM we have these features:
- add require if it was already required before on other file in the same project
- add a common require (set -> clojure.set, string -> clojure.string, etc)
- Add common java imports (java.util.Date, etc)
What is your suggestion here @bpringe ?

**Comment by ericdallo** [comment]
Yeah, I like your idea but the LSP spec doesn't support that AFAIK :/ 
We can only add the require and change the places to some alias, then you can rename the alias

**Comment by bpringe** [comment]
I don't get the add missing libspec code action returned for that union call, but maybe because clojure-lsp knows it can't do anything there.

```
[Trace - 1:58:36 PM] Sending request 'textDocument/codeAction - (322)'.
Params: {
    "textDocument": {
        "uri": "file:///home/brandon/development/clojure-test/src/windows.clj"
    },
    "range": {
        "start": {
            "line": 3,
            "character": 14
        },
        "end": {
            "line": 3,
            "character": 14
        }
    },
    "context": {
        "diagnostics": [
            {
                "range": {
                    "start": {
                        "line": 3,
                        "character": 1
                    },
                    "end": {
                        "line": 3,
                        "character": 18
                    }
                },
                "message": "Unresolved namespace clojure.set. Are you missing a require?",
                "severity": 2,
                "code": "unresolved-namespace",
                "source": "clj-kondo"
            }
        ]
    }
}


[Trace - 1:58:36 PM] Received response 'textDocument/codeAction - (322)' in 8ms.
Result: [
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "command": {
            "title": "Clean namespace",
            "command": "clean-ns",
            "arguments": [
                "file:///home/brandon/development/clojure-test/src/windows.clj",
                3,
                14
            ]
        }
    }
]
```

Are you saying those features exist or those are options to implement?

> add a common require (set -> clojure.set, string -> clojure.string, etc)

The above makes sense to me. It is a bit hard-coded, as opposed to just using a generic solution that would use the last part of the ns, but fairly simple to maintain for common requires it seems.

**Comment by bpringe** [comment]
> We can only add the require and change the places to some alias, then you can rename the alias

I'd say doing this makes sense. Just use the last part of the ns for the alias. If it conflicts, the user can rename the alias easily (I think - not sure if a conflict would cause a rename of the wrong alias usages).

**Comment by ericdallo** [comment]
> I don't get the add missing libspec code action returned for that union call, but maybe because clojure-lsp knows it can't do anything there.

I mean, server return the available code actions for that line column, if server provides a `add-missing-require` code actions, it's because it can be applied there, otherwise it won't return that.
In `lsp-mode`,  we have a icon in the modeline that shows how many code actions there are for that line:

![image](https://user-images.githubusercontent.com/7820865/107094390-af3b4180-67e5-11eb-9b18-f8070559c899.png)

And if user run `lsp-execute-code-action`, we ask which one he wants to apply:

![image](https://user-images.githubusercontent.com/7820865/107094532-e9a4de80-67e5-11eb-9d7a-3332918ac18d.png)

I know VScode supports something like that too.

> I'd say doing this makes sense. Just use the last part of the ns for the alias. If it conflicts, the user can rename the alias easily (I think - not sure if a conflict would cause a rename of the wrong alias usages).

Seems a valid idea for me, we could return this code action only if not conflicts or provide a hard coded alias for user change it.

**Comment by bpringe** [comment]
Yes, VS Code has a similar feature you can see here.

![image](https://user-images.githubusercontent.com/12722744/107095914-83589580-67be-11eb-9339-05bbc435e224.png)

**Comment by snoe** [comment]
Well, in theory we can apply an edit for both the new code `(clojure.set/union) => (set/union)` and the require.

A possible algorithm for determining an alias if a user types in a known ns without a known project alias. (if they type in a ns with a known alias, use that)

if the ns ends in `core` drop it. `(medley.core/map-vals) => (medley/map-vals)`
if the last of the ns is not an existing alias then use it. `(clj-http.client/get) => (client/get)`
if the last part of the ns is already an existing alias then grab the next part (recursively) `(my.utils.string/pluralize) => (utils.string/pluralize)`

**Comment by ericdallo** [comment]
looks valid 👍🏻 I'll add to the project

**Comment by ericdallo** [comment]
The `add-missing-*` code actions are my favorite features of `clojure-lsp`, It'd be really cool to make that work :)

**Comment by bpringe** [comment]
I had suggested in #222 that this code action be sent as the `quickfix` `CodeActionKind`. Just noting here, but should this be a separate issue/request?

**Comment by ericdallo** [comment]
It's the same feature @bpringe, I'm implementing that cide action right now

**Comment by ericdallo** [comment]
Done @bpringe, available on [latest release](https://github.com/clojure-lsp/clojure-lsp/releases/tag/2021.02.07-03.04.31)
