### ISSUE TITLE
Allow clj-kondo to pick up config correctly in mono repos

### ISSUE THREAD

**Issue by svdo** [clojure-lsp/clojure-lsp#303]
This is about https://github.com/BetterThanTomorrow/calva/issues/961:

borkdude says: "not overriding :config-dir and passing :filename for linting a single file should be a sufficient fix"

Thanks! :)

**Comment by ericdallo** [comment]
Thanks! I'll take a look soon

**Comment by ericdallo** [comment]
Fixed on master, I tested and it seems to work picking up the parent dir clj-kondo config from filename :)
Should release tomorrow
