### ISSUE TITLE
Can't re-analyze cache from startup with keywords starting with number

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#305]
As found by @rvlo [here](https://github.com/clj-kondo/clj-kondo/issues/1160) and confirmed by me, clojure-lsp can't parse analysis from cache(sqlite) when there is any keyword that starts with a number.

Probably this fix should be done in clj-kondo persisting the `:name` as string or not providing those keywords.

**Comment by rvlo** [comment]
@ericdallo, I've already implemented a fix and will submit a new PR soon.

**Comment by ericdallo** [comment]
Nice @rvlo, I was talking with @borkdude that probably persisting it as string would be the best approach, is your fix that or something else?

**Comment by ericdallo** [comment]
Fixed with https://github.com/clj-kondo/clj-kondo/pull/1162 and https://github.com/clojure-lsp/clojure-lsp/commit/2d1bb4dd1f7445746ad960c62d7f63bd5dc721da
