### ISSUE TITLE
Re-add support to add libspec from completions

### ISSUE THREAD

**Issue by snoe** [clojure-lsp/clojure-lsp#309]
Pre-kondo un-required namespace completions would add the require automatically when the item was chosen. 
We should do that again.

**Comment by ericdallo** [comment]
Yeah, I didn't notice that, I'll check how hard would be to implement that

**Comment by ericdallo** [comment]
@snoe could you show me an example?
ATM we don't return all available functionvars unless the alias was typed like `foo/b`, I think to fix this issue, we would need to return `foo/bar` even if user just started type the alias like `fo` ?

**Comment by snoe** [comment]
We used to show vars when a full alias or ns was typed. But if you complete to one of those we should still add the spec.

So if `foo/bar` exists and you type:
`f => ["foo (ns)"]` and uses doc-changes to add a require for `foo` if chosen.
`foo = ["foo (ns)", "foo/bar (fn)"]`
`foo/ = ["foo (ns)", "foo/bar (fn)"]` (this one is hard)
`foo/b = ["foo/bar (fn)"]`

**Comment by snoe** [comment]
Fixed by 1de177a63c93bcaf1e93c12ac43d939f9814d439
