### ISSUE TITLE
Autocomplete not working on neovim on required namespaces

### ISSUE THREAD

**Issue by Matsuuu** [clojure-lsp/clojure-lsp#312]
**Describe the bug**

Automatic completion with Neovim and and [completion-nvim](https://github.com/nvim-lua/completion-nvim) doesn't work for required namespaces.

**To Reproduce**
1. Create a fresh file
2. Require a namespace (i used clojure.string as string)
3. Start writing a call to a function inside said namespace (in my example (string//split))

**Expected behavior**
The autocompletion offers from the LSP should offer possible autocompletion offers as soon as the user presses either the `/`-key or the key right after that

Currently in my setup I get nothing

Completion works in the core libraries, so some of it at least works?

**Screenshots**

![image](https://user-images.githubusercontent.com/16068444/107693152-6a684c80-6cb6-11eb-9889-b3f028bc2ed1.png)

![image](https://user-images.githubusercontent.com/16068444/107693249-89ff7500-6cb6-11eb-9bf2-fa2e80251973.png)

**User details (please complete the following information):**
 - OS: Ubuntu 20.04
 - Editor: NeoVim 0.5 Nightly with completion-nvim and nvim-lspconfig (which proven working with js, ts and java)
 - Version: clojure-lsp 2021.02.11-12.43.06

**Logs**

**Additional context**

Discussion started in the clojurians slack with @ericdallo

**Comment by ericdallo** [comment]
@Matsuuu could you provide the request / response info between the vim client and the server?
Not sure how to get that for nvim

**Comment by Matsuuu** [comment]
Is this what you meant? I can try to go through if I can get more info 

https://gist.github.com/Matsuuu/89a24470b3edff6035ed5284751ca4dd

I first wrote `(println "hello world")`  (starting at aroung 350)  to ensure the completion works, and then tried with the `(string/split)` (starting at around 450?)

**Comment by ericdallo** [comment]
No, it is not, we need the json logs between client and server like [here](https://github.com/clojure-lsp/clojure-lsp/issues/311#issuecomment-777617492)

**Comment by ericdallo** [comment]
@Matsuuu not sure, but this could be solved by #315 , could you test it again with latest clojure-lsp?

**Comment by Matsuuu** [comment]
That actually fixed it. Or at least a part of it!

Now I get the autofill for for example `clojure.string`  but it seems to only trigger after I've erased one character and re-typed it. (see video). 

Looking at the logs, (I couldn't find any pure json logs, sorry), it seems to relate to https://github.com/clojure-lsp/clojure-lsp/issues/270


https://user-images.githubusercontent.com/16068444/107738568-98c64600-6d0f-11eb-9029-db41bfc6c884.mp4

```
 [ DEBUG ] 2021-02-12T08:38:11+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]    "decoded"   {  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = "syntax",        message = "Invalid sym
       │ bol: string/.",        range = {          end = {            character = 7,            line = 0          },          start = {            character = 7,            line = 0          }        },        severity = 1,        source = "clj-kondo"      } },    uri
       │  = "file:///home/matsu/projects/learning-clojure/learning/src/learning/dayone/dayone.clj"  }}
 [ DEBUG ] 2021-02-12T08:38:11+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:488 ]    "notification"  "textDocument/publishDiagnostics"   {  diagnostics = { {      code = "syntax",      message = "Invalid symbol: string/.",      range = {        end = {
       │           character = 7,          line = 0        },        start = {          character = 7,          line = 0        }      },      severity = 1,      source = "clj-kondo"    } },  uri = "file:///home/matsu/projects/learning-clojure/learning/src/learning/da
       │ yone/dayone.clj"}
[ DEBUG ] 2021-02-12T08:38:11+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp/handlers.lua:394 ]   "default_handler"   "textDocument/publishDiagnostics"   {  client_id = 1,  params = {    diagnostics = { {        code = "syntax",        message = "Invalid sy
       │ mbol: string/.",        range = {          end = {            character = 7,            line = 0          },          start = {            character = 7,            line = 0          }        },        severity = 1,        source = "clj-kondo"      } },    ur
       │ i = "file:///home/matsu/projects/learning-clojure/learning/src/learning/dayone/dayone.clj"  }}
```

**Comment by ericdallo** [comment]
Not sure is related with #270, but there is a chance indeed, if you type the `string/spl` fast enough to avoid querying preious and with cache results, you should make it work

**Comment by Matsuuu** [comment]
I tried typing at about 1 letter / 5 seconds and still ran into the problem. After a single backspace it's all right again, but not having to do a backspace every time would be grand :)

**Comment by ericdallo** [comment]
@Matsuuu #270 was fixed, could you try again and open a new issue if not fixed?
