### ISSUE TITLE
Autocompletion for namespaces

### ISSUE THREAD

**Issue by Matsuuu** [clojure-lsp/clojure-lsp#314]
**Is your feature request related to a problem? Please describe.**

It would be fantastic to get automatic completion when writing namespaces like so: 
![image](https://user-images.githubusercontent.com/16068444/107693742-35a8c500-6cb7-11eb-940b-2676c0dcf66c.png)

**Describe the solution you'd like**
As the used starts writing the namespace requirement, an autocomplete should kick in.

**Comment by ericdallo** [comment]
It'd be a great addition, I'll look into this soon :)

**Comment by ericdallo** [comment]
Done! I'll be available on next release :)
