### ISSUE TITLE
Completion of local vars doesn't work on native linux amd64 release

### ISSUE THREAD

**Issue by rvlo** [clojure-lsp/clojure-lsp#315]
**Describe the bug**

Completion of local vars doesn't work on native linux amd64. When running from source, it works fine.

**To Reproduce**
1. (defn foo-function [])
2. Type (foo
3. Press TAB

**User details (please complete the following information):**
 - OS: ArchLinux
 - Editor: emacs
 - Version: 2021.02.11-12.43.06 (but has been happening for a few releases)

<details>
 <summary><b>Log - /tmp/clojure-lsp.out</b></summary>
<pre>
2021-02-11T21:40:07.973Z my-host-name ERROR [clojure-lsp.main:?] -
com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine      PosixJavaThreads.java:  192
            com.oracle.svm.core.thread.JavaThreads.threadStartRoutine           JavaThreads.java:  519
                        java.util.concurrent.ForkJoinWorkerThread.run  ForkJoinWorkerThread.java:  183
                          java.util.concurrent.ForkJoinPool.runWorker          ForkJoinPool.java: 1594
                               java.util.concurrent.ForkJoinPool.scan          ForkJoinPool.java: 1656
             java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec          ForkJoinPool.java: 1020
                             java.util.concurrent.ForkJoinTask.doExec          ForkJoinTask.java:  290
              java.util.concurrent.CompletableFuture$AsyncSupply.exec     CompletableFuture.java: 1692
               java.util.concurrent.CompletableFuture$AsyncSupply.run     CompletableFuture.java: 1700
                    clojure-lsp.main.LSPTextDocumentService/reify/get                   main.clj:  150
                                   clojure-lsp.interop/conform-or-log                interop.clj:  419
                                           clojure.spec.alpha/conform                  alpha.clj:  171
                         clojure.spec.alpha/every-impl/reify/conform*                  alpha.clj: 1300
                      clojure.spec.alpha/and-spec-impl/reify/conform*                  alpha.clj: 1190
                                  clojure.spec.alpha/and-spec-impl/fn                  alpha.clj: 1164
                          clojure.spec.alpha/spec-impl/reify/conform*                  alpha.clj:  930
                                               clojure-lsp.interop/fn                interop.clj:  115
                                                                  ...
                           java.util.stream.ReferencePipeline.collect     ReferencePipeline.java:  578
                           java.util.stream.AbstractPipeline.evaluate      AbstractPipeline.java:  234
               java.util.stream.ReduceOps$ReduceOp.evaluateSequential             ReduceOps.java:  913
                    java.util.stream.AbstractPipeline.wrapAndCopyInto      AbstractPipeline.java:  474
                           java.util.stream.AbstractPipeline.copyInto      AbstractPipeline.java:  484
            java.util.ArrayList$ArrayListSpliterator.forEachRemaining             ArrayList.java: 1655
                        java.util.stream.ReferencePipeline$3$1.accept     ReferencePipeline.java:  195
                                                                  ...
                           java.lang.invoke.Invokers$Holder.invoke_MT             Invokers$Holder
                            java.lang.invoke.MethodHandle.invokeBasic           MethodHandle.java
                            java.lang.invoke.MethodHandle.invokeBasic          MethodHandle.java:   75
                         java.lang.invoke.MethodHandleNatives.resolve   MethodHandleNatives.java:  230
java.lang.NoSuchMethodError: java.lang.reflect.AccessibleObject.canAccess(java.lang.Object)
</pre>
</details>

**Comment by ericdallo** [comment]
Thanks, will take a look soon!

**Comment by ericdallo** [comment]
Should be fixed on next release :)
