### ISSUE TITLE
Navigation to var in local project takes me to .m2

### ISSUE THREAD

**Issue by borkdude** [clojure-lsp/clojure-lsp#318]
In clj-kondo I navigate from the analyzer namespace to hooks/hook-fn. This takes me to my .m2 folder instead of the project-local `clj-kondo/impl/hooks.clj` namespace.

<img width="1428" alt="Screenshot 2021-02-12 at 11 19 48" src="https://user-images.githubusercontent.com/284934/107756576-b2be5380-6d24-11eb-8112-f98be67fd552.png">

**Comment by ericdallo** [comment]
I could not repro that, is that what you are doing?

![clj-kondo-find-hook](https://user-images.githubusercontent.com/7820865/107770316-f65e9080-6d17-11eb-8b53-cae2ce27c89f.gif)

**Comment by borkdude** [comment]
![hook-fn-nav](https://user-images.githubusercontent.com/284934/107770881-3c2c5080-6d3a-11eb-9b9c-85592e95ae0a.gif)

**Comment by ericdallo** [comment]
Could you try a debug command?
With the cursor inside the `hooks/hook-fn` run `lsp-clojure-cursor-info`, it should print the element analysis and its definition from clj-kondo analysis :)

**Comment by borkdude** [comment]
``` 
{:element
 {:name-end-col 39,
  :name-end-row 1357,
  :name-row 1357,
  :name hook-fn,
  :filename
  "/Users/borkdude/Dropbox/dev/clojure/clj-kondo/src/clj_kondo/impl/analyzer.clj",
  :alias hooks,
  :from clj-kondo.impl.analyzer,
  :col 26,
  :name-col 26,
  :from-var analyze-call,
  :arity 5,
  :bucket :var-usages,
  :row 1357,
  :to clj-kondo.impl.hooks},
 :definition
 {:end-row 164,
  :name-end-col 13,
  :name-end-row 137,
  :name-row 137,
  :ns clj-kondo.impl.hooks,
  :name hook-fn,
  :filename
  "/Users/borkdude/.m2/repository/clj-kondo/clj-kondo/2021.01.20/clj-kondo-2021.01.20.jar:clj_kondo/impl/hooks.clj",
  :col 1,
  :name-col 6,
  :end-col 18,
  :bucket :var-definitions,
  :row 137}}
  ```

**Comment by borkdude** [comment]
I'm not sure why clj-kondo ended up as a dependency in the analysis. But even then local sources should probably be prioritized.

**Comment by ericdallo** [comment]
Yeah, I'll double check clojure-lsp to check if it prioritize local sources

**Comment by ericdallo** [comment]
Yeah, clojure-lsp do a find-first of all analysis, I'll refactor introducing some kind of sorting the local sources first

**Comment by ericdallo** [comment]
Should be fixed on next release :)

**Comment by borkdude** [comment]
Thanks!
