### ISSUE TITLE
Create custom homebrew clojure-lsp formula

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#321]
Since homebrew-core doesn't have support for compiling with GraalVM and has some bureaucracy, it'd be great to have a `clojure-lsp/homebrew-brew` repo with clojure-lsp formula downloading from Github Releases

**Comment by ericdallo** [comment]
Willing to take a look @Andre0991?

**Comment by ericdallo** [comment]
After we created the custom homebrew tap, then we could setup https://github.com/garden-io/update-homebrew-action

**Comment by ericdallo** [comment]
Created the repo: https://github.com/clojure-lsp/homebrew-brew/tree/main

**Comment by Andre0991** [comment]
> Willing to take a look @Andre0991?

I will be able to work on this 25/26 feb. If it's okay do wait, I can do it, sure. Otherwise, if someone can take it before me, no problems.
