### ISSUE TITLE
Native Binary 2021.02.13-18.04.19 crashing on Mac OS Big Sur

### ISSUE THREAD

**Issue by javahippie** [clojure-lsp/clojure-lsp#322]
**Describe the bug**
The latest version of now, 2021.02.13-18.04.19, crashes without an error message if I try and start it from the commandline:
`zsh: killed     clojure-lsp`.

This error was not happening before, e.g. version 2021.02.12-03.13.12 runs just fine. 

**To Reproduce**
1. Download the Mac OS specific binary of release 2021.02.13-18.04.19 and unzip
2. Set executable with `chmod u+x clojure-lsp`
3. Execute `./clojure-lsp`
4. See error: zsh: killed     clojure-lsp
5. Exit code, regarding to zsh, is 137

**Expected behavior**
clojure-lsp starting

There are no logs in /tmp/lsp.out or in the operating system logs

**User details (please complete the following information):**
 - OS: MacOS Big Sur, 11.1 20C69 with an Intel Chip, not M1
 - Editor: Not applicable, starting from commandline
 - Version: 2021.02.13-18.04.19

**Additional context**
The issue was already briefly discussed on clojurians-slack in #lsp. It seems like the version works as expected on Mac OS Mojave

**Comment by ericdallo** [comment]
Thank you for the report! 
I'm setupping a macos big sur to test the binary, but probably will rollback the UPX change for macos until https://github.com/upx/upx/issues/450 is fixed :/

**Comment by ericdallo** [comment]
The issue seems to happens indeed only with Big Sur: https://github.com/upx/upx/issues/434

**Comment by ericdallo** [comment]
Also I confirmed testing it on a MacOS Big Sur, I'll rollback the UPX compress only for MacOS until the issue is fixed

**Comment by ericdallo** [comment]
Fixed for now :)

**Comment by javahippie** [comment]
Confirmed that it works fine for me, thank you very much for the fix!
