### ISSUE TITLE
Implement textDocument/signatureHelp

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#324]
This is just a nice to have thing that we currently have in Calva using info from nrepl. See a demo here: https://github.com/BetterThanTomorrow/calva#demo-signature-help-while-typing

**Comment by ericdallo** [comment]
Available on next release @bpringe :) 
![signature-help](https://user-images.githubusercontent.com/7820865/108629674-cca41880-743f-11eb-9f27-0a547d059e09.gif)

But we are not sending the active parameter yet, I think it'd be necessary a clj-kondo analysis change for that.

@borkdude, Would you think it would be possible to add to clj-kondo `var-definition` analysis some `:args` field?
For example `(defn foo [a b & rest])` would have something like  `:args ["a" "b" "& rest"]`.

**Comment by borkdude** [comment]
@ericdallo We already have `:arglist-strs`:

``` 
$ clojure -M:clj-kondo/dev --config '{:output {:analysis {:arglists true} :format :edn}}' --lint - <<< '(defn foo [a b])' | jet --query ':analysis :var-definitions (map :arglist-strs)'
[["[a b]"]]
```

**Comment by borkdude** [comment]
Adding this from a conversation on Slack. If you need the individual args, you can parse it as EDN. This should work for most arglists, except those with auto-resolved keywords. You can work around this using edamame, which already comes with the clj-kondo dependency:

``` clojure
user=> (e/parse-string "{::str/keys [:a]}" {:auto-resolve (fn [ns] (symbol (str ":" ns)))})
#::str{:keys [:a]}
```

**Comment by ericdallo** [comment]
Done @bpringe, we have full support for `textDocument/signatureHelp` now :)
Thanks for the help @borkdude

**Comment by bpringe** [comment]
Awesome! Thanks guys.

**Comment by gdanov** [comment]
this is great, but I can't figure out how to display the signature in pop-up. It does show in the mode line but not in postframe

**Comment by ericdallo** [comment]
you need to use `(setq lsp-signature-posframe 'lsp-signature-posframe)`

**Comment by gdanov** [comment]
this did the job for me

`(setq lsp-signature-function 'lsp-signature-posframe)`

source:

https://twitter.com/yonchovski/status/1362858080430604292

**Comment by ericdallo** [comment]
Oh sorry, yes, that is the correct 😅

**Comment by gdanov** [comment]
no problem ;) just wanted to have it documented for the next one to google it
