### ISSUE TITLE
diplicated symbols in imenu for .cljc files

### ISSUE THREAD

**Issue by gdanov** [clojure-lsp/clojure-lsp#328]
First, congrats on the new release. Start-up is definitelly faster and clj-kondo hooks allow me to support some funky macros.

When working with `.cljc` files the defs shared between the two targets appear twice. That's all. Macros as expected appear only once. See the screenshot:
<img width="1169" alt="Screenshot 2021-02-19 at 15 04 21" src="https://user-images.githubusercontent.com/957113/108514149-cc7f0e00-72c3-11eb-9168-8d64eb2196f2.png">

**Comment by ericdallo** [comment]
Thank you @gdanov !

I don't get the issue here, could you please make a simple repro?
For me the `defn` from a `.cljc` file show correct references:

![image](https://user-images.githubusercontent.com/7820865/108517178-d98d0480-72a5-11eb-934f-022d8082f69c.png)

**Comment by gdanov** [comment]
it's not the references. I'm talking about the lsp <-> imenu integration. Another example from different .cljc file this time using `lsp-ui-menu`
<img width="171" alt="Screenshot 2021-02-19 at 19 03 02" src="https://user-images.githubusercontent.com/957113/108543350-3c51c080-72e5-11eb-8eaa-dadd712fe30a.png">

**Comment by ericdallo** [comment]
Alright, I managed to reproduce that :)
Will take a look, it's a bug indeed!

**Comment by ericdallo** [comment]
Fixed! available on next release :)
