### ISSUE TITLE
Improve `:source-paths` usage for projects with different folders organization

### ISSUE THREAD

**Issue by mynomoto** [clojure-lsp/clojure-lsp#329]
I was trying to use clojure-lsp to explore [an polylith project](https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app) and noticed that navigation weren't working even after configuring a custom command for getting the correct classpath.

It would be nice if once the classpath was configure, navigation (go to definition) worked out of the box. It worked after @ericdallo helped me on slack to configure `:source-paths` on `.lsp/config.edn`.

I wonder why there is a separate config for project files and why it affects navigation since navigation works for library namespaces also. I'm sure there is a reason, I just don't know what it is. I think knowing what files are local is important for not allowing renaming library variables but not sure about navigation.

**Comment by ericdallo** [comment]
Yeah, my idea is that we can improve clojure-lsp to get the source paths from deps.edn if in a deps project, project.clj if a lein project and etc, WDYT @snoe ?

**Comment by ericdallo** [comment]
Maybe we could make something like using the deps.edn source paths if clojure-lsp `:source-paths` not provided

**Comment by ericdallo** [comment]
This was improved and smart handled by clojure-lsp now :) Check the docs for more details, thanks!
