### ISSUE TITLE
Auto re-crawl classpath if clj-kondo config changed

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#331]
If a user change the clj-kondo config used to crawl the classpath, we probably want to re analyze that to make sure we have reliable data.
As @borkdude suggested, we could hash the clj-kondo config passed to kondo/run and persisted in db, and only use the analysis from db if the hash is the same.

**Comment by borkdude** [comment]
https://github.com/clj-kondo/clj-kondo/blob/472d1417b504e2f4e91c7e8ec092436926327ac3/src/clj_kondo/impl/core.clj#L511

**Comment by ericdallo** [comment]
@borkdude I'm considering hash the return of this:
```clojure
(kondo.impl/resolve-config (io/file project-root ".clj-kondo") {})
```
If user change any config on home, project or even if clj-kondo change its default-config, we will re-analyze the project, does that makes sense to you?

BTW, when we call clj-kondo to analyze the whole classpath, does clj-kondo consider the existing cache if any, or does it overwrites?

**Comment by borkdude** [comment]
Looks good to me. Note that impl namespaces are not a public API and may change over time. Clj-kondo always overwrites the cache when linting files.

**Comment by ericdallo** [comment]
@borkdude would you accept a PR exposing the kondo configuration and the kondo hash function?

**Comment by borkdude** [comment]
Let's do it.
