### ISSUE TITLE
global ~/.lsp/config.edn does't work

### ISSUE THREAD

**Issue by lucywang000** [clojure-lsp/clojure-lsp#339]
I tried to turn on `:show-docs-arity-on-same-line? true` globally in `~/.lsp/config.edn` as described in the doc, but it didn't work.

Upon some debugging, I searched around the code but seems the current code only tries to locate the dominate file from the project root.

https://github.com/clojure-lsp/clojure-lsp/blob/2021.02.21-21.02.51/src/clojure_lsp/crawler.clj#L197-L211

**Comment by ericdallo** [comment]
We do a `recur` to search until the `/`, but if user has already a project roo, it'll indeed use the project config not the home one.
We should add support for merging those with the project as the priority

**Comment by lucywang000** [comment]
> We do a recur to search until the /, 

Emm, I don't see how that could navigates to `/home/foo/.lsp/config.edn`? Forgive me if I'm missing anything obvious ...

**Comment by ericdallo** [comment]
No problem :)
That should make that happen: https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/crawler.clj#L208

**Comment by lucywang000** [comment]
I mean, say we are currently in folder `/src/projects/foo`, IIUC it would search for:
- `/src/projects/foo/.lsp/config.edn`
- `/src/projects/.lsp/config.edn`
- `/src/.lsp/config.edn`
- `/.lsp/config.edn`

And would gave up if none of them exists, so `/home/foo/.lsp/config.edn` would never be checked. Am I right?

**Comment by lucywang000** [comment]
Ofc if the source code is always in the home directly, e.g. `~/src/projects/foo`, then it would always be possible to fallback to `~/.lsp/config.edn`. Is that what you mean?

**Comment by ericdallo** [comment]
Exactly, that's what I meant as an improvement :)

**Comment by ericdallo** [comment]
we can choose, always check the home dir, or merging recursive the configs until root

**Comment by lucywang000** [comment]
> we can choose, always check the home dir, or merging recursive the configs until root

The latter won't work if the source code isn't under home dir, so I think home dir always need to be checked.

**Comment by ericdallo** [comment]
Yes, looks easier and valid

**Comment by ericdallo** [comment]
Done on ca354b6, available on next release!
I'll add details to the docs tomorrow
