### ISSUE TITLE
`declare` should not define the location or the docs of a definition

### ISSUE THREAD

**Issue by snoe** [clojure-lsp/clojure-lsp#340]
`go to definition` should not go to the `declare` location
`hover` should show the definition info like doc-strings etc...

**Comment by ericdallo** [comment]
Good catch, need to check how to fix that, probably ignore the declare element when finding definition

**Comment by ericdallo** [comment]
Actually, it seems there is no way to know that an analysis is a `declare` and not the actual definition 😔 
```
{:end-row 63,
  :name-end-col 26,
  :name-end-row 63,
  :name-row 63,
  :ns clojure-lsp.queries,
  :name find-definition,
  :filename "/home/greg/dev/clojure-lsp/src/clojure_lsp/queries.clj",
  :col 1,
  :name-col 1,
  :end-col 26,
  :bucket :var-definitions,
  :row 63}
```
This is a sample of the analysis of `(declare find-defintion)` element.

WDYT @borkdude, should we add a flat to a analysis element if it's a declare one and not the real `var-definition`?

**Comment by borkdude** [comment]
@ericdallo I think the analysis should contain the location of the `def`/`defn` and override the `declare` location.

**Comment by borkdude** [comment]
@ericdallo I oh see, you have multiple locations where it's declared. Yes, adding a field makes sense.

**Comment by dpsutton** [comment]
What work is remaining to do now that the analysis data is rich enough to solve this?

Simple test case: `clojure.data/diff` is forward declared. Go to definition and `lsp-ui-doc-show` both currently use the `(declare diff)` form.

**Comment by ericdallo** [comment]
@dpsutton it needs a change on clj-kondo analysis following [my suggestion](https://github.com/clojure-lsp/clojure-lsp/issues/340#issuecomment-786047277)

**Comment by borkdude** [comment]
Is there a clj-kondo issue for it and why not? And why isn't it simply possible to pick the var with the highest line number within a file?

**Comment by borkdude** [comment]
We could have `:defined-by clojure.core/declare` and `:defined-by clojure.core/defn` I guess?

**Comment by borkdude** [comment]
But even then, if you have a re-definition, you should still pick the one with the highest line number, so you should still add that logic, regardless of the extra field.

**Comment by ericdallo** [comment]
> But even then, if you have a re-definition, you should still pick the one with the highest line number, so you should still add that logic, regardless of the extra field.

Good point, what do you think @snoe?

**Comment by ericdallo** [comment]
@borkdude my bad, I already did the necessary changes on clj-kondo [here](https://github.com/clj-kondo/clj-kondo/pull/1219), I just forgot to fix on clojure-lsp side 😅

**Comment by borkdude** [comment]
@ericdallo Cool! And what about:

```
(def x 1)
(def x 2)
<navigate to definition of x>
```

**Comment by ericdallo** [comment]
This will make `clojure-lsp` return the first found definition using the order returned by clj-kondo, in this case will go to the first `x`.
We could improve in the future to use a custom sort on clojure-lsp side

**Comment by borkdude** [comment]
> to use a custom sort 

why not provide a default one that is probably better in 99% of the cases?

**Comment by ericdallo** [comment]
Yes, the logic would increase a little bit since we already find the first ordered by project/external analysis, but yeah it'd work.

**Comment by borkdude** [comment]
If it's a trade-off between performance and correctness, I would understand just picking the first one would be good enough, since re-definition is rare.
