### ISSUE TITLE
Parsing fails on splicing reader conditional

### ISSUE THREAD

**Issue by jkrasnay** [clojure-lsp/clojure-lsp#346]
**Describe the bug**

The following construct triggers an exception, disabling LSP functionality for the whole file:

```
(def foo
  {:foo :bar
   #?@(:clj
        [:baz :quux])})
```

The problem is likely caused by rewrite-clj v0, and appears to be resolved in rewrite-clj v1.

**To Reproduce**

Enter the above form in a `.cljc` file.

<details>
 <summary><b>Log - /tmp/clojure-lsp.*.out</b></summary>
<pre>
ADD HERE
                    clojure-lsp.main.LSPTextDocumentService/reify/get                   main.clj:  138
                                      clojure-lsp.handlers/completion               handlers.clj:   68
                            clojure-lsp.feature.completion/completion             completion.clj:  242
                            clojure-lsp.refactor.edit/inside-require?                   edit.clj:  148
                                clojure-lsp.refactor.edit/find-ops-up                   edit.clj:   29
                                               clojure.core/contains?                   core.clj: 1494
                                                                  ...
                                                  clojure.core/map/fn                   core.clj: 2759
                                   rewrite-clj.node.protocols/fn/fn/G              protocols.clj:    9 (repeats 2 times)
                                   rewrite-clj.node.seq.SeqNode/sexpr                    seq.clj:   16
                                    rewrite-clj.node.seq/list-node/fn                    seq.clj:   95
                                                   clojure.core/apply                   core.clj:  667
                                                                  ...
                                                  clojure.core/map/fn                   core.clj: 2759
                                   rewrite-clj.node.protocols/fn/fn/G              protocols.clj:    9 (repeats 2 times)
                                   rewrite-clj.node.seq.SeqNode/sexpr                    seq.clj:   16
                                     rewrite-clj.node.seq/map-node/fn                    seq.clj:  110
                                                   clojure.core/apply                   core.clj:  667
                                                                  ...
                                                clojure.core/hash-map                   core.clj:  381
                                                clojure.core/hash-map                   core.clj:  389
                                                                  ...
java.lang.IllegalArgumentException: No value supplied for key: (read-string "#?@(:clj\n        [:baz :quux])")
</pre>
</details>

**User details (please complete the following information):**
 - OS: MacOS
 - Editor Neovim/CoC 0.4.4
 - Version: 2021.02.24-14.23.08

**Comment by ericdallo** [comment]
Thank you for report, let's wait for the v1 merge

**Comment by ericdallo** [comment]
@jkrasnay, I did a fix on clojure-lsp to avoid the exception on code actions when on a reader macro, this should fix this issue but I'm thinking in keep this open until we use rewrite-clj v1, could you test if the latest release fix your issue?

**Comment by jkrasnay** [comment]
Version `2021.03.01-19.18.54` no longer shows the exception in the log. Auto-complete now works but only _below_ the section of the file with the splicing reader conditional, but does not work before that point in the file.

**Comment by ericdallo** [comment]
We'll need rewrite-clj v1 that adds support for parsing cljc

**Comment by ericdallo** [comment]
@jkrasnay could you confirm if this is fixed as we are using rewrite-clj v1 now?

**Comment by jkrasnay** [comment]
Yes, this appears to be fixed. Thanks!
