### ISSUE TITLE
Rename doesn't rename symbols in :refer

### ISSUE THREAD

**Issue by orestis** [clojure-lsp/clojure-lsp#350]
First of all, this project is AMAZING and I'm so happy I've finally tried it :) Many thanks to all!

**Describe the bug**
I tried renaming a function in a very central namespace in our code to test things out. It mostly worked, but in all the requiring namespaces the `:refer` symbol wasn't changed. 
 

**To Reproduce**
So e.g. given:

```
(ns root)
(defn f [])

(ns leaf
 (:require [root :refer [f]))

(f)
```

After renaming `f` to `g` I got:

```
(ns root)
(defn g [])

(ns leaf
 (:require [root :refer [f]))

(g)
```

**Expected behavior**
I would expect: 

```
(ns root)
(defn g [])

(ns leaf
 (:require [root :refer [g]))

(g)
```

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
[ DEBUG ] 2021-03-01T10:59:16+0100 ] ...imView.bundle/Contents/Resources/runtime/lua/vim/lsp.lua:692 ]	"LSP[clojure_lsp]"	"client.request"	1	"textDocument/rename"	{  newName = "db*2",  position = {    character = 7,    line = 11  },  textDocument = {    uri = "file:///Users/orestis/dev/nosco/nosco-gamma/src/nosco/graphql/base.clj"  }}	<function 1>	17
[ DEBUG ] 2021-03-01T10:59:16+0100 ] ...ew.bundle/Contents/Resources/runtime/lua/vim/lsp/rpc.lua:388 ]	"rpc.send.payload"	{  id = 16,  jsonrpc = "2.0",  method = "textDocument/rename",  params = {    newName = "db*2",    position = {      character = 7,      line = 11    },    textDocument = {      uri = "file:///Users/orestis/dev/nosco/nosco-gamma/src/nosco/graphql/base.clj"    }  }}
[ DEBUG ] 2021-03-01T10:59:16+0100 ] ...ew.bundle/Contents/Resources/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  id = 16,  jsonrpc = "2.0",  result = {    changes = {      ["file:///Users/orestis/dev/nosco/nosco-gamma/src/nosco/graphql/base.clj"] = { {          newText = "db*2",          range = {            end = {              character = 9,              line = 11            },            start = {              character = 6,              line = 11            }          }        }, {          newText = "db*2",          range = {            end = {              character = 15,              line = 138            },            start = {              character = 12,              line = 138            }          }        } }    }  }}
[ DEBUG ] 2021-03-01T10:59:16+0100 ] ...ndle/Contents/Resources/runtime/lua/vim/lsp/handlers.lua:338 ]	"default_handler"	"textDocument/rename"	{  bufnr = 17,  client_id = 1,  params = {    changes = {      ["file:///Users/orestis/dev/nosco/nosco-gamma/src/nosco/graphql/base.clj"] = { {          newText = "db*2",          range = {            end = {              character = 9,              line = 11            },            start = {              character = 6,              line = 11            }          }        }, {          newText = "db*2",          range = {            end = {              character = 15,              line = 138            },            start = {              character = 12,              line = 138            }          }        } }    }  }}
[ DEBUG ] 2021-03-01T10:59:16+0100 ] ...imView.bundle/Contents/Resources/runtime/lua/vim/lsp.lua:803 ]	"on_lines bufnr: 17, changedtick: 9, firstline: 11, lastline: 139, new_lastline: 139, old_byte_size: 4086, old_utf32_size: 4086, old_utf16_size: 4086"	 SNIP ... a bunch of lines from the changed buffer here / SNIP }
[ DEBUG ] 2021-03-01T10:59:16+0100 ] ...ew.bundle/Contents/Resources/runtime/lua/vim/lsp/rpc.lua:388 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        text = "SNIP ... the whole changed file is here... /SNIP"      } },    textDocument = {      uri = "file:///Users/orestis/dev/nosco/nosco-gamma/src/nosco/graphql/base.clj",      version = 9    }  }}
[ DEBUG ] 2021-03-01T10:59:16+0100 ] ...ew.bundle/Contents/Resources/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///Users/orestis/dev/nosco/nosco-gamma/src/nosco/graphql/base.clj"  }}
[ DEBUG ] 2021-03-01T10:59:16+0100 ] ...imView.bundle/Contents/Resources/runtime/lua/vim/lsp.lua:487 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///Users/orestis/dev/nosco/nosco-gamma/src/nosco/graphql/base.clj"}
[ DEBUG ] 2021-03-01T10:59:16+0100 ] ...ndle/Contents/Resources/runtime/lua/vim/lsp/handlers.lua:338 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///Users/orestis/dev/nosco/nosco-gamma/src/nosco/graphql/base.clj"  }}

</pre>
</details>

<details>
 <summary><b>Log - /tmp/clojure-lsp.*.out</b></summary>
<pre>
</pre>
</details>

**User details (please complete the following information):**
 - OS: macOS
 - Editor NeoVim 
 - Version: `clojure-lsp 2021.02.24-14.23.08`

**Comment by ericdallo** [comment]
Thanks for the report!
that refer analysis was added to master yesterday, still need to add support for it in rename, will try to look to this soon :)

**Comment by ericdallo** [comment]
I confirmed the last clj-kondo bump fixed this, I'll release soon so you can test it
