### ISSUE TITLE
False positive: Unresolved symbol inside a macro invocation

### ISSUE THREAD

**Issue by LoadingBG** [clojure-lsp/clojure-lsp#356]
Problem: I created a macro which expects a symbol to be passed as an argument. I get `Unresolved symbol` for argument which should be unevaluated.

Expected behavior: No error to be reported.

Environment:
 - OS: Ubuntu 20.04 under WSL
 - Editor Neovim v0.4.3
 - Version: 2021.03.01-19.18.54

**Comment by ericdallo** [comment]
Please add a repro, otherwise, there is no way we know what macro is and what is the issue.

Also, this should be a clj-kondo issue since we delegate all lint logic to it.

**Comment by LoadingBG** [comment]
Here's the macro I'm talking about
```clj
(defmacro defendpoint
  [fn-name doc-str endpoint & args]
  (let [arg-syms (take-nth 2 args)]
    `(do
       (defn ~fn-name
         [~@arg-syms]
         (binding [http/*default-client* http-sni/default-client]
           (json->map (:body @(http/get (format ~endpoint ~@arg-syms))))))
       (s/fdef ~fn-name
         :args (s/cat ~@(interleave (map keyword arg-syms) (repeat string?)))
         :ret  map?
         :fn   #(number? (:args %))))))

(defendpoint get-player-profile!
  "docstr"
  "example"
  username)
```
I get errors on `get-player-profile!` and `username`:
![image](https://user-images.githubusercontent.com/51295058/110011400-10442f80-7d28-11eb-94db-9486f4d20eba.png)

**Comment by ericdallo** [comment]
Please check the [troubleshooting section](https://clojure-lsp.github.io/clojure-lsp/settings/#diagnostics-linter) and [clj-kondo config documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#unrecognized-macros) on how to lint macros
