### ISSUE TITLE
Autocomplete for require and refer

### ISSUE THREAD

**Issue by davidpham87** [clojure-lsp/clojure-lsp#364]
Following our conversation on slack, I am opening this issue to have autocomplete on `ns` statements.

When we refer to `vars` in `ns` statements, it would be helpful to have some autocomplete support.

For example, in the following snippet,

```clojure
(ns user
  (:require [clojure.string :refer (upp_)])) ;; cursor on the _
```
it would be helpful if clojure-lsp could suggest `upper-case` (or any other matching public `vars`).

Best regards
David

**Comment by ericdallo** [comment]
Thank you for the report!

It turns out [that was implemented in December](https://github.com/clojure-lsp/clojure-lsp/pull/202) by @anonimitoraf but before the clj-kondo integration, so we lose that feature 🤦🏻‍♂️ 

I'll try to take a look on weekend :)

**Comment by ericdallo** [comment]
Fixed on next release :)
