### ISSUE TITLE
How does clojure-lsp handle project classpath changes?

### ISSUE THREAD

**Issue by didibus** [clojure-lsp/clojure-lsp#365]
This is more of a question.

I'm curious how clojure-lsp handles classpath changes. I see that you can pass it `source-paths` and `project-specs` which would contain `project-path` and `classpath-cmd`. But what happens if someone say adds things to the `deps.edn` after the server is started? Does it watch the `project-path` and `source-paths` for changes and re-runs the `classpath-cmd` on change?

If the above is correct, one more question I have is, what if the classpath could change based on other factor than the `project-path` and `source-paths` being modified? Is there a way to update a running clojure-lsp server to tell it to re-run the `classpath-cmd` explicitly?

Regards

**Comment by ericdallo** [comment]
Hey, you are almost correct, clojure-lsp only check for deps changes, when it starts, it compares the md5 of your deps file with the persisted on .lsp/sqlite if present, if is not the same, it scans the whole classpath again.
For source paths, it always will scan your project folders, and this usually is really fast.

Therefore, clojure-lsp only check for changes when the server starts and will only re-scan if you restart the server or your editor.

We could add some command to re-scan, but I'm not sure this would help a lot, restart the server is quite the same.

**Comment by didibus** [comment]
I see, so adding or removing dependencies require a lsp server restart to pick up the changes?

But adding/removing files in source-paths will not require a lsp server restart, as Clojure-lsp has watches on them?

**Comment by ericdallo** [comment]
yes, when you open a file, lsp client should send the didOpen notification, so server can know that file exists
