### ISSUE TITLE
Clojure-lsp sorts imports in a strange way

### ISSUE THREAD

**Issue by dpsutton** [clojure-lsp/clojure-lsp#380]
Clojure lsp seemingly sorts imports considering any brackets, not just the alphabetic characters. The observed behavior in an ns form is that the following (in my opinion correctly sorted imports)

### Existing (imo correctly sorted ns form)
```clojure
  (:import java.net.ServerSocket
           java.util.concurrent.TimeoutException
           java.util.Locale
           [org.quartz CronTrigger JobDetail JobKey Scheduler Trigger])
```

will be sorted to the following:

### After lsp sorting
```clojure
  (:import [org.quartz CronTrigger JobDetail JobKey Scheduler Trigger]
           java.net.ServerSocket
           java.util.Locale
           java.util.concurrent.TimeoutException)
```

Now the import starting with an `o` is above the `j`. If there were another import from `org.quartz` it might be separated from the other imports from that package.

This seems to not be reported as an error from clj-kondo so I believe it is solely clojure-lsp's behavior and i suspect it is just a simple bug of comparing the names of the imports forgetting to ignore any brackets or parens.

### Failing test case

test case for `clojure-lsp.refactor.transform-test/clean-ns-test`
```clojure
(testing "sorts according to symbols not brackets"
    (test-clean-ns {}
                   (code "(ns foo.bar"
                         " (:import"
                         "  [zebra import1]"
                         "  apple))"
                         "import1."
                         "apple.")
                   (code "(ns foo.bar"
                         " (:import"
                         "  apple"
                         "  [zebra import1]))"
                         "import1."
                         "apple.")))
```

**Comment by ericdallo** [comment]
Thanks for the report!
I think you first example is missing the expected wrong behavior?

**Comment by dpsutton** [comment]
@ericdallo yeah just updated. sorry about that.

**Comment by ericdallo** [comment]
Fixed :) I should release it later today
