### ISSUE TITLE
Config seems to have no effect

### ISSUE THREAD

**Issue by alxdb** [clojure-lsp/clojure-lsp#389]
**Describe the bug**
I'm trying to disable the `unused-public-var` linter, and as far as I can tell, the correct way to do this is to create a file in my project root called `.lsp/config.edn` with these contents: `{:linters {:unused-public-var {:level :off}}}`.

However this seems to have no effect, and the errors are shown all the same. In fact I can't seem to make any kind of configuration work, including disabling `clj-kondo` with `{:linters {:clj-kondo {:level :off}}}`.

**To Reproduce**
`src/foobar.clj`
```clojure
(ns foobar)

(def foo 0)
```
`.lsp/config.edn`
```clojure
{:linters {:unused-public-var {:level :off}}}
```

**Expected behavior**
No errors are reported

<details>
<summary><b>contents of *lsp-log*</b></summary>
<pre>
Found the following clients for /home/alxdb/clojure-lsp-bug/src/foobar.clj: (server-id clojure-lsp, priority 0)
The following clients were selected based on priority: (server-id clojure-lsp, priority 0)
Creating watch for /home/alxdb/clojure-lsp-bug
Creating watch for /home/alxdb/clojure-lsp-bug/src
</pre>
</details>

<details>
 <summary><b>Log - /tmp/lsp.out</b></summary>
<pre>
INFO  clojure-lsp.main: Starting server...
INFO  clojure-lsp.main: ====== LSP nrepl server started on port 35697
WARN  clojure-lsp.main: Initialize
INFO  clojure-lsp.crawler: skipping classpath scan due to project hash match
DEBUG clojure-lsp.main: :initialize 667 ()
WARN  clojure-lsp.main: Initialized #object[org.eclipse.lsp4j.InitializedParams 0x393304ea InitializedParams [
]]
</pre>
</details>

**User details (please complete the following information):**
 - OS: NixOS
 - Editor: Emacs (doom)
 - Version: clojure-lsp release-20200828T065654

**Additional context**

Unfortunately, I don't seem to be able to get trace logs from the lsp in emacs, I've enabled `lsp-server-trace` but I don't see the output anywhere. I can only see the contents of the `*lsp-log*` emacs buffer being filled.

I don't appear to have a `/tmp/clojure-lsp.*.out` file, but I do have a `/tmp/lsp.out` the output of which I have provided

**Comment by ericdallo** [comment]
Hello from another nix and doom user :)
It seems you have super outdated clojure-lsp 😅 How did you installed it?
I suggest installing via the nixpkgs unstable channel https://clojure-lsp.github.io/clojure-lsp/installation/#nix

**Comment by alxdb** [comment]
Ah okay, I installed via the stable channel, I'll try the unstable channel

**Comment by alxdb** [comment]
Yup that seems to have fixed it, although maybe the version on stable could be updated?

**Comment by ericdallo** [comment]
Not really, that's the way nix works, the stable has specific versions that are updated each 6 months, if you want a more updated version you want to use the unstable.
Glad it worked!
