### ISSUE TITLE
report duplicates diagnostics.

### ISSUE THREAD

**Issue by snoe** [clojure-lsp/clojure-lsp#390]
**Is your feature request related to a problem? Please describe.**
We want to show all occurrences of problems, not just the first. Maybe we keep the old way behind a flag but I think our default should be to show all.

**Describe the solution you'd like**
kondo now has the ability to report-duplicates for linters
https://github.com/clj-kondo/clj-kondo/pull/1233
We should set `:report-duplicates true` as part of our kondo config.

**Comment by ericdallo** [comment]
Oh, I was waiting for that feature, nice :)
I'll add a flag with default true

**Comment by snoe** [comment]
@ericdallo we should add it in our code and let them turn it off if they desire.

**Comment by ericdallo** [comment]
Ok, We can add a clojure-lsp flag for that so.
I'll check that after solving the integration tests broken on clj-kondo bump: https://github.com/clojure-lsp/clojure-lsp/pull/391

**Comment by ericdallo** [comment]
Fixed, LMK if any issue
