### ISSUE TITLE
Falsely reporting unused public var

### ISSUE THREAD

**Issue by vindkaldr** [clojure-lsp/clojure-lsp#394]
**Describe the bug**
Used public var is reported as unused when used in escaped collection literals.

**To Reproduce**
1. Write an arbitrary function
2. Refer to it in a collection literal
3. Escape the collection literal

**Expected behavior**
It is recognized as used public var, even within an escaped collection literal.

**Screenshots**
![issue](https://user-images.githubusercontent.com/18601269/113517312-6f8f9c80-957f-11eb-9932-cad16fc0b63a.png)

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
[Trace - 7:32:58 PM] Sending request 'initialize - (0)'.
Params: {
    "processId": 44159,
    "clientInfo": {
        "name": "vscode",
        "version": "1.54.3"
    },
    "rootPath": "/tmp/test",
    "rootUri": "file:///tmp/test",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true,
                "versionSupport": false,
                "tagSupport": {
                    "valueSet": [
                        1,
                        2
                    ]
                }
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true,
                    "tagSupport": {
                        "valueSet": [
                            1
                        ]
                    }
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    }
                },
                "contextSupport": true
            },
            "definition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true
            },
            "codeAction": {
                "dynamicRegistration": true,
                "isPreferredSupport": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
            "documentLink": {
                "dynamicRegistration": true,
                "tooltipSupport": true
            },
            "typeDefinition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "implementation": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            },
            "declaration": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "selectionRange": {
                "dynamicRegistration": true
            }
        },
        "window": {
            "workDoneProgress": true
        }
    },
    "initializationOptions": {
        "dependency-scheme": "jar",
        "auto-add-ns-to-new-files?": true,
        "document-formatting?": false,
        "document-range-formatting?": false,
        "keep-require-at-start?": true
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///tmp/test",
            "name": "test"
        }
    ]
}

[Trace - 7:32:59 PM] Received response 'initialize - (0)' in 1045ms.
Result: {
    "capabilities": {
        "textDocumentSync": {
            "openClose": true,
            "change": 1,
            "save": {
                "includeText": true
            }
        },
        "hoverProvider": true,
        "completionProvider": {
            "resolveProvider": true,
            "triggerCharacters": []
        },
        "signatureHelpProvider": {
            "triggerCharacters": []
        },
        "definitionProvider": true,
        "referencesProvider": true,
        "documentHighlightProvider": true,
        "documentSymbolProvider": true,
        "workspaceSymbolProvider": true,
        "codeActionProvider": {
            "codeActionKinds": [
                "quickfix",
                "refactor",
                "refactor.extract",
                "refactor.inline",
                "refactor.rewrite",
                "source",
                "source.organizeImports"
            ],
            "resolveProvider": true
        },
        "codeLensProvider": {
            "resolveProvider": true
        },
        "documentFormattingProvider": false,
        "documentRangeFormattingProvider": false,
        "renameProvider": true,
        "executeCommandProvider": {
            "commands": [
                "add-missing-libspec",
                "add-import-to-namespace",
                "cycle-privacy",
                "change-coll",
                "thread-last-all",
                "unwind-all",
                "move-to-let",
                "clean-ns",
                "thread-last",
                "introduce-let",
                "unwind-thread",
                "thread-first-all",
                "thread-first",
                "inline-symbol",
                "extract-function",
                "cycle-coll",
                "expand-let",
                "create-function"
            ]
        },
        "callHierarchyProvider": true,
        "semanticTokensProvider": {
            "legend": {
                "tokenTypes": [
                    "type",
                    "function",
                    "macro"
                ],
                "tokenModifiers": []
            },
            "range": true,
            "full": true
        }
    }
}

[Trace - 7:32:59 PM] Sending notification 'initialized'.
Params: {}

[Trace - 7:32:59 PM] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "clojure-lsp": {}
    }
}

[Trace - 7:32:59 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///tmp/test/src/test/core.clj",
        "languageId": "clojure",
        "version": 1,
        "text": "(ns test.core)\n\n(defn f [])\n\n;; [f]\n'[f]\n"
    }
}

[Trace - 7:32:59 PM] Received request 'client/registerCapability - (1)'.
Params: {
    "registrations": [
        {
            "id": "id",
            "method": "workspace/didChangeWatchedFiles",
            "registerOptions": {
                "watchers": [
                    {
                        "globPattern": "**"
                    }
                ]
            }
        }
    ]
}

[Trace - 7:32:59 PM] Sending response 'client/registerCapability - (1)'. Processing request took 1ms
No result returned.

[Trace - 7:32:59 PM] Sending request 'textDocument/codeAction - (1)'.
Params: {
    "textDocument": {
        "uri": "file:///tmp/test/src/test/core.clj"
    },
    "range": {
        "start": {
            "line": 5,
            "character": 4
        },
        "end": {
            "line": 5,
            "character": 4
        }
    },
    "context": {
        "diagnostics": []
    }
}

[Trace - 7:32:59 PM] Received response 'textDocument/codeAction - (1)' in 14ms.
Result: [
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "command": {
            "title": "Clean namespace",
            "command": "clean-ns",
            "arguments": [
                "file:///tmp/test/src/test/core.clj",
                5,
                4
            ]
        }
    }
]

[Trace - 7:32:59 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///tmp/test/src/test/core.clj",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 2,
                    "character": 6
                },
                "end": {
                    "line": 2,
                    "character": 7
                }
            },
            "severity": 3,
            "code": "unused-public-var",
            "source": "clojure-lsp",
            "message": "Unused public var 'test.core/f'",
            "tags": [
                1
            ]
        }
    ]
}

[Trace - 7:32:59 PM] Sending request 'textDocument/codeAction - (2)'.
Params: {
    "textDocument": {
        "uri": "file:///tmp/test/src/test/core.clj"
    },
    "range": {
        "start": {
            "line": 5,
            "character": 4
        },
        "end": {
            "line": 5,
            "character": 4
        }
    },
    "context": {
        "diagnostics": []
    }
}

[Trace - 7:32:59 PM] Received response 'textDocument/codeAction - (2)' in 2ms.
Result: [
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "command": {
            "title": "Clean namespace",
            "command": "clean-ns",
            "arguments": [
                "file:///tmp/test/src/test/core.clj",
                5,
                4
            ]
        }
    }
]

[Trace - 7:33:00 PM] Sending request 'textDocument/codeAction - (3)'.
Params: {
    "textDocument": {
        "uri": "file:///tmp/test/src/test/core.clj"
    },
    "range": {
        "start": {
            "line": 5,
            "character": 4
        },
        "end": {
            "line": 5,
            "character": 4
        }
    },
    "context": {
        "diagnostics": []
    }
}

[Trace - 7:33:00 PM] Received response 'textDocument/codeAction - (3)' in 3ms.
Result: [
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "command": {
            "title": "Clean namespace",
            "command": "clean-ns",
            "arguments": [
                "file:///tmp/test/src/test/core.clj",
                5,
                4
            ]
        }
    }
]
</pre>
</details>

<details>
 <summary><b>Log - /tmp/clojure-lsp.*.out</b></summary>
<pre>
2021-04-04T17:32:58.965Z hostname INFO [clojure-lsp.main:391] - Starting server...
2021-04-04T17:32:58.969Z hostname DEBUG [clojure-lsp.nrepl:24] - nrepl not found, skipping nrepl server start...
2021-04-04T17:32:58.978Z hostname INFO [clojure-lsp.main:293] - Initializing...
2021-04-04T17:32:59.623Z hostname INFO [clojure-lsp.crawler:162] - Paths analyzed, took 0.00482389 secs. Caching for next startups...
2021-04-04T17:32:59.623Z hostname DEBUG [clojure-lsp.main:?] - :initialize 645ms
2021-04-04T17:32:59.628Z hostname INFO [clojure-lsp.main:339] - Initialized!
2021-04-04T17:32:59.629Z hostname DEBUG [clojure-lsp.main:?] - :initialized 0ms
2021-04-04T17:32:59.629Z hostname WARN [clojure-lsp.main:238] - {}
2021-04-04T17:32:59.636Z hostname DEBUG [clojure-lsp.main:?] - :didOpen 4ms
2021-04-04T17:32:59.654Z hostname DEBUG [clojure-lsp.main:?] - :codeAction 9ms
2021-04-04T17:32:59.998Z hostname DEBUG [clojure-lsp.main:?] - :codeAction 1ms
2021-04-04T17:33:00.511Z hostname DEBUG [clojure-lsp.main:?] - :codeAction 1ms
</pre>
</details>

**User details (please complete the following information):**
 - OS: Arch Linux
 - Editor: Visual Studio Code - Open Source (Calva)
 - Version: 2021.03.30-20.42.34

**Additional context**
This issue contains only a simplified example. At first I reported it in the Calva repository: https://github.com/BetterThanTomorrow/calva/issues/1102 with an example closer the the real use case.
Another important note is that `clj-kondo` also falsely reports this for private vars. You can find details about this in the previously mentioned issue. In my opinion, that is too an issue. I'm interested if you also agree. If yes, I'll submit an issue there as well.

Thank you in advance!

**Comment by ericdallo** [comment]
Thanks for the report!
I understand the issue here, I just not sure if we should handle those cases as a quoted form is evaluated at runtime so there is no simple way to know if the f in a quoted form is from a function or just a quoted symbol.
Any suggestions here @snoe @borkdude?

We could have a way to suppress that linter via code just like clj-kondo has a custom way of suppressing that.
Meanwhile you can use the `:exclude` from the linter config for now

**Comment by borkdude** [comment]
``` clojure
(defn foo [])
'foo ;; <- this isn't using the foo var, it's just a random symbol unrelated to the function
```

**Comment by ericdallo** [comment]
yeah, for this case yes, but for the datomic case on the Calva issue, it's using the function, right?

**Comment by borkdude** [comment]
@ericdallo Maybe, I don't know what Datomic does in this case, but like with any external system or even macro, it's not possible to know this using static analysis.

**Comment by vindkaldr** [comment]
Thank you for your input!
I read up on symbols and how they are evaluated and I'd like to make an argument against myself.

As it was pointed out, the symbol in itself is not bound to anything and what they refer to is only established during evaluation. At this point, it seems like a job for a plugin of the framework and not the general programming language.

A similar case would be is how in `shadow-cljs` you define an `init-fn`, that is a namespace-qualified symbol, in the `shadow-cljs.edn` config, which will be invoked by the framework. Having just the Calva plugin, it was not surprising that it was reported as an unused function. It would be the framework's plugin's job to influence linting (?), in a way that makes sense in the context of the framework.

With this I'm thinking in just closing the issue. I'm interested of you have additional input.

**Comment by vindkaldr** [comment]
Thank you for your help! I'm closing the issue as it was based on an unfounded expectation.
