### ISSUE TITLE
code formatting stops certain paredit actions

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-lsp/clojure-lsp#399]
**Describe the bug**

`paredit-forward-slurp-sexp` not working properly when clojure-lsp is enabled on a clojure buffer. it works for the following scenario:
`(foo|) bar` -> `(foo bar)`
but it fails for
`(foo|) (bar)`
nothing happens

for the first, working scenario in the *Messages* buffer I can see
`LSP :: No formatting changes provided`

for the second, failing scenario in the *Messages* buffer:
```
LSP :: Applying 1 edits to `shell.clj' ...
Applying 1 edits to `shell.clj' ...done
```

killing the clojure-lsp server manually fixes the problem, also setting `(setq lsp-enable-indentation nil)` seems to be a workaround

have not tested other paredit actions but others may be affected as well.

**User details (please complete the following information):**
 - OS: MacOS
 - Editor emacs 27.1
 - Version: (post the result of `clojure-lsp --version`)

```
clojure-lsp 2021.03.30-20.42.34
clj-kondo 2021.03.22-SNAPSHOT
```

let me know if you need more info to reproduce, thanks for the amazing clojure-lsp!

**Comment by ericdallo** [comment]
Yeah, I'm having the same issue recently, not sure it's a lsp-mode or clojure-lsp issue yet,
Could you test if it happens in older clojure-lsp versions?

**Comment by benedekfazekas** [comment]
how older should i downgrade to?

**Comment by benedekfazekas** [comment]
my lsp mode is `lsp-mode-20210407.736` just upgraded packages

**Comment by ericdallo** [comment]
Maybe test 2 or 3 clojure-lsp previous releases, this helps finding the release that introduced the bug

**Comment by benedekfazekas** [comment]
will try, i will get back to you if I find a working version

**Comment by ericdallo** [comment]
I'm trying to repro right now and don't get the issue anymore... It seems to be some kind of corner case.
Also, I think this is related to #127

**Comment by ericdallo** [comment]
I confirmed the issue started happens on https://github.com/clojure-lsp/clojure-lsp/releases/tag/2021.03.26-23.41.07, not sure why yet

**Comment by ericdallo** [comment]
I confirmed the bug was introduced with [this `refactoring-async` merge](https://github.com/clojure-lsp/clojure-lsp/commit/b0d872357f3bb3681f2a324e2734a672928775c8), git reverting this commit fix the issue, @snoe could you help identify the issue on that merge please?

**Comment by ericdallo** [comment]
@snoe on this branch I created reverting the commit on master, it works: https://github.com/clojure-lsp/clojure-lsp/pull/401
We can merge it and work on the async again or work on a fix from master

**Comment by ericdallo** [comment]
@benedekfazekas could you test if latest release fixed the issue please?

**Comment by benedekfazekas** [comment]
LGTM, thanks for the quick fix and release
