### ISSUE TITLE
Make :source-path dependent features work for polylith (and similar?) projects

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#416]
**Is your feature request related to a problem? Please describe.**
I noticed that namespace auto creation does not work with the polylith project structure. 

**Describe the solution you'd like**
When I create a new file in a source directory in a polylith project, I'd like the namespace to be created.

**Additional context**
If you clone the [polylith](https://github.com/polyfy/polylith) repo and create a `hello.clj` file in `polylith/components/api/src/polylith/clj/core/api/`, you will notice the auto namespace creation does not happen.

I'm guessing this has something to do with clojure-lsp going off of the `:paths` of the deps.edn, but maybe even that does not occur? I see a similar discussion in https://github.com/clojure-lsp/clojure-lsp/issues/329. 

Anyway, polylith projects have paths defined in aliases. Maybe these could be used? Not sure if there is an easy solution though. (Just a side note, I noticed Go to Definition does work.)

**Comment by bpringe** [comment]
> polylith projects have paths defined in aliases

I mean like here: https://github.com/polyfy/polylith/blob/76936c752fb5b729c216b23d92c8a8d71cfdc92f/deps.edn#L20

**Comment by ericdallo** [comment]
Unfortunately, this is related to #280 as polylith acts like mono-repo or multi-compoents project, so multiple features probably will not work since clojure-lsp will not scan correctly the classpath (as it checks only for deps.edn in the root)

**Comment by seancorfield** [comment]
@ericdallo Perhaps add an LSP config that provides one or more aliases that should be used when computing the classpath from the root `deps.edn` file? Polylith uses `:dev` and `:test` as development-time aliases that include "all code" and at work in our monorepo we have an `:everything` alias that brings in all source and test code.

**Comment by ericdallo** [comment]
@seancorfield I'd like to add support for polylith on clojure-lsp, I'm just not sure the best way to handle it.

ATM clojure-lsp only check for `:source-paths` config if provided by user, if not found it uses a default value of `#{"src" "test"}`. I know this doesn't work for polylith, your idea is to clojure-lsp read the deps.edn file from the configured project root (in this case the mono-repo root?) and check for some common aliases?

Is there any polylith pattern of source paths which could help us on this or those aliases are only users common pattern?

**Comment by seancorfield** [comment]
When you mentioned `deps.edn`, I assumed LSP was reading it with `tools.deps.alpha` and processing `:paths` etc?

Polylith's workspace-level `deps.edn` file **always** contains `:dev` and `:test` aliases and those **always** contain `:extra-paths` which have all the `src` folders (and `resources`) and all the `test` folders respectively, so you can rely on that structure.

In the general case, you would need a list of aliases and then use t.d.a. to process the `deps.edn` file to compute the project basis -- and you can get the classpath from that -- and then you can get all the source/test folders from that (and filter them down to just ones relative to the project root).

You can see how `depstar` does this: https://github.com/seancorfield/depstar/blob/develop/src/hf/depstar/uberjar.clj#L314-L337

**Comment by ericdallo** [comment]
I see, ATM clojure-lsp doesn't read anything on deps.edn but we already use rewrite-edn from @borkdude so I think this could be easily handled.

If we follow your suggestion of folders that always exists on a polylith project and this is enough for building the project classpath, that could work :)

One more question: polylith only works with deps.edn? No lein or other tool is supported to handle classpaths, right?

**Comment by seancorfield** [comment]
If you just want to support it via filesystem structure then you can do it. There are always three top-level folders: `bases`, `components`, and `projects`. Each contains a "subproject" folder. Each of those may contain `src` and `test` (and `resources` but you don't care about that. There may also be `development/src` and/or `development/test` (for dev/test-only code).

Here's what's currently in our repo (we're converting our monorepo to Polylith slowly):
```shell
bases/artifact-uploader-cli/src
bases/artifact-uploader-cli/test
bases/google-search-cli/src
bases/google-search-cli/test
components/artifact-uploader/src
components/artifact-uploader/test
components/caching/src
components/caching/test
components/configuration/src
components/configuration/test
components/crud-form/src
components/crud-form/test
components/datasources/src
components/datasources/test
components/date-time/src
components/date-time/test
components/environment/src
components/environment/test
components/exceptions/src
components/exceptions/test
components/file-system/src
components/file-system/test
components/google-search-console/src
components/google-search-console/test
components/host-services/src
components/host-services/test
components/http-client-response/src
components/http-client-response/test
components/member-engagement/src
components/member-engagement/test
components/safe-coercions/src
components/safe-coercions/test
components/seo-keyword/src
components/seo-keyword/test
components/site/src
components/site/test
components/system-properties/src
components/system-properties/test
development/src
```
(we currently have no project-specific `src` or `test` code)

The original version of Polylith was Leiningen-based but the current version is `deps.edn`-based. The `issue-66` branch is changing a few things about how it is done -- to better match how the CLI/`deps.edn` is evolving -- and will become the "standard" Polylith setup soon -- but the overall structure of `bases`, `components`, `projects`, and `development` is not really changing, at least in terms of "subprojects" containing `src` and `test` folders.

**Comment by ericdallo** [comment]
Great, thanks for the time spent on this!

Alright, so we could scan and get those folder hierarchy and add to classpath, the only missing part now is know if the project is or not a polylith project. We could check deps.edn I think for the polylith deps, do you recommend any other (better?) way to get that?

**Comment by seancorfield** [comment]
If it has `bases` and `components` as top-level folders, it's very likely to be a Polylith workspace :)

While the generated `deps.edn` file has a `:poly` alias, it's common for folks working with Polylith to use the `poly` shell script instead so I don't think you can guarantee the `:poly` alias would be present.

**Comment by ericdallo** [comment]
Nice, thanks for the info, I'll take a look at this soon and try to make it work :)
I'll generate some sample project with polylith but let me know if you have another project where I can test it as well

**Comment by seancorfield** [comment]
The `poly` tool creates a completely employ workspace, and then you need to create components etc as needed.

If you use `clj-new` to create a new Polylith workspace, it will have `bases`, `components`, and `projects`:
```shell
seanc@DESKTOP-30ICA76:~/clojure$ clojure -X:new :template polylith :name eric/poly
Generating a project called poly based on the 'polylith' template.
Initialized the project for use with 'git'.
seanc@DESKTOP-30ICA76:~/clojure$ tree poly/
poly/
├── CHANGELOG.md
├── LICENSE
├── README.md
├── bases
│   └── cli
│       ├── deps.edn
│       ├── resources
│       ├── src
│       │   └── eric
│       │       └── poly
│       │           └── cli
│       │               └── main.clj
│       └── test
│           └── eric
│               └── poly
│                   └── cli
│                       └── main_test.clj
├── components
│   └── greeter
│       ├── deps.edn
│       ├── resources
│       ├── src
│       │   └── eric
│       │       └── poly
│       │           └── greeter
│       │               ├── core.clj
│       │               └── interface.clj
│       └── test
│           └── eric
│               └── poly
│                   └── greeter
│                       └── interface_test.clj
...
```
The other example to look at is https://github.com/seancorfield/usermanager-example/tree/polylith (the `polylith` branch is a refactoring of the original app to the Polylith architecture).

**Comment by ericdallo** [comment]
@seancorfield I was taking a look at polylith docs and setting up the sample project and I noticed that it seems IntelliJ just checks the aliases like `dev`/`test` ([ref](https://github.com/polyfy/polylith#development)). Maybe we could try to make something more generic to clojure-lsp where it reads the deps.edn like IntelliJ and consider the extra-paths for some default aliases (user could configure which ones like IntelliJ does).

**Comment by seancorfield** [comment]
That's what I was suggesting several comments ago so... yeah... reading `deps.edn` and selecting `:extra-paths` based on a configurable set of aliases in the LSP config would be great.

**Comment by ericdallo** [comment]
Yeah, sorry for didn't understand that at the time, I didn't know IntelliJ was doing that and only after I saw the example that it makes sense to me 😅, looks like a valid idea indeed, I'll check it closer

**Comment by ericdallo** [comment]
@bpringe @seancorfield I made a PR improving support for `deps.edn` projects [here](https://github.com/clojure-lsp/clojure-lsp/pull/445), 

I tested on my [polylith-sample](https://github.com/ericdallo/polylith-sample) and the [suggested project](https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app) by @seancorfield and it worked great :)
The necessary documentation is on the branch as well

it'd be great if you could test it with polylith projects or even other complex deps.edn projects which could work well now with that branch. you can release a dev clojure-lsp bin running `make` on that branch.

**Comment by seancorfield** [comment]
Thanks, @ericdallo I've no idea how to test a PR against LSP -- I don't know enough about how it integrates into stuff like Calva -- but I appreciate the work, and I'm pleased to see more `deps.edn` support that actually uses the aliases!

**Comment by ericdallo** [comment]
No problem :)
 I'll make more many tests on other mono-repo deps.edn projects and check if it's working good, LMK if you have non polylith mono-repo examples like that

**Comment by bpringe** [comment]
@ericdallo Awesome! What features should I be testing with that PR?

@seancorfield Just FYI, if you want to test something like this in the future, after making the clojure-lsp binary from the branch you're testing, you can tell Calva to use that binary as mentioned here: https://calva.io/clojure-lsp/#using-a-custom-clojure-lsp-native-binary.

**Comment by ericdallo** [comment]
@bpringe features that depends on the source-paths, testing renaming and correct ns form creation would be enough I think

**Comment by bpringe** [comment]
Works well! Thanks for the work on this!

**Comment by borkdude** [comment]
@ericdallo Side-note: I recently came across a project that _only_ had a `shadow-cljs.edn` file with `:deps` in it, without a `deps.edn` in the project. I think that might also make sense to fall back on when no `deps.edn` or `project.clj` can be found.

**Comment by ericdallo** [comment]
@borkdude clojure-lsl already has a project-spec for shadow-cljs.edn [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/crawler.clj#L63), so the classpath scan works for those projects, what we are solving here are the source-paths. I imagine shadow-cljs.edn can have different source-paths as well, so in the future we can check for those as well

**Comment by borkdude** [comment]
@ericdallo cool! thanks

**Comment by tengstrand** [comment]
Thanks for this!
