### ISSUE TITLE
High memory and CPU usage (on large files)

### ISSUE THREAD

**Issue by wcerfgba** [clojure-lsp/clojure-lsp#423]
I notice consistently high memory usage by clojure-lsp when I am using VSCode with Calva. Once I have a few files open memory usage rises from ~250MiB at start to ~750MiB in use, with 100% core CPU usage. One of these files is quite large, ~2000 LOC. After closing all tabs, the memory usage stays at ~750MiB, but the CPU usage does decrease.

**Comment by ericdallo** [comment]
clojure-lsp uses high cpu when scanning for the first time the project (using clj-kondo to scan all the paths), we already had issues with cpu and mem and them were improved a lot, not sure there's anything more to improve that

**Comment by ericdallo** [comment]
Maybe, could you check if there is a .lsp/sqlite.db file in your project, if so, could you try to remove it, restart the server (restart VSCode) and check if after some time the file is created?
Also you can check clojure-lsp log

**Comment by ericdallo** [comment]
@wcerfgba could you test latest release? we had a huge performance improvement on latest release

**Comment by wcerfgba** [comment]
Hi @ericdallo sorry for the slow response. I've just tried the latest release and it seems to be doing very well, no CPU spike, slightly lower memory usage :) I've deleted my `.lsp/sqlite.db` but it hasn't reappeared yet.

**Comment by ericdallo** [comment]
@wcerfgba check the logs (if using emacs you can get the path via `lsp-clojure-server-info`), it should save the sqlite file after scanning the project successfully
