### ISSUE TITLE
duplicated info in lens

### ISSUE THREAD

**Issue by andreyorst** [clojure-lsp/clojure-lsp#434]
From https://github.com/emacs-lsp/lsp-mode/issues/2249#issuecomment-846569224:

> This looks some corner case on clojure-lsp, please open an issue with more details and a minimal repro

Recently I've encountered this in some clojure file:

![image](https://user-images.githubusercontent.com/19470159/119270872-8eb5bc80-bc07-11eb-9e00-8972d241b12f.png)

Sadly I have no reproduction steps yet. I'll update the issue if I will find small example.

Since the screenshot was taken some time ago and I didn't got the needed info about versions, I'll fill the rest of the template once I get this issue again. I hope this is OK.

**Comment by ericdallo** [comment]
Thanks for the report!

Yeah, we need to know what code made that happen

**Comment by ericdallo** [comment]
Any news on a repro for this issue @andreyorst  ?

**Comment by andreyorst** [comment]
No, wasn't able to reproduce this yet. I'm using this every day, but so far nothing broke.

**Comment by andreyorst** [comment]
I wasn't able to reproduce this so far, so I'll close this. I'll reopen it if I ever find a way to repro this issue.
