### ISSUE TITLE
Fully qualified Java classes not recognised as symbols

### ISSUE THREAD

**Issue by lxsli** [clojure-lsp/clojure-lsp#44]
EG code like `(java.util.Date. ...)` says `Unknown symbol`

**Comment by shepheb** [comment]
This can be worked around by explicitly `(:import [java.util Date])` in your `ns` macro, or otherwise importing the Java classes.

But I agree, this should not be an error.

**Comment by ericdallo** [comment]
This was fixed after the integration with clj-kondo on #261
