### ISSUE TITLE
Duplicate test in features.completion-test/test-completion

### ISSUE THREAD

**Issue by LuisThiamNye** [clojure-lsp/clojure-lsp#442]
In the test `features.completion-test/test-completion`, the two testing contexts "complete-a" and "complete-alpaca" have identical bodies.

I suspect one of them needs to be changed.

```clojure
(testing "complete-a"
    (h/assert-submaps
     [{:label "alpaca" :kind :property :detail "user"}
      {:label "alpaca" :kind :property :detail "alpaca.ns"}
      {:label "alpha" :kind :variable}
      {:label "ba" :detail "alpaca.ns"}]
     (f.completion/completion (h/file-uri "file:///b.clj") 3 3)))
```
```clojure
(testing "complete-alpaca"
    (h/assert-submaps
     [{:label "alpaca" :kind :property :detail "user"}
      {:label "alpaca" :kind :property :detail "alpaca.ns"}
      {:label "alpha" :kind :variable}
      {:label "ba" :detail "alpaca.ns"}]
     (f.completion/completion (h/file-uri "file:///b.clj") 3 3)))
```

**Comment by ericdallo** [comment]
I took a look and at some time in the past they were different, but we had a lot of changes on that code, probably we left that duplicated code, we are safe to remove, LMK if you wanna open a PR :)

**Comment by LuisThiamNye** [comment]
Which one do you want to keep?

**Comment by ericdallo** [comment]
we can rename one of them to `complete-alp` to match the test content and remove the other.
