### ISSUE TITLE
lsp clean ns issues

### ISSUE THREAD

**Issue by weihua-lu** [clojure-lsp/clojure-lsp#447]
From the before we can see for `frontend.util`, only the `profile` function is not used, `util` is used.
![before](https://user-images.githubusercontent.com/9002575/122509283-168bbc80-d036-11eb-8b47-d37f74f87624.png)
After clean ns, the whole `frontend.util` is gone, instead i'd expect `[frontend.util :as util]` to be there
![after](https://user-images.githubusercontent.com/9002575/122509286-18ee1680-d036-11eb-8706-a28b8294dc9c.png)

Also, it'd be nice if clean ns can also remove duplication. from the after clean pic, we can see there're two same lines of `[medley.core :as medley]`.

ver: `2021.06.01-16.19.44`

**Comment by ericdallo** [comment]
Thanks for the report! I confirmed this is an issue, I'll work on a fix.

about the duplicate ones, maybe we can do that if the aliases are exactly the same otherwise we could not remove one of them as both aliases may be used in the code

**Comment by ericdallo** [comment]
Fixed on master, it should be available on next release soon

**Comment by weihua-lu** [comment]
that was quick! lsp is a great companion to cider, thanks :+1:
