### ISSUE TITLE
Custom LSP method which return server-info data

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#450]
Calva team reported that they would like to use `:source-paths` from clojure-lsp, ATM we have a command `server-info` that prints to user this data.

We should create a new LSP custom method `clojure/serverInfo/Raw` which will return the server-info data following the json LSP spec.

We can improve that as well by creating a new LSP custom method `clojure/serverInfo/log` deprecating the command `server-info`.

c/c @PEZ @bpringe

**Comment by PEZ** [comment]
Another use case is getting the version of the running clojure-lsp server. As well as the clj-kondo version it is using.

**Comment by ericdallo** [comment]
Fixed on master, I should release soon.

There is a new LSP custom method called `clojure/serverInfo/raw`, it should return all the info and a new keyword `:final-settings` that is the merge of client + project + default settings The `:source-paths` info should be accessible there.

@bpringe Also, I'm deprecating the `server-info` and `cursor-info` command, It'd be great if the `Calva diagnostics` replace that for the new `clojure/serverInfo/log` LSP method.

**Comment by bpringe** [comment]
@ericdallo Thanks. I've created an issue to make Calva use the new command.
