### ISSUE TITLE
Use of deprecated method .getRootUri

### ISSUE THREAD

**Issue by vemv** [clojure-lsp/clojure-lsp#456]
Hey there,

I was checking out the codebase and found out this is a deprecated method call:

https://github.com/clojure-lsp/clojure-lsp/blob/534831574ccaae0aafe60ed87c14a59ce85b2e52/src/clojure_lsp/main.clj#L298

It looks like this would be a fix:

```diff
       TextDocumentSyncOptions
+      WorkspaceFolder
       WorkspaceSymbolParams)
     (org.eclipse.lsp4j.launch LSPLauncher)
     (org.eclipse.lsp4j.services LanguageServer TextDocumentService WorkspaceService LanguageClient))
@@ -295,7 +296,10 @@
              (end
                (do
                  (log/info "Initializing...")
-                 (handlers/initialize (.getRootUri params)
+                 (handlers/initialize (-> params
+                                          .getWorkspaceFolders
+                                          ^WorkspaceFolder (first)
+                                          .getUri)
```

But I coudn't get it to pass GH actions (I'd get `Timeout running integration tests!` and no more info).

Perhaps you'd find this worth fixing?

**Comment by ericdallo** [comment]
Oh, I didn't know `.getRootUri` was deprecated, good to know I'l ltake a look!

Yeah, we heavily rely on this field, so integration tests would fail probably.

**Comment by ericdallo** [comment]
@vemv I noticed that the new field is not sent from emacs (lsp-mode) and maybe it's used for when the client support different workspaces, so I think we will have to keep using the .getRootUri until most clients use the new field

**Comment by ericdallo** [comment]
Actually it's supported in lsp-mode but they send as null, and according to the LSP spec, this means server should consider there is no workspace configured and discover the root itself, ATM we don't have that logic on the server so for now we should keep supporting the old .getRootUri I think

**Comment by vemv** [comment]
Kudos for giving this a shot!

**Comment by vemv** [comment]
Good to close after the ditching of lsp4j
