### ISSUE TITLE
better-cond :let not supported

### ISSUE THREAD

**Issue by lxsli** [clojure-lsp/clojure-lsp#46]
This is pretty understandable but... better-cond supports sub-lets:

```
(cond
  :let [a 1]
  a (prn "hi"))
```

It'd be nice to support this. Unfortunately I think there are a few libraries like this. I guess this is what the `macro-defs` thing is for? It's hard to see how to configure that though, the link to examples didn't help me much. Granted I didn't spend very long on it.

**Comment by snoe** [comment]
Is this the library? https://github.com/Engelberg/better-cond
There's a lot of magic here so I think it will take custom code in lsp to support it. It would help if you can get me more examples of the libraries that do similar.

However, I'll probably wait on implementing this myself until this issue gets some more votes. Happy to take a PR that adds to macro-defs to support this though (or if you have particular questions about macro-defs, it will help for me to improve the docs).

**Comment by lxsli** [comment]
That's the one.

Two alternatives I Googled up just now, I guess these 3 are the main ones:
https://github.com/walmartlabs/cond-let
https://clojure.github.io/clojure-contrib/branch-master/cond-api.html

**Comment by ericdallo** [comment]
This should already work since we now use clj-kondo to analysis/parse code, if doesn't work, it should be fixed or configured on clj-kondo side
