### ISSUE TITLE
Question : WorkSpaces & RenameSymbol

### ISSUE THREAD

**Issue by thecontinium** [clojure-lsp/clojure-lsp#460]
Hi 

First thanks to everyone for writing this; it's super helpful.

**Workspaces**: for cloure can we think of a lsp workspace as a typical lein project ? Can you have more than one workspace setup and will it work across them.

**Rename Symbol**: Is the rename functionality for the symbols across the workspace/project ? Can it work across multiple workspaces/projects ? In particular can you rename a symbol in a library project and across other projects which have dependencies on it ?

Cheers

**Comment by ericdallo** [comment]
Hi @thecontinium!

> Workspaces: for cloure can we think of a lsp workspace as a typical lein project ? Can you have more than one workspace setup and will it work across them.

Yes, you can think of a workspace as a group of files/folders that you work, for clojure it's pretty common to be the lein/deps project root. You can have multiple workspaces if the server supports it, in this case we do not as is not common. For mono-repos, importing the mono-repo root seems to work fine ATM.

> Rename Symbol: Is the rename functionality for the symbols across the workspace/project ? Can it work across multiple workspaces/projects ? In particular can you rename a symbol in a library project and across other projects which have dependencies on it ?

The rename will rename all symbols from the current workspace only, so all symbols of a lein project, but no other workspaces/projects/dependencies

**Comment by thecontinium** [comment]
Thanks for the quick reply @ericdallo. Perhaps the rename across workspaces is something for the future. Cheers and thanks again.

**Comment by ericdallo** [comment]
Yes, a good idea, but first we'd need to support multiple workspaces which is something not simple at the moment :/

You're welcome!
