### ISSUE TITLE
clojure-lsp terminal cli - clean-ns don't find project files if --project-root isn't provided

### ISSUE THREAD

**Issue by rafaeldelboni** [clojure-lsp/clojure-lsp#463]
**Describe the bug**

**To Reproduce**
1. Clone `https://github.com/parenthesin/microservice-boilerplate`
2. CD into the project dir `cd microservice-boilerplate`
3. Change a namespace order in any `/src` file
3. Run `clojure-lsp clean-ns`
4. No files changed

**Expected behavior**
Expected to clean-ns to fix the namespaces, without providing `-p ./`

**Screenshots**
```bash
# Running this command in the root of the project
$ clojure-lsp clean-ns
Analyzing project... 0ms
Checking namespaces...
```

```bash
# But works fine if -p is provided
$ clojure-lsp -p ./ clean-ns
Analyzing project... 3331ms
Checking namespaces...
Cleaned microservice-boilerplate.adapters

```

**User details (please complete the following information):**
 - OS: ArchLinux, ZSH
 - Version: kernel 5.12.13-arch1-2, zsh 5.8, clojure-lsp 2021.07.01-13.46.18, clj-kondo 2021.06.18

**Comment by ericdallo** [comment]
Thanks for the report!
It's a issue with Graalvm detecting the user.dir I'd guess.
I'll take a look!

**Comment by rafaeldelboni** [comment]
Just tested this version and now is working as expected, thank you for your work!
