### ISSUE TITLE
Markdown hover link on Windows is missing slashes

### ISSUE THREAD

**Issue by oconnor0** [clojure-lsp/clojure-lsp#467]
**Describe the bug**
When I hover a symbol in Sublime Text, I get a popup with a link to the symbol's definition. But the link doesn't have slashes in it and, because it's a URI-less link, it doesn't work.

**To Reproduce**
1. On Windows using Sublime Text with LSP and connected to clojure-lsp.
2. Hover a symbol.
3. See the link has no slashes.
4. Click on it to no avail.

**Expected behavior**
I expect the link to show the correct path and to work.

**Screenshots**
This is what the popup looks like.

![image](https://user-images.githubusercontent.com/64384/124945849-c5833e80-dfcb-11eb-8664-f318c364667f.png)

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
:: --> clojure-lsp textDocument/hover(11): {'position': {'character': 7, 'line': 2}, 'textDocument': {'uri': 'file:///C:/src/path/to/file.clj'}}
:: <<< clojure-lsp 11: {'contents': {'kind': 'markdown', 'value': '```clojure\nabc/hi\n```\n```clojure\n[]\n```\n----\n*[C:\\src\\path\\to\\file.clj](C:\\src\\path\\to\\file.clj)*'}, 'range': {'start': {'character': 6, 'line': 2}, 'end': {'character': 8, 'line': 2}}}
</pre>
</details>

**User details (please complete the following information):**
 - OS: Windows 10
 - Editor: Sublime Text
 - Version: clojure-lsp 2021.07.05-20.31.12
    clj-kondo 2021.06.18

**Additional context**
I brought this up in the Sublime Text LSP channel, and one of the devs there mentioned requesting using a code action with a `window/showDocument` to do the display instead of a link.

**Comment by ericdallo** [comment]
Thank you for the report @oconnor0, I suspect this is some issue with SublimeText or Windows10 as this works well with other clients like emacs and vscode:
![image](https://user-images.githubusercontent.com/7820865/124999205-06a73d00-e024-11eb-86b1-c2abfb5a872e.png)

@LuisThiamNye may confirm that, if the URI we are sending is conforming the spec as well

**Comment by LuisThiamNye** [comment]
clojure-lsp returns `"[C:\\src\\path\\to\\file.clj](C:\\src\\path\\to\\file.clj)"` in the markdown. The reason the backslashes are not showing is because the markdown parser tries to escape the characters `s`, `p`, `t` etc. This would be solved by doubling the backslashes in the link label.

However, I do not think that will solve clicking the link. After very briefly searching the internet, I suspect markdown prefers to use forward slashes in the link destination (URL format). Thus, I would suggest a possible fix would be to use the file URI as the link destination.

`"[C:\\\\src\\\\path\\\\to\\\\file.clj](file:///C:/src/path/to/file.clj)"`

**Comment by ericdallo** [comment]
I thought we were already sending the link as URI

**Comment by ericdallo** [comment]
Willing to make that change @LuisThiamNye ?

**Comment by LuisThiamNye** [comment]
Unfortunately, I’ll be away from My Emacs for a week, so I can’t do any testing myself.

I’m eyeing line 53 of `feature/hover.clj`:
```clojure
filename (str (format "%s*[%s](%s)*" line-break filename filename)))}
```
Maybe try something like this:
```clojure
filename (str (format "%s*[%s](%s)*" line-break
                      (str/replace filename #"\\" "\\\\")
                      (shared/filename->uri filename))))}
```
Also, wrapping with `str` isn’t necessary right?
```clojure
filename (format "%s*[%s](%s)*" line-break
                 (str/replace filename #"\\" "\\\\")
                 (shared/filename->uri filename)))}
```

**Comment by ericdallo** [comment]
Makes sense, thanks for the help! I'll make the proper changes soon so you can confirm it works for you @oconnor0

**Comment by ericdallo** [comment]
I just realized the file uri location in markdown should be a uri indeed and it was not working for other editors like Calva 😅 
Your suggestion works like a charm @LuisThiamNye, I just needed to keep the `str` as for some reason format doesn't return an string exactly and it doesn't work well with LSP classes during serialization.

Fixed on master @oconnor0, you can try building clojure-lsp manually with `make` or waiting for next release (couple of days probably)

**Comment by ericdallo** [comment]
FYI @bpringe this fixed on calva as well:
![calva-fixed-issue](https://user-images.githubusercontent.com/7820865/125141276-ea220800-e0ea-11eb-8c04-0d42a51da24a.png)

**Comment by bpringe** [comment]
Awesome!

**Comment by oconnor0** [comment]
https://github.com/clojure-lsp/clojure-lsp/commit/510f964dc2a63effc6640efc3b841bf154406f48#diff-8231bfc49f0fa86ecfc60d11fed711dd0168ec5e57da0a04873bcd36adfb989cR55 looks like a typo (the # is inside the quotes). I am seeing the paths in the response markdown as `C:#\\src#\\path#\\to#\\file.clj`, but the links work now.

**Comment by ericdallo** [comment]
yes, it's a typo 🤦🏻

**Comment by ericdallo** [comment]
Fixed the typo on master @oconnor0
