### ISSUE TITLE
Symbols marked as `var-usage` if `:to` is `:clj-kondo/unknown-namespace`

### ISSUE THREAD

**Issue by NoahTheDuke** [clojure-lsp/clojure-lsp#468]
**Describe the bug**
In my `project.clj`, I have entries in my `:dependency` vector that don't have a groupId/namespace. Each dependency without a namespace is treated as a `var-usage` and is highlighted as a function. When `clojure/cursorInfo/log` is called on one of these dependencies, it outputs a `:to` value of `:clj-kondo/unknown-namespace`. For example:
```clojure
{:element
 {:name-end-col 25,
  :name-end-row 14,
  :name-row 14,
  :name differ,
  :filename "/Users/noah/Personal/netrunner/project.clj",
  :from user,
  :col 19,
  :name-col 19,
  :bucket :var-usages,
  :row 14,
  :to :clj-kondo/unknown-namespace},
 :definition nil}
```

**To Reproduce**
1. Open a `project.clj`
2. Remove the namespace/groupId portion of a dependency
3. Wait for the editor to receive the semantic highlighting update from clojure-lsp.

**Expected behavior**
Dependencies without a groupId/namespace to be not highlighted as functions when using semantic highlighting.

**Screenshots**
![image](https://user-images.githubusercontent.com/603677/125127128-1711f300-e0ca-11eb-95f6-b0ec1b0ad7ec.png)

**User details (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Editor: Vim 8.2 using coc.nvim
 - Version: clojure-lsp 2021.07.05-20.31.12

**Comment by ericdallo** [comment]
Thanks for the report!

Oh, I just realize this is project.clj file, I was thinking you were in a `(:require ...)` block 😅 

I'll take a look at this soon

**Comment by NoahTheDuke** [comment]
It happens in both! I initially asked about a `:require` block and then demonstrated it happens in the project.clj file as well, hah. Sorry for the confusion.

**Comment by ericdallo** [comment]
I can't repro on the require block though:
![image](https://user-images.githubusercontent.com/7820865/125136901-0c635800-e0e2-11eb-8344-ac4b7942e67e.png)
```
{:name-end-col 13,
  :name-end-row 5,
  :name-row 5,
  :name cheshire,
  :alias-end-row 5,
  :alias-row 5,
  :filename
  "/home/greg/dev/clojure-lsp/src/clojure_lsp/internal_api.clj",
  :alias c,
  :from clojure-lsp.internal-api,
  :col 5,
  :name-col 5,
  :alias-col 18,
  :alias-end-col 19,
  :bucket :namespace-usages,
  :row 5}
```
You can see kondo is finding the namespace, for some reason it's not finding in your project

**Comment by ericdallo** [comment]
It happens only for project.clj:
![image](https://user-images.githubusercontent.com/7820865/125137059-4e8c9980-e0e2-11eb-8a0f-bbf41002298e.png)

**Comment by ericdallo** [comment]
this happens because:
- project.clj is a clj file, so it's analyzed with clojure-lsp
- clj-kondo see `org.clojure/clojure` as a namespace which makes sense, but cheshire is a not found namespace/symbol (as it's only understandable by lein)

Maybe we should change to only don't return tokens for unknown synmbols like the initial idea indeed

**Comment by ericdallo** [comment]
FIxed on master, should be available on next release :)
It should now return no tokens for unknown symbols.

**Comment by NoahTheDuke** [comment]
Thanks for the quick solution! I'll see about the issue you couldn't reproduce, try to remember what the heck I did.
