### ISSUE TITLE
Neovim: All syntax highlighting colors changes to the same color after clojure-lsp is loaded

### ISSUE THREAD

**Issue by oryband** [clojure-lsp/clojure-lsp#470]
Clojure syntax highlighting is proper before clojure-lsp is loaded, but after it does (takes a few seconds) syntax highlighting changes where almost all text is in the same color/highlight. The color depends on the colorscheme currently in use, but no matter the colorscheme, it's a single color.

I executed `:echo synIDattr(synID(line("."), col("."), 1), "name")` on multiple symbols under the cursor where the colors have been changed, and getting different results e.g. `ClojureSymbol` `ClojureSpecial`, etc. but all are highlighted with the same color.

Reproducable by opening a `.clj` file with at least a few dozens of valid Clojure code, waiting for the coc.nvim and clojure-lsp to load up, and after a few seconds clojure-lsp's highlighting will kick in and scramble syntax highlighting. Note I am not seeing any errors related to plugins loading. It just surfaced after executing `brew upgrade` and updating my plugins.

Turning off semantic tokens fixes the issue.

See screenshots before and after the plugin is loaded:

![before](https://user-images.githubusercontent.com/115387/125193516-68022280-e255-11eb-9bce-4fa0401d95d6.png)

![after](https://user-images.githubusercontent.com/115387/125193517-69334f80-e255-11eb-8486-a5090543c66b.png)

- Logs: https://gist.github.com/oryband/66668b5a423b8522d950e74edf66e253
- [Link to my .config/nvim directory](https://github.com/oryband/dotfiles/tree/6b94c69214e6fe2fb4dcce69626bc0cd227e7396/.config/nvim)

```
# nvim --version
Alias tip: vi --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-u4YhjF/neovim-0.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-u4YhjF/neovim-0.4.4/build/config -I/build/neovim-u4YhjF/neovim-0.4.4/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-u4YhjF/neovim-0.4.4/build/src/nvim/auto -I/build/neovim-u4YhjF/neovim-0.4.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

# uname -a
Linux roach 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
```

**Comment by ericdallo** [comment]
This is an lint side issue, as clojure-lsp is returning the correct tokens and the client is using the same color/face to highlight them.
A proof of this is that it works perfect with emacs lsp-mode which has different colors for each token

**Comment by oryband** [comment]
> test it with another LSP client that has semantic tokens feature support
I forgot to mention this only happens with clojure-lsp, not python or java or any other language. Do you have examples of other LSP clients I can test this with?

**Comment by ericdallo** [comment]
Python and java mostly have other kind of tokens, like enums, classes, methods etc, clojure-lsp return keywords, namespace, functions so that may be a bug on these tokens on nvim.
I don't know any other clients that has that feature for sure besides lsp-mode and VSCode (but Calva has not implemented it yet)

**Comment by ericdallo** [comment]
Also, I'd suggest test it with another theme, maybe a famous one

**Comment by oryband** [comment]
> Also, I'd suggest test it with another theme, maybe a famous one

I did this with base16, a popular one. It doesn't matter: This also happens with all plugins turned off except clojure-lsp.

**Comment by ericdallo** [comment]
@oryband, I still think it's a client issue, I added a new `:semantic-tokens` debug info into `cursor-info` custom method to help understand what token clojure-lsp is returning, maybe you can try that. Example of that:
```
{:element
 ...
 :semantic-tokens [{:token-type :keyword, :token-modifier -1}]}
``

**Comment by ericdallo** [comment]
Closing as it's probably a client issue, LMK if need any help
