### ISSUE TITLE
clojure/serverInfo/raw command is returning no result

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#472]
**Describe the bug**
When using the new `clojure/serverInfo/raw` command, no result is returned.

**To Reproduce**

1. Call the `clojure/serverInfo/raw` command once the clojure-lsp server is running
2. See that no result is returned.

**Expected behavior**
I expect for server info to be returned in the command response.

<details>
 <summary><b>clojure-lsp output</b></summary>
<pre>
[Trace - 12:41:37 PM] Sending request 'workspace/executeCommand - (1)'.
Params: {
    "command": "clojure/serverInfo/raw",
    "arguments": []
}

[Trace - 12:41:37 PM] Received response 'workspace/executeCommand - (1)' in 27ms.
No result returned.
</pre>
</details>

**User details (please complete the following information):**
 - OS: ArchLinux (Manjaro)
 - Version: 2021.07.01-13.46.18

@ericdallo, am I calling this command incorrectly?

**Comment by bpringe** [comment]
Sorry, I think I incorrectly created this as an API issue.

**Comment by bpringe** [comment]
CC @pratik97

**Comment by ericdallo** [comment]
Probably some missing Graalvm config, let me check

**Comment by ericdallo** [comment]
@bpringe actually everything seems to be working even with graalvm binary, just to make clear, this is a new custom LSP method, not a new command, the request log should be something like:
```json
[Trace - 05:30:50 PM] Sending request 'clojure/serverInfo/raw - (4287)'.
Params: null
```
and not:
```json
[Trace - 05:31:57 PM] Sending request 'workspace/executeCommand - (4297)'.
Params: {
  "command": "clojure/serverInfo/raw",
  "arguments": []
}
```

**Comment by ericdallo** [comment]
I just saw you log output, yeah, the call is incorrect indeed 😅

**Comment by bpringe** [comment]
Thanks! I think I can make it work.

**Comment by bpringe** [comment]
I'll close this and reopen if there's an issue.
