### ISSUE TITLE
Extra line breaks in documentation hover

### ISSUE THREAD

**Issue by NoahTheDuke** [clojure-lsp/clojure-lsp#473]
**Describe the bug**
When showing the documentation of a given function, each line is padded with blank lines.

**To Reproduce**
Press your editors key combo or hover over any function.

**Expected behavior**
Show the same info, just squished together more.

**Screenshots**
Using clojure-lsp:
<img width="733" alt="Screen Shot 2021-07-12 at 10 56 56 AM" src="https://user-images.githubusercontent.com/603677/125311062-1dd67b00-e301-11eb-9fb8-7f9fdaac6f6d.png">
Using vim-iced (merely to show how things could be more compact):
<img width="544" alt="image" src="https://user-images.githubusercontent.com/603677/125311173-36df2c00-e301-11eb-831f-85bf180f5261.png">

**User details (please complete the following information):**
 - OS: MacOS 10.14.6
 - Editor: macvim 8.2 with coc.nvim
 - Version: `clojure-lsp 2021.07.12-12.30.59`

**Additional context**

**Comment by NoahTheDuke** [comment]
Seems like it's happening here:

https://github.com/clojure-lsp/clojure-lsp/blob/dd2d3082a08022a3d5a2ca8896de031dc08c2a94/src/clojure_lsp/feature/hover.clj#L58-L61

**Comment by NoahTheDuke** [comment]
Seems that this is a facet of how coc.nvim handles returned markdown from all LSPs, so this has nothing to do with clojure-lsp.

**Comment by ericdallo** [comment]
Closing as it seems to be a issue on client side: https://clojurians.slack.com/archives/CPABC1H61/p1626102656361200
