### ISSUE TITLE
Empty XDG_CONFIG_HOME should default to "$HOME/.config"

### ISSUE THREAD

**Issue by andreyorst** [clojure-lsp/clojure-lsp#474]
Not all GNU/Linux distributives set the `XDG_CONFIG_HOME` variable to some value. For example Fedora doesn't. [According to XDG spec](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html):

> `$XDG_CONFIG_HOME` defines the base directory relative to which user-specific configuration files should be stored. **If `$XDG_CONFIG_HOME` is either not set or empty, a default equal to `$HOME/.config` should be used.**

Right now, `clojure-lsp` is checking if variable is set, and if it is not it defaults to `$HOME/.lsp`:

https://github.com/clojure-lsp/clojure-lsp/blob/dd2d3082a08022a3d5a2ca8896de031dc08c2a94/src/clojure_lsp/config.clj#L65-L68

This doesn't exactly follow the XDG conventions. Instead, when `(get-env "XDG_CONFIG_HOME")` returns `nil`, the `(io/file (get-property "user.home") ".config" ".lsp" "config.edn")` should be checked for existence. And if it doesn't exist, the ` (io/file (get-property "user.home") ".lsp" "config.edn")` should be tried next.

**To Reproduce**

1. Unset `XDG_CONFIG_HOME` variable
2. Put `.lsp` directlry to `$HOME/.config/ 
3. Start `clojure-lsp` in any project, and see that server configuration is not applied

**Expected behavior**

Config is read from `$HOME/.config/.lsp/config.edn`

**User details (please complete the following information):**

 - OS: Fedora 34
 - Version: clojure-lsp 2021.06.01-16.19.44 clj-kondo 2021.06.01

**Comment by andreyorst** [comment]
@ericdallo sorry for bumping recently closed thread, but I forgot to ask why `.lsp` directory name is used, and not `.clojure_lsp`/`.clojure-lsp`? 

`.lsp` feels very generic, for a configuration specific to clojure, and storing hidden directory under `$HOME/.config/` is quite not a standard. Usually users expect `$HOME/.config/programname/` or `$HOME/.programname/` (or `$HOME/.programname.d`) style of configuration directories.

**Comment by ericdallo** [comment]
`.lsp` was defined long ago when the project started, I agree `clojure-lsp` would be a better name, but changing that right now would be a bad breaking-change, maybe we could add support for `$HOME/.config/lsp` instead of `$HOME/.config/.lsp`, WDYT?

**Comment by andreyorst** [comment]
> maybe we could add support for $HOME/.config/lsp instead of $HOME/.config/.lsp, WDYT?

Now that the path construction for home and for XDG case are separate we can do that, I guess.

But could we, potentially, gradually move from `.lsp` under several releases by deprecating `.lsp` in favor of `$HOME/.clojure-lsp` and `$HOME/.config/clojure-lsp`? Maybe displaying a warning in the server logs

**Comment by ericdallo** [comment]
> But could we, potentially, gradually move from .lsp under several releases by deprecating .lsp in favor of $HOME/.clojure-lsp and $HOME/.config/clojure-lsp? Maybe displaying a warning in the server logs

It sounds the best approach indeed, we would need to change every reference on the docs as well, feel free to open an PR :)
A warning on server log looks good too.

**Comment by andreyorst** [comment]
> feel free to open an PR :)

I'll start with the issue :)
