### ISSUE TITLE
Project analysis in loop during startup

### ISSUE THREAD

**Issue by sittim** [clojure-lsp/clojure-lsp#484]
When running `clojure-lsp` command on a repo such as [fulcro-template](https://github.com/fulcrologic/fulcro-template), the project analysis gets stuck.  The output is the following:

```
sporty@vboxsporty:~/clojure/app$ clojure-lsp clean-ns --verbose
Analyzing project... 0ms2021-07-17T14:45:01.871Z vboxsporty INFO [clojure-lsp.crawler:239] - Automatically resolved source-paths from deps.edn: #{"src/test" "src/workspaces" "src/dev" "src/main" "resources"}
Analyzing project... 100ms2021-07-17T14:45:01.983Z vboxsporty WARN [clojure-lsp.db:55] - Could not load db [SQLITE_ERROR] SQL error or missing database (no such table: project)
2021-07-17T14:45:01.983Z vboxsporty INFO [clojure-lsp.crawler:29] - Finding classpath via ` clojure -A:dev -Spath `
Analyzing project... 1959ms^C
```

**To Reproduce**

1. Clone project https://github.com/fulcrologic/fulcro-template
2. Run clojure-lsp clean-ns --verbose
3. See error

**Expected behavior**
Analysis should be completed and the sqlite database in the ./.lsp directory populated.

**User details (please complete the following information):**
Ubuntu 20.04 OS, clojure_lsp https://github.com/fulcrologic/fulcro-template

NOTE: The fix for me was to clone the repo, build it and copy binary to `/usr/local/bin/clojure-lsp` or any folder in the $PATH.

**Comment by ericdallo** [comment]
@sittim the message probably could be improved but this is expected to happen every new time you run clojure-lsp in a project that doesn't has the .lsp/sqlite.db yet.
Does that message happens on the next try after the analysis is done for the first time?

**Comment by ericdallo** [comment]
I confirmed this happens only the first time clojure-lsp runs which is expected, next time works without that error. I'll improve the message to avoid confusion like this

**Comment by sittim** [comment]
@ericdallo, for some reason, it never completes analysis.  I wonder if it got into an infinite loop.  It ran for 15 or so minutes and than something killed it:

```
sporty@vboxsporty:~/clojure/app$ clojure-lsp clean-ns --verbose
Analyzing project... 0ms2021-07-17T15:04:42.833Z vboxsporty INFO [clojure-lsp.crawler:239] - Automatically resolved source-paths from deps.edn: #{"src/test" "src/workspaces" "src/dev" "src/main" "resources"}
Analyzing project... 100ms2021-07-17T15:04:42.956Z vboxsporty WARN [clojure-lsp.db:55] - Could not load db [SQLITE_ERROR] SQL error or missing database (no such table: project)
2021-07-17T15:04:42.956Z vboxsporty INFO [clojure-lsp.crawler:29] - Finding classpath via ` clojure -A:dev -Spath `
2021-07-17T15:04:42.978Z vboxsporty INFO [clojure-lsp.crawler:206] - Analyzing classpath for project root /home/sporty/clojure/app
2021-07-17T15:04:42.978Z vboxsporty INFO [clojure-lsp.crawler:90] - Analyzing 141 paths with clj-kondo with batch size of 3 ...
2021-07-17T15:04:42.979Z vboxsporty INFO [clojure-lsp.crawler:96] - Analyzing 1/3 batch paths with clj-kondo...
Analyzing project... 1147293msKilled
```

**Comment by ericdallo** [comment]
15 minutes is to much, for me it worked in less than 30s. It seems that it's not completing the clj-kondo analysis, could you try to remove a `.clj-kondo` folder in your project if any.

**Comment by sittim** [comment]
I tried it, did not help.  Did you run it on the repo I provided?

**Comment by ericdallo** [comment]
Yes, this is the output running from your project:
```bash
Analyzing project... 1ms2021-07-17T15:30:37.299Z gregnix-note INFO [clojure-lsp.crawler:239] - Automatically resolved source-paths from deps.edn: #{"src/test" "src/workspaces" "src/dev" "src
/main" "resources"}                                                                                                                                                                           
Analyzing project... 102ms2021-07-17T15:30:37.433Z gregnix-note WARN [clojure-lsp.db:56] - Could not load project cache from '/home/greg/dev/clojure-lsp-issue-484/.lsp/sqlite.db'. This usual
ly happens the first time project is being analyzed.                                                                                                                                          
2021-07-17T15:30:37.434Z gregnix-note INFO [clojure-lsp.crawler:29] - Finding classpath via `clojure -A:dev -Spath`                                                                           
Analyzing project... 3926ms2021-07-17T15:30:41.282Z gregnix-note INFO [clojure-lsp.crawler:206] - Analyzing classpath for project root /home/greg/dev/clojure-lsp-issue-484                   
2021-07-17T15:30:41.285Z gregnix-note INFO [clojure-lsp.crawler:90] - Analyzing 1 paths with clj-kondo with batch size of 1 ...                                                               
Analyzing project... 4027ms2021-07-17T15:30:41.318Z gregnix-note INFO [clojure-lsp.crawler:179] - Paths analyzed, took 0.03341948 secs. Caching for next startups...                          
2021-07-17T15:30:41.360Z gregnix-note INFO [clojure-lsp.crawler:213] - Manual GC after classpath scan took 0.03753981 seconds                                                                 
2021-07-17T15:30:41.394Z gregnix-note INFO [clojure-lsp.crawler:221] - Analyzing source paths for project root /home/greg/dev/clojure-lsp-issue-484                                           
Analyzing project... 5030ms2021-07-17T15:30:42.360Z gregnix-note INFO [clojure-lsp.crawler:179] - Paths analyzed, took 0.9657172 secs. Caching for next startups...                                                                                                                                                                                                                                    
....
```

**Comment by ericdallo** [comment]
Could you try with the non graalvm binary?
the `clojure-lsp` one from [here](https://github.com/clojure-lsp/clojure-lsp/releases/tag/2021.07.12-12.30.59)

**Comment by sittim** [comment]
```
[I] /home/sporty/clojure/app~> clojure-lsp --version
clojure-lsp 2021.07.12-12.30.59
clj-kondo 2021.06.18
```

Same thing, does not finish the analysis.  What is strange is it works fine on a clean repo I start using `clj-new`

**Comment by ericdallo** [comment]
Yeah, that's new to me, no exception is thrown, what is the output of `clojure -A:dev -Spath` ? I'm also working on improve error handling for the classpath lookup command on clojure-lsp, I'm suspecting it's ignoring if that command is returning an error.

**Comment by ericdallo** [comment]
@sittim also, could you check if  the same behaviour happens if you use clojure-lsp via your editor?

**Comment by sittim** [comment]
- No issues with `clojure -A:dev -Spath` but same issue in the editor, I looked through logs.
- No issue running [reagent-template](https://github.com/reagent-project/reagent-template)
- Seems to have an issue with [fulcro-template](https://github.com/fulcrologic/fulcro-template)

**Comment by ericdallo** [comment]
That's odd, all those projects work for me, the fulcro one took 1-2 minutes the first time as it has a lot of dependencies but it worked

**Comment by ericdallo** [comment]
@sittim I made a commit on master improving error handling and logging during project analysis, not sure it'll help with your issue, but I'd suggest testing it, if you'd like to test it you can just `make` on clojure-lsp to generate a `clojure-lsp` binary.

**Comment by sittim** [comment]
cloned, built it and installed it.  It seems to work so far.  The db is populated with 51MB!

**Comment by ericdallo** [comment]
Yeah, usually cljs libs like fulcro have a lot of dependencies, glad to know it works now

**Comment by sittim** [comment]
@ericdallo, thank you, I love it, I edited the initial question so it is easier to understand and closing the issue.

**Comment by ericdallo** [comment]
Thank you, don't forget to test the next release as this should work with the graalvm binary
