### ISSUE TITLE
NixOS: Never progresses past `Starting` state

### ISSUE THREAD

**Issue by crinklywrappr** [clojure-lsp/clojure-lsp#487]
**Describe the bug**
Never progresses past the 'Starting' state.

**To Reproduce**
Execute on nixos, using the builtin package.

**Details**

I ran with `strace` and found that it's waiting for ... something.

![Screenshot from 2021-07-24 15-58-10](https://user-images.githubusercontent.com/56522/126881046-73139471-d483-4e3a-9b58-621947bc779d.png)

The file output from that run:

```
2021-07-24T20:57:14.005Z nomad INFO [clojure-lsp.main:391] - Starting server...
2021-07-24T20:57:14.009Z nomad INFO [clojure-lsp.nrepl:21] - ====== LSP nrepl server started on port 40659
```

Emacs appears to get a connection to clojure-lsp, but it claims to be in the `Starting` state, and doesn't perform any function.

## System details
**verbose flag**
clojure-lsp 2021.04.13-12.47.33
clj-kondo 2021.04.01-SNAPSHOT

NixOS 25.01

**Comment by ericdallo** [comment]
Thank you for the report, @crinklywrappr, could you try the embedded JVM binary from releases?
It's called `clojure-lsp` on [this Page](https://github.com/clojure-lsp/clojure-lsp/releases/tag/2021.07.19-14.46.52), just to confirm it's not a issue with your config/nix installation?

**Comment by crinklywrappr** [comment]
Sure thing.  I am also going to try the build on nix unstable, since the stable version is a few releases old.

**Comment by ericdallo** [comment]
Oh, for sure you should use the unstable one, also, I updated it recently

**Comment by crinklywrappr** [comment]
The more recent version on unstable works fine.
