### ISSUE TITLE
Emacs: `Error processing message (wrong-type-argument  sequencep count)`

### ISSUE THREAD

**Issue by crinklywrappr** [clojure-lsp/clojure-lsp#488]
**Describe the bug**
Displays this error message below the emacs modeline, after any interaction with the file (including simply moving the pointer around)

![Screenshot from 2021-07-24 17-22-38](https://user-images.githubusercontent.com/56522/126882338-505060bf-c121-4dca-bb2b-856367ad50c9.png)

I have seen this on Windows and Linux.  Screenshot taken w/ nixos

clojure-lsp 2021.07.19-14.46.52
clj-kondo 2021.06.18

**Comment by ericdallo** [comment]
This is a client issue, or a lsp-mode bug or a bug with some package of yours, you can try to debug emacs with `M-x` `toggle-debug-on-error` to get the stacktrace.
