### ISSUE TITLE
Unable to open up jar file when going to definition (for dependencyContents)

### ISSUE THREAD

**Issue by dharrigan** [clojure-lsp/clojure-lsp#492]
Arch Linux,
neovim 0.5.0

```
❯ clojure-lsp --version       
clojure-lsp 2021.07.19-14.46.52
clj-kondo 2021.06.18
```

Hi,

On trying to executed `clojure/dependencyContents` on, for example `clojure.string/join`, I receive these two errors (note that the exceptions, one after the other, are subtly different):

```
2021-07-28T07:05:52.642Z daffy ERROR [clojure-lsp.server:?] - 
com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine      PosixJavaThreads.java:  192
            com.oracle.svm.core.thread.JavaThreads.threadStartRoutine           JavaThreads.java:  553
                        java.util.concurrent.ForkJoinWorkerThread.run  ForkJoinWorkerThread.java:  183
                          java.util.concurrent.ForkJoinPool.runWorker          ForkJoinPool.java: 1594
                               java.util.concurrent.ForkJoinPool.scan          ForkJoinPool.java: 1656
             java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec          ForkJoinPool.java: 1020
                             java.util.concurrent.ForkJoinTask.doExec          ForkJoinTask.java:  290
              java.util.concurrent.CompletableFuture$AsyncSupply.exec     CompletableFuture.java: 1692
               java.util.concurrent.CompletableFuture$AsyncSupply.run     CompletableFuture.java: 1700
                  clojure-lsp.server.LSPTextDocumentService/reify/get                 server.clj:  192
                                       clojure-lsp.handlers/code-lens               handlers.clj:  263
                    clojure-lsp.feature.code-lens/reference-code-lens              code_lens.clj:   41
                                     clojure-lsp.shared/uri->filename                 shared.clj:  100
                                                  java.net.URL.<init>                   URL.java:  488
                                                  java.net.URL.<init>                   URL.java:  541
                                                  java.net.URL.<init>                   URL.java:  674
                            sun.net.www.protocol.jar.Handler.parseURL               Handler.java:  163
                   sun.net.www.protocol.jar.Handler.parseAbsoluteSpec               Handler.java:  181
java.lang.NullPointerException: no !/ in spec
java.net.MalformedURLException: no !/ in spec

2021-07-28T07:10:56.144Z daffy DEBUG [clojure-lsp.server:?] - :codeLens 1ms
2021-07-28T07:10:56.144Z daffy DEBUG [clojure-lsp.server:?] - :documentHighlight 1ms
2021-07-28T07:10:57.643Z daffy ERROR [clojure-lsp.server:?] - 
com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine      PosixJavaThreads.java:  192
            com.oracle.svm.core.thread.JavaThreads.threadStartRoutine           JavaThreads.java:  553
                        java.util.concurrent.ForkJoinWorkerThread.run  ForkJoinWorkerThread.java:  183
                          java.util.concurrent.ForkJoinPool.runWorker          ForkJoinPool.java: 1594
                               java.util.concurrent.ForkJoinPool.scan          ForkJoinPool.java: 1656
             java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec          ForkJoinPool.java: 1020
                             java.util.concurrent.ForkJoinTask.doExec          ForkJoinTask.java:  290
              java.util.concurrent.CompletableFuture$AsyncSupply.exec     CompletableFuture.java: 1692
               java.util.concurrent.CompletableFuture$AsyncSupply.run     CompletableFuture.java: 1700
                  clojure-lsp.server.LSPTextDocumentService/reify/get                 server.clj:  212
                            clojure-lsp.handlers/semantic-tokens-full               handlers.clj:  272
                      clojure-lsp.feature.semantic-tokens/full-tokens        semantic_tokens.clj:  110
                                     clojure-lsp.shared/uri->filename                 shared.clj:  100
                                                  java.net.URL.<init>                   URL.java:  488
                                                  java.net.URL.<init>                   URL.java:  541
                                                  java.net.URL.<init>                   URL.java:  674
                            sun.net.www.protocol.jar.Handler.parseURL               Handler.java:  163
                   sun.net.www.protocol.jar.Handler.parseAbsoluteSpec               Handler.java:  181
java.lang.NullPointerException: no !/ in spec
java.net.MalformedURLException: no !/ in spec
```

The URI that is being passed to clojure-lsp is like this:

`
jar:file:///home/david/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar!/clojure/core.clj
`

Which is invoked via this function:

```
function! LoadClojureContent(uri)
    setfiletype clojure
    let content = CocRequest('clojure-lsp', 'clojure/dependencyContents', {'uri': a:uri})
    call setline(1, split(content, "\n"))
    setl nomodified readonly
endfunction
```

**Comment by dharrigan** [comment]
It seems that the `uri` being passed to `shared/uri->filename` is this:

`jar:file%3A///home/david/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar%21/clojure/string.clj`

which causes the URL connection to fail, as it can't unescape the escaped characters (colon and question mark)

**Comment by dharrigan** [comment]
More Details.

Since the change to `coc-clojure` as the language server (rather than using `clojure-lsp` directly, I've discovered I need to change the function LoadClojureContent (detailed above) to have this:

`CocRequest('clojure', ........` and not `CocRequest('clojure-lsp', ......`)

Doing that gets a step further, but then I observe a stack trace:

```
2021-07-28T10:31:22.025 ERROR (pid:148481) [attach] - Request error: sendRequest [
  'clojure',
  'clojure/dependencyContents',
  {
    uri: 'jar:file:///home/david/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar!/clojure/string.clj'
  }
] ag [Error]: Internal error.
    at $l (/home/david/.env/vim/bundle/coc.nvim/build/index.js:36:224)
    at Kh (/home/david/.env/vim/bundle/coc.nvim/build/index.js:35:11261)
    at Immediate.<anonymous> (/home/david/.env/vim/bundle/coc.nvim/build/index.js:35:11111)
    at processImmediate (node:internal/timers:464:21) {
  code: -32603,
  data: 'java.lang.RuntimeException: java.lang.reflect.InvocationTargetException\n' +
    '\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)\n' +
    '\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)\n' +
    '\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)\n' +
    '\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)\n' +
    '\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)\n' +
    '\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)\n' +
    '\tat org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)\n' +
    '\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n' +
    '\tat java.util.concurrent.FutureTask.run(FutureTask.java:264)\n' +
    '\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n' +
    '\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n' +
    '\tat java.lang.Thread.run(Thread.java:829)\n' +
    '\tat com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)\n' +
    '\tat com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)\n' +
    'Caused by: java.lang.reflect.InvocationTargetException\n' +
    '\tat java.lang.reflect.Method.invoke(Method.java:566)\n' +
    '\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)\n' +
    '\t... 13 more\n' +
    "Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #'clojure-lsp.main/extension\n" +
    '\tat clojure.lang.Var$Unbound.throwArity(Var.java:45)\n' +
    '\tat clojure.lang.AFn.invoke(AFn.java:36)\n' +
    '\tat clojure.lang.Var.invoke(Var.java:388)\n' +
    '\tat clojure_lsp.ClojureExtensions.dependencyContents(ClojureExtensions.java:26)\n' +
    '\t... 15 more\n'
```

**Comment by ericdallo** [comment]
@dharrigan we had some changes on namespaces, before it was clojure-lsp.main/extension but now is clojure-lsp.server/extension.
I have no ideas why the com client calls that directly and why that change broke vim though

**Comment by ericdallo** [comment]
I'm not sure why that works for all other clients but vim, WDYT about the PR @LuisThiamNye ?

**Comment by dharrigan** [comment]
Hi,

I don't think it was vim related, simply that was manifested as I use vim. I've done a patch, and tested on my local clone and it appears to have resolved it. Thoughts on the patch?

-=david=-

**Comment by LuisThiamNye** [comment]
This, with the escaping, is not a valid URI:
`jar:file%3A///home/david/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar%21/clojure/string.clj`

- https://en.wikipedia.org/wiki/Uniform_Resource_Identifier
- https://docs.oracle.com/javase/7/docs/api/java/net/JarURLConnection.html

I do not understand why there should be escaping in those places, and it is confusing that only the second colon is escaped. Escaping should only be used in the contents of the path so that there isn't ambiguity in how the URI string is interpreted. (Paths may contain exotic characters like `!` which should be encoded to not cause confusion with an unencoded `!/` delimiter.)

For these reasons, I think the client should be responsible for sending correct URIs to avoid confusion.

**Comment by ericdallo** [comment]
@dharrigan I'd like to understand here why the current behavior works for emacs/vscode and not for vim, I suspect clients are sending different URI patterns.
Could you share the `textDocument/definition request`? in your logs it seems it only contains the response one.

mine on emacs is:
```json
...
[Trace - 10:26:15 AM] Sending request 'textDocument/definition - (138)'.
Params: {
  "textDocument": {
    "uri": "file:///home/greg/dev/clojure-lsp/src/clojure_lsp/shared.clj"
  },
  "position": {
    "line": 99,
    "character": 21
  }
}


[Trace - 10:26:15 AM] Received response 'textDocument/definition - (138)' in 63ms.
Result: {
  "uri": "jar:file:///home/greg/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar!/clojure/string.clj",
  "range": {
    "start": {
      "line": 359,
      "character": 6
    },
    "end": {
      "line": 359,
      "character": 18
    }
  }
}


[Trace - 10:26:15 AM] Sending request 'clojure/dependencyContents - (139)'.
Params: {
  "uri": "jar:file:///home/greg/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar!/clojure/string.clj"
}
...
```

**Comment by dharrigan** [comment]
Hi,

This is on the unpatched, released version (I've truncated it a bit, in order to not to show all of the clojure core source code):

```
[Trace - 15:03:43] Sending request 'textDocument/definition - (7)'.
Params: {
    "textDocument": {
        "uri": "file:///home/david/tmp/baz/src/foo/bar/baz.clj"
    },
    "position": {
        "line": 7,
        "character": 14
    }
}


[Trace - 15:03:43] Received response 'textDocument/definition - (7)' in 4ms.
Result: {
    "uri": "jar:file:///home/david/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar!/clojure/string.clj",
    "range": {
        "start": {
            "line": 212,
            "character": 14
        },
        "end": {
            "line": 212,
            "character": 24
        }
    }
}


[Trace - 15:03:43] Sending request 'clojure/dependencyContents - (8)'.
Params: {
    "uri": "jar:file:///home/david/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar!/clojure/string.clj"
}


[Trace - 15:03:43] Received response 'clojure/dependencyContents - (8)' in 2ms.
Result: ";   Copyright (c) Rich Hickey. All rights reserved.\n;   
```

**Comment by ericdallo** [comment]
It looks the same to me, I wonder what is the difference between the clients, @LuisThiamNye any thoughts?

**Comment by ericdallo** [comment]
@dharrigan are you using `:dependency-scheme "jar"` or `:dependency-scheme "zipfile"` ?

**Comment by dharrigan** [comment]
jar.

**Comment by ericdallo** [comment]
We can see from the exceptions that it's happening for a lot of features, semantic-tokens, code-lens, document-highlighting

**Comment by ericdallo** [comment]
so the issue is not in definition @dharrigan, that is the only that is correct, the issue is the other requests sending as escaped already

**Comment by dharrigan** [comment]
Indeed, if I look at an example for the codeLens:

```
[Trace - 15:26:45] Sending request 'textDocument/codeLens - (9)'.
Params: {
    "textDocument": {
        "uri": "jar:file%3A///home/david/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar%21/clojure/string.clj"
    }
}


[Trace - 15:26:45] Received response 'textDocument/codeLens - (9)' in 2ms.
No result returned.
```

It's sending to clojure-lsp the escaped uri.

**Comment by ericdallo** [comment]
yeah, so unfortunately it seems to be a wrong uri sent from vim client

**Comment by dharrigan** [comment]
Hi,

Maybe so, but wouldn't it be okay to add in that patch, since the code itself looks to see if the URI start with a `jar:` schema first? In order to understand why, potentially, the client is sending the escaped URL, will require some investigation first. The patch could be removed at a later point?

**Comment by dharrigan** [comment]
Hi,

Been looking through CoC and the relevant sections of the spec,as detailed here:

https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#documentUri

I believe CoC is parsing the URI, then sending it out encoded using the node module `vscode-uri`. This causes the string to be encoded, i.e.,

```
❯ cat index.mjs
import pkg from 'vscode-uri';
const { URI } = pkg;
let uri = URI.parse("jar:file:///home/greg/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar!/clojure/string.clj")
console.log(uri.toString())
```

```
❯ node index.mjs
jar:file%3A///home/greg/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar%21/clojure/string.clj
```

**Comment by LuisThiamNye** [comment]
> Yeah, it could work, I have a little concern about that affect other features or other editors that already work following the URI spec.

As for other editors, people would probably not notice. However, it might leave Vim with some weird issues as `filename->uri` would give a result inconsistent with what is passed to `uri->filename` — and I think URIs are used by clojure-lsp as a unique identifier.

> I believe CoC is parsing the URI, then sending it out encoded using the node module vscode-uri.

Oh dear. vscode-uri has caused problems with Calva as well in the past due to the way it encodes URIs. If it is really not an option for the client to use something else, we might need to implement some more special snowflake settings ([like these](https://github.com/clojure-lsp/clojure-lsp/blob/bb1af97b6c5ca2b0d726f41d3696858c140a403a/src/clojure_lsp/crawler.clj#L268-L271)) so that clojure-lsp can handle these URIs — not ideal. 🤔

**Comment by dharrigan** [comment]
Hi,

Just looking through the codebase of CoC, and I can see at line https://github.com/neoclide/coc.nvim/blob/5aa3197360a76200e8beb30c9957fac1205b7ad5/src/model/document.ts#L203 it initialises itself, and the block of code it invokes does a parse (starting from https://github.com/neoclide/coc.nvim/blob/5aa3197360a76200e8beb30c9957fac1205b7ad5/src/util/index.ts#L36).

This suggests to me, that every URI will be send out encoded as part of the request to the LSP, thus escaping the appropriate characters.

**Comment by ericdallo** [comment]
maybe @bpringe can help here, how Calva handles/send URIs to clojure-lsp? does it uses vscode-uri or something else?

**Comment by dharrigan** [comment]
After speaking with @ericdallo a bit of I'm going to rework my patch a bit to use java 11 URLDecoder inside a function with a try...catch. Using URLDecoer will probably a lot better than my attempt :-)

If any errors occurs, then it'll log the error and simply return the string as-is.

I'll work on that shortly.

**Comment by ericdallo** [comment]
yeah, this makes it safer for existent clients and fixes it when it comes escaped.
I don't think we will have any issues with uniqueness as we use the filename from clj-kondo most of the time

**Comment by bpringe** [comment]
I'm not sure about what the client library does to URIs before sending requests, but in some places where we manually send a request to clojure-lsp, we call `decodeURIComponent`. IIRC, I did that to fix an issue we had with URIs.

 Example: https://github.com/BetterThanTomorrow/calva/blob/5b2d1d7d43f62376c16f46765be7056a92a9504c/src/lsp/main.ts#L230
