### ISSUE TITLE
Semantic Highlighting - is it vim issue?

### ISSUE THREAD

**Issue by dharrigan** [clojure-lsp/clojure-lsp#495]
Hi,

I've put together a very simple project showing semantic highlighting not working. I don't know if this is only a vim + coc issue.

Here's a link to the log:

* https://github.com/dharrigan/semantic-tokens/blob/master/semantic-tokens-log.txt

And here's an image of it not working

![Image showing no highlighting](https://github.com/dharrigan/semantic-tokens/blob/master/semantic-tokens.png)

-=david=-

**Comment by ericdallo** [comment]
Thanks for the report!
So, it seems a vim issue or something wrong with your vim theme?
We can see from the logs that clojure-lsp is returning an array of integers for the semantic tokens, let's get the first 25 elements and analyze them:
```
[5, 1, 4, 2, -1,
 1, 3, 7, 5, -1,
 1, 3, 7, 1, -1
 0, 9, 1, 0, -1,
 0, 2, 10, 1, -1,
 ...]
```
It follows a pattern to know what to collor, lets get the first 5 elements: 
- `5` - means count 5 lines from last token (starts at top)
- `1` - means count 1 character from the last token (starts at top)
- `4` - means the lengh of the token, which is `defn` in your code.
- `2` - means which token index will be applied following the tokens the server responded before in the initialized response, in this case `macro`
- `-1` not important for clojure, and optional.

so the first line will color the first `defn` as a `macro` which makes sense.

following the other lines, we will have:
- token `message` as a `variable`.
- token `println` as `function`
- token `s` as `type`
- token `lower-case` as `function`

Everything seems correct from the server point of view, probably vim :
- is not applying the tokens
- or is applying only specific tokens
- or some tokens for your theme are colored as white?

The best way is to debug on vim side what color is being used

**Comment by dharrigan** [comment]
Hello,

Yup, a Coc (Vim) issue:

I've done some more digging and semantic highlighting is now disabled by default, *at a CoC level*, unless it is switched back on again :facepalm: 

Here is the relevant commit:

https://github.com/neoclide/coc.nvim/commit/76f407d45640aeadc97a555eac0939217d0dd662

And thus, to enable semantic highlighing again, whack this beauty into your vim config:

`let g:coc_default_semantic_highlight_groups = 1`

Then all will be well with the world.

-=david=-
