### ISSUE TITLE
Option to disable source on hover?

### ISSUE THREAD

**Issue by knubie** [clojure-lsp/clojure-lsp#498]
**Is your feature request related to a problem? Please describe.**
When using the hover feature in neovim, the source displayed at the bottom is usually not very useful and adds a lot of noise:
<img width="968" alt="Screen Shot 2021-07-31 at 11 03 44 AM" src="https://user-images.githubusercontent.com/431251/127744244-01405b57-2a05-4606-947e-b8becc482884.png">

**Describe the solution you'd like**
It would be nice to have an option to remove the source URL at the bottom.

**Describe alternatives you've considered**
Using vim's conceal feature to hide the source URL.

**Additional context**

**Comment by ericdallo** [comment]
I think neo vim should show only the file location, not the link location as well, is this using correct markdown?

**Comment by ericdallo** [comment]
c/c @NoahTheDuke

**Comment by knubie** [comment]
Even the link text by itself would still be pretty noisy.

**Comment by ericdallo** [comment]
We can add a flag to disable it

**Comment by knubie** [comment]
Awesome, thank you!
