### ISSUE TITLE
Unable to navigate to CLJS files from CLJC files within a jar

### ISSUE THREAD

**Issue by p-himik** [clojure-lsp/clojure-lsp#509]
**Describe the bug**
Calva with clojure-lsp always navigates to a symbol inside a CLJ file even if the context suggests that there's such a symbol in a CLJS file as well.

**To Reproduce**
1. Add `quil "3.1.0"` to your project's dependencies
2. Create a new `.cljs` file and add `(:require [quil.core])` in there
3. Navigate to the definition of `quil.core`
4. Notice that the `quil/core.cljc` file has `quil.sketch` in both `:clj` and `:cljs` branches
5. Navigate to `quil.sketch` in the `:clj` branch and confirm that it opens `quil/sketch.clj`
6. Navigate to `quil.sketch` in the `:cljs` branch and see how it still opens the `.clj` file instead of the `.cljs` one

**Expected behavior**
`quil/sketch.cljs` should have been opened.

No new log entries appear when navigating to the mentioned namespaces, even though the trace level is set to verbose.

**User details (please complete the following information):**
 - OS: Ubuntu 20.04
 - Editor: VSCode (Calva)
 - Version: Calva says "latest", so I assume it's 2021.08.05-19.36.09

**Comment by ericdallo** [comment]
thank you for the report!
I found that clojure-lsp is using the filename of the current file always instead of checking if that element analysis has a `:lang`, I'll try to check this later today

**Comment by ericdallo** [comment]
Fixed on master! it should be availalbe on next release. In case you want to try, you can clone this repo and `make` to generate a `clojure-lsp` binary.
