### ISSUE TITLE
Stale unused var warnings when the file is deleted

### ISSUE THREAD

**Issue by introom** [clojure-lsp/clojure-lsp#513]
I’ve a file containing unused vars. Now I deleted the file, but lsp (calva) still shows the problems in the problems tab.

**Comment by ericdallo** [comment]
we probably need to return empty diagnostics when a didClose is sent and the file is not available anymore, I'll take a look soon

**Comment by ericdallo** [comment]
Fixed on master, available on next release!

**Comment by introom** [comment]
Thanks for the efforts!
