### ISSUE TITLE
Question: Completion with neovim+nvim-lsp + compe.nvim + clojure-lsp

### ISSUE THREAD

**Issue by thecontinium** [clojure-lsp/clojure-lsp#517]
Hi

I am using a combination of plugins with neovim using the native lsp client and autocompletion with nvim-compe

This works well with a number of different lsp servers but I am seeing some strange behaviour when using with clojure-lsp.

I am not sure where the problem is ( in neovim or plugin or clojure-lsp ) and am trying to debug the issue.

The completion problem occurs when I start the line with a bracket "(". Not ideal with a lisp :)

This is the behaviour I see.

1. I am looking at the clojure-lsp debug and see that on typing "(p" a :completion is logged but on the client the completion "flashes" up and then disappears. 
2. There are no completions from any sources e.g. conjure or buffer
3. If I disable clojure-lsp as a source other sources work with "(p"
4. If I type "p" alone ( or any other combination ) I get a list of completions to choose from all sources including clojure-lsp
5. I have tried the same combination with other lsp clients typing "(p" and I don't have any issues.

Can you advise on how I might get more debug information from clojure-lsp to see the interaction between neovim and clojure-lsp in more detail ?

Any other advice welcome.

Cheers

**Comment by ericdallo** [comment]
We need to understand if the issue is on client or server side, could you try to get the client<->server json log?

This log should be available somehow from your LSP client, I don't know anything about vim though

We seek here the response of `completion` request.

**Comment by ericdallo** [comment]
Also, feel free to add an entry for nvim client here with the proper link on how to get that log: https://clojure-lsp.github.io/clojure-lsp/troubleshooting/#client-server-log

**Comment by thecontinium** [comment]
Thanks.

Once I have things up and running I'll give a description of the setup I am using with settings etc.
The problem seems to be something to do with the snippets.
If I disable the snippets capabilities at setup for clojure-lsp then all works as expected.
I suspect this is something on the client.

**Comment by ericdallo** [comment]
Hum, yeah, you can double-check if there is no exception from server checking the [server logs](https://clojure-lsp.github.io/clojure-lsp/troubleshooting/#server-log)

**Comment by thecontinium** [comment]
For those of you who find there way here. This is now fixed in the update nvim-cmp [here](https://github.com/hrsh7th/nvim-cmp/issues/191)
