### ISSUE TITLE
Report as unused public var if the function was self referred only

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#531]
The same issue clj-kondo had on private-vars, but for public ones: https://github.com/clj-kondo/clj-kondo/issues/1367

**Comment by ericdallo** [comment]
@borkdude It seems it's not possible for clojure-lsp use this same logic for unused-public-vars as the analysis don't provide a :in-def or something like that.

**Comment by ericdallo** [comment]
@borkdude after a lot of debugging, I realized that is not possible for clojure-lsp to add this logic unless we change to have some way to know that a var-usage is a var-usage of a defrecord.

Let me explain, clojure-lsp ATM includes the var-definition on find-references if `(not (identical? :var-definitions (:bucket %)))` [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/queries.clj#L192). if we introduce this logic to not include the reference if the `:from-var` == `:name` we will have to drop that clause since it's a var-usage, breaking the references for defrecord.
Therefore I think the best approach here is to clj-kondo return some flag indicating that var-usage is a usage of a defrecord, this way I can change the current clause to check this new flag and then later introduce this change.
WDYT?

**Comment by ericdallo** [comment]
If clj-kondo adds a `:defined-by 'clojure.core/defrecord` or something to the :var-usage of the defrecord, __not only the var-definition__, I think this code added [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/queries.clj#L191-L193) on clojure-lsp would work:
```clojure
(filter #(or include-declaration?
             (and (not (identical? :var-definitions (:bucket %)))
                  (= 'clojure.core/defrecord (:defined-by %)))
             (= (:from-var %) (:name element))
             (= (:defined-by %) 'clojure.core/declare)))
```

**Comment by borkdude** [comment]
> Therefore I think the best approach here is to clj-kondo return some flag indicating that var-usage is a usage of a defrecord

You already have this information available in `:var-definitions` right?

**Comment by ericdallo** [comment]
You are right @borkdude I thought it would be a bad performance search for the var-definition every time but I found a way to just find one time, I think everything is good for this feature indeed :)

**Comment by borkdude** [comment]
@ericdallo Btw, I think we could leave out some data in the analysis: the var usages copy some of the fields of var-definitions (because 2 years ago I thought this would be "easier") but this results in more data than necessary. We could strip that data if it helps performance, using some option.

**Comment by ericdallo** [comment]
Sure, sounds good, do you have the fields that would go away so I can check clojure-lsp, also it'd be good to do a performance test if that changed anything.

**Comment by borkdude** [comment]
All of this:

```
Optional:

:arity: if the usage was a function call, the amount of arguments passed
:lang: if usage occurred in a .cljc file, the language in which the call was resolved: :clj or :cljs
several attributes of the used var: :private, :macro, :fixed-arities, :varargs-min-arity, :deprecated.
```

We can just not put that on the var usages as its just more data.

**Comment by ericdallo** [comment]
I see, some of them like `deprecated` and `macro` seems a good idea to me keep it as clojure-lsp adds different colors when checking those attrs, and avoid the need to find the definition for those cases seems a performance improvement to me, but others like arity ones seem not useful. 
We actually need to check if it's a good tradeoff remove those fields to have less data and when we need that data we find the definition and check if worth it
