### ISSUE TITLE
Error initializing lsp server in latest version 2021.08.24-14.41.56

### ISSUE THREAD

**Issue by scotts777** [clojure-lsp/clojure-lsp#537]
**Describe the bug**
When LSP client is starting the clojure-lsp server and calls the initialize method, the server fails with an error in the .out log
"clojure.lang.Keyword cannot be cast to java.lang.String".  Works fine in previous version  2021.08.05-19.36.09.  See full exception from log below.  

**To Reproduce**
run lsp client against the two different versions.

clojure trace logging:

[Trace - 09:05:26 AM] Sending request 'initialize - (1)'
Params: {
  "processId": null,
  "rootUri": "file:///C:/Users/Scott/Projects/Clojure/niofiles/",
  "initializationOptions": {
    "source-paths": [
      "cljsrc",
      "src",
      "test"
    ],
    "project-specs": [
      {
        "project-path": "deps.edn",
        "classpath-cmd": [
          "C:\\Users\\Scott\\scoop\\apps\\pwsh\\current\\pwsh.exe",
          "-Command",
          "clojure",
          "-Spath"
        ]
      }
    ]
  }
----------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------
clojure-lsp logging:

`INFO [clojure-lsp.source-paths:133] - Using given source-paths: #{:src :cljsrc :test}
ERROR [clojure-lsp.server:?] - 
                                   [37mcom.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine[m  [32m        WindowsJavaThreads.java:  138[m
                                             [37mcom.oracle.svm.core.thread.JavaThreads.threadStartRoutine[m  [32m               JavaThreads.java:  553[m
                                                                                  [37mjava.lang.Thread.run[m  [32m                    Thread.java:  829[m
                                                    [37mjava.util.concurrent.ThreadPoolExecutor$Worker.run[m  [32m        ThreadPoolExecutor.java:  628[m
                                                     [37mjava.util.concurrent.ThreadPoolExecutor.runWorker[m  [32m        ThreadPoolExecutor.java: 1128[m
                                                                   [37mjava.util.concurrent.FutureTask.run[m  [32m                FutureTask.java:  264[m
                                                   [37mjava.util.concurrent.Executors$RunnableAdapter.call[m  [32m                 Executors.java:  515[m
                                         [37morg.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run[m  [32mConcurrentMessageProcessor.java:  113[m
                                           [37morg.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen[m  [32m     StreamMessageProducer.java:   94[m
                                    [37morg.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage[m  [32m     StreamMessageProducer.java:  194[m
                                                      [37morg.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume[m  [32m            RemoteEndpoint.java:  190[m
                                                [37morg.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest[m  [32m            RemoteEndpoint.java:  261[m
                                            [37morg.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request[m  [32m           GenericEndpoint.java:  120[m
                                      [37morg.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0[m  [32m           GenericEndpoint.java:   65[m
                                                                                                   [37m...[m  [32m                                     [m
[37mclojure_lsp.server.proxy$clojure_lsp.ClojureExtensions$ExtraMethods$LanguageServer$4129860f.initialize[m  [32m                                     [m
                                                                              [33mclojure-lsp.server/fn/[1;33mfn[m  [32m                     server.clj:  305[m
                                                                       [33mclojure-lsp.handlers/[1;33minitialize[m  [32m                   handlers.clj:   49[m
                                                                [33mclojure-lsp.crawler/[1;33minitialize-project[m  [32m                    crawler.clj:  157[m
                                                                                   [33mclojure.core/[1;33mupdate[m  [32m                       core.clj: 6185[m
                                                                               [33mclojure.core/partial/[1;33mfn[m  [32m                       core.clj: 2635[m
                                                         [33mclojure-lsp.source-paths/[1;33mprocess-source-paths[m  [32m               source_paths.clj:  141[m
                                                                                     [33mclojure.core/[1;33mmapv[m  [32m                       core.clj: 6905[m
                                                                                   [33mclojure.core/[1;33mreduce[m  [32m                       core.clj: 6830[m
                                                                           [33mclojure.core.protocols/fn/[1;33mG[m  [32m                  protocols.clj:   13[m
                                                                             [33mclojure.core.protocols/[1;33mfn[m  [32m                  protocols.clj:   75[m
                                                                    [33mclojure.core.protocols/[1;33miter-reduce[m  [32m                  protocols.clj:   49[m
                                                                                  [33mclojure.core/mapv/[1;33mfn[m  [32m                       core.clj: 6914[m
                                                      [33mclojure-lsp.source-paths/process-source-paths/[1;33mfn[m  [32m               source_paths.clj:  141[m
                                                                            [33mclojure-lsp.shared/[1;33mto-file[m  [32m                     shared.clj:  251[m
[1;31mjava.lang.ClassCastException[m: [3mclojure.lang.Keyword cannot be cast to java.lang.String[m`

**User details (please complete the following information):**
 - OS:Windows 10
 - Version: 2021.08.24-14.41.56

**Comment by ericdallo** [comment]
Thanks for the report!

Could you paste you project.clj, deps.edn, bb.edn or shadow-cljs.edn?

**Comment by scotts777** [comment]
deps.edn

`{:paths ["cljsrc" "javaclasses" "resources"]
 :deps {org.clojure/clojure {:mvn/version "1.10.3"}}
 :aliases
 {:test
  {:extra-paths ["test"]
   :extra-deps {org.clojure/test.check {:mvn/version "1.1.0"}
                io.github.cognitect-labs/test-runner
                {:git/url "https://github.com/cognitect-labs/test-runner"
                 :sha "62ef1de18e076903374306060ac0e8a752e57c86"}}
   :exec-fn cognitect.test-runner.api/test}
  :jar {:replace-deps {com.github.seancorfield/depstar {:mvn/version "2.1.278"}}
        :exec-fn hf.depstar/jar
        :exec-args {:jar "niofiles.jar" :sync-pom true}}
  :install {:replace-deps {slipset/deps-deploy {:mvn/version "0.1.5"}}
            :exec-fn deps-deploy.deps-deploy/deploy
            :exec-args {:installer :local :artifact "niofiles.jar"}}
  :deploy {:replace-deps {slipset/deps-deploy {:mvn/version "0.1.5"}}
           :exec-fn deps-deploy.deps-deploy/deploy
           :exec-args {:installer :remote :artifact "niofiles.jar"}}}}`

**Comment by scotts777** [comment]
I do have a config.edn is the project's .lsp directory

{
 :log-path "C:\\Users\\Scott\\clj-lsp.out"
 :auto-add-ns-to-new-files? false
 :project-specs [{:project-path "deps.edn"
                  :classpath-cmd ["C:\\Users\\Scott.E.Suler\\scoop\\apps\\pwsh\\current\\pwsh.exe" "-Command" "clojure" "-Spath"]}]}

**Comment by ericdallo** [comment]
I can't repro the issue with the provided deps.edn, could you create a minimal project in a repository where the error happens?

**Comment by scotts777** [comment]
yes I will try to create a shareable minimal project.  This one is pretty minimal as however for work reasons I can't share it.  Is there a way to make the log more legible?  that is basically be created by item in the config.edn file inside the projects .lsp directory.  Is there a pretty print of something?  no matter how i view it (notepad, notepad++ vscode) , it is messy like that

**Comment by ericdallo** [comment]
Probably a cat/vim int he log file would be better, otherwise it's something windows probably is messing up :/

**Comment by ericdallo** [comment]
Also, I wonder why you have a custom `project-specs`, the default one doesn't work for you? something we could improve in clojure-lsp for windows?

**Comment by scotts777** [comment]
So because the case program is already so simple, I started looking at this by putting some log messages where the Exception is pointing to.  The error is occurring in shared.clj in the function `to-file`.  the shared/to-file function is being called from `source-paths.clj` from the `process-source-paths` function.

I put in a bunch of log/infos in the `process-source-paths` function so it looks like this
```clojure
(defn process-source-paths [root-path settings settings-source-paths]
  (log/info "source-paths/process-source-path root-path:"  root-path)
  (log/info "source-paths/process-source-path settings:"  settings)
  (log/info "source-paths/process-source-path settings-source-paths:"  settings-source-paths)
  (let [{:keys [origins source-paths deps-source-paths lein-source-paths bb-source-paths] :as key-paths} (resolve-source-paths root-path settings settings-source-paths)]
    (log/info "source-paths/process-source-path"  key-paths)
    (condp set/subset? origins
      #{:settings} (log/info "Using given source-paths:" settings-source-paths)
      #{:deps-edn} (log/info "Automatically resolved source-paths from deps.edn:" deps-source-paths)
      #{:leiningen} (log/info "Automatically resolved source-paths from project.clj:" lein-source-paths)
      #{:bb} (log/info "Automatically resolved source-paths from bb.edn:" bb-source-paths)
      #{:empty-deps-edn} (log/info "Empty deps.edn source-paths, using default source-paths:" default-source-paths)
      #{:empty-leinigen} (log/info "Empty project.clj source-paths, using default source-paths:" default-source-paths)
      #{:empty-bb} (log/info "Empty bb.edn paths, using default source-paths:" default-source-paths)
      #{:default} (log/info "Using default source-paths:" default-source-paths))
    (mapv #(->> % (shared/to-file root-path) .getAbsolutePath str) source-paths)))
```

and one in the shared/to-file function :
```clojure
(defn to-file ^java.io.File
  [^java.nio.file.Path path
   ^String child]
  (log/info "Inside shared/to-file: path:" path " child:" child)
  (.toFile (.resolve path child)))
```

this resulted in this output in the log file:
2021-09-02T02:40:34.072Z APGRW4G8AAWNC28 INFO [clojure-lsp.server:304] - Initializing...
2021-09-02T02:40:34.099Z APGRW4G8AAWNC28 INFO [clojure-lsp.source-paths:131] - source-paths/process-source-path root-path: C:\Users\Scott\Projects\Clojure\niofiles
2021-09-02T02:40:34.101Z APGRW4G8AAWNC28 INFO [clojure-lsp.source-paths:132] - source-paths/process-source-path settings: {:source-aliases nil, :uri-format {:upper-case-drive-letter? true, :encode-colons-in-path? false}, :document-formatting? true, :source-paths #{:src :cljsrc :test}, :text-document-sync-kind nil, :project-specs [{:project-path "deps.edn", :classpath-cmd ["C:\\Users\\Scott\\scoop\\apps\\pwsh\\current\\pwsh.exe" "-Command" "clojure" "-Spath"]}], :dependency-scheme "zipfile", :document-range-formatting? true, :cljfmt {:indents {}}}
2021-09-02T02:40:34.108Z APGRW4G8AAWNC28 INFO [clojure-lsp.source-paths:133] - source-paths/process-source-path settings-source-paths: #{:src :cljsrc :test}
2021-09-02T02:40:34.109Z APGRW4G8AAWNC28 INFO [clojure-lsp.source-paths:135] - source-paths/process-source-path {:source-paths #{:src :cljsrc :test}, :origins #{:settings}}
2021-09-02T02:40:34.111Z APGRW4G8AAWNC28 INFO [clojure-lsp.source-paths:137] - Using given source-paths: #{:src :cljsrc :test}
2021-09-02T02:40:34.112Z APGRW4G8AAWNC28 INFO [clojure-lsp.shared:266] - Inside shared/to-file: path: C:\Users\Scott\Projects\Clojure\niofiles  child: **:src**

It looks like the `to-file's` type hint of **^String** is failing to cast the keyword **:src** to a String type.  I verified this behavior pulling out that function and testing it like this:

```clojure
(defn to-file ^java.io.File
  [^java.nio.file.Path path
   ^String child]
  (.toFile (.resolve path child)))
  
  (to-file (Paths/get "C:\\Users\\Scott" (into-array String [])) :Projects)
```
results in same exception: **clojure.lang.Keyword cannot be cast to java.lang.String**

I haven't been able to trace back further of why the `source-paths` are a vector of keyword instead of String.  Maybe it is a Windows issue?  or something with me using Eclipse org.eclipse.lsp4j as my client?  Although the trace logging shows lsp4j sending the initialization options as json and string values for the source paths.

Tomorrow I will trace further back unless you have some ideas of why keywords are being passed to that function

**Comment by ericdallo** [comment]
thanks for the debug! The input to that function really must be a string not a keyword so we need to pas correctly the string.
We had a recent change where we keywordize some params from initializationOptions, maybe @NoahTheDuke can help with that?

**Comment by scotts777** [comment]
I will give that a try Eric.  Thanks

**Comment by ericdallo** [comment]
@scotts777 it's a bug, https://github.com/clojure-lsp/clojure-lsp/pull/540 should fix it
