### ISSUE TITLE
`:clojure-lsp/unused-public-var` breaks with "No matching clause: `:off`"

### ISSUE THREAD

**Issue by simonacca** [clojure-lsp/clojure-lsp#546]
**Describe the bug**

Whenever the `:clojure-lsp/unused public-var` linter is disabled by setting `{:level :off}`, some LSP features don't work anymore in Calva.

**To Reproduce**
1. Open vscode with calva
2. Write some clojure with an issue, for example `unresolved-symbol`
3. set `$YOURPROJECT/.clj-kondo/config.edn`
4. show "problems" view. ctrl-p -> "focus on problems view"
6. observe that the "problems" pane contains the problem

Now for the problem: 

1. set `$YOURPROJECT/.clj-kondo/config.edn` to `{:linters {:clojure-lsp/unused-public-var {:level :off}}}` as per [the docs](https://clojure-lsp.io/settings/#clojure-lspunused-public-var)
2. Reload the editor ctrl-p -> "reload window"
3. show "problems" view. ctrl-p -> "focus on problems view"
4. observe that the "problems" pane is empty

**Expected behavior**
In both cases the issue should show in the "problems" pane (provided that the issue is not a `unused-public-var` of course).

**Screenshots**
![image](https://user-images.githubusercontent.com/1206381/132255621-986c1d2a-f9c6-4dab-8f71-4ddddd37eaa9.png)

**Config details**

- [Working config](https://gist.github.com/simonacca/dc92adf6e8768beea5c0e6ad830e9706)
- [Broken config](https://gist.github.com/simonacca/06badc8982b79185f3f94df9b4acacbe)

I imagine the issue could be related to `IllegalArgumentException: No matching clause: :off` in the 2nd log.

Note that cleaning up lsp's and kondo's caches does not affect the issue.

**User details (please complete the following information):**
 - OS: Ubuntu 20.10
 - Editor VSCode (Calva) v1.60.0
 - Version: 2021.09.04-17.11.44

Thanks for looking into this!

**Comment by ericdallo** [comment]
Thanks for the report, I'll try to repro this

**Comment by ericdallo** [comment]
@simonacca thank you for the detailed repro, but unfortunately I can't repo the issue :/
I do see that exception though from clojure-lsp log and I will fix it for the next release, maybe the could be related to this issue on Calva somehow

**Comment by ericdallo** [comment]
@simonacca I fixed the exception, maybe this should fix your issue as well? 

Could you test the clojure-lsp master? to generate a dev release you just need to run `make` on the repo root and then make calva use the generated `clojure-lsp` binary instead of the one it has built-in, there is a calva setting for that.

**Comment by simonacca** [comment]
@ericdallo I can confirm that the issue is solved in master!

Thank you for the incredibly prompt resolution :)
