### ISSUE TITLE
Cannot navigate into JARS in Sublime Text, opens browser instead

### ISSUE THREAD

**Issue by askonomm** [clojure-lsp/clojure-lsp#547]
**Describe the bug**
Whenever I hover over a function or package that isn't in my own project (e.g any external dependency), I get a popup with a path to the function inside of a JAR. Clicking on that link will however prompt to open the path in the browser, where it obviously fails to open it, because it is inside of a JAR. Worth mentioning that it attempts to load the file with a http://zipfile/// prefix, which I'm not sure if is Clojure LSP doing it or Sublime LSP.

Go to definition to that function also doesn't work, with Sublime instead prompting a "Unable to open URI". Thus, navigating to any dependency is not possible.

**To Reproduce**
1. Open any Clojure file with dependencies in Sublime Text
2. Try to go-to-definition or click on the path in the popup

**Expected behavior**
I expect it would open the correct file in Sublime Text, and scroll to the correct function.

**Screenshots**
<img width="731" alt="Screen Shot 2021-09-09 at 00 15 58" src="https://user-images.githubusercontent.com/84135165/132616920-7bc9875d-2641-462e-ae53-33232aefb381.png">
<img width="312" alt="Screen Shot 2021-09-09 at 00 18 27" src="https://user-images.githubusercontent.com/84135165/132616927-3fabebf5-e7fb-4f0d-b500-60e30f13bdba.png">

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
ADD JSON HERE
</pre>
</details>

<details>
 <summary><b>Log - clojure-lsp</b></summary>
<pre>
error: Unable to open URI
</pre>
</details>

**User details (please complete the following information):**
 - OS: MacOS
 - Editor Sublime Text 4
 - Version: clojure-lsp 2021.08.24-14.41.56, clj-kondo 2021.08.07-SNAPSHOT

**Additional context**

**Comment by askonomm** [comment]
I managed to stumble upon [this (abandoned) pull request in Sublime LSP](https://github.com/sublimelsp/LSP/pull/1711) where it seems to also attempt to fix a pretty similar issue, but where the discussion seems to suggest that it is not the fault of Sublime LSP, but rather the Language LSP. I'm not sure where the issue really is, but thought it might be useful to point this out as well.

**Comment by ericdallo** [comment]
@askonomm there is a flag that some editors pass like `emacs`, `vscode` but other doesn't pass like `vim` that should make that work, is the `:dependency-scheme`, check the [docs](dependency-scheme), passing a `:jar` should probably solve your issue. if so, the best would be to make the sublime-text client send that flag enabled for clojure-lsp, just like lsp-mode does [here](https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-clojure.el#L303)

**Comment by askonomm** [comment]
@ericdallo It seems to work in that it changes the URL prefix to `http://jar:file:///`, but still opens in the browser where it fails to actually open, and go-to-definition still says "Unable to open URI". But what you are saying is, it is probably the fault of Sublime LSP then, right? In that case I can continue this conversation in Sublime LSP's repo instead.

**Comment by ericdallo** [comment]
oh, `http://jar:file:///`it's indeed wrong, it should be `file://jar:file:///`. can you confirm server is returning correct?

**Comment by askonomm** [comment]
This may seem like a stupid question, but how do I confirm that?

**Comment by ericdallo** [comment]
This should help: https://clojure-lsp.io/troubleshooting/#client-server-log

**Comment by askonomm** [comment]
The log output when trying to go-to-definition of a function in a dependency is this:

```
--> clojure-lsp textDocument/definition(3): {'position': {'character': 22, 'line': 55}, 'textDocument': {'uri': 'file:///Users/asko/Documents/Projects/babe/src/babe/utils.clj'}, 'workDoneToken': 'wd3'}
:: <<< clojure-lsp 3: {'uri': 'jar:file:///Users/asko/.m2/repository/markdown-clj/markdown-clj/1.10.6/markdown-clj-1.10.6.jar!/markdown/core.clj', 'range': {'end': {'character': 23, 'line': 124}, 'start': {'character': 6, 'line': 124}}}
```

The log output when trying to navigate to a namespace in a dependency:

```
 --> clojure-lsp textDocument/definition(22): {'position': {'character': 24, 'line': 4}, 'textDocument': {'uri': 'file:///Users/asko/Documents/Projects/babe/src/babe/utils.clj'}, 'workDoneToken': 'wd22'}
:: <<< clojure-lsp 22: {'uri': 'jar:file:///Users/asko/.m2/repository/markdown-clj/markdown-clj/1.10.6/markdown-clj-1.10.6.jar!/markdown/core.clj', 'range': {'end': {'character': 17, 'line': 0}, 'start': {'character': 4, 'line': 0}}}
```

And when trying to open a path in the popup that leads to a file inside of a JAR it still opens a browser, and that doesn't seem to update the log.

**Comment by ericdallo** [comment]
yeah, the server is returning everything correct, unfortunately, this seems to be an issue with the Sublime text LSP client 😔

**Comment by askonomm** [comment]
No worries at all! I'll continue the conversation at the Sublime LSP repo instead, thank you for all the help!
