### ISSUE TITLE
Include built-in clj-kondo cache in native image

### ISSUE THREAD

**Issue by borkdude** [clojure-lsp/clojure-lsp#548]
I think I'm getting now what's going wrong....

@ericdallo You also need to include https://github.com/clj-kondo/clj-kondo/blob/13066e47b8418072edc15a853164a2ef73ddc75a/script/compile#L20 in the graalvm resources :)
This will fix it the weird problem we were seeing with clojure.test.
Your clojure-lsp native image doesn't have the built-in clj-kondo caches for clojure.test, etc.

Feel free to do a similar PR for clj-kondo as you did for babashka to move these settings to META-INF,  then clojure-lsp will automatically benefit from this too.

_Originally posted by @borkdude in https://github.com/clojure-lsp/clojure-lsp/issues/316#issuecomment-915962878_

**Comment by ericdallo** [comment]
Oh, that really makes sense now!
