### ISSUE TITLE
Support rename file/folder tool-assisted refactoring

### ISSUE THREAD

**Issue by maxrothman** [clojure-lsp/clojure-lsp#552]
Moving and renaming Clojure files is a pain. You have to go hunt down all the references to the file and update them as well. Moving or renaming a directory is even worse, since you have to do the same thing for every file in the directory tree. Seems like a job for tool-assisted refactoring!

**Describe the solution you'd like**
A tool exists for renaming Clojure(script) files or folders containing Clojure(script) files that also updates their ns declarations and all references to that ns

**Describe alternatives you've considered**
Find-replace is workable, but kind of a pain.

**Comment by ericdallo** [comment]
Thank you for the report!
this feature is new in protocol, meanwhile users can call `rename` on the `ns` form which should rename the file name and all references as well

**Comment by ericdallo** [comment]
Related method on SPEC: https://microsoft.github.io/language-server-protocol/specification#workspace_willRenameFiles

**Comment by ericdallo** [comment]
This was implemented on latest release and it should work on all editors that support that capability (I know both Emacs lsp-mode and Calva/vscode have)

**Comment by chrishowejones** [comment]
@ericdallo I can't figure out how to rename all the files in a directory in Emacs using Clojure-lsp and get this to work? How is this triggered? Is there a special rename command that needs to be executed?
I can rename an individual ns symbol and have that rename the file it's in but I want to rename all the files and namespaces under a top level namespace. CIDER can do this using clj-refactor but that only works for Clojure and not ClojureScript.
