### ISSUE TITLE
lsp-find-definition: The connected server(s) does not support method textDocument/declaration.

### ISSUE THREAD

**Issue by cloudbuck3t** [clojure-lsp/clojure-lsp#553]
```
lsp--send-request-async: The connected server(s) does not support method textDocument/declaration.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
```

Hi, I have Prelude (emacs) installed on my machine and I installed via `M-x package-install` "use-package"
I installed clojure-lsp via the brew install command, there was no prior version of Clojure-lsp to remove.

I edited my ~/.emacs.d/init.el to include the relevant emacs script located at https://clojure-lsp.io/clients/

**Expected behavior**
I expect to be able to use `M-x lsp-find-definition` when the cursor is on a function name.  However, I get the error message:

```
lsp--send-request-async: The connected server(s) does not support method textDocument/definition.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
```

 - OS: MacOS
 - Editor: emacs with Prelude presets
``` clojure-lsp --version
clojure-lsp 2021.09.13-22.25.35
clj-kondo 2021.08.07-SNAPSHOT
```

Could just be a neophyte mistake on my behalf, I am not the most experienced emacs user.  Very much appreciate all your hard work team.

**Comment by ericdallo** [comment]
thanks for the report @cloudbuck3t, I think it's a issue with your lsp-mode configuration, maybe the docs can has some bug.
Could you check if the function works after you `M-x` `lsp` on the clojure buffer?

**Comment by cloudbuck3t** [comment]
Okay let's see
`M-x lsp`

```
LSP :: There are no language servers supporting current mode `emacs-lisp-mode' registered with `lsp-mode'.
This issue might be caused by:
1. The language you are trying to use does not have built-in support in `lsp-mode'. You must install the required support manually. Examples of this are `lsp-java' or `lsp-metals'.
2. The language server that you expect to run is not configured to run for major mode `emacs-lisp-mode'. You may check that by checking the `:major-modes' that are passed to `lsp-register-client'.
3. `lsp-mode' doesn't have any integration for the language behind `emacs-lisp-mode'. Refer to https://emacs-lsp.github.io/lsp-mode/page/languages and https://langserver.org/ .
4. You are over `tramp'. In this case follow https://emacs-lsp.github.io/lsp-mode/page/remote/.
5. You have disabled the `lsp-mode' clients for that file. (Check `lsp-enabled-clients' and `lsp-disabled-clients').
```

**Comment by ericdallo** [comment]
yeah, that's the issue, lsp-mode is not being able to start the server for some reason, I suspect this could be related to lsp-mode not finding clojure-lsp on your $PATH.
if `clojure-lsp --version` works in your terminal could you try launching emacs from the terminal and checking if the error happens again?

**Comment by ericdallo** [comment]
This is a lib that usually fix this issue: https://github.com/purcell/exec-path-from-shell

**Comment by cloudbuck3t** [comment]
Hi again.  I tried running emacs from the command line but it still gives me the same error.  I also tried installing exec-path-from-shell and adding in to init.el but I'm still encountering the same issue.  Should I specify the path where brew installed clojure-lsp in my init.el?

**Comment by ericdallo** [comment]
that's a option @cloudbuck3t you can try something like `(setq lsp-clojure-custom-server-command '("/path/to/clojure-lsp"))`

**Comment by cloudbuck3t** [comment]
Well, I changed that path to /usr/local/bin/clojure-lsp  and now it says

```
e snippet support.
LSP :: Connected to [clojure-lsp:9192/starting].
lsp--send-request-async: The connected server(s) does not support method textDocument/definition.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
```

**Comment by ericdallo** [comment]
that's odd, it seems it correctly found the clojure-lsp, but that error doesn't make much sense 🤔

**Comment by cloudbuck3t** [comment]
Are there any preparatory steps for getting the definition finder to work?

**Comment by ericdallo** [comment]
nope, this is a really simple feature that almost all LSP servers have, I suggest you ask for help on lsp-mode chat [here](https://discord.gg/swuxy5AAgT)

**Comment by cloudbuck3t** [comment]
So I moved the binary `clojure-lsp` to `/usr/local/bin` and now everything appears to work.  Thanks =)
