### ISSUE TITLE
Declarations to ignore unused public vars are initially ignored

### ISSUE THREAD

**Issue by simon-katz** [clojure-lsp/clojure-lsp#554]
**Describe the bug**

In Emacs, `lsp-treemacs-errors-list` initially ignores unused public var declarations.

**To Reproduce**

1. Clone https://github.com/simon-katz/clojure-lsp-unused-public-var-misreports
2. In Emacs, navigate to `project.clj` and run `lsp-treemacs-errors-list`.
3. Note that the Errors List buffer has unused public var reports.

**Expected behavior**

There should be no unused public var reports.

**User details (please complete the following information):**

 - OS: macOS 10.15.7 (Catalina)
 - Editor: Emacs
 - Version: clojure-lsp 2021.09.13-22.25.35 / clj-kondo 2021.08.07-SNAPSHOT

**Other info**

The repro repo has 1000 namespaces, each with an unused public var. If I am displaying a buffer with an unused public var and run `lsp-restart-workspace`, `flycheck` initially shows the erroneous reports; editing the file causes the reports to go away. There are no erroneous reports in a project with a small number of these namespaces.

I came across this initially by noticing that `flycheck` behaves non-deterministically on such code in large-enough projects: In small projects, there’s never an erroneous report; in large projects, there are always erroneous reports; in projects of a certain middle size there are sometimes erroneous reports.

(EDIT: This last part seems to depend on the project size. For large projects it doesn't fix things.)
If I move the declaration to the project’s config.edn like this…

```
:clojure-lsp/unused-public-var {:exclude #{my-ns/foo}}
```

…then all is OK.

**Comment by ericdallo** [comment]
@simon-katz I found the issue on clojure-lsp and it's related with concurrency, it's not easy to fix unless my proposed improvement on clj-kondo is accepted
