### ISSUE TITLE
Consider exposing API via babashka pod

### ISSUE THREAD

**Issue by borkdude** [clojure-lsp/clojure-lsp#555]
When doing so, we can call the API directly from babashka scripts.

More info on how clj-kondo does this: https://github.com/clj-kondo/clj-kondo/blob/master/src/pod/borkdude/clj_kondo.clj

**Comment by borkdude** [comment]
This is not the bug, please remove the bug label.

**Comment by ericdallo** [comment]
Oh, interesting, I will take a look!

**Comment by borkdude** [comment]
@ericdallo Here is an example of how to run the clj-kondo pod:

https://github.com/babashka/pod-registry/blob/master/examples/clj-kondo.clj

**Comment by ericdallo** [comment]
I think I wrongly mentioned this issue on the PR, sorry
