### ISSUE TITLE
Sort namespace when adding missing require/import

### ISSUE THREAD

**Issue by dharrigan** [clojure-lsp/clojure-lsp#558]
Hi,

Presently, when clojure-lsp adds a missing require/import, the addition is done to the end of the list. I then have to issue another command to sort the namespace after the addition is done. It would be nicer if there was an opt-in way to tell clojure-lsp that after adding the missing require/import, to also sort the namespace requires/imports (or, maybe just insert the missing require/import into the correct location in the list?).

I believe the feature should be `opt-in`, rather than `opt-out` since not everyone might want their namespaces automatically sorted. Not sure, maybe for those who would rather not have it automatically done, it could be opt out (it all depends if the majority prefer to have it automatically sorted or vice versa).

Thank you.

-=david=-

**Comment by ericdallo** [comment]
thanks for the suggestion! seems a good optional addition

**Comment by ericdallo** [comment]
@dharrigan @rafaeldelboni done! available on #clojure-lsp-builds otherwise on next release
