### ISSUE TITLE
`clean-ns` drops comments from ns form

### ISSUE THREAD

**Issue by dpsutton** [clojure-lsp/clojure-lsp#559]
**Describe the bug**
Sorting the ns form does not preserve comments

**To Reproduce**

```clojure
(ns foo
  (:require [clojure.set :as set] ;; important comment
            [clojure.edn :as edn]))
```

Sort-ns command yields
```clojure
(ns foo
  (:require
   [clojure.edn :as edn]
   [clojure.set :as set]))
```

**Expected behavior**
The comment is added on purpose and should be preserved

**Screenshots**
#### Before
<img width="546" alt="image" src="https://user-images.githubusercontent.com/6377293/133472864-c715b7be-2a80-4ad4-b478-9828182ce53e.png">

#### After
<img width="444" alt="image" src="https://user-images.githubusercontent.com/6377293/133473071-d8b54a19-54f0-4d71-b376-f8b502d4d647.png">

**Comment by ericdallo** [comment]
Hey @dpsutton it was not easy but I made it work for your case and probably the most cases, it's not perfect, I need to improve the code yet, but I'd love to hear from you if it helps, do you think you can test with the clojure-lsp from this branch?
https://github.com/clojure-lsp/clojure-lsp/pull/567

You can just run `make` on the project and it should generate a `clojure-lsp` binary on the project root

**Comment by dpsutton** [comment]
i ran `make` and it kept the comment. Kudos. Thanks for handling that case. Sort-ns is very close to handling all ns forms in our codebase. Thanks!
