### ISSUE TITLE
warn on shadowing function from ns

### ISSUE THREAD

**Issue by dpsutton** [clojure-lsp/clojure-lsp#56]
Local binding had a logical name "import-data". This was such a good name there was already a function in the ns named the same thing. So ended up calling the vector `import-data` on some args rather than the function which was shadowed.

be nice to have a warning when shadowing

**Comment by ericdallo** [comment]
This now should be handled on clj-kondo after we merged #261, not sure if clj-kondo already supports it, if you think it should, please open a PR there, thanks!
