### ISSUE TITLE
Read cljfmt settings from a file

### ISSUE THREAD

**Issue by amithgeorge** [clojure-lsp/clojure-lsp#563]
**Is your feature request related to a problem? Please describe.**
Calva use cljfmt for formatting. It also uses clojure-lsp for as the lsp client. clojure-lsp also uses cljfmt for its formatting actions. As it stands, it is possible for Calva to format differently from how clojure-lsp would format it. This could lead to false negatives when running clojure-lsp format checking on the CI. 

**Describe the solution you'd like**
[cljfmt](https://github.com/weavejester/cljfmt) doesn't have a preferred file path for its config. So there is no established convention for cljfmt standalone config. Calva in its [config](https://calva.io/formatting/#configuration) accepts a filepath for cljfmt settings `calva.fmt.configPath`. 

clojure-lsp could also support reading the cljfmt settings from a file path. We could use a config key like `:cljfmt-config-path`.  And its value would be a string containing the path to the cljfmt config file, the same one used for Calva. 

**Describe alternatives you've considered**
Since Calva embeds/uses clojure-lsp, it could potentially read the cljfmt config from clojure-lsp's config file `.lsp/config.edn`. It however creates a coupling between the two, and not very maintainable. 

**Additional context**
N/A

**Comment by ericdallo** [comment]
Thank you for the suggestion, I think we can try to read from the same path Calva reads by default if the user doesn't provide the `:cljfmt-config-path` file.
@PEZ What is the default path Calva search for cljfmt configs?

**Comment by PEZ** [comment]
Actually, there is no default. I thought there was, but I have been running with `cljmft.edn` in my User setting which I thought was the default. And also cljfmt itself doesn't seem to have a default file...

Does `cljfmt.edn` in the project root make sense? I think clj-kondo has a scheme where it finds config files from the linted file and up to some project root? Maybe we can mimic that behaviour with this.... Can @borkdude enlighten us maybe? 

Anyway, what is important here is that clojure-lsp and Calva (and whatever editor) is in sync. Or that the user easily can make them be in sync. I'm up to fix whatever default behaviour in Calva. Maybe Calva could ask clojore-lsp for the config? The Calva setting could be something like:

* Ask clojure-lsp (default)
* A file -> specify, though there is a default
 
Then any project that uses both clojure-lsp and Calva can specify in clojure-lsp where to find the config. Amd clojure-lsp can have a default like `cljfmt.edn` in the project root.

Another datapoint is that lein-cljfmt looks for the `:cljfmt` entry in project.clj.

**Comment by ericdallo** [comment]
Sure, we can make that setting available via the serverInfo LSP method that already exists and Calva uses.
Maybe I would just suggest to the file be something like `.cljfmt.edn` to follow the hidden files convention like .lsp and .clj-kondo and .vscode WDYT?

**Comment by borkdude** [comment]
I personally like the hidden convention for config files like `.lsp`, `.clj-kondo`, `.circleci` but for bb I've chosen `bb.edn` in the project root similar to `deps.edn` and `package.json`.

**Comment by PEZ** [comment]
Currently in Calva we hot-reload cljfmt config as the file is saved. With server-info we'd loose that, but I lean towards that that is OK. Maybe we can make the manual server-info command that we have side-effect that the formatting config is updated....

As for convention. There is also `deps.edn`, `project.clj`,  `shadow-cljs.edn` and the like. `.vscode`, `.clj-kondo` and `.lsp` are directories (where we also have `.calva` as an example).

Btw, clj-kondo's config scheme is pretty well documented: https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md I think formatting rules are conceptually similar enough to linting rules for us to consider taking inspiration.

**Comment by ericdallo** [comment]
Yeah, I see `deps.edn`, `project.clj`, `shadow-cljs.edn` and `bb.edn` as the build file, it's important for the project run, the other ones are optional for linting, formatting, ide configuration.

**Comment by PEZ** [comment]
I'm good with a hidden default file.

**Comment by ericdallo** [comment]
@PEZ regarding the hot-reload config, probably we can make that happen after #502

**Comment by ericdallo** [comment]
Done, available on new release, added a new `:cljfmt-config-path` setting with a default value of `.cljfmt.edn`.

@PEZ this setting is already available on the both `serverInfo` and `serverInfoRaw` custom methods that Calva already uses, so Calva can now check use the file provided from the return of that method if no file was provided by the user :)
