### ISSUE TITLE
emacs: blacklisted home directory, all sub directories believed to be blacklisted

### ISSUE THREAD

**Issue by cloudbuck3t** [clojure-lsp/clojure-lsp#568]
Hi, how can I un-blacklist directories in clojure-lsp?
I blacklisted an upstream folder `~/` and this is interpreted as blacklisting all subfolders...  
How can I revise this?  I'm unable to find it in the docs.
(emacs)

**Comment by ericdallo** [comment]
`lsp-workspace-folders-remove` should work for you

**Comment by cloudbuck3t** [comment]
Maybe I'm mistaken, but that looks like it will remove currently indexed directories, how can I remove them from the blacklist?

**Comment by ericdallo** [comment]
oh, sorry, I think what you want is `lsp-workspace-blacklist-remove`
