### ISSUE TITLE
Function signature is not shown in minibuffer when writing arguments in Emacs

### ISSUE THREAD

**Issue by ccann** [clojure-lsp/clojure-lsp#569]
**Describe the bug**
The function signature is not shown in the minibuffer (via eldoc?) when I type, e.g. `(filter |` (the bar being my cursor).
I’m using DOOM emacs and I have the same issue regardless of CIDER being enabled or disabled. 

**To Reproduce**
With a non-`nil` value for `lsp-signature-auto-activate`, type out an invocation of a built-in function and leave the cursor at the expected location for the first argument, e.g. `(filter |)`

**Expected behavior**
The function signature (function name and arguments, and possibly documentation) to show up in the minibuffer.

**Screenshots**

You can see in the first screenshot that with the cursor over the symbol we get the function signature in the minibuffer.
<img width="657" alt="Screen Shot 2021-09-18 at 7 54 50 PM" src="https://user-images.githubusercontent.com/2650566/133913875-a5e26d8d-ad2a-479d-abfc-519367cbe3f8.png">
But in this screenshot with the cursor positioned one whitespace character away, we do not.
<img width="657" alt="Screen Shot 2021-09-18 at 7 54 43 PM" src="https://user-images.githubusercontent.com/2650566/133913876-998b14ea-c00a-4d08-bcd7-a79a45035dc9.png">
And here is it working in Python with the same emacs LSP settings
<img width="636" alt="Screen Shot 2021-09-18 at 8 01 19 PM" src="https://user-images.githubusercontent.com/2650566/133914005-70b4650c-8263-4aa5-a73c-cde9c894cc18.png">

**User details (please complete the following information):**
 - OS: macOS
 - Editor emacs 28 ([lightly configured](https://github.com/ccann/doom-emacs/blob/master/config.el) DOOM emacs)
 - Version: 
```
 ❯ clojure-lsp --version
clojure-lsp 2021.09.13-22.25.35
clj-kondo 2021.08.07-SNAPSHOT
```

**Additional context**
We chatted on Clojurians Slack about this

**Comment by ericdallo** [comment]
Thanks for the report, I will take a look and confirm it's a bug on server side first

**Comment by ericdallo** [comment]
I found the issue, clojure-lsp return the `range` of the element for the __hover__ feature, the range is the location information about that element like row/col/end-row/end-col and turns-out the `end-row`/`end-col` of a `var-usage` is the end of the element name not the function usage (parens).

@borkdude, do you think clj-kondo could provide a `:scope-end-row` and `:scope-end-col` for `var-usages` like it does for `:locals`? this would help know when the parens end for var-usages helping fixing issues like that.
I considered using rewrite-clj but that would really affect performance as we'd need to parse the buffer text every hover, also this info sounds good to come from clj-kondo IMO, WDYT?

**Comment by ericdallo** [comment]
This is the analysis of that `filter`:
```clojure
{:fixed-arities #{1 2},
  :name-end-col 7,
  :name-end-row 4,
  :name-row 4,
  :name filter,
  :filename "...",
  :from clojure-lsp.logging,
  :col 2,
  :name-col 2,
  :arity 0,
  :bucket :var-usages,
  :row 4,
  :to clojure.core}
```
in this case something like this would help:
```clojure
{:fixed-arities #{1 2},
  :name-end-col 7,
  :name-end-row 4,
  :name-row 4,
  :name filter,
  :filename "...",
  :from clojure-lsp.logging,
  :col 2,
  :name-col 2,
  :arity 0,
  :bucket :var-usages,
  :row 4,
  :to clojure.core
  :scope-end-row 4
  :scope-end-col 9}
```

**Comment by borkdude** [comment]
@ericdallo I think that would be useful to add.

**Comment by ericdallo** [comment]
@ccann Improved this to fix this issue on master, available on next release. It's not bullet-proof for all cases but it fixes this issue and most common cases
