### ISSUE TITLE
[hover] Include material from Clojuredocs in hover documentation

### ISSUE THREAD

**Issue by shinichy** [clojure-lsp/clojure-lsp#571]
**Is your feature request related to a problem? Please describe.**
The clojuredocs.org documentation for clojure core is really handy. The examples are invaluable given how terse clojure docs can be.

It would be great to have access to the clojuredocs for a given function.

**Describe the solution you'd like**
The hover documentation includes Clojuredocs information like examples, see also texts, and notes.

**Describe alternatives you've considered**
No alternative solutions.

**Additional context**
This feature request originally comes from Calva.
https://github.com/BetterThanTomorrow/calva/issues/689

**Comment by ericdallo** [comment]
@shinichy available on next clojure-lsp release :)

Example on emacs:
![image](https://user-images.githubusercontent.com/7820865/137637245-d8ae19b7-add1-4315-8327-1f8e02a6690f.png)
