### ISSUE TITLE
clojure-lsp exits with 1 even if all linters reported only :info

### ISSUE THREAD

**Issue by thiagokokada** [clojure-lsp/clojure-lsp#572]
**Describe the bug**

On `clj-kondo`, if all linters reported only `:info`, it would exit with error code 0. This was useful for CI, when you wanted to have a informative linter that didn't fail CI, however you still wanted to know about it when running locally.

On `clojure-lsp` even if only one linter reports :info, `clojure-lsp` itself will exit with error code 1. So you either needs to disable all linters or use some hack, like:

```
clojure-lsp diagnostics | grep -Ev 'warning|error'
```

**To Reproduce**

1. Setup clojure-lsp on a project
2. Set `.clj-kondo/config.edn` as:
    ```
    {:linters {:unused-binding {:level :info}}}
    ```
3. Add any unused binding to the project
4. Run `clojure-lsp diagnostics; echo $?`. This will return 1 instead of 0.

**Expected behavior**

It should return 0.

<details>
 <summary><b>clojure-lsp output</b></summary>
<pre>
ADD HERE
</pre>
</details>

**User details (please complete the following information):**
 - OS: NixOS (21.05)
 - Version: Not working with `lein-clojure-lsp`, but it is on version 1.0.5

**Additional context**
Using `lein-clojure-lsp`, this is why I didn't fill some info above.

**Comment by ericdallo** [comment]
Thanks for the report!
That makes sense, I should prioritize for the next release

**Comment by ericdallo** [comment]
Now we follow [the same status code](https://github.com/clj-kondo/clj-kondo#exit-codes) from clj-kondo, available on the next release
