### ISSUE TITLE
Rename namespaces could rename explicitly qualified keywords

### ISSUE THREAD

**Issue by mynomoto** [clojure-lsp/clojure-lsp#573]
**Is your feature request related to a problem? Please describe.**
When renaming a namespace clojure-lsp doesn´t rename explicit qualified keywords. E.g. If i do a namespace renaming from `foo.bar` to `bar.baz` clojure-lsp do not change explicit keywords from `:foo.bar/x` to `:bar.baz/x`.

**Describe the solution you'd like**
clojure-lsp renames `:foo.bar/x` to `:bar.baz/x` when the namespace is renamed.

**Describe alternatives you've considered**
I could rename it myself manually but it is not great. I could write a tool to do it but clojure-lsp is great and does almost what I want.

**Comment by ericdallo** [comment]
We can do that, I'd just like to understand there are no cases we don't want this behavior

**Comment by ericdallo** [comment]
@DeLaGuardo said:

I’m often begin writing code in single namespace (let’s call it `foo.bar`) and when it starts to be big enough I extract some functions using following steps:
* rename entire namespace `foo.bar` -> `foo.bar.lib`
* create empty `foo.bar`
* move some functions from `foo.bar.lib` back to foo.bar
After that `foo.bar` can require `foo.bar.lib` to have access to the rest of functionality. Normally `foo.bar` exposes api for the program, sometimes via implementation for integrant keys.
If during the step 1 such keys will be changed without notice in some file it might break my program.

**Comment by ericdallo** [comment]
Maybe a opt-out flag would solve that issue
