### ISSUE TITLE
autocomplete for math symbols pops up, won't hide on Ctrl+G 

### ISSUE THREAD

**Issue by cloudbuck3t** [clojure-lsp/clojure-lsp#575]
Hi, I'm using emacs and occasionally the autocomplete with *, +, -, and other operators will show up.  It's not clear to me how to disable it or how to exit out of it once it shows up.  I can hit TAB a few times and have it spit out a * symbol, but I'm not sure how to simply cancel it.  I hit Ctrl+G and that seems to have a 50/50 chance of working at hiding the prompt.  I'm unable to find any documentation on how to use these features, maybe I'm missing something obvious...

**Comment by ericdallo** [comment]
Hi, this is something configured on the client side, probably lsp-mode for you, or even `company` the lib responsible for completion on lsp-mode.
For me, which use emacs + lsp-mode, is just `ESC`, but I use doom-emacs and probably I have a different setup than yours

**Comment by ericdallo** [comment]
Closing as is not a server issue, we can keep discussing here or on Clojurians slack :)
