### ISSUE TITLE
clojure-lsp fails to start with empty project.clj file

### ISSUE THREAD

**Issue by paulbutcher** [clojure-lsp/clojure-lsp#579]
**Describe the bug**
clojure-lsp fails to start if there's an empty `project.clj` file present

**To Reproduce**
1. Create a `project.clj` file containing `{}`
2. Start VSCode/Calva
3. clojure-lsp fails with `java.lang.AssertionError: Assert failed: zloc`

**Expected behavior**
My project is compiled via `deps.edn`, but I have an empty `project.clj` because Heroku's Clojure buildpack insists upon there being one. It would be convenient not to have to populate it with unused data just to allow clojure-lsp to start.

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
Sep 26, 2021 4:41:55 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: An error occurred while processing an incoming message.
java.lang.NullPointerException
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:279)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

</pre>
</details>

<details>
 <summary><b>Log - clojure-lsp</b></summary>
<pre>
2021-09-26T14:58:59.026Z Pauls-16in-MBP ERROR [clojure-lsp.server:?] - 
                                 com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine            PosixJavaThreads.java:  192
                                             com.oracle.svm.core.thread.JavaThreads.threadStartRoutine                 JavaThreads.java:  567
                                                                                  java.lang.Thread.run                      Thread.java:  829
                                                    java.util.concurrent.ThreadPoolExecutor$Worker.run          ThreadPoolExecutor.java:  628
                                                     java.util.concurrent.ThreadPoolExecutor.runWorker          ThreadPoolExecutor.java: 1128
                                                                   java.util.concurrent.FutureTask.run                  FutureTask.java:  264
                                                   java.util.concurrent.Executors$RunnableAdapter.call                   Executors.java:  515
                                         org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run  ConcurrentMessageProcessor.java:  113
                                           org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen       StreamMessageProducer.java:   94
                                    org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage       StreamMessageProducer.java:  194
                                                      org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume              RemoteEndpoint.java:  190
                                                org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest              RemoteEndpoint.java:  261
                                            org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request             GenericEndpoint.java:  120
                                      org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0             GenericEndpoint.java:   65
                                                                                                   ...                                       
clojure_lsp.server.proxy$clojure_lsp.ClojureExtensions$ExtraMethods$LanguageServer$4129860f.initialize                                       
                                                                              clojure-lsp.server/fn/fn                       server.clj:  301
                                                                       clojure-lsp.handlers/initialize                     handlers.clj:   49
                                                                clojure-lsp.crawler/initialize-project                      crawler.clj:  186
                                                                                   clojure.core/update                         core.clj: 6185
                                                                               clojure.core/partial/fn                         core.clj: 2635
                                                         clojure-lsp.source-paths/process-source-paths                 source_paths.clj:  131
                                                         clojure-lsp.source-paths/resolve-source-paths                 source_paths.clj:  126
                                              clojure-lsp.source-paths/resolve-source-paths-from-files                 source_paths.clj:   92
                                                                     clojure-lsp.parser/lein-zloc->edn                       parser.clj:  112
                                                                                rewrite-clj.zip/remove                         zip.cljc:  569
                                                                        rewrite-clj.zip.removez/remove                     removez.cljc:   57
java.lang.AssertionError: Assert failed: zloc

2021-09-26T14:58:59.028Z Pauls-16in-MBP DEBUG [clojure-lsp.server:?] - :initialize 21ms
</pre>
</details>

**User details (please complete the following information):**
 - OS: MacOS
 - Editor: VSCode (Calva)
 - Version: 2021.09.13-22.25.35

**Comment by ericdallo** [comment]
Thanks, I managed to repro the issue, will work on a fix

**Comment by ericdallo** [comment]
Fixed on master, it should be available on the next release.
For testing with clojure-lsp master, you can clone the repro and run `make` to generate a local `clojure-lsp` binary on the project root.
