### ISSUE TITLE
Create automatic test file when right click in a function

### ISSUE THREAD

**Issue by marinacavalari** [clojure-lsp/clojure-lsp#582]
While using cursive in intellij I noticed that when we do a right click in a function, we can select the option to automatic create a  test, so the cursive itself creates a new file in the same namespace organization with one test to the function I first clicked. It would be  nice to help us on unit tests

**Comment by ericdallo** [comment]
We could add that via code actions, like a code action for `create test for 'foo/bar'`, even so, we would need to know which source-path is the test one, for a project which has only `src` and `test` that could work already, but for another one with `src`, `unit-test`, `integration-test`, how we would know which one we should create the new file/test?

**Comment by ericdallo** [comment]
We could just always prompt to user choose what source-path makes sense, it looks safer and it should work for all cases
