### ISSUE TITLE
Declarations to ignore unused public vars don't work in .cljc files

### ISSUE THREAD

**Issue by simon-katz** [clojure-lsp/clojure-lsp#589]
**Describe the bug**
It seems that declarations to ignore unused public vars don't work in .cljc files.

**To Reproduce**

1. Clone project https://github.com/simon-katz/clojure-lsp-unused-public-var-and-cljc-files
2. Run `clojure-lsp diagnostics`
3. Observe the unexpected report: Unused public var 'clojure-lsp-unused-public-var-and-cljc-files.my-cljc/foo-cljc' 

Note that the similar unused-public-var declarations in the .clj and .cljs files work fine.

**Expected behavior**
No diagnostic should be issued.

<details>
 <summary><b>clojure-lsp output</b></summary>
<pre>
$ clojure-lsp --verbose diagnostics
[  0%] Resolving project           2021-10-07T13:28:19.824Z sheringham.home INFO [clojure-lsp.source-paths:135] - Automatically resolved source-paths from project.clj: #{"src" "src/main/clojure" "test" "src/test/clojure"}
[ 15%] Discovering classpath       2021-10-07T13:28:21.251Z sheringham.home INFO [clojure-lsp.crawler:169] - Using cached classpath for project root /Users/simonkatz/development-100/repositories/nomis/_bug-reports/clojure-lsp-unused-public-var-and-cljc-files
[ 90%] Resolving config paths      2021-10-07T13:28:21.252Z sheringham.home INFO [clojure-lsp.crawler:243] - Analyzing source paths for project root /Users/simonkatz/development-100/repositories/nomis/_bug-reports/clojure-lsp-unused-public-var-and-cljc-files
[ 95%] Analyzing project files     2021-10-07T13:28:21.269Z sheringham.home INFO [clojure-lsp.kondo:64] - Starting to lint whole project files...
2021-10-07T13:28:21.270Z sheringham.home INFO [clojure-lsp.kondo:?] - Linting whole project files took 0.00 secs
2021-10-07T13:28:21.271Z sheringham.home INFO [clojure-lsp.crawler:?] - Project only paths analyzed, took 0.02 secs
[100%] Project analyzed            
Finding diagnostics...
src/clojure_lsp_unused_public_var_and_cljc_files/my_cljc.cljc:3:6: info: [unused-public-var] Unused public var 'clojure-lsp-unused-public-var-and-cljc-files.my-cljc/foo-cljc'
</pre>
</details>

**User details (please complete the following information):**
 - OS: MacOS 10.15.7
 - Version: clojure-lsp 2021.09.30-15.28.01, clj-kondo 2021.09.25

**Comment by borkdude** [comment]
@ericdallo We should fix this. Can you make a issue + repro (as failing test) in clj-kondo?

**Comment by ericdallo** [comment]
Done @borkdude https://github.com/clj-kondo/clj-kondo/issues/1403

**Comment by borkdude** [comment]
Thanks! I'll take a look soon, hopefully.

**Comment by ericdallo** [comment]
Confirmed this was fixed on clojure-lsp master bumping clj-kondo, it should be available on next release @simon-katz
