### ISSUE TITLE
Add CodeAction to insert clj-kondo ignore rule for line

### ISSUE THREAD

**Issue by leoiacovini** [clojure-lsp/clojure-lsp#591]
**Is your feature request related to a problem? Please describe.**
Sometimes we have situations where we are dealing with libraries of legacy code that will make us need to ignore linting rules for a specific piece of code in the project, and stop having it from complaining in the analysis or CI about it

**Describe the solution you'd like**
Usually, other analysis tools in IDEs have an option to "ignore" the linting rule for the next line. `clj-kondo` itself has this feature by just adding a comment above the line with `#_{:clj-kondo/ignore [...rules...]}`, it would be very nice to have a suggestion from code actions to `clojure-lsp` adding this comment automatically for a specific linting issue

**Describe alternatives you've considered**
If identifying the specific rule being violated would be hard, using the default ignore `#_:clj-kondo/ignore` would also work as a good MVP

**Comment by ericdallo** [comment]
Available on next release!
