### ISSUE TITLE
Clojure-lsp running on many unknown namespaces

### ISSUE THREAD

**Issue by AndreaCrotti** [clojure-lsp/clojure-lsp#597]
**Describe the bug**

When running `clojure-lsp format` I see a lot more namespaces that are not really relevant to the project I'm running on.
For example

```Formatted byf.datomic
Formatted rewrite-clj.zip.utils
Formatted day8.re-frame-10x.inlined-deps.re-frame.v0v10v9.re-frame.router
Formatted day8.re-frame-10x.view.event
Formatted day8.re-frame-10x.inlined-deps.re-frame.v0v10v9.re-frame.utils
Formatted day8.re-frame-10x.inlined-deps.reagent.v0v8v1.reagent.impl.template
Formatted byf.stats-test
Formatted taoensso.timbre
Formatted data-migrations.merge-users-players
Formatted cljs.repl
Formatted day8.re-frame-10x.inlined-deps.re-frame.v0v10v9.re-frame.events
Formatted iron.closure-utils
Formatted devtools.defaults
Formatted com.degel.re-frame-firebase.database
Formatted day8.re-frame-10x.inlined-deps.garden.v1v3v9.garden.selectors
Formatted day8.re-frame-10x.view.fx
Formatted re-frame.cofx
Formatted clojure.string
```

where only the ones starting with `byf` are actually relevant.

**To Reproduce**

1. clone https://github.com/AndreaCrotti/elo
2. run `clojure-lsp format`

**Expected behavior**

It should only run on namespaces in the project.

**Comment by ericdallo** [comment]
@AndreaCrotti I improved clojure-lsp to filter project analysis checking the [configured or auto-resolved source-paths](https://clojure-lsp.io/settings/#source-paths-discovery) fixing this issue :)
Available on next release
