### ISSUE TITLE
Completion Issues [neovim]

### ISSUE THREAD

**Issue by tami5** [clojure-lsp/clojure-lsp#630]
# Overview
  A list of weird Clojure-lsp completion issues + some symbol documentation missing.

  Issues:
  - Slow Keyword completion
  - Inaccurate namespace-function completion and sometimes no completion suggestions.
  - Keyword and modules duplications.
  - Missing documentation for some symbols.

  # Screenshots

  ### Slow Keywords Completion

  Keyword completion actually wouldn't work because [clojure-lsp] doesn't provide `completionProvider.triggerCharacters`.
  In my setup, I had to overwrite it with `{ ":", "/", "." }` so [nvim-cmp] can receive it (see [cmp-nvim-lsp triggerCharacters]).

  **Using [clojure-lsp] and [cmp-nvim-lsp]**
  
![keyword-completion-with-clojure-lsp](https://user-images.githubusercontent.com/65782666/140643563-17fdea96-988a-4cbd-8f20-ec3dfb551ae8.gif)

  **Using [conjure] and [cmp-conjure]**
![keyword-completion-with-conjure](https://user-images.githubusercontent.com/65782666/140643569-d65d9662-0162-4f59-894c-0b0b9ddd9ecc.gif)

  ### Module Duplication and Namespace completion
  **Using [clojure-lsp] and [cmp-nvim-lsp]**
  In clojure-lsp source `d` which points to `datomic.api`, is duplicated a large number of time + can't access methods:
  
![duplications-wtih-clojure-lsp-source](https://user-images.githubusercontent.com/65782666/140643595-7f07699f-663e-4910-a24c-cd9d98cf239b.gif)

  **Using [conjure] and [cmp-conjure]**
  In conjure setup, this isn't an issue
  
  ![duplications-wtih-conjure-source](https://user-images.githubusercontent.com/65782666/140643604-0ff9685c-2723-4f7e-b11f-b36f777ae72f.gif)

  **User details**
   - OS: MacOs
   - Editor Neovim
   - Version: clojure-lsp 2021.09.30-15.28.01

  **Additional context**
  
  Possible fixes maybe:
   - return triggerCharacters` so completion frameworks like [cmp.nvi] [cmp-nvim] use it

[cmp-nvim-lsp]: https://github.com/hrsh7th/cmp-nvim-lsp/tree/main/lua/cmp_nvim_lsp
[nvim-cmp]: https://github.com/hrsh7th/nvim-cmp
[cmp-conjure]: https://github.com/PaterJason/cmp-conjure/blob/master/lua/cmp_conjure/init.lua
[conjure]: https://github.com/Olical/conjure
[clojure-lsp]: https://github.com/clojure-lsp/clojure-lsp
[cmp-nvim-lsp triggerCharacters]: https://github.com/hrsh7th/cmp-nvim-lsp/blob/main/lua/cmp_nvim_lsp/source.lua#L32-L34

**Comment by ericdallo** [comment]
Thanks for the report, I think we can add `/` and `:` as completion trigger chars, not sure about `.` though, why we would like `.` as a completion trigger in clojure?
Also, I'll do some improvements on the keywords completion performance as ATM when you type `:` and completes, clojure-lsp is considering a completion without any prefix, bringing all possible completion items and affecting performance

**Comment by tami5** [comment]
> why we would like `.` as a completion trigger in clojure?

I like it because it gives me a quickly way to access namespace and then later using a custom editing function, move it in to `:require` and rename it. 

**With conjure:** is simple and straightforward 
![access-namespaces-conjure4](https://user-images.githubusercontent.com/65782666/140659257-329b25cb-dc27-4ee7-818a-4508b2f428a8.gif)

**with clojure-lsp**
![access-namespaces-clojure-lsp](https://user-images.githubusercontent.com/65782666/140659253-bde6a7a4-f6bd-42ba-9e4d-f6597c70263b.gif)


> I'll do some improvements on the keywords completion performance as ATM when you type `:` and completes, clojure-lsp is considering a completion without any prefix, bringing all possible completion items and affecting performance

🎉🎉🎉🎉🎉🎉 better experience, thanks I look forward.

Do you think it's better if the server sent symbol-patterns [example-pattern]? and can clojure-lsp support custom trigger: e.g. `#` return snippets that create anonymous function out of a chosen symbol.

```clojure
#str/contains?| -> #(str/contains? $str $substr)
``` 

[here:example-pattern]: https://github.com/PaterJason/cmp-conjure/blob/master/lua/cmp_conjure/init.lua#L19-L21

**Comment by ericdallo** [comment]
> I like it because it gives me a quickly way to access namespace and then later using a custom editing function, move it in to :require and rename it.

I don't actually see the difference with and without the `.` testing with emacs/lsp-mode 🤔 

> Do you think it's better if the server sent symbol-patterns [example-pattern]? and can clojure-lsp support custom trigger: e.g. # return snippets that create anonymous function out of a chosen symbol.

Sounds good to me, we already have some snippets and even support custom snippets from user: https://clojure-lsp.io/features/#snippets, but we don't support this kind of automatic snippet

**Comment by ericdallo** [comment]
BTW opened this one on clj-kondo, it should help improve the completion for `:`: https://github.com/clj-kondo/clj-kondo/issues/1451

**Comment by ericdallo** [comment]
@tami5 would you mind testing the clojure-lsp version from this branch? https://github.com/clojure-lsp/clojure-lsp/pull/632
You can generate a dev clojure-lsp from this branch just running `make`

**Comment by tami5** [comment]
@ericdallo unfortunately, I wasn't able to test it out maybe when when #604 is merged. However, if you have neovim installed locally, you can use https://gist.github.com/tami5/dbf004eb138da98d7b0c61658ac95b4c: 

```bash 
curl https://gist.githubusercontent.com/tami5/dbf004eb138da98d7b0c61658ac95b4c/raw/cc4224d73269cd67834719883ae9cf557f219f90/init.lua
nvim -nu init.lua && nvim-nu init.lua /path/to/clojure/project/file.clj
```

NOTE: After first run, it will exist when runtime files are available, just re-run

**Comment by ericdallo** [comment]
I'm a NixOS user as well :)
clojure-lsp dev works good, you just need java on your PATH even if you are a nix user

**Comment by tami5** [comment]
GO NIX, Oh yah, that's true, I will try to check it a bit. thanks

**Comment by ericdallo** [comment]
Good news @tami5 , https://github.com/clj-kondo/clj-kondo/pull/1452 was fixed and it should improve even more the `:` keyword completion, I already bumped clojure-lsp

**Comment by tami5** [comment]
Okay I managed to set it up locally, and check it out #632, I have bumped clj-kondo manually on that branch.

Let's see:

![test-keyword-completion-with-clojure](https://user-images.githubusercontent.com/65782666/140881006-7236f011-4f38-435d-aaff-b1ae8093f8a9.gif)
![test-namespace-completion-with-clojure](https://user-images.githubusercontent.com/65782666/140881556-3783af2e-6423-4a01-afc1-14822340f15e.gif)
![test-keyword-again-completion-with-clojure](https://user-images.githubusercontent.com/65782666/140882814-0a91980d-4491-4257-98df-b3b98fc89977.gif)

- It's much faster now, but sometimes it isn't fast enough or
 maybe not recognizing specs idk
- Duplications is still an issue
- notice when I typed `user/username` the backspaced to get `:user/` items, it disappear. It would be nice if idk somehow back
- notice when `namespace/` included snippets.

btw, I ran make and pointed nvim lsp to `clojure-lsp-src/clojure-lsp`

**Comment by ericdallo** [comment]
> Duplications is still an issue

I didn't work on that yet, I'll try to understand the duplicates and fix on that branch later today

> Duplications is still an issue

> notice when I typed user/username the backspaced to get :user/ items, it disappear. It would be nice if idk somehow back

Looks odd indeed, I'll take a look as well

> notice when I typed user/username the backspaced to get :user/ items, it disappear. It would be nice if idk somehow back

We can remove the snippets I think in those cases

**Comment by ericdallo** [comment]
@tami5 I think I fixed all issues above 🤞🏻, could you test that branch again please? I already rebased with master

**Comment by tami5** [comment]
Wonderful @ericdallo 

Okay so far

- No more duplication 
- `:userpass` lead to seeing `:user/password` as expected.

Issues:

## appending slash bring irreverent results, e.g. function for unloaded namespace

Clojure-lsp before slash
![Screen Shot 2021-11-10 at 12 45 45 PM](https://user-images.githubusercontent.com/65782666/141090326-16355a05-df94-499b-86d6-ed2d2c00c3e1.png)

Clojure-lsp after slash
![Screen Shot 2021-11-10 at 12 45 51 PM](https://user-images.githubusercontent.com/65782666/141090362-3e008ab8-dada-402c-84f2-454ff4e08c1d.png)


Conjure
![Screen Shot 2021-11-10 at 12 46 42 PM](https://user-images.githubusercontent.com/65782666/141090411-17a28d3a-a73c-4950-8b78-401677329129.png)
![Screen Shot 2021-11-10 at 12 46 53 PM](https://user-images.githubusercontent.com/65782666/141090428-485a192e-6a42-47be-b0b7-118c4956e64e.png)


## Not recognizing d -> `datomic api`
![Screen Shot 2021-11-10 at 12 50 48 PM](https://user-images.githubusercontent.com/65782666/141090624-8f06acd8-0f38-4d36-a782-f725950e643d.png)

Conjure
![Screen Shot 2021-11-10 at 1 00 15 PM](https://user-images.githubusercontent.com/65782666/141092222-ea54527d-a961-49bd-a790-18be1aa7125b.png)
 
## Issue with`::`
![test-namspaced-with-clojure-lsp](https://user-images.githubusercontent.com/65782666/141091559-8dad26c7-3c94-4ec8-9916-736714be9276.gif)

Conjure
![test-namspaced-with-clojure](https://user-images.githubusercontent.com/65782666/141091632-2ed5c944-934a-4a2b-a0be-bbd75110fb4a.gif)

## Missing keywords

Clojure-lsp
![Screen Shot 2021-11-10 at 12 57 42 PM](https://user-images.githubusercontent.com/65782666/141091891-e6110c25-a36d-4e4b-8539-1e44446c5974.png)

Conjure
![Screen Shot 2021-11-10 at 12 58 05 PM](https://user-images.githubusercontent.com/65782666/141091926-c82b1b59-af68-44d8-a389-c7c5f2440c4e.png)

## Using `*`
Not sure if this is a wanted behavior or not, but here's how both show results:
![Screen Shot 2021-11-10 at 1 02 32 PM](https://user-images.githubusercontent.com/65782666/141092707-e3488d93-3798-47fb-888c-57a0094a46fc.png)
![Screen Shot 2021-11-10 at 1 02 35 PM](https://user-images.githubusercontent.com/65782666/141092698-05cd25e5-0d77-472d-a62e-cb42d9509bdd.png)

Conjure
![Screen Shot 2021-11-10 at 1 01 27 PM](https://user-images.githubusercontent.com/65782666/141092744-2ce3dd91-7d2e-4d17-b56f-445e7275c6f1.png)

## Overlapping with snippets 
This one I hated for long time, It would be cool if there is an option that will remove anything that has snippet equivalent, and bring docs to snippets if it's a default symbol i.e. let/defn
 
![Screen Shot 2021-11-10 at 1 06 40 PM](https://user-images.githubusercontent.com/65782666/141093359-2ae74377-dd44-47c6-bfb2-a78f71907ead.png)
![Screen Shot 2021-11-10 at 1 06 45 PM](https://user-images.githubusercontent.com/65782666/141093370-2744d42b-0a27-4029-b497-3ef7a74f4520.png)
![Screen Shot 2021-11-10 at 1 07 01 PM](https://user-images.githubusercontent.com/65782666/141093397-d33a787d-6f68-4d3b-b30c-f71c89514a73.png)
## Performance 

It's definitely a big improvement, but not yet matching conjure performance.

**Comment by ericdallo** [comment]
> appending slash bring irreverent results, e.g. function for unloaded namespace

I could not repro this one, could you give more details or something?

> Issue with::

This one deserves a separate issue, it'd need some work to specifically fix this one

> Missing keywords

This one looks hard to repro, would you mind creating a separate issue for this one with a minimal repro so I can test it and understand it?

> issues with *

Sounds like a vim bug or something else, for me this works

> Not recognizing d -> datomic API

This happens because we don't have datomic source download since it's closed source, we'd nee to have stubs like cursive has or something on clj-kondo first, definitely the hardest one :/

![image](https://user-images.githubusercontent.com/7820865/141116890-e7e1610f-a543-496f-b353-94f813e87b4c.png)

> Overlapping with snippets

This is intended to show snippets if they are match the typed prefix, not sure we could do too much here

> Performance

I can try to improve performance later, I think that PR already fix the keyword performance, now we need to improve the performance overall

**Comment by tami5** [comment]
> This happens because we don't have datomic source download since it's closed source, we'd nee to have stubs like cursive has or something on clj-kondo first, definitely the hardest one :/

Oh makes sense now, I wonder if clojure-lsp can hook into the repl using project/.nrepl. This would speed things up or maybe be a fall-back

> Sounds like a vim bug or something else, for me this works

You are right, overwriting `cmp nvim-lsp` source, made it work
```lua
function source:get_keyword_pattern()
  return [[\%([0-9a-zA-Z\*\+!\-_'?<>=\/.:]*\)]]
end
```

This also fixed `appending slash bring irreverent results, e.g. function for unloaded namespace` and `::` I wonder if the server can send this keyword pattern so I can open a pr in 1cmp nvim-lsp` to receive it.

> This is intended to show snippets if they are match the typed prefix, not sure we could do too much here

I understand but filtering out results would be cool. Maybe better to open an issue for that since it's out of the scope.

> I can try to improve performance later, I think that PR already fix the keyword performance, now we need to improve the performance overall

There is still an issue with the results missing some keywords, maybe on clj-kondo part

**Comment by ericdallo** [comment]
> Oh makes sense now, I wonder if clojure-lsp can hook into the repl using project/.nrepl. This would speed things up or maybe be a fall-back

We use static analysis only on whole clojure-lsp, maybe in the future we could improve that

> This also fixed appending slash bring irreverent results, e.g. function for unloaded namespace and :: I wonder if the server can send this keyword pattern so I can open a pr in 1cmp nvim-lsp` to receive it.

What do you mean? you mean adding `::` as a triggerCharacter?

> I understand but filtering out results would be cool. Maybe better to open an issue for that since it's out of the scope.

Yeah, maybe a snippets opt-out flag

> There is still an issue with the results missing some keywords, maybe on clj-kondo part

I didn't see any missing keywords for me, I'll close this issue merging that PR, I think we can open an issue for each specific case in the future, WDYT?

**Comment by tami5** [comment]
> What do you mean? you mean adding :: as a triggerCharacter?

No I meant that adding ` \%([0-9a-zA-Z\*\+!\-_'?<>=\/.:]*\)` fixed both issues. This is keyword pattern used by the completion plugin, 

> I didn't see any missing keywords for me,

There is see

> ## Missing keywords

> Clojure-lsp
> ![Screen Shot 2021-11-10 at 12 57 42 PM](https://user-images.githubusercontent.com/65782666/141091891-e6110c25-a36d-4e4b-8539-1e44446c5974.png)

> Conjure
> ![Screen Shot 2021-11-10 at 12 58 05 PM](https://user-images.githubusercontent.com/65782666/141091926-c82b1b59-af68-44d8-a389-c7c5f2440c4e.png)

>  I think we can open an issue for each specific case in the future, WDYT?

Sure it would make it easier to track, I will try to do that after the PR is merged, but for now I suggest few trails on performance, maybe do some caching idk.

**Comment by ericdallo** [comment]
> Sure it would make it easier to track, I will try to do that after the PR is merged, but for now I suggest few trails on performance, maybe do some caching idk.

Maybe we could do some kind of cache on the prefix sent previously 🤔

**Comment by ericdallo** [comment]
Anyway, something for another PR IMO

**Comment by ericdallo** [comment]
> I wonder if the server can send this keyword pattern so I can open a pr in 1cmp nvim-lsp` to receive it.

This doesn't fit on LSP protocol right? only if we add a custom method to return that, but I don't know, seems too specific for this case

**Comment by ericdallo** [comment]
Merged, Let's tackle other minor issues in separate issues

**Comment by oblitum** [comment]
How is signatureHelp supposed to be triggered automatically given `signatureHelpProvider.triggerCharacters` comes empty?

**Comment by ericdallo** [comment]
@oblitum, signatureHelpProvider.triggerCharacters is empty since I can't see a char that makes sense to be used for clojure to show signature, for example, for Java, the `(` makes sense as when user is typing `foo(` it's trying to call a method and show its signature makes sense.
But for lisp/clojure, not sure what char we could use

**Comment by oblitum** [comment]
@ericdallo okay but then, how is it showcased in the emacs gifs? In there it gives the impression it comes up automatically.

There's also [this PR on coc.nvim's side](https://github.com/neoclide/coc.nvim/pull/3227), and which got solved!, but until now I can't make sense of it.

**Comment by oblitum** [comment]
From PR, it indeed makes me wonder whether whitespace could be make usable for this. Would also make sense in Haskell.

**Comment by ericdallo** [comment]
It's not automatically because there are no triggerChars for signature, it's manually triggered for emacs calling `lsp-signature-activate`
I don't think whitespace is a good triggerChar, imagine that every whitespace typed would make the client request the server asking for signature

**Comment by oblitum** [comment]
Yeah I know it sounds overkill... and I guess most instances would come empty as it wouldn't be in call site location, but I'd like to try some in this sense for real just to check how it goes, maybe I patch it locally to check how it behaves.

Yes thanks, I also can bring it up manually, but that makes it subpar experience compared with other languages where triggers are simpler to tackle.

**Comment by ericdallo** [comment]
yes, I think it worth a test indeed, but I think it would cause performance issues, even if clojure-lsp doesn't return anything, it needs to query analysis to confirm that.
