### ISSUE TITLE
Support 'find definition/references' for vars defined by macros.

### ISSUE THREAD

**Issue by AlexChalk** [clojure-lsp/clojure-lsp#633]
**Is your feature request related to a problem? Please describe.**

Some community projects implement macros that define vars, like `defstate` from https://github.com/tolitius/mount or `defroutes` from https://github.com/weavejester/compojure. (And some projects implement macros like these ones internally.)

Conceptually, these macros work similarly to `def`, or `defn`, but unlike these, `clojure-lsp` doesn't know how to 'goto definition' or 'find references' for the vars they define.

**Describe the solution you'd like**
I'd like clojure-lsp to support 'goto definition' or 'find references' for vars defined by custom macros like `defstate`.

`clj-kondo` also has issues with macros, and they're sometimes solved with [hooks](https://github.com/clj-kondo/clj-kondo/blob/911feec52b797de2192cf8bbdee89f701c459105/doc/hooks.md), or with a config like this in `.clj-kondo/config.edn`:
```
{:linters {:lint-as {mount.core/defstate clojure.core/def}}}
```

Perhaps a similar config is possible in `.lsp/config.edn`, something like this:
```
{:macros {:parse-as {mount.core/defstate clojure.core/def}}}
```
or maybe just something like this:
```
{:extend-var-defs [(mount.core/defstate)]}
```

or maybe you'd need something more involved like clj-kondo hooks.

I'm not familiar with the codebase, so those particular config suggestions might be way off, and I don't mind how the config is structured anyway. But hopefully it gives an idea of what I'm after: a way of configuring clojure-lsp to say, 'hey, treat invocations of these functions like a fancy version of `def`'.

**Describe alternatives you've considered**
I don't know to be honest. Maybe there's some way of leveraging an existing clj-kondo configuration to get this kind of functionality? But if that's even possible it seems overcomplicated and adds unnecessary coupling to clj-kondo.

**Additional context**
Happy to help if I can get some guidance on where to make any approved changes.

**Comment by ericdallo** [comment]
@AlexChalk this is already possible if you code the hook for the macro correctly, an example of that is the [stateflow](https://github.com/nubank/state-flow/blob/master/resources/clj-kondo.exports/nubank/state-flow/config.edn#L2) macro.
There is nothing we can do on clojure-lsp side as this is totally something that should be done on clj-kondo config side creating custom hooks for those macros, LMK if you need more details
