### ISSUE TITLE
Could work on edn files

### ISSUE THREAD

**Issue by mynomoto** [clojure-lsp/clojure-lsp#634]
**Is your feature request related to a problem? Please describe.**
I have some edn configuration files that references keywords from code and would like to find-references to navigate to the files.
I have a bb.edn with tasks and would like to find code errors on them.

**Describe the solution you'd like**
clojure-lsp features that make sense would work on edn files.

**Describe alternatives you've considered**
I use grep to find keywords and hope that they are explicit on the code and if I find one I use find-references to find others. Or I add the keyword to some clojure file and use find-references there.
I hope that my bb.edn files have no errors that clojure-lsp could have found.

**Comment by ericdallo** [comment]
yeah, that makes sense indeed, we would need to make first clj-kondo understand and provide analysis for .edn files, WDYT @borkdude?

**Comment by borkdude** [comment]
@ericdallo yes

**Comment by elken** [comment]
I'm also interested in this, per a discussion on Slack https://github.com/clj-kondo/clj-kondo/issues/1926 has been created to track the feature in kondo, after which it should be possible to implement :)

**Comment by elken** [comment]
@ericdallo This can be closed now yes?

**Comment by ericdallo** [comment]
Yay!
