### ISSUE TITLE
`[Add <ns> :refer [<sym>]` code action generate a duplicate mention of the added namespace

### ISSUE THREAD

**Issue by viebel** [clojure-lsp/clojure-lsp#640]
Overall, it works very well.
But in cases of subsequent additions of symbols from the same namespace, it could work better.

Suppose I am starting from the following code:

```clj
(ns my.foo)

(defn bar []
  (upper-case "aaa")
  (lower-case "bbb"))
```

When the cursor is on `upper-case`, I see a code action `Add [clojure.string :refer [upper-case]]`,  that works exactly as expected.
However, if after applying the action, I apply a similar action on `lower-case`,  it creates a second mention of clojure.string in the ns form leading to this code:
```clj
(ns my.foo 
  (:require
   [clojure.string :refer [upper-case]]
   [clojure.string :refer [lower-case]]))

(defn bar []
  (upper-case "aaa")
  (lower-case "bbb"))
```
It causes a clojure-lsp warning `duplicate require of clojure.string`. I would prefer to have the second action generate a single mention of clojure.string.

**Comment by ericdallo** [comment]
thanks for the report, I was aware of this bug, it was not trivial to fix it, I'll take a look again how hard would be to fix it

**Comment by ericdallo** [comment]
I made a refactor and fixed this one 779ee8a

**Comment by viebel** [comment]
It seems that the code action is broken.
On latest master,  commit id b72f68a34978104ec4e35b980504503f38113262, after triggering it, I am getting an invalid `ns` form:

```clj
(ns gadjett.aa 
  (:require
    [clojure.string :refer [upper-case]]))
  (:require
    [clojure.string :refer [upper-case]]))


(defn foo []
  (upper-case "aaa")
  (lower-case "BBB"))
```

**Comment by ericdallo** [comment]
@viebel what editor are you using?
For me latest master is working properly with this issue fixed, also all tests are passing, so it's weird this behavior only happening for you:

![code-actions](https://user-images.githubusercontent.com/7820865/141686276-d70a2e2a-db24-4585-aab8-c223a5d3abcb.gif)
