### ISSUE TITLE
[Feature Request] code action: new namespace and new namesapce functions/vars

### ISSUE THREAD

**Issue by tami5** [clojure-lsp/clojure-lsp#646]
**Is your feature request related to a problem? Please describe.**

I always find my self starting new project and requiring namespace before creating them, e.g. writing`com.appx.db` in require block, then running` goToDefinition` on the symbol as if I already created it

**Describe the solution you'd like**

`goToDefinition` interrupt and handle a condition that state:

If **symbol not found** and **in require block**  e.g. `(ns ... (:require [com.appx.db :as db]))` *then* send fake response to switch to the new file path.

**Describe alternatives you've considered**

hmm it could be possible to wrap my go to definition shortcut to check first that case and create new file or jump to the actual symbol. Though, it sound hacky 🤔 and exclusive.

**Comment by ericdallo** [comment]
@tami5 I'm afraid we can achive that but on other way, instead of trying to find the definition and we do something different like create the namespace, we return a code action to allow create that namespace, WDYT? we already have something similar when you are in a line that contains a `unresolved-symbol`, we then return a code action to create a `private function`, that would be similar but to create the namespace on a require or in an usage like :
```clojure
(ns foo
  (:require [baz.bar])) ;; Show code action: "Create baz.bar namespace"

(foo.bar/something) ;; show code action: "Create foo.bar namespace"
```

**Comment by ericdallo** [comment]
the advantage I see on the second one is that we can automatically require the ns after creating :)

**Comment by tami5** [comment]
> @tami5 I'm afraid we can achive that but on other way, instead of trying to find the definition and we do something different like create the namespace, we return a code action to allow create that namespace, WDYT?

hmmm, idk, on one hand it seems better for user discoverability to have it as code action, on the other, it feels more natural,  `(if symbol doesn't exist create it, else go to it)`. Perhaps, the code action could be first implemented  then an experimental option to upgrade `GoToDefinition` Functionality wdyt?

btw here's a quick edit on the behaviors:

```clj
(ns foo
  (:require [baz.bar])) ;; Show code action: "Create baz.bar namespace"

(foo.bar/something) ;; show code action: "Create foo.bar namespace AND something function"
(foo.bar/something arg1 arg2) ;; include arguments
foo.bar/something ;; show code action: "Create foo.bar namespace AND something var"
```

> the advantage I see on the second one is that we can automatically require the ns after creating :)

How so? didn't get that one

**Comment by ericdallo** [comment]
Honestly, I don't like the idea of creating something when trying to find a definition.

> How so? didn't get that one

We already have a feature that when you try to complete a unrequited ns, we auto add that to the requires, the code action would be similar, we'd create the namespace (and function) and then require it on the current namespace

**Comment by tami5** [comment]
Oh I see it's more consistent with requiring namespaces action. good call

**Comment by tami5** [comment]
😆 I didn't update my page srry

**Comment by ericdallo** [comment]
@tami5, I implemented 2 new code actions: `Create namespace 'foo' and 'bar' function` and `Create function 'bar' on 'foo'` following those cases, the code action already require the new ns as well :)
Available on next release, couple of days
