### ISSUE TITLE
Add sort map literal keys command

### ISSUE THREAD

**Issue by justone** [clojure-lsp/clojure-lsp#651]
**Is your feature request related to a problem? Please describe.**
Thank you for all of the refactoring actions included in clojure-lsp. I've grown to rely on them for my daily editing. One thing that would be wonderful as a command would be the ability to sort the keys of map literals. I end up with several of these throughout my code and sometimes I get them from imported data or fail to keep the keys properly alphabetized, and so I manually sort the keys so that they are easy to find. This always ends up taking more keystrokes than I like (need to move the first key from behind the opening curly and the closing curly brace from the end, select lines, sort, then join lines back together).

**Describe the solution you'd like**
When my cursor is on a map literal and I open the code actions palette, there would be a "Sort map keys" action that would sort the keys of the map literal.

**Describe alternatives you've considered**
Currently, I sort my map literals manually. I've considered writing some vimscript (or lua) to accomplish this task.

**Additional context**
```clojure
; Before
(def person
  {:height 72
   :age 42
   :weight 22})

; After
(def person
  {:age 42
   :height 72
   :weight 22})
```
I definitely understand that time and resources are limited and this might not make the cut. I appreciate all you do for the community.

**Comment by ericdallo** [comment]
thanks for the report, it sounds a good refactor, we need to check how hard would be to do it with rewrite-clj + performance for code actions, if the performance is huge, we should add only as a refactoring command

**Comment by ericdallo** [comment]
I'll try to take a look at this on weekend

**Comment by ericdallo** [comment]
Related https://github.com/clojure-emacs/clj-refactor.el/issues/32

**Comment by ericdallo** [comment]
Available on next release!
![sort-map](https://user-images.githubusercontent.com/7820865/143666169-0df76a51-cedb-4179-9470-f94437af9f7e.gif)
