### ISSUE TITLE
Provide information on tests

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#653]
It would be nice if clojure-lsp provided information on tests in a codebase, such as line numbers, test names, and maybe other metadata.

**Comment by ericdallo** [comment]
That's something nice modern LSPs have like Dart/Flutter LSP, it's not LSP official(yet?), it returns a tree hierarchy of tests because it's allowed to have nested tests, but for clojure this may be easier I believe?

@borkdude doyou see something clojure-lsp could use from kondo analysis for that kind of info?

**Comment by borkdude** [comment]
Aren't you already using this info from clj-kondo? Tests are just vars that are available in `:var-definitions` and they have, like every var, `:row`, `:end-row`, etc.

**Comment by ericdallo** [comment]
Yeah, I was thinking more about this ([ref](https://dartcode.org/releases/v3-27/)) for example:
![image](https://user-images.githubusercontent.com/7820865/143771179-98b13728-0c45-4cd3-b7c1-c988ca9961f8.png)

Create a test hierarchy for each nested `testing` in a deftest or something like that.
We could check each line/row of each testing but not sure would be easy or if there is a better way to handle that

**Comment by borkdude** [comment]
There is a better approach, we can use the new `:context` "architecture" to add the `testing` context to the var usages. I'm not 100% sure of your use case, please make it more concrete.

**Comment by ericdallo** [comment]
I'll do some testing and research to check what kind of info we would need, but using context sounds like a good idea to me

**Comment by ericdallo** [comment]
For the code below I was thinking about something like:
```clojure
(deftest foo
  (testing "bar 1"
    (is true))
  (testing "bar 2"
    (testing "bar 3"
      (is true))
    (testing "bar 4"
      (is true))))
```
A new notification from clojure-lsp, called `clojure/textDocument/testTree` with the following data for that code:
```clojure
{:uri "..."
 :tests [{:name "foo"
          :range {:start {:line 1 :character 1} :end {:line 8 :character 18}}
          :name-range {:start {:line 1 :character 10} :end {:line 1 :character 12}}
          :kind :deftest
          :children [{:name "bar 1"
                      :range {:start {:line 2 :character 3} :end {:line 3 :character 14}}
                      :name-range {:start {:line 2 :character 13} :end {:line 2 :character 17}}
                      :kind :testing}
                     {:name "bar 2"
                      :range {:start {:line 4 :character 3} :end {:line 8 :character 17}}
                      :name-range {:start {:line 4 :character 13} :end {:line 4 :character 17}}
                      :kind :testing
                      :children [{:name "bar 3"
                                  :range {:start {:line 5 :character 5} :end {:line 6 :character 16}}
                                  :name-range {:start {:line 5 :character 15} :end {:line 5 :character 19}}
                                  :kind :testing}
                                 {:name "bar 4"
                                  :range {:start {:line 7 :character 5} :end {:line 8 :character 16}}
                                  :name-range {:start {:line 7 :character 15} :end {:line 7 :character 19}}
                                  :kind :testing}]}]}]}
```

WDYT @bpringe? would that help as a first iteration? in the future we could enhance that with more details.

@borkdude from what I can see, we would need information about `testing`, including its location and the location of the testing string, right?

**Comment by borkdude** [comment]
`testing` is just a var that's being called, so we already have the locations for that I think? (I haven't checked)
we can add `:context {:clojure.test {:testing-str "...."}}` or so to the call.

**Comment by ericdallo** [comment]
Yes, I think that should work, the logic would be on clojure-lsp side which I think makes sense

**Comment by borkdude** [comment]
I'm fine with having this logic in clj-kondo itself btw.

**Comment by ericdallo** [comment]
@borkdude you mean add more besides the testing-str?

**Comment by borkdude** [comment]
I mean, having the context data as a built-in thing rather than a custom hook. The nesting structure as you described above should be in LSP.

**Comment by ericdallo** [comment]
oh yeah, I was not thinking about any extra hook indeed, alright, so I'll start with the `testing-str` only on the context

**Comment by bpringe** [comment]
> WDYT @bpringe? would that help as a first iteration? in the future we could enhance that with more details.

That looks good to me, but @marcomorain is doing test-related work and would be using this, I think, so I'm including him here too.

**Comment by ericdallo** [comment]
@bpringe @borkdude 
I started implementing both on clojure-lsp and emacs to see how would look, check it out:
![image](https://user-images.githubusercontent.com/7820865/145319248-6d1e98ce-4c4b-423e-9ac7-0a1b6b13efcf.png)

**Comment by bpringe** [comment]
That's great! I'm guessing `mock` is a placeholder and should/will say the string passed to `testing`, like `bar 1`, etc.?

**Comment by ericdallo** [comment]
Exactly, borkdude is finishing adding that to kondo and then clojure-lsp will return the correct testing name :)

**Comment by borkdude** [comment]
Merged to master on kondo.

**Comment by ericdallo** [comment]
Done, available on next release!
The documentation about the custom notification can be found [here](https://clojure-lsp.io/capabilities/#test-tree), but basically, client need to provide a extra capability under `experimental` called `testTree` as `true`, then server will start to send notifications of type `clojure/textDocument/testTree`, which client can listen and build the tree data.
Also, Implemented the client side of this feature on Emacs lsp-mode [here](https://github.com/emacs-lsp/lsp-mode/pull/3250) if you want an example.

![image](https://user-images.githubusercontent.com/7820865/145721199-bcaf7e42-c063-46c3-823f-7f6272407028.png)

**Comment by bpringe** [comment]
Awesome!
