### ISSUE TITLE
Return edits in codeAction/resolve responses rather than commands

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#655]
**Is your feature request related to a problem? Please describe.**

vscode-languageclient / VS Code (I'm not sure which handles this exactly) doesn't support commands being returned in the `codeAction/resolve` request. It only sends 'edit' as a property for its resolve support.

This means Calva has to manually take the command and args from the `codeAction/resolve` response and send a `workspace/executeCommand` request.

**Describe the solution you'd like**

The protocol seems to say that edits can (and maybe should) be returned in `codeAction/resolve` responses, rather than commands. I believe this would cause the edit to be applied when a code action is run by the user without Calva having to do something itself.

**Additional context**

* https://microsoft.github.io/language-server-protocol/specifications/specification-current/#codeAction_resolve
* More details in this issue: https://github.com/microsoft/vscode-languageserver-node/issues/864

**Comment by ericdallo** [comment]
Done, available on next release
