### ISSUE TITLE
Renaming namespaced keywords not working as expected

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#665]
**Describe the bug**
When I rename a namespaced keyword using VS Code and Calva, the result is not what I expect

**To Reproduce**

Example code:

``` clojure
(reg-event-db
 ::hello-world
 (fn [db]
   (assoc db :hello "world")))
```
1. Place cursor on `::hello-world`
2. Run `Rename Symbol` (F2)
3. Insert `:hello/world` as the new symbol name
4. See that the keyword is renamed to `::world`

**Expected behavior**
I expect the keyword to be renamed to `:hello/world`.

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
[Trace - 2:33:08 PM] Sending request 'textDocument/prepareRename - (2010)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/brandon/development/honestdeed/honestdeed-app/src/honestdeed/facilities.cljs"
    },
    "position": {
        "line": 13,
        "character": 9
    }
}

[Trace - 2:33:08 PM] Received response 'textDocument/prepareRename - (2010)' in 17ms.
Result: {
    "start": {
        "line": 13,
        "character": 1
    },
    "end": {
        "line": 13,
        "character": 14
    }
}

[Trace - 2:33:11 PM] Sending request 'textDocument/rename - (2011)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/brandon/development/honestdeed/honestdeed-app/src/honestdeed/facilities.cljs"
    },
    "position": {
        "line": 13,
        "character": 9
    },
    "newName": ":hello/world"
}

[Trace - 2:33:11 PM] Received response 'textDocument/rename - (2011)' in 13ms.
Result: {
    "documentChanges": [
        {
            "textDocument": {
                "version": 164,
                "uri": "file:///Users/brandon/development/honestdeed/honestdeed-app/src/honestdeed/facilities.cljs"
            },
            "edits": [
                {
                    "range": {
                        "start": {
                            "line": 13,
                            "character": 1
                        },
                        "end": {
                            "line": 13,
                            "character": 14
                        }
                    },
                    "newText": "::world"
                }
            ]
        }
    ]
}
</pre>
</details>

There were no relevant exceptions in the clojure-lsp logs.

**User details (please complete the following information):**
 - OS: MacOS
 - Editor: VS Code (Calva)
 - Version: 2021.12.01-12.28.16

**Comment by ericdallo** [comment]
So the issue is related with renaming/converting a implicit namespace keyword to a explicit one?
is this that common?
anyway, I think makes sense to fix it

**Comment by bpringe** [comment]
Yes. I'm not sure how common it is, but I'm doing that in code base that uses re-frame, in which I started out using the double colon (`::`) syntax and [decided to move away from it](https://purelyfunctional.tv/issues/purelyfunctional-tv-newsletter-430-use-keyword-notation-for-unique-values/).
