### ISSUE TITLE
Inline symbol doesn't do anything

### ISSUE THREAD

**Issue by blueskyonmars** [clojure-lsp/clojure-lsp#678]
**Describe the bug**
In Calva when I use Calva Refactor: Inline Symbol, it doesn't inline the symbol.

**To Reproduce**
1. Create a new lein project, open in Calva
2. go to core.clj, add this code:
3. 
```
(let [x 5
 x 5
 improved-x (inc x)]
 (when (seq [])
  (when (= x 5)
      (seq (vec improved-x)))))
```
3. stand on improved-x and do Command P > Calva Refactor: Inline Symbol

**Expected behavior**
I expected the (inc x) to be put in place like this:
```
(let [x 5
 x 5]
 (when (seq [])
  (when (= x 5)
      (seq (vec (inc x))))))
```

**Screenshots**

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
[Trace - 5:31:57 PM] Sending request 'initialize - (0)'.
Params: {
    "processId": 60244,
    "clientInfo": {
        "name": "Visual Studio Code",
        "version": "1.63.2"
    },
    "locale": "en-us",
    "rootPath": "/private/tmp/foo",
    "rootUri": "file:///private/tmp/foo",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional",
                "normalizesLineEndings": true,
                "changeAnnotationSupport": {
                    "groupsOnLabel": true
                }
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                }
            },
            "codeLens": {
                "refreshSupport": true
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true,
            "semanticTokens": {
                "refreshSupport": true
            },
            "fileOperations": {
                "dynamicRegistration": true,
                "didCreate": true,
                "didRename": true,
                "didDelete": true,
                "willCreate": true,
                "willRename": true,
                "willDelete": true
            }
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true,
                "versionSupport": false,
                "tagSupport": {
                    "valueSet": [
                        1,
                        2
                    ]
                },
                "codeDescriptionSupport": true,
                "dataSupport": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true,
                    "tagSupport": {
                        "valueSet": [
                            1
                        ]
                    },
                    "insertReplaceSupport": true,
                    "resolveSupport": {
                        "properties": [
                            "documentation",
                            "detail",
                            "additionalTextEdits"
                        ]
                    },
                    "insertTextModeSupport": {
                        "valueSet": [
                            1,
                            2
                        ]
                    }
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    },
                    "activeParameterSupport": true
                },
                "contextSupport": true
            },
            "definition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true,
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "labelSupport": true
            },
            "codeAction": {
                "dynamicRegistration": true,
                "isPreferredSupport": true,
                "disabledSupport": true,
                "dataSupport": true,
                "resolveSupport": {
                    "properties": [
                        "edit"
                    ]
                },
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                },
                "honorsChangeAnnotations": false
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true,
                "prepareSupportDefaultBehavior": 1,
                "honorsChangeAnnotations": true
            },
            "documentLink": {
                "dynamicRegistration": true,
                "tooltipSupport": true
            },
            "typeDefinition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "implementation": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            },
            "declaration": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "selectionRange": {
                "dynamicRegistration": true
            },
            "callHierarchy": {
                "dynamicRegistration": true
            },
            "semanticTokens": {
                "dynamicRegistration": true,
                "tokenTypes": [
                    "namespace",
                    "type",
                    "class",
                    "enum",
                    "interface",
                    "struct",
                    "typeParameter",
                    "parameter",
                    "variable",
                    "property",
                    "enumMember",
                    "event",
                    "function",
                    "method",
                    "macro",
                    "keyword",
                    "modifier",
                    "comment",
                    "string",
                    "number",
                    "regexp",
                    "operator"
                ],
                "tokenModifiers": [
                    "declaration",
                    "definition",
                    "readonly",
                    "static",
                    "deprecated",
                    "abstract",
                    "async",
                    "modification",
                    "documentation",
                    "defaultLibrary"
                ],
                "formats": [
                    "relative"
                ],
                "requests": {
                    "range": true,
                    "full": {
                        "delta": true
                    }
                },
                "multilineTokenSupport": false,
                "overlappingTokenSupport": false
            },
            "linkedEditingRange": {
                "dynamicRegistration": true
            }
        },
        "window": {
            "showMessage": {
                "messageActionItem": {
                    "additionalPropertiesSupport": true
                }
            },
            "showDocument": {
                "support": true
            },
            "workDoneProgress": true
        },
        "general": {
            "regularExpressions": {
                "engine": "ECMAScript",
                "version": "ES2020"
            },
            "markdown": {
                "parser": "marked",
                "version": "1.1.0"
            }
        }
    },
    "initializationOptions": {
        "dependency-scheme": "jar",
        "auto-add-ns-to-new-files?": true,
        "document-formatting?": false,
        "document-range-formatting?": false,
        "keep-require-at-start?": true
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///private/tmp/foo",
            "name": "foo"
        }
    ]
}

[Trace - 5:31:58 PM] Received notification '$/progress'.
Params: {
    "token": "clojure-lsp",
    "value": {
        "kind": "begin",
        "title": "clojure-lsp",
        "percentage": 0
    }
}

[Trace - 5:31:58 PM] Received notification '$/progress'.
Params: {
    "token": "clojure-lsp",
    "value": {
        "kind": "report",
        "message": "Finding kondo config",
        "percentage": 5
    }
}

[Trace - 5:31:58 PM] Received notification '$/progress'.
Params: {
    "token": "clojure-lsp",
    "value": {
        "kind": "report",
        "message": "Finding project specs",
        "percentage": 8
    }
}

[Trace - 5:31:58 PM] Received notification '$/progress'.
Params: {
    "token": "clojure-lsp",
    "value": {
        "kind": "report",
        "message": "Finding cache",
        "percentage": 10
    }
}

[Trace - 5:31:58 PM] Received notification '$/progress'.
Params: {
    "token": "clojure-lsp",
    "value": {
        "kind": "report",
        "message": "Discovering classpath",
        "percentage": 15
    }
}

[Trace - 5:31:58 PM] Received notification '$/progress'.
Params: {
    "token": "clojure-lsp",
    "value": {
        "kind": "report",
        "message": "Resolving config paths",
        "percentage": 90
    }
}

[Trace - 5:31:58 PM] Received notification '$/progress'.
Params: {
    "token": "clojure-lsp",
    "value": {
        "kind": "report",
        "message": "Analyzing project files",
        "percentage": 95
    }
}

[Trace - 5:31:58 PM] Received notification '$/progress'.
Params: {
    "token": "clojure-lsp",
    "value": {
        "kind": "end",
        "message": "Project analyzed"
    }
}

[Trace - 5:31:59 PM] Received response 'initialize - (0)' in 1273ms.
Result: {
    "capabilities": {
        "textDocumentSync": {
            "openClose": true,
            "change": 1,
            "save": {
                "includeText": true
            }
        },
        "hoverProvider": true,
        "completionProvider": {
            "resolveProvider": true,
            "triggerCharacters": [
                ":",
                "/"
            ]
        },
        "signatureHelpProvider": {
            "triggerCharacters": []
        },
        "definitionProvider": true,
        "referencesProvider": true,
        "documentHighlightProvider": true,
        "documentSymbolProvider": true,
        "workspaceSymbolProvider": true,
        "codeActionProvider": {
            "codeActionKinds": [
                "quickfix",
                "refactor",
                "refactor.extract",
                "refactor.inline",
                "refactor.rewrite",
                "source",
                "source.organizeImports"
            ],
            "resolveProvider": true
        },
        "codeLensProvider": {
            "resolveProvider": true
        },
        "documentFormattingProvider": false,
        "documentRangeFormattingProvider": false,
        "renameProvider": {
            "prepareProvider": true
        },
        "executeCommandProvider": {
            "commands": [
                "add-missing-libspec",
                "add-import-to-namespace",
                "cycle-privacy",
                "create-test",
                "change-coll",
                "thread-last-all",
                "unwind-all",
                "move-to-let",
                "clean-ns",
                "suppress-diagnostic",
                "thread-last",
                "introduce-let",
                "sort-map",
                "unwind-thread",
                "thread-first-all",
                "thread-first",
                "inline-symbol",
                "extract-function",
                "cycle-coll",
                "expand-let",
                "create-function"
            ]
        },
        "callHierarchyProvider": true,
        "linkedEditingRangeProvider": true,
        "semanticTokensProvider": {
            "legend": {
                "tokenTypes": [
                    "namespace",
                    "type",
                    "function",
                    "macro",
                    "keyword",
                    "class",
                    "variable",
                    "method",
                    "event"
                ],
                "tokenModifiers": [
                    "definition",
                    "defaultLibrary"
                ]
            },
            "range": true,
            "full": true
        },
        "experimental": {
            "testTree": true,
            "cursorInfo": true,
            "serverInfo": true,
            "clojuredocs": true
        }
    }
}

[Trace - 5:31:59 PM] Sending notification 'initialized'.
Params: {}

[Trace - 5:31:59 PM] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {}
}

[Trace - 5:31:59 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/foo/src/foo/core.clj",
        "languageId": "clojure",
        "version": 1,
        "text": "(ns foo.core)\n\n(defn foo\n  \"I don't do a whole lot.\"\n  [x]\n  (println x \"Hello, World!\"))\n\n(let [x 5\n x 5\n improved-x (inc x)]\n (when (seq [])\n  (when (= x 5)\n      (seq (vec improved-x)))))\n"
    }
}

[Trace - 5:31:59 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/foo/.calva/output-window/output.calva-repl",
        "languageId": "clojure",
        "version": 1,
        "text": "; This is the Calva evaluation results output window.\n; TIPS: The keyboard shortcut `ctrl+alt+c o` shows and focuses this window\n;   when connected to a REPL session.\n; Please see https://calva.io/output/ for more info.\n; Happy coding! ♥️\n\n; Jacking in...\n; Starting Jack-in Terminal: lein update-in :dependencies conj '[nrepl,\"0.8.3\"]' -- update-in :plugins conj '[cider/cider-nrepl,\"0.26.0\"]' -- update-in '[:repl-options,:nrepl-middleware]' conj '[\"cider.nrepl/cider-middleware\"]' -- repl :headless\n; Hooking up nREPL sessions...\n; Connected session: clj\n; TIPS: \n;   - You can edit the contents here. Use it as a REPL if you like.\n;   - `alt+enter` evaluates the current top level form.\n;   - `ctrl+enter` evaluates the current form.\n;   - `alt+up` and `alt+down` traverse up and down the REPL command history\n;      when the cursor is after the last contents at the prompt\n;   - Clojure lines in stack traces are peekable and clickable.\nclj꞉foo.core꞉>  ; Use `alt+enter` to evaluate\n; Jack-in done.\nclj꞉foo.core꞉> \nnil\nclj꞉foo.core꞉> \n#'foo.core/foo\nclj꞉foo.core꞉> \n#'foo.core/mynewfunc2\nclj꞉foo.core꞉> \n('(42))\nclj꞉foo.core꞉> \n#'foo.core/here-is-a-test\nclj꞉foo.core꞉> \n42\nclj꞉foo.core꞉> \n; nREPL Connection was closed\n"
    }
}

[Trace - 5:31:59 PM] Sending request 'clojure/serverInfo/raw - (1)'.
[Trace - 5:31:59 PM] Sending request 'textDocument/documentSymbol - (2)'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/foo/src/foo/core.clj"
    }
}

[Trace - 5:31:59 PM] Sending request 'textDocument/documentSymbol - (3)'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/foo/.calva/output-window/output.calva-repl"
    }
}

[Trace - 5:31:59 PM] Sending request 'textDocument/codeAction - (4)'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/foo/src/foo/core.clj"
    },
    "range": {
        "start": {
            "line": 9,
            "character": 6
        },
        "end": {
            "line": 9,
            "character": 6
        }
    },
    "context": {
        "diagnostics": []
    }
}

[Trace - 5:31:59 PM] Sending request 'textDocument/codeAction - (5)'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/foo/.calva/output-window/output.calva-repl"
    },
    "range": {
        "start": {
            "line": 32,
            "character": 0
        },
        "end": {
            "line": 32,
            "character": 0
        }
    },
    "context": {
        "diagnostics": []
    }
}

[Trace - 5:31:59 PM] Received request 'client/registerCapability - (1)'.
Params: {
    "registrations": [
        {
            "id": "id",
            "method": "workspace/didChangeWatchedFiles",
            "registerOptions": {
                "watchers": [
                    {
                        "globPattern": "**/*.{clj,cljs,cljc,edn}"
                    }
                ]
            }
        }
    ]
}

[Trace - 5:31:59 PM] Sending response 'client/registerCapability - (1)'. Processing request took 1ms
No result returned.

[Trace - 5:31:59 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///private/tmp/foo/src/foo/core.clj",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 2,
                    "character": 6
                },
                "end": {
                    "line": 2,
                    "character": 9
                }
            },
            "severity": 3,
            "code": "clojure-lsp/unused-public-var",
            "source": "clojure-lsp",
            "message": "Unused public var 'foo.core/foo'",
            "tags": [
                1
            ]
        },
        {
            "range": {
                "start": {
                    "line": 7,
                    "character": 6
                },
                "end": {
                    "line": 7,
                    "character": 7
                }
            },
            "severity": 2,
            "code": "unused-binding",
            "source": "clj-kondo",
            "message": "unused binding x",
            "tags": [
                1
            ]
        }
    ]
}

[Trace - 5:31:59 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///private/tmp/foo/.calva/output-window/output.calva-repl",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 0
                }
            },
            "severity": 1,
            "code": "syntax",
            "source": "clj-kondo",
            "message": "Can't parse /private/tmp/foo/.calva/output-window/output.calva-repl, No matching clause: :unknown",
            "tags": []
        }
    ]
}

[Trace - 5:31:59 PM] Received response 'clojure/serverInfo/raw - (1)' in 87ms.
Result: {
    "client-settings": {
        "auto-add-ns-to-new-files?": true,
        "cljfmt": {
            "indents": {}
        },
        "document-formatting?": false,
        "dependency-scheme": "jar",
        "keep-require-at-start?": true,
        "document-range-formatting?": false,
        "cljfmt-config-path": ".cljfmt.edn"
    },
    "project-root-uri": "file:///private/tmp/foo",
    "clj-kondo-version": "2021.12.19",
    "final-settings": {
        "auto-add-ns-to-new-files?": true,
        "cljfmt": {
            "indents": {}
        },
        "document-formatting?": false,
        "dependency-scheme": "jar",
        "keep-require-at-start?": true,
        "source-paths": [
            "/private/tmp/foo/src",
            "/private/tmp/foo/src/main/clojure",
            "/private/tmp/foo/test",
            "/private/tmp/foo/src/test/clojure"
        ],
        "project-specs": [
            {
                "project-path": "project.clj",
                "classpath-cmd": [
                    "lein",
                    "classpath"
                ]
            },
            {
                "project-path": "deps.edn",
                "classpath-cmd": [
                    "clojure",
                    "-A:dev:test",
                    "-Spath"
                ]
            },
            {
                "project-path": "build.boot",
                "classpath-cmd": [
                    "boot",
                    "show",
                    "--fake-classpath"
                ]
            },
            {
                "project-path": "shadow-cljs.edn",
                "classpath-cmd": [
                    "npx",
                    "shadow-cljs",
                    "classpath"
                ]
            },
            {
                "project-path": "bb.edn",
                "classpath-cmd": [
                    "bb",
                    "print-deps",
                    "--format",
                    "classpath"
                ]
            }
        ],
        "source-aliases": [
            {},
            {}
        ],
        "uri-format": {
            "upper-case-drive-letter?": false,
            "encode-colons-in-path?": false
        },
        "document-range-formatting?": false,
        "cljfmt-config-path": ".cljfmt.edn"
    },
    "port": "NREPL only available on :debug profile (`make debug-bin`)",
    "server-version": "2021.12.20-00.36.56",
    "log-path": "/var/folders/39/rw0jd1p90nl6_rpx4gdpj4gr0000gn/T/clojure-lsp.9476110582869549336.out",
    "project-settings": {}
}

[Trace - 5:31:59 PM] Received response 'textDocument/documentSymbol - (2)' in 102ms.
Result: [
    {
        "name": "foo.core",
        "kind": 3,
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 999999,
                "character": 999999
            }
        },
        "selectionRange": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 12
            }
        },
        "children": [
            {
                "name": "foo",
                "kind": 12,
                "range": {
                    "start": {
                        "line": 2,
                        "character": 0
                    },
                    "end": {
                        "line": 5,
                        "character": 30
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 2,
                        "character": 6
                    },
                    "end": {
                        "line": 2,
                        "character": 9
                    }
                }
            }
        ]
    }
]

[Trace - 5:31:59 PM] Received response 'textDocument/documentSymbol - (3)' in 109ms.
Result: [
    {
        "name": "/private/tmp/foo/.calva/output-window/output.calva-repl",
        "kind": 21,
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 999999,
                "character": 999999
            }
        },
        "selectionRange": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 999999,
                "character": 999999
            }
        },
        "children": []
    }
]

[Trace - 5:31:59 PM] Received response 'textDocument/codeAction - (4)' in 115ms.
Result: [
    {
        "title": "Inline symbol",
        "kind": "refactor.inline",
        "data": {
            "id": "refactor-inline-symbol",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 9,
            "character": 6
        }
    },
    {
        "title": "Move to let",
        "kind": "refactor.extract",
        "data": {
            "id": "refactor-move-to-let",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 9,
            "character": 6
        }
    },
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "data": {
            "id": "clean-ns",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 9,
            "character": 6
        }
    }
]

[Trace - 5:31:59 PM] Received response 'textDocument/codeAction - (5)' in 122ms.
Result: [
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "data": {
            "id": "clean-ns",
            "uri": "file:///private/tmp/foo/.calva/output-window/output.calva-repl",
            "line": 32,
            "character": 0
        }
    }
]

[Trace - 5:31:59 PM] Sending request 'textDocument/codeAction - (6)'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/foo/src/foo/core.clj"
    },
    "range": {
        "start": {
            "line": 9,
            "character": 6
        },
        "end": {
            "line": 9,
            "character": 6
        }
    },
    "context": {
        "diagnostics": []
    }
}

[Trace - 5:31:59 PM] Received response 'textDocument/codeAction - (6)' in 10ms.
Result: [
    {
        "title": "Inline symbol",
        "kind": "refactor.inline",
        "data": {
            "id": "refactor-inline-symbol",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 9,
            "character": 6
        }
    },
    {
        "title": "Move to let",
        "kind": "refactor.extract",
        "data": {
            "id": "refactor-move-to-let",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 9,
            "character": 6
        }
    },
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "data": {
            "id": "clean-ns",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 9,
            "character": 6
        }
    }
]

[Trace - 5:31:59 PM] Sending request 'textDocument/codeAction - (7)'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/foo/src/foo/core.clj"
    },
    "range": {
        "start": {
            "line": 9,
            "character": 6
        },
        "end": {
            "line": 9,
            "character": 6
        }
    },
    "context": {
        "diagnostics": []
    }
}

[Trace - 5:31:59 PM] Sending request 'textDocument/codeAction - (8)'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/foo/.calva/output-window/output.calva-repl"
    },
    "range": {
        "start": {
            "line": 32,
            "character": 0
        },
        "end": {
            "line": 32,
            "character": 0
        }
    },
    "context": {
        "diagnostics": []
    }
}

[Trace - 5:31:59 PM] Received response 'textDocument/codeAction - (8)' in 31ms.
Result: [
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "data": {
            "id": "clean-ns",
            "uri": "file:///private/tmp/foo/.calva/output-window/output.calva-repl",
            "line": 32,
            "character": 0
        }
    }
]

[Trace - 5:31:59 PM] Received response 'textDocument/codeAction - (7)' in 36ms.
Result: [
    {
        "title": "Inline symbol",
        "kind": "refactor.inline",
        "data": {
            "id": "refactor-inline-symbol",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 9,
            "character": 6
        }
    },
    {
        "title": "Move to let",
        "kind": "refactor.extract",
        "data": {
            "id": "refactor-move-to-let",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 9,
            "character": 6
        }
    },
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "data": {
            "id": "clean-ns",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 9,
            "character": 6
        }
    }
]

[Trace - 5:32:03 PM] Sending request 'textDocument/hover - (9)'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/foo/src/foo/core.clj"
    },
    "position": {
        "line": 12,
        "character": 21
    }
}

[Trace - 5:32:03 PM] Received response 'textDocument/hover - (9)' in 29ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```clojure\nimproved-x\n```\n\n----\n\n*[/private/tmp/foo/src/foo/core.clj](file:///private/tmp/foo/src/foo/core.clj)*"
    },
    "range": {
        "start": {
            "line": 12,
            "character": 16
        },
        "end": {
            "line": 12,
            "character": 26
        }
    }
}

[Trace - 5:32:04 PM] Sending request 'textDocument/hover - (10)'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/foo/src/foo/core.clj"
    },
    "position": {
        "line": 9,
        "character": 7
    }
}

[Trace - 5:32:04 PM] Received response 'textDocument/hover - (10)' in 51ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```clojure\nimproved-x\n```\n\n----\n\n*[/private/tmp/foo/src/foo/core.clj](file:///private/tmp/foo/src/foo/core.clj)*"
    },
    "range": {
        "start": {
            "line": 9,
            "character": 1
        },
        "end": {
            "line": 9,
            "character": 11
        }
    }
}

[Trace - 5:32:04 PM] Sending request 'textDocument/documentHighlight - (11)'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/foo/src/foo/core.clj"
    },
    "position": {
        "line": 9,
        "character": 7
    }
}

[Trace - 5:32:04 PM] Received response 'textDocument/documentHighlight - (11)' in 36ms.
Result: [
    {
        "range": {
            "start": {
                "line": 9,
                "character": 1
            },
            "end": {
                "line": 9,
                "character": 11
            }
        }
    },
    {
        "range": {
            "start": {
                "line": 12,
                "character": 16
            },
            "end": {
                "line": 12,
                "character": 26
            }
        }
    }
]

[Trace - 5:32:04 PM] Sending request 'textDocument/codeAction - (12)'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/foo/src/foo/core.clj"
    },
    "range": {
        "start": {
            "line": 9,
            "character": 7
        },
        "end": {
            "line": 9,
            "character": 7
        }
    },
    "context": {
        "diagnostics": []
    }
}

[Trace - 5:32:05 PM] Received response 'textDocument/codeAction - (12)' in 265ms.
Result: [
    {
        "title": "Inline symbol",
        "kind": "refactor.inline",
        "data": {
            "id": "refactor-inline-symbol",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 9,
            "character": 7
        }
    },
    {
        "title": "Move to let",
        "kind": "refactor.extract",
        "data": {
            "id": "refactor-move-to-let",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 9,
            "character": 7
        }
    },
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "data": {
            "id": "clean-ns",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 9,
            "character": 7
        }
    }
]

[Trace - 5:32:10 PM] Sending request 'workspace/executeCommand - (13)'.
Params: {
    "command": "inline-symbol",
    "arguments": [
        "file:///private/tmp/foo/src/foo/core.clj",
        9,
        7
    ]
}

[Trace - 5:32:10 PM] Received response 'workspace/executeCommand - (13)' in 3ms.
No result returned.

[Trace - 5:34:43 PM] Sending request 'textDocument/codeAction - (14)'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/foo/src/foo/core.clj"
    },
    "range": {
        "start": {
            "line": 7,
            "character": 9
        },
        "end": {
            "line": 7,
            "character": 9
        }
    },
    "context": {
        "diagnostics": []
    }
}

[Trace - 5:34:43 PM] Received response 'textDocument/codeAction - (14)' in 20ms.
Result: [
    {
        "title": "Change coll to set",
        "kind": "refactor",
        "data": {
            "id": "refactor-change-coll",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 7,
            "character": 9,
            "coll": "set"
        }
    },
    {
        "title": "Change coll to list",
        "kind": "refactor",
        "data": {
            "id": "refactor-change-coll",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 7,
            "character": 9,
            "coll": "list"
        }
    },
    {
        "title": "Change coll to map",
        "kind": "refactor",
        "data": {
            "id": "refactor-change-coll",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 7,
            "character": 9,
            "coll": "map"
        }
    },
    {
        "title": "Move to let",
        "kind": "refactor.extract",
        "data": {
            "id": "refactor-move-to-let",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 7,
            "character": 9
        }
    },
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "data": {
            "id": "clean-ns",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 7,
            "character": 9
        }
    }
]

[Trace - 5:34:46 PM] Sending request 'textDocument/codeAction - (15)'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/foo/src/foo/core.clj"
    },
    "range": {
        "start": {
            "line": 7,
            "character": 0
        },
        "end": {
            "line": 13,
            "character": 0
        }
    },
    "context": {
        "diagnostics": [
            {
                "range": {
                    "start": {
                        "line": 7,
                        "character": 6
                    },
                    "end": {
                        "line": 7,
                        "character": 7
                    }
                },
                "message": "unused binding x",
                "code": "unused-binding",
                "severity": 2,
                "tags": [
                    1
                ],
                "source": "clj-kondo"
            }
        ]
    }
}

[Trace - 5:34:46 PM] Received response 'textDocument/codeAction - (15)' in 12ms.
Result: [
    {
        "title": "Change coll to map",
        "kind": "refactor",
        "data": {
            "id": "refactor-change-coll",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 7,
            "character": 0,
            "coll": "map"
        }
    },
    {
        "title": "Change coll to vector",
        "kind": "refactor",
        "data": {
            "id": "refactor-change-coll",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 7,
            "character": 0,
            "coll": "vector"
        }
    },
    {
        "title": "Change coll to set",
        "kind": "refactor",
        "data": {
            "id": "refactor-change-coll",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 7,
            "character": 0,
            "coll": "set"
        }
    },
    {
        "title": "Move to let",
        "kind": "refactor.extract",
        "data": {
            "id": "refactor-move-to-let",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 7,
            "character": 0
        }
    },
    {
        "title": "Thread first all",
        "kind": "refactor.rewrite",
        "data": {
            "id": "refactor-thread-first-all",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 7,
            "character": 0
        }
    },
    {
        "title": "Thread last all",
        "kind": "refactor.rewrite",
        "data": {
            "id": "refactor-thread-last-all",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 7,
            "character": 0
        }
    },
    {
        "title": "Suppress 'unused-binding' diagnostic",
        "kind": "quickfix",
        "data": {
            "id": "refactor-suppress-diagnostic",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 7,
            "character": 6,
            "diagnostic-code": "unused-binding"
        }
    },
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "data": {
            "id": "clean-ns",
            "uri": "file:///private/tmp/foo/src/foo/core.clj",
            "line": 7,
            "character": 0
        }
    }
]

</pre>
</details>

**User details (please complete the following information):**
 - OS: MacOS
 - Editor VSCode (Calva)
 - Version: clojure-lsp version used: 2021.12.20-00.36.56
clj-kondo version used: 2021.12.19

**Comment by ericdallo** [comment]
We introduced a regression recently, thanks for the report

**Comment by ericdallo** [comment]
Fixed, available on next release
