### ISSUE TITLE
Semantic tokens mismatching

### ISSUE THREAD

**Issue by PEZ** [clojure-lsp/clojure-lsp#679]
**Describe the bug**

The semantic tokenization get's out of whack now and then and starts coloring the code weirdly. We get quite a few error reports on Calve about this. Even though everything else works, users get the impression ”everything is broken”, it seems.  I don't have a clear repro. It doesn't happen to me very often. Sometimes I can provoke it by checking out a different version of the file I am working with.

Though it doesn't necessarily have to do with the file being changed from ”under/outside”. In this video, it happens quite a few time and the developer is only editing the file ”by hand”.

https://youtu.be/3w0FWqGC0PM?t=548

**Screenshots**

This one is from the video:

<img width="904" alt="image" src="https://user-images.githubusercontent.com/30010/147734901-5d5a066f-3500-4577-bed8-0f1d9f8d7a04.png">

**Additional context**

This has been happening with all version since semantic tokens were introduced. Not sure if it is VS Code specific.

I'm thinking that as long as we haven't fixed it, maybe the semantic tokens can be disabled by default? (Depends a bit on if the problem is VS Code specific, of course). At least with Calva users are seldom aware of all the systems working to help them. They haven't turned the key to enable semantic tokens, so they don't realize that that is what is going wrong. If it is disabled and we promote the feature, then at least we have the users awareness about it as a specific thing.

**Comment by ericdallo** [comment]
I suspect this was already fixed on master with the `async-custom-lint?` fix, is it possible to ask for one of the users test with master ?

**Comment by ericdallo** [comment]
@PEZ with latest clojure-lsp which included https://github.com/clojure-lsp/clojure-lsp/commit/32ecfb559108a47c24d41946ff74108b7ca7e541 I suspect this is not happening anymore, I'll close this issue for now, LMK if any issues
