### ISSUE TITLE
Find every test in the project by default at init to fulfill test tree managers

### ISSUE THREAD

**Issue by erickisos** [clojure-lsp/clojure-lsp#697]
**Is your feature request related to a problem? Please describe.**

As the new feature of test-tree for Calva was released it was noticeable that the test tree is only populated after open some files, and only with the tests from opened files.

**Describe the solution you'd like**

Maybe it would be great to do a quick scan in the project to detect every test after the initialization of clojure-lsp.

**Comment by ericdallo** [comment]
Thanks, I think we should do that async to not block the startup time, after clojure-lsp initialized successfully, if you wanna give it a try you can check how we refresh clojuredocs, we can probably use the same approach here to add something like when not API:

```clojure
(async/go
  (->> (f.test-tree/project-tree db)
        (map (producer/notify-test-tree (:producer @db)))))
```

I can work on that during next week

**Comment by ericdallo** [comment]
Done, available on next release, LMK if any issues

**Comment by erickisos** [comment]
Thanks Greg, amazing
