### ISSUE TITLE
Support going to definition on an alias (i.e., :as :as-alias)

### ISSUE THREAD

**Issue by dharrigan** [clojure-lsp/clojure-lsp#706]
Given the following requires:

`(:require [foo.bar :as baz])`

Presently, clojure-lsp only knows how to goto definition on the full require namespace, i.e., by placing the cursor on `foo.bar`, and going to definition, the namespace `foo.bar` is loaded into the editor.

It would be super awesome if that would also work with the alias, i.e., `:as baz`, so that by placing the cursor on `baz` and going to definition, clojure-lsp knows that it's really `foo.bar` and opens up that namespace in the editor.

**Describe the solution you'd like**

Support going to definition on `:as` and `:as-alias`

Maybe it needs to also work with the aliased namespace within the code, i.e., if I have this:

`(baz/super-amazing-function)`

I can only go to definition with the cursor over `super-amazing-function`. Would it be able to go to definition by taking the whole form (in effect, resolve the super-amazing-function in the baz alias).

-=david=-

**Comment by ericdallo** [comment]
I implemented the find defintion from the alias, not from a alias usage though since this would not be that easy as we consider a `foo/bar` as a single usage when we find a definition
