### ISSUE TITLE
completionItem/resolve does not return insertText

### ISSUE THREAD

**Issue by Cyrik** [clojure-lsp/clojure-lsp#719]
**Describe the bug**
When calling `completionItem/resolve` with a snippet completionItem the result should also contain that snippet.

[calva issue](https://github.com/BetterThanTomorrow/calva/issues/1483)
**To Reproduce**

1. type "kwarg", hit tab

sends:
```
Sending request 'completionItem/resolve - (99)'.
Params: {
    "label": "def",
    "detail": "clojure.core/def",
    "insertTextFormat": 2,
    "insertText": "(def ${1:name} ${0:value})",
    "kind": 18,
    "data": {
        "filename": "/clojure.core.clj",
        "name": "def",
        "ns": "clojure.core"
    }
}
Received response 'completionItem/resolve - (99)' in 39ms.
Result: {
    "label": "def",
    "kind": 18,
    "detail": "clojure.core/def",
    "data": {
        ":filename": "/clojure.core.clj",
        ":name": "def",
        ":ns": "clojure.core"
    }
}
```

**Expected behavior**
get an enriched version back

PR incoming

**Comment by ericdallo** [comment]
I'm taking a look at this issue + your PR, just a FYI that we don't need to fix the data adding `:` as client don't care about data field, it only a field server can return on `textDocument/completion` and client forward to `completionItem/resolve`.

**Comment by Cyrik** [comment]
I've added ::snippet-kind to data so that vim can still show the underlying kind but :kind is set to 15 for vscode and emacs. That was the compromise with @tami5 to get every IDE what it needs.
Just not sure why it gets set as a namespaced keyword instead of the same as the others.
