### ISSUE TITLE
When using the action menu, the cursor is not repositioned

### ISSUE THREAD

**Issue by mainej** [clojure-lsp/clojure-lsp#722]
**Describe the bug**

Some commands attempt to move the cursor via `:show-document-after-edit`. The cursor is not relocated correctly when the command is invoked from the action menu. Invoking the same command directly does move the cursor.

There are two parts to this bug. First the code that attempts to move the cursor was broken by 2b8b66bf8, which removed the `:client` from the db. [This line](https://github.com/clojure-lsp/clojure-lsp/blob/c1890e53e54b8e553124fa0c9ffd935d6013f3e0/lib/src/clojure_lsp/handlers.clj#L291) wasn't updated to remove the check for the `:client`.

However, even after removing that check,  the bug persists. It appears that on the (working) `executeCommand` path, the edit happens before the cursor movement, but on the `resolveCodeAction` path, they happen in the reverse order, with the movement before the edit. See logs below.

This bug probably also manifests in a different way, which I haven't researched. I suspect that related files are not focused (when a command is invoked from the action menu). It would happen for anything that uses `:take-focus? true`: creating tests, or creating functions in an aliased namespace.

**To Reproduce**

1. Create a map with several entries, each covering a different number of lines, including their comments.
2. Move cursor to one of the entries. Note this as the "starting cursor"
2. Invoke "Move coll entry down" from the action menu
3. Note where the cursor ends up as the "after action cursor"
4. Undo. Move back to the "starting cursor" position.
5. Invoke `lsp-clojure-move-coll-entry-down` directly.
6. Note where the cursor ends up as the "after command cursor".
7. Observe the "after action cursor" and "after command cursor" are not the same. You may have to retry the experiment with different "starting cursor" positions, including on the comments or between a key and value.

**Expected behavior**

The cursor is always positioned in the same place, regardless of how the command is invoked.

**Screenshots**

<details>
 <summary><b>Log - clojure-lsp</b> :executeCommand</summary>
<pre>
2022-01-27T02:41:55.509Z  DEBUG [clojure-lsp.server:?] - :didChange 1ms
2022-01-27T02:41:55.509Z  INFO [clojure-lsp.server:495] - Requesting to show on editor the document {:uri "file:///Users/jmaine/workspace/opensource/clojure-lsp/lib/src/clojure_lsp/feature/move_coll_entry.clj", :take-focus? true, :range {:row 470, :col 4, :end-row 470, :end-col 4}}
2022-01-27T02:41:55.515Z  DEBUG [clojure-lsp.server:?] - :executeCommand 40ms
</pre>
</details>

<details>
 <summary><b>Log - clojure-lsp</b> :resolveCodeAction</summary>
<pre>
2022-01-27T02:10:18.753Z  DEBUG [clojure-lsp.server:?] - :codeAction 161ms
2022-01-27T02:10:19.935Z  INFO [clojure-lsp.server:495] - Requesting to show on editor the document {:uri "file:///Users/jmaine/workspace/opensource/clojure-lsp/lib/src/clojure_lsp/feature/move_coll_entry.clj", :take-focus? true, :range {:row 469, :col 4, :end-row 469, :end-col 4}}
2022-01-27T02:10:19.940Z  DEBUG [clojure-lsp.server:?] - :resolveCodeAction 50ms
2022-01-27T02:10:20.530Z  DEBUG [clojure-lsp.server:?] - :didChange 3ms
</pre>
</details>

**User details (please complete the following information):**
 - OS: MacOS
 - Editor emacs
 - Version: clojure-lsp 2022.01.22-01.31.09, clj-kondo 2022.01.15

**Comment by ericdallo** [comment]
Yeah, I think I broke this behavior, we should probably add integration tests for code actions like those that move the cursor. I'll take a look, thanks for the report

**Comment by ericdallo** [comment]
@mainej I tested removing the :client from the `if` as it's not needed anymore and it fixed the issue to me, could you try again?
Something I noticed is that the cursor position is not perfect, for example:
```clojure
{|:a 1
 :b {:c 2
      :d 3}}
```
If we try to move cursor(`|`) to down, it becomes:
```
{:b {:c 2
 |    :d 3}
 :a 1}
 ```

**Comment by mainej** [comment]
@ericdallo thanks for updating master. I'll test it again. If I can, I'll provide a reproducible test case.

I noticed this while I was on a branch (a branch that fixes the incorrect positioning that you noted above!) which I haven't pushed yet. So there's a chance it's only reproducible there, in which case, I'll update this bug after that branch has been reviewed and merged.

**Comment by mainej** [comment]
I was able to reproduce this on master. Starting from here:

```clojure
(def m
  {|:b 2 ;; 2 comment
   :c 3
   })
```
Direct invocation of move-coll-entry-down: cursor correctly moves to location requested by refactoring.
```clojure
(def m
  {:c 3
   |:b 2 ;; 2 comment
   })
```
Action menu: cursor moves elsewhere, in this case to the end of the changed text. (I have no theories as to why the editor picks that spot. It doesn't always seem to be the end of the changed text.)
```clojure
(def m
  {:c 3
   :b 2 ;; 2 comment|
   })
```

**Comment by mainej** [comment]
Here's a theory... `handlers/execute-command` and `handlers/resolve-code-action` do things in different orders.

* `handlers/execute-command` calls `producer/publish-workspace-edit` first, then `producer/show-document-request` second. So in this case, the client sees:
  1. `WorkspaceEdit`
  2. `ShowDocumentParams`
* `handlers/resolve-code-action` calls `producer/show-document-request`, and then _returns_ a `CodeAction`. I assume the `CodeAction` is automatically sent to the client. So in this case, the client sees:
  1. `ShowDocumentParams`
  2. `CodeAction`

Indeed, if I change `handlers/resolve-code-action` by wrapping `producer/publish-workspace-edit` in a `future` with a small sleep, the bug disappears.

I don't like the future+sleep solution because it replaces an always-incorrect behavior with an occasionally-correct behavior.

What's the right way to handle this? I don't fully understand the wiring between servers and clients. Maybe make `server.LSPTextDocumentService/resolveCodeAction` work more like `server.LSPWorkspaceService/executeCommand`? That is, instead of returning a `CompletableFuture` that wraps the `CodeAction`, return `(CompletableFuture/completedFuture 0)` after notifying the client first of the edit, and then of the cursor movement.

I'll see if I can get that to work.

**Comment by mainej** [comment]
Yes, that works! I'll clean it up and submit a PR.

**Comment by ericdallo** [comment]
Yeah, I'm no fan of having a future, sounds like a fragile feature that should even cause issues for integration-tests if we do that.
Not sure if we could wait for the LSP completable future, but sounds better than wrapping with a `(future)` indeed.
