### ISSUE TITLE
Do code actions need to be resolved?

### ISSUE THREAD

**Issue by mainej** [clojure-lsp/clojure-lsp#725]
**Is your feature request related to a problem? Please describe.**

There are two code paths for getting edits applied. 

First, obviously, you can execute a command. This code path returns nil but begins a background process to calculate edits, which the editor will be notified about later. 

Second, you can use the action menu. Currently, after picking an action menu item, the server is sent a "resolve code action" request. (If the client supports that capability. If the client doesn't, the server is sent an "execute command" request.) This "resolve code action" request also schedules a background process to calculate edits. (It currently fails to return a valid response—its return value doesn't match the expected clojure.spec—but that's not the bug I'm focused on here.)

Having two code paths leads to some code duplication and to bugs like #722, which stem from slight differences in the way the client is notified of edits.

I'd like to propose that the "resolve code action" path be removed. Here's my argument... 

According to the [LSP spec on code actions](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction), when the server is generating the action menu options, it has three options.

First, it can include edits along with an action menu item. The spec recommends that servers only do this if the edits are so easy to compute that they won't slow down the generation of the menu option. `clojure-lsp` does not use this option currently.

Second, the server can include a command along with an action menu item. When the menu item is selected the client is supposed to send this command back to the server, i.e. "execute" it. The spec recommends that servers do this whenever the edits would take too long to calculate but they can quickly calculate a command. `clojure-lsp` asks clients to use this option if they don't support the third option.

Third, the server can include some arbitrary data with the action menu item. When the menu item is selected, the client sends this data back to the server via the "resolve code action" path. The server then generates the edits. The spec recommends that servers do this when both the edits _and_ the command would take too long to calculate. It's a way for the server to say "I know this action menu item should be available, but figuring out the exact command would slow down the menu popup". Not all clients support this option, but when they do `clojure-lsp` always asks them to follow it.

**Describe the solution you'd like**

I think `clojure-lsp` should stop generating menu items of the third type. My argument is that `clojure-lsp` never actually takes advantage of the "resolve code action" capability. That is, it never uses it as a shortcut to generate the menu items more quickly. Thus, it might as well always generate options of the second type. Then all clients would execute commands, instead of some executing commands and some resolving code actions, ensuring that all edits are applied in the same way.

The biggest question is whether all the editors will be OK with this. It's possible that some editors that support the "resolve code action" capability actually _require_ it.

One open question is whether the server should stop advertising that it supports "resolve code action". This may be necessary for some editors, who might otherwise try to follow that path regardless of the contents of the menu item.

I'll work on a PR for this, but will need help testing in various editors (I use Emacs so can test there.) There aren't currently any integration tests for action menu interaction or direct execution of commands, but there should be to validate that this refactoring works correctly. I'll write some of those tests as I work on the PR.

**Comment by ericdallo** [comment]
Thanks for the detailed explanation, I don't see any issues with that approach if all editors work.
@bpringe do you see any issues with that approach for Calva on removing dropping the `resolveCodeAction` support and always return commands for code actions? Related to Calva: https://github.com/clojure-lsp/clojure-lsp/issues/655

**Comment by bpringe** [comment]
I saw in the PR discussion that the change seems to work on Calva. Thanks for testing, @ericdallo.
