### ISSUE TITLE
Fix incoming request coercion

### ISSUE THREAD

**Issue by Cyrik** [clojure-lsp/clojure-lsp#727]
Based on the problems left in #720 

I'd like to do the camelCase <-> kebab-case conversion by hand in the clojure.java.data/from-java multimethod, but clojure-lsp.server/sync-request pipes the clojure-lsp.coercer/java->clj call directly into the handler.
I think the cleanest solution would be to also pipe this through a request-spec spec before calling the handler. That way we can change the casing or any other stuff that might come up at the "right" location.

I'm not sure when I'll have time to work on this but I wanted to keep the design idea alive.

**Comment by mainej** [comment]
Input is now converted to kebab-case by camel-snake-kebab. And instead of being converted only to the depth specified by the coercer, it is converted fully.
