### ISSUE TITLE
:additional-text-edits don't get returned on completionItem/resolve

### ISSUE THREAD

**Issue by Cyrik** [clojure-lsp/clojure-lsp#728]
Left over from #720 

The coercion for this case needs to be handled. Should probably be based on #727

**Comment by mainej** [comment]
This group of changes was all for Calva, right? Does that mean additionalTextEdits aren't applied to Calva at all? Or does it apply the the edits it gets before starting completion/resolve?

**Comment by mainej** [comment]
Or I guess a better question is, does that mean additionalTextEdits are currently broken for all editors? I can check that myself for Emacs.

**Comment by ericdallo** [comment]
I don't think they are broken since we have a feature of adding the require when completing a not required symbol, you can test from that feature I think

**Comment by Cyrik** [comment]
They are broken for editor's that use resolve as the source of truth, so anything based on top of official libs. In those additional edits won't be used at all because resolve does not return them.
I think emacs wrote the whole client? They don't seem to follow the spec on this bit.
I think postponing them would actually fix it for calva since then the resolve would return it. Currently it doesn't 😁

**Comment by ericdallo** [comment]
@mainej Almost sure you are absolutely correct, thanks for summarizing.

There are few features that I know that emacs-lsp is smart and tries to be safe from server misinformation like this one.
Even so, we should try to follow the spec to fix the issue for most(all?) clients that don't do the same, and probably improving in-request coercer would be a good start.

BTW calva uses vscode-languageclient node lib, which already has most built-in capabilities enabled, for the rest, Calva enable manually on the lsp.ts file on the server object initialization.

**Comment by mainej** [comment]
@ericdallo ok, thanks. I'll move forward with looking at postponing additionalTextEdits. Doesn't seem like it'll hurt anything. I know the input coercion is more important, but I'm intimidated by that project. :)

For my reference in the future [here](https://github.com/microsoft/vscode-languageserver-node/blob/6c689d22501aa2bac9990f3a41139d47428b5f40/client/src/common/client.ts#L1745) are the Calva capabilities.

**Comment by mainej** [comment]
I've decided not to move additionalTextEdits to resolve, at least for now. If anyone is interested, the reasons are [here](https://github.com/clojure-lsp/clojure-lsp/pull/764#issuecomment-1053684207). So, in regards to this bug, nothing has changed. As discussed above, moving additionalTextEdits to resolve would partially solve the bug, but A) I'm not going to work on that right now, and B) the better fix is still to change input coercion so that it can copy additionalTextEdits during resolve.

**Comment by mainej** [comment]
#1069 fixed type 3a clients, by postponing `:additional-text-edits` to `completionItem/resolve`.

#1117 ensures we don’t have similar errors in the future by copying `:additional-text-edits` and other attributes from the `completionItem/resolve` request to the response.
