### ISSUE TITLE
API for exporting/dumping clojure-lsp info

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#744]
It would be really useful to export or provide clojure-lsp information via API/CLI, with that any tool could benefit from clojure-lsp information like project clj-kondo analysis, classpath/source-paths information, and more.

One suggestion after talking with @stuartsierra, is to provide a data dump feature where one could call clojure-lsp and tell to export to some format (json, end, transit etc) with a documented structured schema. We could implement this feature for both API (JVM) and CLI, but probably this feature would most be used on CLI.

**Comment by ericdallo** [comment]
@vemv may be interested on this as well

**Comment by vemv** [comment]
Thanks!

IDK, from my side I'd feel on a safer side using a programmatic API (which can have various affordances e.g. Spec checking) rather than parsing data.

**Comment by stuartsierra** [comment]
I recommended a data dump for a few reasons:

1. Consumers do not have to be written in Clojure (assuming a common data format like CSV or JSON)
2. You can generate the data dump once and store it (e.g. on a CI/CD server) for clients to download
3. You can easily store multiple versions of the data dump, at different points in the project's history, and compare them (_a la_ [codeq](https://github.com/Datomic/codeq))

[Language Server Index Format](https://microsoft.github.io/language-server-protocol/overviews/lsif/overview/) (LSIF) appears to be related work from the LSP project:

> The LSIF defines a standard format for language servers or other programming tools to emit their knowledge about a code workspace. This persisted information can later be used to answer LSP requests for the same workspace without running a language server.

Of course, having a data dump does not preclude having a programmatic API. The LSIF starts from the point of view that the Language Server Protocol itself is the API.

**Comment by ericdallo** [comment]
> The purpose of the Language Server Index Format (LSIF) is it to define a standard format for language servers or other programming tools to dump their knowledge about a workspace. This dump can later be used to answer language server [LSP](https://microsoft.github.io/language-server-protocol/) requests for the same workspace without running the language server itself.

@stuartsierra Really good point, the LSIF seems to be the exact feature we seek, and it already contains a [specification](https://microsoft.github.io/language-server-protocol/specifications/lsif/0.4.0/specification/), we could offer the dump via CLI and API just like we already offer some clojure-lsp features like clean-ns, formatting, rename and diagnostics

**Comment by ericdallo** [comment]
I took a look at [lsif-java](https://github.com/microsoft/lsif-java), and it seems they use the eclipse jdt manually, which is what the jdt lsp does as well, so to build a lsif, it needs to process similar what a lsp does, so I think we could make clojure-lsp emit lsif data, or even better, have a `clojure-lsif` which would use the dump from clojure-lsp to build the graph that lsif has

**Comment by andrewzhurov** [comment]
Much of knowledge clojure-lsp offers comes from clj-kondo.
Shouldn't it be provided as a dump by clj-kondo?
To be enriched with derived knowledge clojure-lsp has to offer.

**Comment by ericdallo** [comment]
Yeah, clj-kondo already export data, but it doesn't know anything about the project, like what are the source paths, the classpath etc.
So my idea was to make clojure-lsp provide what it knows at the moment that is all its kondo analysis of the project + whatever we thing it would make sense in the future.
The issue I see regarding lsif is that it's limited by the protocol, we could still have a project that takes the output and convert to lsif

**Comment by Cyrik** [comment]
I think I'm misunderstanding something since we mostly have this already in transit format, at least for the external deps.
So now the question is, what's the best way to also get live data, not just the startup cache, correct? It feels like a good starting point would be a config option that makes clojure-lsp write a second file with the actual source analysis.

**Comment by ericdallo** [comment]
My idea was a cli arg like `clojure-lsp dump` which would print or export to a file all known analysis including external and internal, giving the option to get only internal too

**Comment by Cyrik** [comment]
My perspective was tooling that runs side by side with clojure-lsp, so a live view would be helpful.
I guess those are two different use cases though.

**Comment by ericdallo** [comment]
I see, yeah, something like pathom and pathom-viz I think you meant, yeah, sounds like a different thing

**Comment by ericdallo** [comment]
This is now available both programatically via `clojure-lsp.api/dump` and via CLI `clojure-lsp dump`.

ATM the new dump output is:

`:project-root` a string path representing the project root.
  `:source-paths` list of source-paths considered by clojure-lsp.
  `:classpath` list of paths of found classpath.
  `:analysis` clj-kondo analysis normalized for clojure-lsp usage.
  `:dep-graph` Dependency graph of namespaces relationship derived from clj-kondo analysis.
  `:findings` clj-kondo findings used for diagnostics.
  `:settings` a map with all settings considered by clojure-lsp.
  
  For more details check the API docstring [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/lib/src/clojure_lsp/api.clj#L249)
