### ISSUE TITLE
Failure to start on Windows 10

### ISSUE THREAD

**Issue by zeitstein** [clojure-lsp/clojure-lsp#745]
**To Reproduce**
1. Download `clojure-lsp-native-windows-amd64.zip` from [Releases](https://github.com/clojure-lsp/clojure-lsp/releases)
2. Unzip and run with `.\clojure.lsp --version`

There is no output. The latest version that works correctly is 2022.01.22-01.31.09.

**User details (please complete the following information):**
 - OS: Windows 10
 - Editor: Calva (setting lsp version in Calva settings to 2022.01.22-01.31.09 works)
 - Version: (post the result of `clojure-lsp --version`) Doesn't work :)

**Comment by LouDnl** [comment]
Having problems in Calva with VSCode too. Clojure-lsp wont connect to server in versions [2022.02.01-16.53.14](https://github.com/clojure-lsp/clojure-lsp/releases/tag/2022.02.01-16.53.14) and [2022.02.01-20.02.32](https://github.com/clojure-lsp/clojure-lsp/releases/tag/2022.02.01-20.02.32)

Mentioned version above 2022.01.22-01.31.09 works and clojure-lsp connects to server again.

**Comment by ericdallo** [comment]
@LouDnl @zeitstein it should be fixed on the same release, I made the windows binary use a previous graalvm version and if you install/download again it should work

**Comment by LouDnl** [comment]
Thanks, will check right now and report back.

**Comment by LouDnl** [comment]
Fixed, thanks a bunch!

**Comment by ericdallo** [comment]
Not related @LouDnl it should be no problem as well
