### ISSUE TITLE
Improve completion performance on comments

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#750]
As discussed on this [thread](https://clojurians.slack.com/archives/CPABC1H61/p1643959935463449), we should probably do not return completion items (or just what makes sense?) on comments.

**Comment by mainej** [comment]
I have a lot of context from the thread discussion, so I'll take this. To summarize, when completion is invoked in comments, whitespace, or anywhere it can't find a symbol/keyword zloc, clojure-lsp currently returns every symbol defined in clojure.core, java.lang and java.util. (Note that this is true even before the changes in #716.)

I'm concerned that finding and serializing that large result set causes the performance problems mentioned in the thread. (Note that these problems are probably exacerbated by the particular client mentioned in the thread, nvim+coc.vim, which requests completion for single characters, without much or any delay.)

We think the client provides the text it is trying to complete. But it looks like we ignore that data. So, the proposal is to research that more. If possible, we'll use that text to filter the completions. @ericdallo, should the server _always_ use that text for completion? Or only when it can't find a valid zloc? What's the benefit of finding a zloc at all, if the client provides the text it's trying to complete? It looks like there's special handling of completion inside ns definitions and other scenarios, so maybe it's related to that? I'll have to understand that code better.

Also we'll short-circuit when no prefix string can be found. This will avoid running completion when the cursor is on whitespace, or on forms that aren't symbols or keywords. A variation of this idea is that we could have a setting for the minimum prefix length. If we defaulted that to 2, the result sets would be much smaller. Users that wanted more results could configure it to 1 (or even 0) at their own risk of performance problems. @ericdallo do you think that's worth it? I don't know how hard it is to add configuration options.

As a reminder to myself, it'd be good to benchmark the existing code a little, and keep an eye on how these changes and any other refactorings affect performance.

And finally, we're still exploring the performance issues mentioned in the original thread. If we decide that completion isn't the problem, it may make sense to abandon this line of work.

**Comment by ericdallo** [comment]
@mainej My bad, double checking the SPEC [here](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionParams), client only pass uri, row and col, so we don't have any extra text, we do need to parse the URI with that row/col and get the zipper to know what is being completed.

**Comment by ericdallo** [comment]
Agreed with all your points, I think we can open a new issue to discuss the performance improvements and leave this one to remove completion on comments, I'd like to avoid a setting at most, a benchmark may help tell whether we need that flag or not I think.

**Comment by mainej** [comment]
Gotcha. OK, if the completion request doesn't include extra text, I agree, we should exclude comments from completion. What about whitespace and non-keyword/symbol forms? I.e., if you're sitting here

```clojure
(foo "a")
|
```

or here

```clojure
|(foo "a")
```

... should completion return an empty list? Or all of the clojure+java symbols?

I can benchmark it, but I suspect that I'd miss the time it takes to conform and serialize that much data.

**Comment by ericdallo** [comment]
I think those two cases makes sense to return everything indeed, I think it's much more common than completing comments

**Comment by emilaasa** [comment]
Hi @mainej and @ericdallo, thanks for your great investigation into this - now I feel bad for leaving you with a crappy gif and some breadcrumbs as only clues for your digging.

I've disabled a few interesting completion sources like `coc-conjure` that had very strange suggestions, and I've set the `CocConfig` as standard as I know how:

```json
{
    "languageserver": {
        "clojure-lsp": {
            "command": "clojure-lsp",
            "filetypes": ["clojure"],
            "disableDiagnostics": false,
            "rootPatterns": ["deps.edn", "project.clj"],
            "additionalSchemes": ["jar", "zipfile"],
            "trace.server": "verbose"
        }
}
```

I don't build from source, I use the release that's in the arch user repository.

The problem goes away when I disable the autocomplete in `coc.nvim` completely using `let b:coc_suggest_disable = 1`.

If I type away in a comment I get output like this in the logs (now with autocomplete enabled again):

`2022-02-06T20:59:13.689Z  DEBUG [clojure-lsp.server:?] - :completion 12836ms`

**Comment by ericdallo** [comment]
So it seems disabling completion on comments should fix your issue indeed.

Even so, 12sec to return all LSP completions looks too much, a simple repro would help

**Comment by emilaasa** [comment]
All right it was trivial to reproduce, a fresh `lein new app comment-completion-repro` did it: https://github.com/emilaasa/comment-completion-repro
 
I can open the `core.clj` file there, wait for the initial scans and everything (basically I wait until the LSP disappears from `top`) add a comment and start typing.
This gives the identical experience that I described in the gif / thread.

Log excerpt from the reproduction:
```
==> clojure-lsp.9865649248038698763.out <==
2022-02-06T21:33:25.217Z  DEBUG [clojure-lsp.server:?] - :completion 1848ms
2022-02-06T21:33:25.293Z  INFO [clojure-lsp.feature.file-management:?] - changes analyzed by clj-kondo took 0.00 secs

==> clojure-lsp.15811590313577536258.out <==
2022-02-06T21:33:25.305Z  DEBUG [clojure-lsp.server:?] - :didSave 0ms

==> clojure-lsp.9865649248038698763.out <==
2022-02-06T21:33:25.305Z  DEBUG [clojure-lsp.server:?] - :didSave 0ms

==> clojure-lsp.15811590313577536258.out <==
2022-02-06T21:33:25.318Z  INFO [clojure-lsp.feature.file-management:?] - changes analyzed by clj-kondo took 0.03 secs

==> clojure-lsp.9865649248038698763.out <==
2022-02-06T21:33:25.332Z  DEBUG [clojure-lsp.server:?] - :documentHighlight 129ms
2022-02-06T21:33:25.637Z  DEBUG [clojure-lsp.server:?] - :documentHighlight 0ms

==> clojure-lsp.15811590313577536258.out <==
2022-02-06T21:33:25.647Z  DEBUG [clojure-lsp.server:?] - :completion 1838ms

==> clojure-lsp.9865649248038698763.out <==
2022-02-06T21:33:25.727Z  DEBUG [clojure-lsp.server:?] - :completion 1917ms
2022-02-06T21:33:25.902Z  DEBUG [clojure-lsp.server:?] - :didChange 0ms

==> clojure-lsp.15811590313577536258.out <==
2022-02-06T21:33:25.902Z  DEBUG [clojure-lsp.server:?] - :didChange 0ms
2022-02-06T21:33:26.163Z  DEBUG [clojure-lsp.server:?] - :completion 1832ms
```

**Comment by ericdallo** [comment]
I can't repro this on emacs, what did you do to repro that @mainej ?

**Comment by mainej** [comment]
I had to switch to nvim + coc.nvim to repro @ericdallo. Emacs doesn't request completion while in a comment, or at least not in my configuration of it.

@emilaasa the logs for your minimal repo say completion takes ~1-2 seconds. I was getting similar times in my experiments. clojure-lsp uses a good amount of CPU, but it can keep up. But above you say that your full repo takes an order of magnitude longer, ~13 seconds. Do you have a sense of what causes the difference?

**Comment by ericdallo** [comment]
@mainej I'm ok with not spending too much time debugging those 13s on comments if we are intended to remove completion on those

**Comment by mainej** [comment]
@ericdallo that's fair. I'm curious, but it's probably a rabbit hole. :) Maybe it'd be nice to add a log line for how many completions it's suggesting.

**Comment by ericdallo** [comment]
Good suggestion, a log line saying how much completion items we are return seems to not make no harm

**Comment by ericdallo** [comment]
Done @mainej 

![2022-02-06_21-06](https://user-images.githubusercontent.com/7820865/152707491-0ffa0176-57dd-4b0b-afb4-082dda8637a5.png)

**Comment by emilaasa** [comment]
> @emilaasa the logs for your minimal repo say completion takes ~1-2 seconds. I was getting similar times in my experiments. clojure-lsp uses a good amount of CPU, but it can keep up. But above you say that your full repo takes an order of magnitude longer, ~13 seconds. Do you have a sense of what causes the difference?

I'm working in a somewhat large code base - both in dependencies and lines of clojure. That would be my first guess but I don't know how that would impact this issue.

**Comment by mainej** [comment]
@ericdallo thanks! I'll be interested to see what that returns for Emil. When I was researching this earlier, I thought that blank completion returns only clojure.core + java.lang + java.util. But those three define only about 900 symbols. On closer inspection, blank completion will also return things defined in the namespace that the cursor is in. And maybe it will return other things too. There are many paths through that code, and I haven't followed them all. Anyway, I think that's why you see 1037 symbols. It sounds like Emil is seeing even more, but we'll find out in the next release.

**Comment by ericdallo** [comment]
@emilaasa would you mind testing a dev clojure-lsp to avoid waiting next release? you can build a local clojure-lsp just cloning this repo and running `make`

**Comment by emilaasa** [comment]
```
==> clojure-lsp.1324046870250596329.out <==
2022-02-08T07:04:08.714Z  DEBUG [clojure-lsp.server:?] - :completion 18169ms - total items: 995
2022-02-08T07:04:09.601Z  DEBUG [clojure-lsp.server:?] - :completion 18214ms - total items: 995
2022-02-08T07:04:10.259Z  DEBUG [clojure-lsp.server:?] - :completion 18334ms - total items: 995
```

**Comment by emilaasa** [comment]
When I run it and I write code I get times similar to this:
```
2022-02-08T07:08:12.179Z  DEBUG [clojure-lsp.server:?] - :completion 111ms - total items: 2
```

**Comment by emilaasa** [comment]
I also have decent PC specs and low load on the system otherwise:
RAM: 11539 MB / 64283 MB
Processor Type: AMD Ryzen 7 5800X 8-Core Processor

**Comment by ericdallo** [comment]
Thanks, it seems to be related with items count on a big project maybe

**Comment by ericdallo** [comment]
@emilaasa merged on master, LMK if any performance issues on comments still
