### ISSUE TITLE
Support go to definition of java classes/methods

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#762]
This was already requested some times but we never created a issue about that.
This one is specifically to offer to users what REPL navigation has well, the find definition of a java class and if viable/easy a method as well, and with probably that we could offer other features derived of definition like showing docs of java classes/methods, references etc

**Comment by ericdallo** [comment]
We would need java analysis, probably from clj-kondo: https://github.com/clj-kondo/clj-kondo/issues/1330

**Comment by borkdude** [comment]
The question is still: what do you navigate to? In most cases there is no source code to navigate to.

**Comment by ericdallo** [comment]
@borkdude I don't think we need the exact source, but maybe we can build it just like we did with stubs. How CIDER does when you find a java class? I think they get the source somehow right?

**Comment by nxtk** [comment]
@borkdude disasseble the class file, if source is not available, intellij and eclipse jdt ls are doing just that.

**Comment by ericdallo** [comment]
I'm not sure integrate with jdtls would be that easy for now @nxtk, maybe a next step after having this already working on clojure-lsp.
@borkdude Do you think that the decompile class would be a hard option? I'd like to help on this issue but not sure the best way to then dive into it.

**Comment by snoe** [comment]
I looked into this a bit at the beginning of the project.

For JDK sources: I remember seeing that the source code for the jdk is often available locally in a known location.
For most jars: The source is often included `jar tvf ~/Downloads/org.eclipse.lsp4j-0.9.0.jar | grep java | head` [download](https://repo.maven.apache.org/maven2/org/eclipse/lsp4j/org.eclipse.lsp4j/0.9.0/)

If you index those two categories, you will handle almost all the open source stuff. I believe it is actually quite rare for intellij to decompile.

**Comment by snoe** [comment]
The JDK source is often in a `src.zip` folder:
```
$ find /Library/Java/JavaVirtualMachines -name src.zip
/Library/Java/JavaVirtualMachines/openjdk-14.jdk/Contents/Home/lib/src.zip
/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/src.zip
/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/src.zip
/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/demo/jfc/Stylepad/src.zip
/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/demo/jfc/FileChooserDemo/src.zip
/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/demo/jfc/CodePointIM/src.zip
/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/demo/jfc/TransparentRuler/src.zip
/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/demo/jfc/SwingSet2/src.zip
/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/demo/jfc/Metalworks/src.zip
/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/demo/jfc/TableExample/src.zip
/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/demo/jfc/SampleTree/src.zip
/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/demo/jfc/Notepad/src.zip
/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/demo/jfc/J2Ddemo/src.zip
/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/lib/src.zip
```

**Comment by ericdallo** [comment]
Thanks @snoe , me and @borkdude were discussing about adding support for jdk sources as a next step, we could have a cache for it or something or a option user would select the jdk version and we handle cache it and analyze.
This part is still in discuss, so feel free to give more suggestions

**Comment by ericdallo** [comment]
We finally have find-definitions for java classes 🎉 
- We can find existing java source files
- We can find java class, decompile and present to user (working on emacs for now, other editors need to use `clojure/dependencyContents` to make that work) c/c @bpringe @Cyrik 

- This only works for java classes, not methods yet
- This doesn't work for JDK yet since we don't have the class or source available, we should add this feature soon probably downloading JDK source under a flag.

c/c @borkdude

**Comment by snoe** [comment]
@ericdallo is there an example of emacs/lsp-mode using `clojure/dependencyContents` we can look at?

**Comment by ericdallo** [comment]
@snoe yes: https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-clojure.el#L263
