### ISSUE TITLE
Get the cljfmt config as a string containing the EDN text

### ISSUE THREAD

**Issue by PEZ** [clojure-lsp/clojure-lsp#768]
**Is your feature request related to a problem? Please describe.**

When making Calva use cljfmt config from clojure-lsp I started by making it possible to read a JS sctructure and feed that to Calva's formatter to turn into a Clojure hashmap config. I have that working, but it was much trickier than I thought it would be and I still don't know how to get metadata in there, so it wouldn't support using `^:replace` to signal that the indents should fully replace the built in rules.

**Describe the solution you'd like**

If serverInfo could give me the config as a string containing the EDN text, then I could feed it to Calva's formatter the same way I feed it regular clfmt.edn configs.

**Comment by ericdallo** [comment]
Not sure it's the best idea to have a duplicated field showing the same info just converted, but I think it's ok

**Comment by ericdallo** [comment]
@PEZ let me know if it works for you, I added `cljfmt-raw` setting as string

**Comment by PEZ** [comment]
Thanks!

However the `^:replace` meta on the `:indents` map is stripped. 😄 

There are a few more issues. I'll summarize them in one report, if that's OK?
