### ISSUE TITLE
Indent metadata gets stripped in cljfmt-raw serverInfo 

### ISSUE THREAD

**Issue by PEZ** [clojure-lsp/clojure-lsp#770]
**Describe the bug**

In the new `cljfmt-raw` item in `serverInfo`(#768), metadata gets stripped.

Some things that tripped me up a bit

* Maybe by intention?, the field is placed at the top level of the `serverInfo`, not in `final-settings`.
* If I use a regular expression for an indent rule the whole indents map gets replaced by an empty map. It works if I use the `#re` reader tag, but that seems unnecessary to me (who have no idea about the rationale, so feel free to ignore 😄).
* The serverInfo reports the `["client-settings", "cljfmt-config-path"]: ".cljfmt.edn"`.
   * I don't know from where this config comes, can't see that Calva does it.
   * Placing a `.cljfmt.edn` file in the project root (as reported by `project-root-uri`) doesn't seem to work. (The `:cljfmt` entry in `.lsp/config.edn` works.)

**To Reproduce**

1. Place this in clojure-lsp config:
    ```clojure
    {:cljfmt {:indents ^:replace {foo [[:inner 0]]
                                  #re "bar" [[:inner 0]]}}}
    ```
2. Run the serverInfo command
3. The result contains this, with metadata missing:
    ```
      "cljfmt-raw": "{:indents {foo [[:inner 0] [:inner 0]], #\"bar\" [[:inner 0]], #\"bar\" [[:inner 0]]}}",
    ```

**Expected behavior**

I need the metadata to be retained. 😄 

```
      "cljfmt-raw": "{:indents ^:replace {foo [[:inner 0] [:inner 0]], #\"bar\" [[:inner 0]], #\"bar\" [[:inner 0]]}}",
```

**Additional context**

Since the JavaScript `"cljfmt"` object is missing both metadata and regular expressions, I question the value of including this information in server info. Seems like any client that needs to consume this will need to use the EDN string anyway.

**Comment by ericdallo** [comment]
I think we can use rewrite-clj to get the raw string instead of `str`, not sure it would work, I can try later

**Comment by ericdallo** [comment]
@PEZ I didn't find a way to get the string + metadata :( not sure this is viable

**Comment by ericdallo** [comment]
The issue is:
To get the `:cljfmt` setting, we need to parse from end, when parsing we already read it understanding the #re and converting to regex patterns, the same apply to ^replace that it's already applied to the node, so we get only: 
```clojure
{:indents {foo [[:inner 0] [:inner 0]], #"bar" [[:inner 0]], #"bar" [[:inner 0]]}}
```
To read it as raw and don't parse, we need to read the config manually, but it could be other keys there as well besides :cljfmt, so not easy to get it

**Comment by PEZ** [comment]
I see. Very sad news!

Leave this open a while and maybe we can figure something out? I can still use this, just need to inform about. the limitation with replace metadata. The workaround for users will be that they need to provide their own defaults for anything they care about.

**Comment by PEZ** [comment]
One more thing, looking at the EDN string again, I see that `foo` gets two `[:inner 0]` tuples, and `#"bar"` gets repeated twice. The latter doesn't matter all that much, but the former, I wonder if it could mess something up. You want a separate issue?

**Comment by PEZ** [comment]
Trying to run the tests, I fail to load them because `clojure-lsp/test-helper` can't be found. Is this something you recognize?

**Comment by ericdallo** [comment]
are you using the Makefile from project root?
`make test` or `make integration-test`

**Comment by PEZ** [comment]
I want to run the tests in the REPL. `make test` will just run the tests, right?

**Comment by PEZ** [comment]
I could copy the `test_helper.clj` file to to the `test/clojure_lsp` folder and can now run tests in the REPL. Curious how you do it. 😄

**Comment by PEZ** [comment]
I haven't configured Calva to connect to a running clojure-lsp so didn't start the REPL using jack-in.

I'm building with `make` and using that binary from Calva. Then connecting Calva's REPL to it. So far all that seems missing then to run the tests is that `test_helper.clj` isn't loaded. But I can do that first and things are dandy.

**Comment by ericdallo** [comment]
@PEZ managed to make it work with a "hack" `*print-meta*` dynamic clojure variable, could you try latest master?

**Comment by PEZ** [comment]
When I looked for ways to fix this I noticed that the settings stored in the db lack the meta-data. Is clojure-lsp's formatting working correctly w/o it somehow?

**Comment by ericdallo** [comment]
@PEZ we don't persists cljfmt config on db, only on memory after starting the project, and we consider the meta correctly, the only issues was to print that meta info outside of end, like we did for cljfmt-raw, so AFAIK everything is/was working as expected

**Comment by PEZ** [comment]
Thanks! I suspected I was reading the code incorrectly. 😄

**Comment by ericdallo** [comment]
FYI @PEZ I made [a commit](https://github.com/clojure-lsp/clojure-lsp/commit/184999bb7ddd0356113ad25e620630ceb529c7b0) right now fixing that merge issue on cljfmt config, avoiding things like `{:indents {foo [[:block 1] [:block 1]]}}`, now we just merge properly: `{:indents {foo [[:block 1]]}}`

**Comment by PEZ** [comment]
Stellar. Thanks!
