### ISSUE TITLE
Support file-filter from command-line

### ISSUE THREAD

**Issue by ikitommi** [clojure-lsp/clojure-lsp#775]
Would like to have a file filter for `clojure-lsp` command-line utility. 

Currently using `clj-format` like this as a pre-commit hook:

```clj
clj -M:format fix $(git diff --staged --name-only --diff-filter=d | grep 'edn\|clj[scx]\?$')
```

It's quick as it only formats the non-deleted changed files (our codebase is a large polylith repo, formatting all files takes a long time). Couldn't find an option to do this with `clojure-lsp`, just the ns-based filtering. 

We would like to move to `clojure-lsp` for all formatting (from the command line).

**Comment by ericdallo** [comment]
I think this makes sense, I just don't know the proper flag to add to clojure-lsp, do you know how clj-format does that?

**Comment by ericdallo** [comment]
I see, the git diff result gets passed as a array of files, I was trying to avoid adding a option to apply clojure-lsp actions to specific files as the files could be outside the project, but I can see how convenient this is for this kind of workflow

**Comment by ericdallo** [comment]
@ikitommi Done, I hope it works for you, LMK if any issues.
Now there is the `--filenames` option so you can achieve what you want with something like:

```clojure
clojure-lsp format --dry --filenames $(git diff --staged --name-only --diff-filter=d | grep 'edn\|clj[scx]\?$' | tr '\n' ',' | sed 's/.$//')
```

**Comment by ikitommi** [comment]
awesome, thanks!
