### ISSUE TITLE
Proposal: adjust changelog format

### ISSUE THREAD

**Issue by mainej** [clojure-lsp/clojure-lsp#782]
During the last release I found it hard to decide where to put CHANGELOG entries. I'd like to propose a slightly different format, one which separates the **Features**, the **Performance**  improvements, the **General** maintenance, and the **API/CLI**-specific changes.

This is all very specific to my personal preferences. I'm not tied to this idea at all, and would be totally OK with a different format, or even if we keep the same format. 

Here's how I might have edited the last release:

```markdown
## 2022.02.23-12.12.12

- Features
  - clean-ns: Fix sorting of multiple refers when there is an alias before the refers.
  - code action: Fix exception when in an unbalanced map.
  - extract-function: Fix small anomalies in parameter names. #759 @mainej
  - find implementation: *new feature* find impls of defprotocol and references of defrecord/deftype #656
  - lint: Don't return diagnostics for external files like files on jar dependencies, avoiding noise on lint when opening dependencies.
  - lint: Fix scenarios where the findings in individual files differ from the .clj-kondo/config.edn settings.
  - lint: ^:export metadata excludes function from unused-public-var linter #753
  - move-coll-entry: Correctly position the cursor after moving multi line entries. #758 @mainej
  - semantic tokens: Add tokens for protocol implementations methods like defrecord and deftype.
  - Actions and commands are now aware of when they were invoked from a comment or whitespace. This will allow individual refactorings to be more deliberate about how they handle comments and whitespace. #716 @mainej

- Performance
  - code actions: Small improvement by avoiding repeated parsing.
  - code lens: Small improvement using transducers.
  - completion: Skip completions when invoked from a comment. #756
  - completion: Large improvement when many clojure.core or cljs.core symbols are valid completions. #764, #771 @mainej
  - format, clean-ns, diagnostics, rename: Small improvement via parallelizing parts of the logic.
  - startup: Medium improvement on unused-public-var calculation by parallelizing calculations.
  - startup: Medium improvement when unused-public-var linter is disabled.

- General
  - Bump clj-kondo from `2022.01.15` to `2022.02.09` adding support for implementation analysis and more improvements.
  - Bump `org.clojure/clojure` to `1.11.0-rc1`.
  - Use `:source-aliases` setting during default deps.edn and lein project-spec aliases, avoiding the need to configure a whole project-spec just because of a additional alias.
  - Add `:use-source-paths-from-classpath` setting defaulting to true, which makes clojure-lsp do not manually discovery source-paths but get from classpath excluding jar files and paths outside project-root. #752 #551
  - Add `:exclude-regex` and `:exclude-when-defined-by-regex` to `:clojure-lsp/unused-public-var` linter.
  
- API/CLI
  - API: `textDocument/implementation`: new LSP method for finding defprotocol/defrecord/deftype implementations or uses. #656
  - API: `serverInfo/raw`: Fix edn->json parser for Calva use cljfmt configuration. #763
  - API: `serverInfo/raw`: Add `:cljfmt-raw` config for Calva. #768
  - CLI: Add support for passing specific `--filenames` for most actions. #775
```

**Comment by ericdallo** [comment]
Yes, latest release had a lot of performance so I agree the current format didn't look ideal, I like to see things that affect API/CLI and/or Editor or both though, your suggestion seems to not make it easy to identify what affects editors only or API/CLI only or both, right? Maybe we find something between both ways

**Comment by mainej** [comment]
> your suggestion seems to not make it easy to identify what affects editors only or API/CLI only or both, right?

That's a good question, and may be why I was getting confused. Everything I've worked on is for the Editors. I don't think any of it affects the API or CLI, but if so, that's accidental. I couldn't really even tell you what the API and CLI expose. Anyway, they're definitely not my focus. I care most about the Editor experience: features and performance.

I guess what I was most confused about wasn't Editor vs API/CLI, but Editor vs General. Is General for things that affect the both Editors and API/CLI? If so, I may have put some things in General that belonged in Editors.

Isn't _everything_ that's in the editors exposed in the CLI via `listen`? Do you consider `listen` part of the public CLI, or is it just for integration tests?

**Comment by ericdallo** [comment]
Exactly, most clojure-lsp users are either editor users or cli/API only and some use both.
Most refractors and features are only available for editors, check clojure-lsp.api and clojure-lsp.main to check all available.

Not sure what you meant with `listen` to be honest

**Comment by mainej** [comment]
> General means some core part of clojure-lsp that affects both

OK, that makes sense. Maybe there are too many interesting axis to easily organize the changelog:

- User: Editor/API/CLI/General
- High-level feature: refactor/code action/completion/lint, etc
- Refactoring: introduce-let/extract-function, etc
- Change type: breaking change/addition/fix/perf/deps/config 

> Not sure what you meant with `listen`

I meant the [default CLI action](https://github.com/clojure-lsp/clojure-lsp/blob/b0eddbea19ffe8500d3d83836597051f1074afdc/cli/src/clojure_lsp/main.clj#L141-L144). Technically you can get to any of the "Editor-only" features through the CLI via that interface. But I'm wondering if it's actually meant for human interaction or only script interaction, like we do in the [integration tests](https://github.com/clojure-lsp/clojure-lsp/blob/b0eddbea19ffe8500d3d83836597051f1074afdc/cli/integration-test/integration/lsp.clj#L89).

**Comment by ericdallo** [comment]
I agree clojure-lsp is a tool that does too many things 😅 so we can't fit everything in multiple categories in the readme indeed, but LMK if you have other suggestions!
