### ISSUE TITLE
Add aarch64 install to bash script

### ISSUE THREAD

**Issue by mruzekw** [clojure-lsp/clojure-lsp#794]
**Is your feature request related to a problem? Please describe.**
I would like to run this command and have it download the correct binary for the architecture I'm running:

```
sudo bash < <(curl -s https://raw.githubusercontent.com/clojure-lsp/clojure-lsp/master/install)
```

This would be great for image automation.

**Describe the solution you'd like**

I think all we need to do is uncomment this line?
https://github.com/clojure-lsp/clojure-lsp/blob/master/install#L88

I'm guessing aarch64 is available given https://github.com/clojure-lsp/clojure-lsp/issues/718

**Update 1**

Forked and tried just uncommenting that line.

It's looking for:
```
https://github.com/clojure-lsp/clojure-lsp/releases/download/2022.02.23-12.12.12/clojure-lsp-native-linux-aarch64.zip
```

But the latest [release](https://github.com/clojure-lsp/clojure-lsp/releases/tag/2022.02.23-12.12.12) is outputting `.../clojure-lsp-native-linux-aarch64.zip.zip`.

**Comment by ericdallo** [comment]
Thanks! Fixed both script and release name

**Comment by mruzekw** [comment]
Thanks for making those changes! Looks like https://github.com/clojure-lsp/clojure-lsp/blob/master/lib/resources/CLOJURE_LSP_VERSION needs updating as well for the vanilla command to work.

**Comment by mruzekw** [comment]
Sorry, never mind, I see you're working on it, and it has yet to be released. 🙇

**Comment by ericdallo** [comment]
Not really, that file seems correct, what do you think it's wrong there?

**Comment by mruzekw** [comment]
Never mind! I assume that will be updated when you actually release. Sorry to bother.

**Comment by ericdallo** [comment]
yes, that's how it works! no problem, thank you!
