### ISSUE TITLE
Add practicalli snippets to built-in snippets

### ISSUE THREAD

**Issue by practicalli-john** [clojure-lsp/clojure-lsp#797]
Add to the built in snippets using those defined in [practicalli/clojure-lsp-config](https://github.com/practicalli/clojure-lsp-config/blob/main/config.edn)
https://github.com/practicalli/clojure-lsp-config/blob/main/config.edn

* Increases the number of snippets available for developers, especially for Clojure CLI deps.edn files
* Placeholder text removed from $0 (or value greater than 0 used) as $0 does not replace text when tabbed into.

#### Docs / comments
* "comment-heading" - describe purpose of the namespace
* "comment-separator" - logically separate code sections, helps identify opportunities to refactor to other name spaces

### Repl Driven Development
* "rich-comment" - comment block
* "rich-comment-rdd" - comment block with ignore :redefined-var for repl experiments
* "rich-comment-hotload" - comment block with add-libs code for hotloading libraries in Clojure CLI repl

#### Standard library functions
* "def" - def with docstring
* "def-" - private def with docstring
* "defn" - defn with docstring
* "defn-" private defn with docstring
* "ns" - namespace form with docstring

#### Clojure CLI deps.edn aliases
* "deps-alias" - add Clojure CLI alias 
* "deps-maven" - add a maven style dependency
* "deps-git" - add a git style dependency using `:git/sha`
* "deps-git-tag" - as above including `:git/tag`
* "deps-git-url" - add git style dependency using git url (url taken from dependency name as it is typed - mirrored placeholder)
* "deps-local" - add a `:local/root` dependency

#### Requiring dependencies
* "require-rdd" - add a require expression, for adding a require in a rich comment block for RDD
* "require" - simple require
* "require-refer" - require with `:refer`
* "require-as" - require with `:as` alias
* "use" - creates a require rather than the more troublesome use

#### Unit testing
* "deftest" - creates a deftest with testing directive and one assertion

**Comment by ericdallo** [comment]
> Placeholder text removed from $0 (or value greater than 0 used) as $0 does not replace text when tabbed into.

Could you elaborate? I tested both on Emacs/lsp-mode and $0 is tabbed properly, check the gif:

![Peek 2022-03-05 13-13](https://user-images.githubusercontent.com/7820865/156891395-ccd9935e-7e37-4aed-9e15-32a2d5989dd5.gif)

**Comment by ericdallo** [comment]
I added all suggested snippets and a few I noticed was missing/would be nice to have like `for`, `testing`, `is` and some `req-*`.
I just didn't followed exactly the __Standard library functions__ as it's not all the time one wants to add those with docstrings, so I kept both options for users.

Thank you for the help!
