### ISSUE TITLE
Expand `https://clojure-lsp.io/settings/#ns-inner-blocks-indentation` doc?

### ISSUE THREAD

**Issue by vemv** [clojure-lsp/clojure-lsp#804]
Hi there, I want to link to https://clojure-lsp.io/settings/#ns-inner-blocks-indentation for others to understand it, however I'm not sure the current wording is clear enough:

> Where to place first require/import following [Clojure Style Guide](https://github.com/bbatsov/clojure-style-guide#line-breaks-in-ns), :same-line, :next-line or :keep.

Perhaps each item could be described, just like in https://clojure-lsp.io/settings/#sort ?

Cheers - V

**Comment by vemv** [comment]
Thanks much!

For `next-line` it also can be added that it follows the [how-to-ns](https://stuartsierra.com/2016/08/27/how-to-ns) guide (which is relevant b/c a few tools honor it)

**Comment by ericdallo** [comment]
Done!

**Comment by vemv** [comment]
Cheers ❤️🍻
