### ISSUE TITLE
lsp-treemacs-show-call-hierarchy does not report call sites within defmethod bodies

### ISSUE THREAD

**Issue by lassemaatta** [clojure-lsp/clojure-lsp#808]
**Describe the bug**

`lsp-treemacs-show-call-hierarchy` does not report call sites which are inside `defmethod` bodies.

**To Reproduce**

```clojure
(defn foobar
  [])
​
(defn zed
  []
  (foobar))  ;; shows up in call hierarchy
​
(defmulti my-multi :some-key)
​
(defmethod my-multi :some-value
  [_]
  (foobar)) ;; does not show up in hierarchy
```

**Expected behavior**

`lsp-treemacs-show-call-hierarchy` should show all call sites.

**Screenshots**

![Screenshot_20220308_150915](https://user-images.githubusercontent.com/18479268/157245198-93b07689-b745-446f-99df-ed04c38a6946.png)

**User details (please complete the following information):**
 - OS: ArchLinux
 - Editor: emacs
 - Version: `clojure-lsp 2022.02.23-12.12.12`

**Additional context**

- [Slack discussion](https://clojurians.slack.com/archives/CPABC1H61/p1646745006768989)

**Comment by ericdallo** [comment]
I just realized this issue depends on https://github.com/clj-kondo/clj-kondo/issues/1570 :(

**Comment by ericdallo** [comment]
My PR was merged so I can work on that fix !

**Comment by ericdallo** [comment]
Fixed on master @lassemaatta! you can try the nightly release on #clojure-lsp-builds on Clojurians slack

**Comment by lassemaatta** [comment]
Great, thanks! I tested with the latest nightly and the issue is now fixed :+1:
