### ISSUE TITLE
clojure-lsp repo includes cli/target

### ISSUE THREAD

**Issue by Cyrik** [clojure-lsp/clojure-lsp#811]
**Describe the bug**
When opening the repo with Calva, the cli/target folder files show up as references.

Based on this [slack](https://clojurians.slack.com/archives/CPABC1H61/p1646830737011859?thread_ts=1645624599.312619&cid=CPABC1H61) discussion.

**Comment by ericdallo** [comment]
@Cyrik I couldn't repro with emacs, and I recall fixing that bug before releasing lastest release, I'll try with Calva

**Comment by ericdallo** [comment]
Couldn't repro on calva as well, any details on how to repro?
![image](https://user-images.githubusercontent.com/7820865/157538091-383ae4ba-76c4-49b5-bbd2-2f76d03613e1.png)

**Comment by ericdallo** [comment]
c/c @Cyrik

**Comment by Cyrik** [comment]
Ok so this must have been an issue with the clj-kondo cache after pulling out the `common` folder. It was gone after switching to master and didn't come back when switching to #805, even when clearing all caches. If it ever shows up again I'll reopen.
