### ISSUE TITLE
Lsp4clj left-overs

### ISSUE THREAD

**Issue by Cyrik** [clojure-lsp/clojure-lsp#818]
Leftover comments from the PR and issue. Should probably be cleaned up into 3+ issues, just don't want to lose the for now.

---
Yeah, the problem is that the server needs to implement the function and the lib needs to call it. And we do have it on the API, `ClojureLspProducer` in server.clj implements it. I'm also not happy with the way this part is working.

The good thing is that this is all purely Clojure, with no lsp4j or java in the way. So I think we can come up with something better here.
I do like the producer design, so maybe we should just have two of those. One is provided by lsp4clj with a default implementation for built-in LSP things and a second one for custom messages. The custom one can look however you want since the implementation and the calling side is fully outside of lsp4clj. lsp4clj would just handle construction and clean up for you.
_Originally posted by @Cyrik in https://github.com/clojure-lsp/clojure-lsp/pull/805#discussion_r824773595_

- I'd like ILSPFeature to already have the actual params as input, so that it's easier to know what to implement and easier to write a spec for it.
I think this will be easier when we run the incoming messages through the coercion as well instead of only going through java->clj, so I'm happy to wait.

- Extending the server with custom messages means you have to write Java classes (because of attributes). @ericdallo started building a more generic way to do it for dependencyContents messages, but seems to have abandoned it. Was there a reason? Do we want to find an easier way to extend the server before we push this out?
Do we pull more stuff from lib, like the transit caching? (agree with @ericdallo, lets do this in a separate PR)

**Comment by ericdallo** [comment]
Closing this since we merged #1117, Talking with @mainej, we think we can open specific issues for what #1117 didn't fix
