### ISSUE TITLE
Request: report accurate times in logs

### ISSUE THREAD

**Issue by mainej** [clojure-lsp/clojure-lsp#824]
**Is your feature request related to a problem? Please describe.**
The logs are useful for monitoring the performance of clojure-lsp features. But currently when you change a file, the logs report several misleading times:
```
2022-03-13T17:35:01.439Z  DEBUG [lsp4clj.core:?] - :didChange 0ms
2022-03-13T17:35:01.844Z  INFO [clojure-lsp.feature.file-management:?] - changes analyzed by clj-kondo took 0.10 secs
2022-03-13T17:35:01.917Z  DEBUG [lsp4clj.core:?] - :documentHighlight 477ms
2022-03-13T17:35:01.932Z  DEBUG [lsp4clj.core:?] - :semanticTokensRange 492ms
2022-03-13T17:35:02.044Z  DEBUG [lsp4clj.core:?] - :semanticTokensFull 603ms
```
 In reality, didChange take several hundred milliseconds—it reports 0ms because it does its work asynchronously. While didChange is working documentHighlight, semanticTokensRange and semanticTokensFull all wait. The logs report their wait time plus their processing time, even though the actual work usually takes only tens of milliseconds.

**Describe the solution you'd like**
I'd like the logs to report the true processing time for all of these methods. (For easy comparison, I'd also like the logs to report times in milliseconds, instead of a mix of seconds and milliseconds.)

I think the easiest way to report true processing time would be to move the logging out of lsp4clj.core and in many cases even out of clojure-lsp.server, all the way down to the handlers. In most cases whichever layer does things synchronously has the right information to log the true times.

At the moment, lsp4clj.core contains macros that facilitate logging of asynchronous things, most often CompletableFutures. The macros create closures around the async thing, capturing the time that the async process was started, and then writing a log line when its body finishes. Though this doesn't work when you have several layers of asynchronicity (consider, for example, didChange), I think we may want to keep a facility like it for other users of lsp4clj. When possible, though, I'd like clojure-lsp to log at the synchronous layer.

@Cyrik since you were part of the recent extraction of lsp4clj, I wanted to ask—will you miss the logging at that layer? Would it help to keep async logging tools in lsp4clj, even if they aren't used in lsp4clj.core?

**Describe alternatives you've considered**
* We could log from both lsp4clj.core and lower layers. However, this would make the logs noisier.

**Comment by ericdallo** [comment]
IMO we have the idea of having lsp4clj separated from clojure-lsp, so logging there doesn't makes sense as it's something we want a clojure-lsp using our log implementation.
I was aware of that bug on didChange log but I don't see a way to fix that unless moving logs indeed.

**Comment by Cyrik** [comment]
I'm not married to keeping the log stuff in lsp4clj, although it would be nice if everyone didn't have to implement it themselves. Passing the log function into the ILSPFeature handler so that the function itself does it might be a way.
To be honest, I haven't looked into our logging yet, so I trust you to make a good decision here 😄

**Comment by ericdallo** [comment]
we definitely should make log generic somehow, ATM we use timbre specific for good graalvm compatibility and because we want to log to a specific file, the server log, but other lsps probably may want something else

**Comment by Cyrik** [comment]
A log protocol would probably make it most generic. Clojure-lsp would just forward it to timbre and anyone else can do whatever fits.
Not sure if that works with @mainej's timing problem though.

**Comment by ericdallo** [comment]
I'm working on the Log protocol and it seems it will work good, it adds a little more complexity to code as it's another protocol but we could add the idea of the components I mentioned before to in the future have producer, logger, db and everything on those components.

**Comment by mainej** [comment]
It sounds like there are two questions:
* How do these two libs coordinate logging?
* Which one should log durations?

Though the first is interesting, I'm focused on the second.

@Cyrik, I'll see what I can do about sharing logging tools, but... no promises. I think it gets into the same questions @ericdallo had about where to put shared protocols.

@ericdallo since you're working on logging too, I'll plan to hold off on moving any logging statements until you're done.

**Comment by ericdallo** [comment]
Sounds good @mainej, I should have something in a couple of days

**Comment by snoe** [comment]
The java answer to this is to use slf4j interfaces in the library and let implementors of the library set the log library and log level they want.

**Comment by ericdallo** [comment]
I need some refactor in a branch I should finish soon, basically we have a new component called logger, removing any logger dependency from `lib` which is a plus
