### ISSUE TITLE
introduce-let refactor isn't published

### ISSUE THREAD

**Issue by Cyrik** [clojure-lsp/clojure-lsp#825]
**Describe the bug**
When asking for available actions, "introduce let" is never returned.

**To Reproduce**
In calva when you hit the "get refactors" key you never see "introduce let".

This happens because `code_actions.clj` does not publish the refactoring.

**Comment by ericdallo** [comment]
Yeah, this is something that was on my head to do for a long time but never did 😂 thanks!
Done!

**Comment by Cyrik** [comment]
I never knew that refactor existed. Only found it because it was mentioned as a calva command 😄  good to see it become easier to use
