### ISSUE TITLE
lsp4clj features to move

### ISSUE THREAD

**Issue by Cyrik** [clojure-lsp/clojure-lsp#826]
This is just a collection of functions / features we should think about moving out of the cli/lib folder:

1. most parts of server/run-server!
2. server/client-settings
3. shared/debound-by (and sub functions)
4. db/ all the channels
5. a protocol version of f.file-management/analyze-changes and analyze-watched-created-files!
6. file_management/did-change + handle-change

**Comment by ericdallo** [comment]
Not sure I agree with most suggestions, IMO lsp4clj should be agnostic of language implementations, we could use lsp4clj to implement a python language server for example, and not sure those servers would make sense use db/channels, debounced-by, and things like that, so we should probably discuss each one of them separately

**Comment by ericdallo** [comment]
Check lsp4j, we should be as agnostic as them IMO

**Comment by Cyrik** [comment]
Yeah, I do want it to be agnostic. But all of them need shared/debounce-by
The ones that call Clojure specific stuff would need to be made generic/turned into protocols. But that's only only parts of 2 and 5

**Comment by ericdallo** [comment]
I'm closing this since this is actually a mirror of https://github.com/clojure-lsp/lsp4clj/issues/14 which has some good discussion there
