### ISSUE TITLE
List implementations of protocol implementation with reify

### ISSUE THREAD

**Issue by dbunin** [clojure-lsp/clojure-lsp#827]
Now you are able to list implementations of `defmethod` and `defrecords` but reify is not working 😢 

Consider the following code

```clojure
(defprotocol MyFoo
  (something [this]))

(defn make-foo []
  (reify MyFoo
    (something [_]
      123)))
```

Would be really cool if it was working for reifies too

**Comment by ericdallo** [comment]
https://github.com/clj-kondo/clj-kondo/issues/1613

**Comment by ericdallo** [comment]
Fixed! available on next release, you can test with a nightly build if you want on #clojure-lsp-builds on Clojurians Slack
