### ISSUE TITLE
Move to let doesn't handle other binding forms like if-let/doseq/for/etc..

### ISSUE THREAD

**Issue by snoe** [clojure-lsp/clojure-lsp#830]
**Describe the bug**

Move to let doesn't consider other functions with binding forms 

**To Reproduce**
With the cursor at the `|`

```clojure
(let [x 1]
  (doseq [n nums]
    |(+ x n)))
```
this transforms to the invalid

```clojure
(let [x 1
      m (+ x n)]
  (doseq [n nums]
    m))
```

I believe anything other than `let` that introduces bindings will run into this.

**Expected behavior**
instead, it should noop since the move is illegal.

after https://github.com/clojure-lsp/clojure-lsp/issues/829 it should introduce a `:let [m (+ x n)]` in the doseq.
I think the order of these two issues can be tackled independent but they should consider each other.

**User details (please complete the following information):**
```
clojure-lsp 2022.02.23-12.12.12
clj-kondo 2022.02.09
```

**Comment by ericdallo** [comment]
How we could kwno if we should noop? check if it's inside a loop or something like that?

**Comment by snoe** [comment]
Yeah I think locals have a valid range in kondo, so if the nearest `let` is outside that range for any locals in the extracted var it should stop.
