### ISSUE TITLE
Remove timbre logger and its dependencies from lib

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#831]
We have the timbre dependency really coupled to almost all namespaces, timbre has some dependencies and it would be nice to remove it from `lib` to provide a API with less dependencies.

**Comment by ericdallo** [comment]
@Cyrik @mainej FYI: almost finished the `components` branch, just fixing a bug with log/error, basically we have now a components concept (I still want to improve the components build, probably [stuartsierra component](https://github.com/stuartsierra/component) would help a lot with the dependencies between them).

Things done:
- Created logger component, in a next step I'll remove timbre deps from `lib` and add only on `cli` :yay:
- Created a function just to build the `components` map with the provided protocols impls.
- ATM the `components` have just `db`, `logger` and `producer`


Things still to be done:
- I want in the future to add more like `settings`, but still have some doubts how to do it since the component initialization would need to be done after server initialization and things like that. 
- change a lot of places that receive components separated like `[arg1 logger db]` to `[arg1 components]` and do the restructuring if using one or more components. I changed few places already
- Remove the need to assoc `:logger` and `:producer` in the db to use later, `components` should be passed from top to bottom to achieve that. There are still few places using that deprecated way

**Comment by Cyrik** [comment]
> `[arg1 logger db]` to `[arg1 components]`

Unless I'm misunderstanding where you want to do this, I don't like this change 😄 
Currently, there's a lot of places(e.g. shared/uri->namespace) that get the db atom passed instead of just getting the map, or even better, the actual value they need. This makes it hard to know where mutation actually happens. The same thing would be true if we just pass all components into everything instead of giving it the component it needs.

**Comment by ericdallo** [comment]
The idea is to pass at certain points, like handlers and features, and leave pire/specific functions to not use or use just the specific dependency indeed

**Comment by mainej** [comment]
> add more like `settings`, but still have some doubts how to do it since the component initialization would need to be done after server initialization

Will you elaborate? Are you saying you need the settings to do the server initialization but then need to update the settings based on the output of the server initialization?

I was just reading about donut.system, which is another component library. It has some ideas that might apply, in particular, per-component [config](https://github.com/donut-power/system#constant-instances), which can depend on config from other parts of the system, and the idea of [stages](https://github.com/donut-power/system#stages), where you can start part of a system, get its components, and then start the rest of the system.

**Comment by ericdallo** [comment]
> Will you elaborate? Are you saying you need the settings to do the server initialization but then need to update the settings based on the output of the server initialization?

the settings components is something that to be built we would need to know the `project-root` which is only available during `initialize` lsp method, not when the application is starting (where we build producer, logger etc), so it's a component that would be build later on the application

yeah, that sounds pretty similar to https://github.com/stuartsierra/component, both would probably help with components creation.

**Comment by mainej** [comment]
Gotcha. Well, you can always put atoms in the components, and swap! in data as you gather it. It feels kind of yucky, but isn't much different from what we do now.

**Comment by ericdallo** [comment]
Yes, I'm studying other ways to achieve that, like the need to get the logger component every time we need to logger which is a little too much I think. Maybe having atom for some components makes sense indeed

**Comment by mainej** [comment]
I was worried about that... and then you have to ask, "Is accessing a global atom in my namespace much different from accessing a global function in `taoensso.timbre`?"

**Comment by ericdallo** [comment]
yes, but we will fix the root issue here, that is removing timbre from `lib` dep, having only on `cli`

**Comment by Cyrik** [comment]
> "Is accessing a global atom in my namespace much different from accessing a global function in taoensso.timbre?"

It depends if the atom holds all the components. Hopefully, it's possible to only pass the actually needed components in, ideally already deref'ed.
