### ISSUE TITLE
Add missing changes

### ISSUE THREAD

**Issue by snoe** [clojure-lsp/clojure-lsp#837]
**Is your feature request related to a problem? Please describe.**

There are two places where `add-missing-libspec` fails to add to the `:require`
- Namespaces that have never been aliased in the project.
- If you do not wish to alias namespace (think top level packages) but still require it.

As well, including a namespace that you just created is cumbersome, if you could use completion to find the new ns, and choosing it requires it it would be much better.

**Describe the solution you'd like**
`add-missing-libspec` right now asks "is there an alias?"
If we split it to ask "is this a namespace?" and "what alias should I use?" then both these issues would be handled.

If the symbol under cursor's namespace is either an alias or namespace, then it should be added to the require. If it is an alias it should be added to the require.

This could also introduce a client-setting like `:auto-alias-add-missing?` that if a namespace is found instead of an alias, then an alias could be added automatically by taking splitting the namespace by `.` and progressively adding the tail until a unique project alias is created. 
i.e. if `[foo.bar.models.thing :as thing]` exists, and you are adding to `foo.bar.common.thing/name` it would require `[foo.bar.common.thing :as common.thing]` and change the cursor to `common.thing/name`

This should also work with completions that add `:additional-text-edits` for adding missing from selecting the completion.

**Comment by snoe** [comment]
Hrm, just found the code action that does much of this. @ericdallo is there a reason `add-missing-libspec` and coompletion didn't use `find-require-suggestions` ?

**Comment by ericdallo** [comment]
Probably because it's/was a separated code action until we improved that recently.
I think we can try make add-missing-libspec smarter and use that logic or even make everything happens In a single command, without affecting code actions behaviour which works good ATM AFAIK

**Comment by snoe** [comment]
Something that find suggestions does differently than add-missing-libspec that I do not like:
- if the project uses a particular alias for a namespace or two, then I would think that only those namespaces should be suggested. 
- same if they add a fully qualified namespace, I would think that if it is aliased elsewhere, those are the only suggested aliases instead of our derived ones.

Do people really want to introduce a common alias pointing to multiple different namespaces or use different aliases for the same namespace in their projects? My feeling is that we always suggest the fully qualified namespace and then they can manually add a conflicting alias if they want to.

**Comment by ericdallo** [comment]
> Do people really want to introduce a common alias pointing to multiple different namespaces or use different aliases for the same namespace in their projects? My feeling is that we always suggest the fully qualified namespace and then they can manually add a conflicting alias if they want to.

Do you have a example?
I already saw lots of projects that use 2 namespaces for the same namespace because of legacy, ideally the project would need  to be refactored to use a single one, but I wouldn't suggest making lsp not suggest both

**Comment by snoe** [comment]
Example 1.
In clojure-lsp we only require `taessano.timbre` `log` but the suggestion that comes back for `log` are 
(the top one is from `add-missing` so ignore)
<img width="811" alt="image" src="https://user-images.githubusercontent.com/105012/159134547-bc9b4288-cc75-40cd-bf50-74b70d6cc4b3.png">
- I wouldn't mind `clojure-lsp.logging` coming back with the suggestion of `[clojure-lsp.logging :as logging]`


Example 2
Getting suggestions for the namespace, `subedit` should only suggest `zsub` or `zip.sub` (if we were inconsistent about it like that)
<img width="746" alt="image" src="https://user-images.githubusercontent.com/105012/159134689-19e3baca-c800-46b3-9344-ea1c553b0cb7.png">

**Comment by ericdallo** [comment]
Got it, I think bot makes sense, can't think in a case user would want something else for now
