### ISSUE TITLE
Using Graal

### ISSUE THREAD

**Issue by agzam** [clojure-lsp/clojure-lsp#84]
Seeing tools like clj-kondo nicely using Graal, made me think that we can considerably improve startup time. Can we discuss this possibility?

**Comment by ericdallo** [comment]
@thiagokokada is working on that now :)

**Comment by thiagokokada** [comment]
Note that I am really stuck on how to continue from there, so some help would be welcome.

**Comment by ericdallo** [comment]
Finally we have this now on clojure-lsp @agzam :)

**Comment by agzam** [comment]
Sorry for the delay. I just tried compiling it on Mac. Installed "GraalVM Community Edition based on JDK11 for macOS"; set the `GRAALVM_HOME`, ran the `./graalvm/native-unix-compile.sh`, it seems compiled everything, but it fails at the last step:

```
Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true
Compiling 1 source files to /Users/ag/sandbox/clojure-lsp/target/classes
Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true
Compiling clojure-lsp.clojure-core
Compiling clojure-lsp.crawler
Compiling clojure-lsp.db
Compiling clojure-lsp.feature.call-hierarchy
Compiling clojure-lsp.feature.code-actions
Compiling clojure-lsp.feature.completion
Compiling clojure-lsp.feature.diagnostics
Compiling clojure-lsp.feature.document-symbol
Compiling clojure-lsp.feature.hover
Compiling clojure-lsp.feature.refactor
Compiling clojure-lsp.feature.rename
Compiling clojure-lsp.feature.semantic-tokens
Compiling clojure-lsp.handlers
Compiling clojure-lsp.interop
Compiling clojure-lsp.main
Compiling clojure-lsp.nrepl
Compiling clojure-lsp.parser
Compiling clojure-lsp.producer
Compiling clojure-lsp.queries
Compiling clojure-lsp.refactor.edit
Compiling clojure-lsp.refactor.transform
Compiling clojure-lsp.shared
Created /Users/ag/sandbox/clojure-lsp/target/clojure-lsp-2021.02.07-22.51.26.jar
Created /Users/ag/sandbox/clojure-lsp/target/clojure-lsp-2021.02.07-22.51.26-standalone.jar
./graalvm/native-unix-compile.sh: line 51: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0/Contents/Home/bin/native-image: No such file or directory
```

What do I miss?

**Comment by agzam** [comment]
It looks like `gu install native-image` step is missing in the Readme.

**Comment by agzam** [comment]
yet it is still failing for me. Here's the full log: https://gist.github.com/agzam/57b2547f1627c8a62927e781e582e144

**Comment by ericdallo** [comment]
Any reason why you are compiling manually and not downloading from the GitHub releases?
But yeah, you need to install graalvm, and by install native-image

**Comment by agzam** [comment]
> Any reason why you are compiling manually and not downloading from the GitHub releases?

Ah, I prefer to use latest and greatest :) . I feel bad not finding time to contribute directly and using the latest to flush out bugs early is currently my only way to participate. I love lsp and I love Clojure I want to find a way to build it locally. It seems I'm having some gcc/clang conundrum on my Mac.

**Comment by ericdallo** [comment]
I see :)
We could improve the docs to tell to run the gu install native-image, but this error is odd indeed, are you using graalvm 21.0.0? maybe you could ask for help on Clojurians slack #graalvm channel
