### ISSUE TITLE
Vars that are declared but never used are not marked as unused

### ISSUE THREAD

**Issue by mainej** [clojure-lsp/clojure-lsp#840]
**Describe the bug**
I want to check... is this actually a bug or desired behavior? In the below code, I expect `foo` to get the unused-public-var diagnostic, but it doesn't:
```clojure
(declare foo) ;; should be marked as unused, but isn't
```
If the declared var is later defined, but is still unused, both should get the unused-public-var diagnostic, but neither does:
```clojure
(declare foo) ;; should be marked as unused, but isn't
(def foo 1) ;; should be marked as unused, but isn't
```

**Expected behavior**
I expect `foo` to be marked as unused in all three declarations above.

When `foo` is finally used, I expect the diagnostic to be removed from both of them
```clojure
(declare foo) ;; should be used
(def foo 1) ;; should be used
(inc foo)
```

If it's a bug, the fix is to remove [this line](https://github.com/clojure-lsp/clojure-lsp/blob/f4ee01df134988a7d8191e9de973672244d9784b/lib/src/clojure_lsp/queries.clj#L354). I did a quick test—it gives me the expected behavior and all the tests pass.

**Comment by ericdallo** [comment]
It seems to be your expected result makes sense, but I can't recall that was on purpose to solve some kind of edge case.
Anyway, I'm ok fixing it since all tests pass adding a new test and waiting to see if anyone complains
