### ISSUE TITLE
defmultis are never marked as unused

### ISSUE THREAD

**Issue by mainej** [clojure-lsp/clojure-lsp#841]
**Describe the bug**
This is similar to #840... In the below code, I expect `foo` to get the unused-public-var diagnostic, but it doesn't:
```clojure
(defmulti foo :bar) ;; should be marked as unused, but isn't
(defmethod foo :baz [_] 1)
```

**Expected behavior**
I expect `foo` to be marked as unused above.

When `foo` is used, I expect the diagnostic to be removed
```clojure
(defmulti foo :bar) ;; should be used
(defmethod foo :baz [_] 1)
(foo {:bar :baz})
```

If it's a bug, I have a fix.

**Comment by ericdallo** [comment]
Thanks for the report, the issue is that a defmethod is a var-usage of a defmulti I think, making it a usage.

**Comment by mainej** [comment]
> defmethod is a var-usage

That's exactly right, that's why it isn't marked as unused. So, my proposal is to make `find-references` exclude defmulti when `include-declaration?` is false. With that change, and with the change in #840, the implementations of `find-references` for var-usages and var-definitions will match, which I think makes sense.

I have a patch that will fix both issues at once, so I'll submit that.

**Comment by ericdallo** [comment]
not sure it's a good idea exclude defmulti from find-references, most of the time references should include both implementations and usages, but I guess this won't be a problem since users could call find-implementation now for those cases

**Comment by mainej** [comment]
Yeah, I'd expect to use find-implementation for that case. Here's how things work currently, and my proposed changes. What do you think? Are there other cases to consider?

| highlighting | from defmulti | from defmethod | from usage |
|--------------|---------------|----------------|------------|
| to defmulti  | yes           | yes            | yes        |
| to defmethod | yes           | yes            | yes        |
| to usage     | yes           | yes            | yes        |

| unused public var                   | warning on defmulti   | warning on defmethod |
|-------------------------------------|-----------------------|----------------------|
| only defmulti defined               | yes                   | n/a                  |
| only defmulti and defmethod defined | no **(proposed yes)** | n/a                  |
| at least one other usage            | no                    | n/a                  |

| code lens                           | on defmulti                   | on defmethod |
|-------------------------------------|-------------------------------|--------------|
| only defmulti defined               | 0 references                  | n/a          |
| only defmulti and defmethod defined | 1 reference **(proposed 0)**  | n/a          |
| at least one other usage            | 2 references **(proposed 1)** | n/a          |


| find references | from defmulti                                          | from defmethod | from usage |
|-----------------|--------------------------------------------------------|----------------|------------|
| to defmulti     | no                                                     | no             | no         |
| to defmethod    | yes **(proposed no, replaced by find implementation)** | no             | no         |
| to usage        | yes                                                    | yes            | yes        |

**Comment by ericdallo** [comment]
Just to give a little more context, What I did was tried to follow other languages conventions regarding usages and implementations, for example, in Java/Dart and probably more LSPs, when you find a reference of a interface/abstract class you find both Implementations and calls, which makes sense when you think about all possible references to that symbol, implementations are just like a subset of references. I thought that would apply as good for Clojure, maybe just defmethod/defmulti are a little bit different? not sure.

I agree with the 2 table (unused) and 3 (code lens), but I have doubts about the 4 table (references) because of the above. WDYT?

**Comment by mainej** [comment]
> all possible references to that symbol, implementations are just like a subset of references

I follow, but I see two problems.

First, if that's the policy, why does find-references from a protocol method definition not show the implementations? Or to put it another way, why have find-implementation at all, when it could be part of find-references?

Second, if you want table 2 and 3, but not 4, you need to pass another boolean through `queries/find-references`. That is you need not only `include-declaration?` but also `include-implementation?`. That's possible, but I already find `queries/find-references` hard to reason about because it's used in so many different scenarios.

**Comment by ericdallo** [comment]
> First, if that's the policy, why does find-references from a protocol method definition not show the implementations? Or to put it another way, why have find-implementation at all, when it could be part of find-references?

Maybe we should show implementations when find references of a protocol too.

But yeah, I guess we can go with you table idea as the defmulti/defprotocol references/implementations feature is recent and it sounds easier to understand and explain, I hope code would be simpler too

**Comment by mainej** [comment]
> Maybe we should show implementations when find references of a protocol too.

Yeah, that would make it more consistent too.

>  I hope code would be simpler too

It is simpler, which is why I'm pushing for it. :) I'll submit a PR. If you experiment with it and don't like how it works, or even if you merge it and hear complaints, let me know—I can work on making find-references show implementations for both defmulti and protocols. I'd just prefer to do that separately.

My real goal is to see if I can speed up custom linting at all, so I'm trying to make find-references as simple and consistent as possible for that.

**Comment by snoe** [comment]
Here's some context for followup work this.

To me, unused-vars and find references are tools I use to know that I'm done refactoring. If I'm trying to remove all calls to a `defmulti`, and it gets marked as unused, or my list of references to it is empty, I know I can remove it from the code.

`defmethod` is tricky because they are often done in files that are not near the `defmulti` and just need to be loaded, probably far from the call sites. `declare` is similar but at least more local.

If a `defmethod` is sitting around, I probably don't catch it until CI (or possibly later). So I do think

**Comment by ericdallo** [comment]
> IMO if we say something is unused, it should be ok to excise from the code.

Yes, agreed, but I think we can still mark as unused following that, we do have all the necessary analysis to confirm that, right?

**Comment by mainej** [comment]
@snoe, will you clarify a little? For defmulti there are two potential meanings to the word "unused":
1. "no code calls this method"
2. "no code calls _and_ no defmethod implements this method"

Personally, I'm most interested in the first one. I want my editor to point out to me that a defmulti is unused, and that therefore it's a candidate for removal. That is, I want the unused-var squiggle to tell me when I can start the refactoring process. As I'm removing things, I know that if I remove the defmulti before I remove its defmethods, my code won't compile. But fortunately, I have clojure-lsp to help me out. I can call `find-implementations` (a relatively new feature) to navigate to all of the defmethods before I remove the defmulti. I don't want the second meaning of "unused" because I'd be left with defined but uncalled defmultis, since I don't keep a mental map of where every defmulti is called.

It sounds like you're more interested in the second meaning, where the defmulti looks like it's used until the last defmethod is deleted, and only then is it marked as unused. Is that correct?

**Comment by mainej** [comment]
> how do I know that I can delete a definition
>... I can't delete unused defmulti's until I track down the defmethods

I agree that clojure-lsp should warn you if you delete the defmulti before deleting its defmethods, but it already does and will, by putting an "unresolved symbol" lint on the defmethod. That's an `:error` level lint, which you should expect to have to fix. Even if you don't fix it, you find out immediately, as soon as you compile, for example by running tests, which I assume you're doing regularly in big refactorings.

> how the workflow would go

Current workflow:

1. know that you want to delete a defmulti
1. go-to-def to find defmulti 
1. find-references to find calls and defmethods
1. delete calls and defmethods, get info squiggle on defmulti
1. delete defmulti

New workflow:

1. know that you want to delete a defmulti
1. go-to-def to find defmulti
1. find-references to find calls
1. delete calls, get info squiggle on defmulti
1. delete defmulti, get error squiggle on defmethods
1. delete defmethods

Or for those who know about find-implementation:

1. know that you want to delete a defmulti
1. go-to-def to find defmulti
1. find-references to find calls
1. delete calls, get info squiggle on defmulti
1. find-implementations to find defmethods
1. delete defmethods
1. delete defmulti

Most importantly, this lets clojure-lsp suggest a new workflow, which to me is more interesting than when you've already decided you want to delete the defmulti:

1. get warning on defmulti that you've deleted all calls!
1. find-implementations to find defmethods
1. delete defmethods
1. delete defmulti

> lint like "implementations exist but otherwise unused"

Having another custom lint could be interesting, although I worry that one is very specific to your use case. I was thinking of a similar solution where the code lens on the defmulti showed `0 references | 2 implementations` or something like that, but it would only help if you use code lens. If we were to add a custom lint, I think it should be `:clojure-lsp/no-implementations`. But I see why you might not be happy with that because you'd still have to know that defmultis are special and need two lint warnings (no usages and no implementations) before they can be deleted. Or to put it another way, you want the info-level squiggles to mean "delete-able" when I think they should mean "more info available".

> that's an extra burden of knowledge I would expect most users to miss

With the introduction of `find-implementation`, we've already added to the knowledge we expect users to have. 

I don't know... I can see both sides of this. When find-implementations was first introduced I also felt, "Another thing to remember? Why not make find-implementations part of find-references? Isn't the idea of implementations too OO?"  As I've used it more though, I've come to appreciate that it's a separate concept, and I no longer want them mashed together. There's another question, "Is an implementation a reference to the definition? Or is it a definition itself?" And I think the answer is, "It's its own thing." That highlights the polymorphism in your code and therefore expands your understanding of how the codebase works, which is usually good even if it takes a bit more thinking to fully understand.

**Comment by snoe** [comment]
Thanks for the steps! I think it shows the issue I have.

What we can see is that the current workflow works no matter how the var was def'd (`defmulti, defn, declare, def, let, :keys destructuring`, etc...) if the squiggle shows up, then it can be deleted. IME often these refactors are deleting multiple vars at once, and my lizard brain will see the "unused" squiggle -> so I delete.

> New workflow:
> 4. delete calls, get info squiggle on defmulti
> 5. delete defmulti, get error squiggle on defmethods
>
> Or for those who know about find-implementation:
> 4. delete calls, get info squiggle on defmulti
> 5. find-implementations to find defmethods

Here is the crux. It is common for a `defmethod` to live away from the `defmulti`. You will not see the squiggle on the `defmethod` - repl state will often hide the deletion, and it won't be caught until tests run (if they load the defmethod ns) or compile (with aot). Even if you know about `find-implementation`, there's no indication that you need to use it or you'll break your code in some namespace you don't even know exists.

So, I think it is ok to separate find-references and find-implementations.

> Or to put it another way, you want the info-level squiggles to mean "delete-able" when I think they should mean "more info available".
Right, I see "delete-able" as a consistent and clear action that can be performed. "More info available" means that I have to get out of lizard brain and ask "what am I forgetting?" if we can build a tool that avoids that context switch I think it's a better experience. Imagine a `clean-cruft` refactor, I believe we should know what can and can't be deleted.

I understand simplicity and speed is part of the issue here so maybe (this is brainstorming)
- could analysis be indexed as it comes through to count/update usages of defs. 
- This has a lot of overlap in my mind with [carve](https://github.com/borkdude/carve).

**Comment by ericdallo** [comment]
So I think we can procceed with #843 merge as @snoe agree with the segregation between find-implementations and find-references, right?

**Comment by mainej** [comment]
@ericdallo ... not quite yet. I'll respond in a minute.

**Comment by mainej** [comment]
@ericdallo I believe what @snoe is saying is that he doesn't mind that find-implementations exists, but he also doesn't want to change his usage of find-references now that it does exist. And in particular he doesn't want unused-public-var—which is built on find-references (atm)—to change.

> Imagine a `clean-cruft` refactor, I believe we should know what can and can't be deleted.

Isn't this making my argument for me @snoe? Wouldn't you consider an implemented but uncalled defmulti cruft? Shouldn't `clean-cruft` delete it and its defmethods?

That said, I accept that defmultis can be far from their defmethods, and that the lizard brain wants to just act. 

So, I think I'm going to concede here, if you'll concede something in return... Stepping back, what I really want is these two things:

1. As a contributor to clojure-lsp, I want find-references to return the same results whether you're on a defmulti, defmethod, or usage. Right now they do different things, which means it's especially hard to think about how that code works. (Note that this isn't about speed or simplicity, it's about consistency.)
2. As a user of clojure-lsp, I want the editor to tell me when I have an uncalled method.

I'm willing to give up the second desire, if I can have the first. What would that look like? In terms of the [tables](https://github.com/clojure-lsp/clojure-lsp/issues/841#issuecomment-1073359269) above, we'll keep everything the same as it is currently, except for the last table. In that table, we'll make the second and third columns the same as the first. That is, find-references from a defmulti will stay the same, returning defmethods and usages. But calling find-references from defmethods and usages will start returning the defmethods too, not just the usages. Is that acceptable? I don't think it impacts your workflow. Does it interfere with any other workflow? The tests don't seem to indicate it would. In terms of code, it will mean deleting [this line](https://github.com/clojure-lsp/clojure-lsp/pull/843/files#diff-953310fb5e54c1b32a0f931450ceb70ffc4e0130927391c85964242ebbc61c7cR344).

And note, there are still ways for me to have my second desire:
1. A new custom lint for implemented-but-unused defmultis, as you suggested, possibly with configuration for whether that gets the ["deletable" indication](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticTag) in the editor.
2. A new configuration option, something like `:include-implementations-in-references`. (This would be a pain to implement.)
3. Deleting all calls marks the defmethods as unused. (This would also be a big change.)

And as one final question, @snoe, does your workflow work for deleting protocols? I don't think it does or ever has. It's something you could propose.

**Comment by snoe** [comment]
> So, I think I'm going to concede here, if you'll concede something in return... Stepping back, what I really want is these two things:
>
>    1. As a contributor to clojure-lsp, I want find-references to return the same results whether you're on a defmulti, defmethod, or usage. Right now they do different things, which means it's especially hard to think about how that code works. (Note that this isn't about speed or simplicity, it's about consistency.)

Yes, that's weird and should be consistent.

>    2. As a user of clojure-lsp, I want the editor to tell me when I have an uncalled method.

Ah, I see. To me `uncalled` is different than `unused`.

> I'm willing to give up the second desire, if I can have the first. What would that look like? In terms of the https://github.com/clojure-lsp/clojure-lsp/issues/841#issuecomment-1073359269 above, we'll keep everything the same as it is currently, except for the last table. In that table, we'll make the second and third columns the same as the first. That is, find-references from a defmulti will stay the same, returning defmethods and usages. But calling find-references from defmethods and usages will start returning the defmethods too, not just the usages. Is that acceptable?

That's acceptable, but it would also be acceptable to me if everything except the `unused-var` table changed as proposed.

> And note, there are still ways for me to have my second desire:

The `uncalled` lint, I think could also solve this if it went from > no squiggle > delete calls > uncalled > delete methods > unused.

> does your workflow work for deleting protocols?

I don't know if it does but I feel that it should be consistent. I rarely work with protocols, so I definitely spent little time making that code anything other than ok. At first glance it would make sense if the same rules were applied there as defmultis.

**Comment by ericdallo** [comment]
I like @mainej proposal both to keep consistency as a user and a clear flow as a developer.

**Comment by mainej** [comment]
OK, #843 has been [updated](https://github.com/clojure-lsp/clojure-lsp/pull/843/commits/0ced8f60546a8a6d5ed650d0f21f21e6b9d83636) to match the latest proposal. It no longer addresses this issue, only #840.

This issue is still open. See above for possible solutions. At the moment I'm leaning toward @snoe's suggestion of a new custom lint, something like `:clojure-lsp/uncalled-multimethod`.

**Comment by ericdallo** [comment]
yeah, in the end, a new linter is a safe new option

**Comment by mainej** [comment]
> it would also be acceptable to me if everything except the unused-var table changed as proposed.

Agh, really @snoe? I misunderstood that. I thought you were saying that you wanted both the unused-var and the find-references table to remain unchanged, so that the squiggle and your flow for deleting defmethods stays the same. But I guess you're saying it'd be OK if you had to use find-implementations to delete defmethods?

In the end, it's not a big deal I guess. A new linter may be better anyway.

**Comment by mainej** [comment]
On second thought, this issue has gathered too many side discussions to be a succinct summary. I'm going to close this issue and open another one with a new linter as the proposed solution.

**Comment by snoe** [comment]
Replying to wrap up the questions here, not to reopen anything.

> I believe what @snoe is saying is that he doesn't mind that find-implementations exists, but he also doesn't want to change his usage of find-references now that it does exist. And in particular he doesn't want unused-public-var—which is built on find-references (atm)—to change.

> Agh, really @snoe? I misunderstood that. I thought you were saying that you wanted both the unused-var and the find-references table to remain unchanged, so that the squiggle and your flow for deleting defmethods stays the same. But I guess you're saying it'd be OK if you had to use find-implementations to delete defmethods?

Sorry @mainej  I think you understood me pretty well. Primarily I'm concerned with unused-public-var. Secondarily, I think keeping find-references is a nice to have as a master list to work through and for the symmetry with unused-public-var. 

But as you brought up concessions, I'm happy to concede that `find-references` and `find-implementations` can be changed to be non-overlapping sets if it feels like it's worthy tradeoff.



>    Imagine a clean-cruft refactor, I believe we should know what can and can't be deleted.
> Isn't this making my argument for me @snoe? Wouldn't you consider an implemented but uncalled defmulti cruft? Shouldn't clean-cruft delete it and its defmethods?

This was a good point. I didn't mean to skip over it. You're right those are cruft. I guess I was coming from the perspective of how hard it would be to implement `clean-cruft`. If you can simply look for `public-unused-var` and delete the `(z/up loc)`s, without having to figure out if it's a defmulti or defn. Which I think is another argument for the lint as you can handle `uncalled-multi` lints as you describe.

**Comment by mainej** [comment]
> a good point. I didn't mean to skip over it.

Thanks for acknowledging that @snoe :)

> I was coming from the perspective of how hard it would be to implement `clean-cruft`

That makes sense, and as you said, it's a good argument for a custom lint.

> `find-references` and `find-implementations` can be changed to be non-overlapping sets 

For now, it's still a mix. The results overlap for defmultis, but not for defprotocols or the other implementable things, which is more an artifact of the order things were implemented in than any explicit decision. 🤷‍♂️ I'm expect that'll be revisited someday.
