### ISSUE TITLE
move-coll-entry-up / move-coll-entry-down selects a range after edit instead of maintaining cursor position

### ISSUE THREAD

**Issue by snoe** [clojure-lsp/clojure-lsp#862]
**Describe the bug**
move-coll-entry-up / move-coll-entry-down selects a range after edit instead of maintaining cursor position

**To Reproduce**
Call move-coll-entry-up or move-coll-entry-down and get a full range back for the edit.

**Expected behavior**
The intent is to maintain cursor position not to select a range.

**Additional context**
From clojurians:
[snoe](https://app.slack.com/team/U0BUV7XSA) [Today at 1:44 PM](https://clojurians.slack.com/archives/CPABC1H61/p1648064672479169)[](https://files.slack.com/files-pri/T03RZGPFR-F038D8MKBK5/recording_2022-03-23_at_13.36.38.gif)[](https://files.slack.com/files-pri/T03RZGPFR-F038D8MKBK5/download/recording_2022-03-23_at_13.36.38.gif)
Is there a reason move-coll-entry-up/down  uses a the full range of the loc in show-document-after-edit ? I believe the intent is to keep the cursor position as you repeat, but in vim because the range is more than one char it selects the range and breaks repeatability. I think a change like (assoc cursor-position :end-row (:row cursor-position) :end-col (:col cursor-position)) would be ok if i have the intent correct.
![Recording 2022-03-23 at 13 36 38](https://user-images.githubusercontent.com/105012/159784909-731ab421-4a3d-4730-95b9-cb64329beb5f.gif)

[ericdallo](https://app.slack.com/team/UKFSJSM38):clojure-lsp:  [8 minutes ago](https://clojurians.slack.com/archives/CPABC1H61/p1648064818024029?thread_ts=1648064672.479169&cid=CPABC1H61)
hum, I think that was intentional, looks like vim has a different behavior, [@jacob.maine](https://clojurians.slack.com/team/U07M2C8TT) knows more about that feature

[jacob.maine](https://app.slack.com/team/U07M2C8TT)  [3 minutes ago](https://clojurians.slack.com/archives/CPABC1H61/p1648065144666639?thread_ts=1648064672.479169&cid=CPABC1H61)
[@snoe](https://clojurians.slack.com/team/U0BUV7XSA) that’s an accident and your proposed fix looks good. Thanks for tracking that down

[jacob.maine](https://app.slack.com/team/U07M2C8TT)  [2 minutes ago](https://clojurians.slack.com/archives/CPABC1H61/p1648065211070209?thread_ts=1648064672.479169&cid=CPABC1H61)
And yes, the intent is to maintain position, not to select a range

**Comment by ericdallo** [comment]
taking a closer look, I don't know why that doesn't happen on emacs but on vim
