### ISSUE TITLE
Problem with expand-let duplicating outer form

### ISSUE THREAD

**Issue by snoe** [clojure-lsp/clojure-lsp#879]
**Describe the bug**
Simply put, this transform is incorrect

```clojure
(do [(let [f 1] |f)])
;;=>
(do (let [f 1]
     (do [f])))
;;=> should be
(do (let [f 1]
     [f]))
```

I encountered it on this form calling move-to-let (that delegates to expand-to-let)
```clojure
(defn get-table [{:keys [path-params]}]
  {:status 200
   :body |path-params})
;;=>
(defn get-table [{:keys [path-params]}]
  (let [f path-params]
   (defn get-table [{:keys [path-params]}]
  {:status 200
   :body f})))
```

This has something to do with being in a collection like a map or a vector.

This is on master acc953a9b315353e18ef8be50ce06253fc4ae69f

**Comment by ericdallo** [comment]
Hum, I thought we fixed this recently, there was another report of this issue

**Comment by ericdallo** [comment]
https://github.com/clojure-lsp/clojure-lsp/issues/676
Probably some leftover?

**Comment by snoe** [comment]
Looks like a slightly different issue with nested lets, this was trying to expand out of a vec or map

**Comment by ericdallo** [comment]
Fixed on https://github.com/clojure-lsp/clojure-lsp/pull/880
