### ISSUE TITLE
Move-coll-entry should work at top level

### ISSUE THREAD

**Issue by snoe** [clojure-lsp/clojure-lsp#891]
So I recognize that the name of the command makes this weird, but semantics aside I believe `move-coll-entry` is a smarter transpose  (`transpose-sexps` in emacs). If the command worked to transpose `(defn...)` forms at the top of level of the namespace, it would be able to completely replace my transpose keybindings. As it is, I need to maintain both. This is useful in clojure when you need to maintain declare order of vars.

```
(def x 0)
|(def y 1)
=> move up
|(def y 1)
(def x 0)
=> move down
(def x 0)
|(def y 1)
```

**Comment by ericdallo** [comment]
It looks like a good improvement, WDYT @mainej ?

**Comment by mainej** [comment]
#893 lets you move top-level forms. My memory was right—the obvious solution caused the whole file to get duplicated—but I was able to work around it. When the rewrite-clj bug linked above is fixed, we won't need the workaround.

>  I recognize that the name of the command makes this weird

Naming has been in the back of my mind too... The feature was originally about moving terms within data structures, which is how it got its name. But it does more now. How about renaming it to "Move clause" since it moves clauses in both collections and other forms? I'd like to change it's name in the actions menu and in the docs, but not in the commands. Otherwise the clients have to be updated too, or at least emacs-lsp does. Any objections @ericdallo or @snoe? Do you know if it'll cause other problems?

**Comment by ericdallo** [comment]
Sounds good @mainej , maybe we could add a new command with the new name and keep the old one pointing to the same function, WDYT?
With that we could remove any references on docs to the old command and mark on code as deprecated, so we can later remove on each client if they already implemented (lsp-mode and Calva already I think)

**Comment by snoe** [comment]
@mainej
For a name, I think possible verbs are `move`, `swap`, and `transpose`. I think "forward" and "backward" are more precise and idiomatic directions than up/down (mirror tree nav). The noun is either `clause`, `sexp`, `element`, or `form`. Possibly with the "smart" adjective to differentiate from the naive implementations, although in cursive I was never surprised by it.

emacs `transpose-sexp` `transpose-sexp-1` 
cider `move form backward` `move form forward` (says `form`, means element or pair)
vim-sexp `swap the position of current element`  (bound to Meta left/right)  `swap the position of current form` bound to up/down)

With regards to a two letter initial for both, mf/mb and sf/sb both are available, tf is not. 

I think that including the noun in the command is actually confusing, as it changes depending on context. I'd just drop it and be understood as smallest possible/atomic syntactic unit.

So I'll suggest either `move-forward` & `move-backward`, or `swap-forward` & `swap-backward`.

I think setting precedent to deprecate commands is great, as I have similar naming qualms about a few others as well.

**Comment by snoe** [comment]
For a couple asides:

1. I think vim-sexp's distinction between `element` and `form` is very useful. 
`element` being the smallest unit the cursor is on (`#inst "...."`, `{}`, `var`, `(def ...)`, `1000`)
 `form` being the enclosing parenthesized sexpr (`(defn x [] (inc |1)) => (inc 1)`) 
(if the cursor is on a paren then they are same) .

2. Cursive also has an extend/shrink selection that follows the same rules as `move-coll-entry` so something to keep in mind re: naming.

**Comment by mainej** [comment]
> add a new command with the new name and keep the old one

Great idea! I'll plan on that.

> "forward" and "backward" are more precise and idiomatic directions than up/down

Sigh... I know. This has been a significant impediment in my evolution toward being a full lisp parser. I know that the correct term is "forward", or "right", but when I look at the code below, my intuition says "down".
```clojure
{|:a 1
 :b 2}
```
Don't even get me started on the fact that climbing from the root toward the leaves is "down" not "up". The whole field is upside down and inside out.

Anyway, I agree, I should use the correct computer science term, as should the command. But as a consolation to my brain, maybe it'd be OK to use the "wrong" term in the action menu and docs. Or use both terms? Something like "forward/down" or "backward/up"?

> The noun is either clause, sexp, element, or form

If it's going to be any of those, I'd pick "clause". To me, the other three suggest "one thing only". But I think I prefer your idea of omitting the noun entirely. I'll plan on that.

> verbs are move, swap, and transpose

I've been toying with "move", but without a noun it's so generic. And it'd be easy to mistake move-form with move-forward, both phonemically and semantically. In emacs "transpose" only applies to two element and only works to move backward, AFAIK. In my mind "swap"  also implies an operation on only two elements. 

Maybe a new term—"shift". Or "drag"? It looks like Calva [calls it "drag"](https://calva.io/paredit/#drag-bindings-forwardbackward).

We could even go crazy and use two verbs: "Push forward" and "Drag backward". Anyway, I'm sinking into analysis paralysis. Do any of these options appeal strongly to either of you?

**Comment by snoe** [comment]
ah forgot about `mf` and agree move is generic. I'm fine with either drag or shift, I'd prefer not to change the verb. If calva has precedent, I'm inclined to go there.
