### ISSUE TITLE
Add .bb and .cljd to the watchlist

### ISSUE THREAD

**Issue by Cyrik** [clojure-lsp/clojure-lsp#906]
Based on a ticket in calva and the slack discussion: https://github.com/BetterThanTomorrow/calva/issues/1617

**Comment by Cyrik** [comment]
@ericdallo I haven't looked deeply into it, but I think the following functions also need to be updated: `shared/uri->file-type` and `shared/uri->available-langs`

**Comment by ericdallo** [comment]
Yes, probably, but I don't know for sure how we should handle those files, for example, cljd is more like a cljs or a clj file?

**Comment by Cyrik** [comment]
Good question, I haven't used either yet, just forwarded the user request. Does clj-kondo have any special handling for them @borkdude?

**Comment by ericdallo** [comment]
Done @Cyrik thank you!
