### ISSUE TITLE
:clojure-lsp/unused-public-var can't be disabled for comments.

### ISSUE THREAD

**Issue by Cyrik** [clojure-lsp/clojure-lsp#918]
**Describe the bug**
:clojure-lsp/unused-public-var can't be disabled for comments.

**To Reproduce**
1. add `:config-in-comment {:linters {:clojure-lsp/unused-public-var {:level :off}}}` to .clj-kondo/config.edn
2. put `(comment (def something 1))`  into your file.
3. it still produces a diagnostic

**Expected behavior**
should not produce a diagnostic

Not sure if this is a clj-kondo problem with custom linters and the :config-in-comment settings or if it's specific to that lsp linter

**Comment by ericdallo** [comment]
This is known and explained [here ](https://github.com/clojure-lsp/clojure-lsp/issues/900) why it's not supported.
