### ISSUE TITLE
Autocomplete can pull in other alias shadowing an alias already present

### ISSUE THREAD

**Issue by dpsutton** [clojure-lsp/clojure-lsp#920]
**Describe the bug**
We use plumatic schema with the common alias `:as s`. When asking for autocompletions for `s/val` to find how schema validates schemas, the autocompletions will include the schema validate functions but also the spec validate functions. I often unwittingly choose `s/valid?` instead of the schema version `s/validate`. The result is that my namespace ends up with two aliases `:as s` and I am choosing a function I do not want.

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/6377293/162481173-fc023606-c6b7-4ec7-8d26-d87bc7b92333.png">

Another example, is in a namespace with `clojure.tools.logging :as log`. I'll type `log/wa` and press enter on `log/warn`. But this has identified a `warn` function from some util namespace with logging in its name from our codebase so i end up with `<repo>.utils.logging :as log` in the ns form.

This `log` version is actually worse because it is not clear from the autocomplete suggestions that the `log/warn` I'm choosing is some `<repo>.utils.logging/warn` rather than `clojure.tools.logging/warn` since the UI only shows `log/warn` in both cases.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/6377293/162482250-1f6138f2-e5bb-496a-aa3f-02a225f48b22.png">

**To Reproduce**
`prismatic/schema {:mvn/version "1.2.0"}` and include it in a namespace. Type `s/val` and see the choices from the screenshot above

**Expected behavior**
Should not show autocomplete suggestions for namespace aliases which are already present. In this case, the common `s/valid?` from spec should be ignored when i already have schema present. The same for the `log` situation.

**Comment by ericdallo** [comment]
@dpsutton fixed, could you test a nightly build?
