### ISSUE TITLE
move-coll-entry moves :keys destructuring in pairs

### ISSUE THREAD

**Issue by snoe** [clojure-lsp/clojure-lsp#927]
**Describe the bug**
move-coll-entry moves :keys destructuring in pairs

**To Reproduce**
Happens in fn parameters and let bindings. Also explains why with uneven keys, nothing happens.

```clojure
(let [{:keys [a b |c d]} x] 1)
;;=expected>
(let [{:keys [a |c b d]} x] 1)
;;=actual>
(let [{:keys [c d |a b]} x] 1)
```

```clojure
(let [{:keys [a |b c]} x] 1)
;;=expected>
(let [{:keys [|b a c]} x] 1)
;;=actual>
(let [{:keys [a |b c]} x] 1)
```

clojure-lsp 2022.02.23-12.12.12
clj-kondo 2022.02.09

**Comment by ericdallo** [comment]
Makes sense to me, WDYT @mainej ?

**Comment by mainej** [comment]
Yep, that's a bug. And I have a hunch about how to fix it.
