### ISSUE TITLE
Consider having clean ns also sort imported classes

### ISSUE THREAD

**Issue by lread** [clojure-lsp/clojure-lsp#932]
**Is your feature request related to a problem? Please describe.**
When I am doing Java interop, I sometimes have long lists of classes names for my imports.
I find it easier to read these longer lists when the class names are sorted.

**Describe the solution you'd like**
I'd like clean-ns to also sort imported class names.

For example:
```Clojure
(ns some.ns.here
  (:import
   (a.lovely.java.package Fabulously Sorted Absolutely)))
```
Would be cleaned to:
```Clojure
(ns some.ns.here
  (:import
   (a.lovely.java.package Absolutely Fabulously Sorted)))
```
**Describe alternatives you've considered**
This can be done manually by hand, but that's not a ton of fun.

**Additional context**
- Should this behaviour be optionally enabled/disabled by a setting?
- Are there some syntaxes of `:import` that are not candidates for class name sorting?

**Comment by ericdallo** [comment]
@lread I was wondering, ATM we don't have any sorting inside `()` or `[]` imports, and checking Clojure Style Guide I don't see anything regarding how the Classes inside those brackets should behave, I mean, how we should sort the following code:

Subject
```clojure
(:import 
 (foo.bar A C B))
```

1.
```clojure
(:import 
 (foo.bar A B C))
```
2.
```clojure
(:import 
 (foo.bar A
          B
          C))
```
3.
```clojure
(:import 
 (foo.bar 
   A
   B
   C))
```

1. looks the obvious expected result for that code since it would only sort but not touch formatting, but I don't know how hard/possible would be to sort rewrite-clj nodes without changing whitepsace/new-line nodes positions, WDYT?

**Comment by lread** [comment]
Hiya @ericdallo, I suppose you could have another option like [`ns-inner-blocks-indentation`](https://clojure-lsp.io/settings/#ns-inner-blocks-indentation) maybe, `ns-import-classes-indentation`, which might inherit from `ns-inner-blocks-indentation` by default?

For `ns-inner-blocks-indentation` what do you do when setting is `keep`? Do you preserve whitespace/newlines? Or does it not sort in that case?

**Comment by ericdallo** [comment]
Yeah, that was supposed to keep the indentation, but checking code, it does use specific formatting that should work in most of the cases, but we don't ignore totally the format, unfortunately.

I think your idea makes sense of a second setting for that, I can't see it working easily without using specific formatting pre-defined.

**Comment by lread** [comment]
Yeah, I think it would be a good start anyhow!
And then you'll find out if anybody is aching to sort import classes and preserve formatting.
Maybe nobody is!

**Comment by ericdallo** [comment]
@lread Done! LMK if any issues, I updated the docs as well: https://clojure-lsp.io/settings/#ns-import-classes-indentation

**Comment by lread** [comment]
Sweet! Thanks!
