### ISSUE TITLE
n classes per line in ns import declaration

### ISSUE THREAD

**Issue by dchelimsky** [clojure-lsp/clojure-lsp#966]
**Is your feature request related to a problem? Please describe.**

As of [2022.05.03-12.35.40](https://github.com/clojure-lsp/clojure-lsp/commit/e68428965f78291b5c116f7e14558ff4e206f630), lint converts

```clojure
  (:import [java.io ByteArrayOutputStream DataOutputStream]
           [java.text Normalizer Normalizer$Form NumberFormat]
           [java.util Locale UUID])
```

to

```clojure
  (:import [java.io
            ByteArrayOutputStream
            DataOutputStream]
           [java.text
            Normalizer
            Normalizer$Form
            NumberFormat]
           [java.util
            Locale
            UUID])
```

**Describe the solution you'd like**

```clojure
  (:import (java.io ByteArrayOutputStream DataOutputStream)
           (java.text Normalizer Normalizer$Form NumberFormat)
           (java.util Locale UUID))

* Lists instead of vectors for `:import` (maybe as a config option since some people will care and others won't)
* classes per line, any of:
   * all on one line
   * n per line
   * split at character n

**Comment by ericdallo** [comment]
Thanks for the report, so I think there are 2 features request here, to to replace vectors with lists or the other way around (if that makes sense) and one to change indentation of classes, maybe a config like this would be enough:
 
```clojure
{:clean {:import-classes {:classes-per-line 1 ;; -1 for all in single line
                                       :split-on-column 80}}}  ;; takes precedence over classes-per-line
```
Any suggestion on what would be the default for `classes-per-line` (current 1)?

**Comment by dchelimsky** [comment]
> Any suggestion on what would be the default for `classes-per-line` (current 1)?

I think 4 would be a good default, but 3 or 5 could work, too :)

**Comment by ericdallo** [comment]
@dchelimsky I ended up adding support for `classes-per-line` only with a default of 3, if we receive too many complaints about the need for a `:split-on-column` we can consider adding it, for now, I think it will be enough for most cases.
