### ISSUE TITLE
drag doesn't work in `are` when `clojure.test` is aliased

### ISSUE THREAD

**Issue by mainej** [clojure-lsp/clojure-lsp#967]
**Describe the bug**
This should drag three elements, but only drags one:
```clojure
(ns my-test-ns
  (:require [clojure.test :as test]))

(deftest my-test
  (test/are [x y z] (= x y z)
    1 2 3
    |4 4 4))
```

**Additional context**
This happens because the drag code only uses its smarter clause-breadth detection when the symbol is exactly `are`, not `test.are`. There are two possible fixes...

1. Look at the `name` of the symbol, not the whole thing.
2. Use the clj-kondo analysis to check whether the call site actually uses `clojure.test/are`.

The second option is technically more correct, but I'm going to use the first. The first option is (very slightly) faster, but that's not my main motivator. Instead, I kind of like that we look only at the symbol for `are`, along with `cond`, `case`, and other special functions, as well as the binding forms `let`, etc. This means that other libraries that define functions with these same names get treated the same. The argument is that if a library author names a var `let`, its parameters should have the same structure as `clojure.core/let`'s.

I'll submit a PR momentarily.

**Comment by ericdallo** [comment]
> The second option is technically more correct, but I'm going to use the first. The first option is (very slightly) faster, but that's not my main motivator. Instead, I kind of like that we look only at the symbol for are, along with cond, case, and other special functions, as well as the binding forms let, etc. This means that other libraries that define functions with these same names get treated the same. The argument is that if a library author names a var let, its parameters should have the same structure as clojure.core/let's.

Yeah, sounds good
