### ISSUE TITLE
Drag should work from quoted symbols

### ISSUE THREAD

**Issue by mainej** [clojure-lsp/clojure-lsp#969]
**Describe the bug**
Drag isn't available here, or from any other location within the quoted symbol.
```clojure
[var '|quote :keyword]
```

**Expected behavior**
Drag should be available.

**Additional context**
Note that dragging from the quote works, just not within it:

```clojure
[var |'quote :keyword] ;; <-- drag is available
```

**Comment by mainej** [comment]
This happens because
```clojure
[v 'q :kw]
```
Is parsed as
```clojure
[:vector
 [:token v]
 [:quote [:token q]]
 [:keyword :kw]]
```
When the cursor is on `q`, the parent node is `:quote`, which has only one child, and which therefore doesn't support drag.

I think the fix is to pretend that the drag request actually came from the `:quote` node, although I need to experiment to see whether that causes other problems.

**Comment by ericdallo** [comment]
Yeah, I can see other issues happening with things like `#_foo` or `#(:cljs 1)` since they behave similar to quote I think

**Comment by mainej** [comment]
> `#_foo` or `#(:cljs 1)`

Thanks... I'll keep those in mind too.
