### ISSUE TITLE
Rename symbol on re-frame keyword not working

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#978]
**Describe the bug**
When I try to rename a re-frame keyword using "rename symbol" in VS Code + Calva, only the name part of the keyword is renamed, but not the namespace part.

**To Reproduce**
1. Right-click a keyword - `:hello/test`
2. Select Rename Symbol
3. Name it `:foo/bar`
4. See that it's renamed to `:hello/bar`

**Expected behavior**
I expect the keyword to be renamed to `:foo/bar`.

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
[Trace - 5:26:02 PM] Sending request 'textDocument/prepareRename - (53)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/brandon/development/clojure-test/src/core.clj"
    },
    "position": {
        "line": 33,
        "character": 9
    }
}

[Trace - 5:26:02 PM] Received response 'textDocument/prepareRename - (53)' in 13ms.
Result: {
    "start": {
        "line": 33,
        "character": 2
    },
    "end": {
        "line": 33,
        "character": 13
    }
}

[Trace - 5:26:02 PM] Sending request 'textDocument/hover - (54)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/brandon/development/clojure-test/src/core.clj"
    },
    "position": {
        "line": 35,
        "character": 22
    }
}

[Trace - 5:26:02 PM] Received response 'textDocument/hover - (54)' in 1ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```clojure\nis\n```\n\n----\n\n*[/Users/brandon/development/clojure-test/src/core.clj](file:///Users/brandon/development/clojure-test/src/core.clj)*"
    },
    "range": {
        "start": {
            "line": 35,
            "character": 22
        },
        "end": {
            "line": 35,
            "character": 25
        }
    }
}

[Trace - 5:26:07 PM] Sending request 'textDocument/rename - (55)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/brandon/development/clojure-test/src/core.clj"
    },
    "position": {
        "line": 33,
        "character": 9
    },
    "newName": ":foo/bar"
}

[Trace - 5:26:07 PM] Received response 'textDocument/rename - (55)' in 15ms.
Result: {
    "documentChanges": [
        {
            "textDocument": {
                "version": 16,
                "uri": "file:///Users/brandon/development/clojure-test/src/core.clj"
            },
            "edits": [
                {
                    "range": {
                        "start": {
                            "line": 33,
                            "character": 2
                        },
                        "end": {
                            "line": 33,
                            "character": 13
                        }
                    },
                    "newText": ":hello/bar"
                }
            ]
        }
    ]
}
</pre>
</details>

**User details (please complete the following information):**
 - OS: MacOS
 - Editor: VSCode (Calva) 😃 ❤️ 
 - Version: 2022.05.03-12.35.40 (from the Calva Says output)

**Comment by ericdallo** [comment]
I think that behavior was expected to avoid some critical renamings, but for specific simple namespace keywords, I don't see any issues allowing renaming that, fixed on master

**Comment by bpringe** [comment]
Thanks!
