### ISSUE TITLE
Expanding snippets within parentheses adds extra parentheses

### ISSUE THREAD

**Issue by ferdinand-beyer** [clojure-lsp/clojure-lsp#982]
**Describe the bug**
When expanding a snippet like `(comment` within parentheses, I end up with double parentheses:

```clojure
((comment
  |
  ))
```

**To Reproduce**
1. Type `(`
2. Start typing the name of a snippet, such as `comm`
3. Expand the snippet with Tab or Enter
4. Observe that the result is not valid

**Expected behavior**
Either I'd like Clojure-LSP to recognise that the parentheses already exist and not add extra ones, or that it does not try to expand snippets when in parentheses context.

**Screenshots**

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
ADD JSON HERE
</pre>
</details>

**User details (please complete the following information):**
 - OS: MacOS
 - Editor VSCode (Calva)
 - Version: Not sure (using Calva 2.0.274)

**Additional context**
[See this thread in `#calva` Clojurians Slack](https://clojurians.slack.com/archives/CBE668G4R/p1652719186038689)

**Comment by PEZ** [comment]
FYI, @ferdinand-beyer: The clojure-lsp version used by Calva is reported in the **Calva says** output channel in VS Code.

As of this writing the version is: `2022.05.03-12.35.40`

(It is not tied to the version of Calva being used. By default Calva uses the latest release.)
