### ISSUE TITLE
Build native image for Apple Silicon Macs (ARM / aarch64)

### ISSUE THREAD

**Issue by danielcompton** [clojure-lsp/clojure-lsp#986]
**Is your feature request related to a problem? Please describe.**

When using an Apple Silicon based Mac (M1 Mac), there is only an x86 native-image to use. This requires translation which is fast, but presumably a native-image for aarch64 would be faster still.

**Describe the solution you'd like**

Additional M1 Mac based build.

**Describe alternatives you've considered**

Keep using the current build.

**Additional context**

https://spring.io/blog/2022/03/23/building-native-images-with-graalvm-and-spring-native-on-apple-s-m1-architecture
https://github.com/oracle/graal/issues/2666#issuecomment-1074884020
https://github.com/babashka/babashka/wiki/Compiling-for-M1

It's not super clear to me quite what stage this is at yet, @borkdude has done some work on this for Babashka.

**Comment by ericdallo** [comment]
Thanks for the report!
If we find a quick way to make CI use the nightly graalvm build, we can make available on releases page, I'll take a look soon!

**Comment by borkdude** [comment]
@danielcompton 

> It's not super clear to me quite what stage this is at yet

No special work has to be done to compile for M1 other than downloading GraalVM for M1 here:

https://www.graalvm.org/downloads/

The wiki you linked to was made at the time when there was only a development GraalVM build for M1 but now there is a proper release. So you should be able to build any GraalVM native image for M1 now using the regular scripts.

Like @ericdallo says, the only thing we need now is a CI which lets us build for M1, to distribute a pre-built binary.

**Comment by ericdallo** [comment]
IIRC, @DeLaGuardo 's action [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/.github/workflows/release.yml#L99), can use a nightly build of graalvm, so it may work, I can test that soon

**Comment by borkdude** [comment]
@ericdallo There is no nightly build necessary anymore, I explained that in my previous message :).

**Comment by ericdallo** [comment]
Oh, right, so we need Github to support M1 right?

**Comment by borkdude** [comment]
yes:

> the only thing we need now is a CI which lets us build for M1

**Comment by borkdude** [comment]
@danielcompton What if the Clojure community (CT?) hired one of these machines:

https://www.hetzner.com/dedicated-rootserver/mac-mini-m1

so we could use it via self-hosted Github actions for a couple of projects? 

Not sure how easy it would be to configure this, but maybe worth a shot, until there are better alternatives?

**Comment by borkdude** [comment]
So here's another idea. You can install babashka for m1 via nix:

https://github.com/babashka/babashka#nix

But for people not using nix, we can maybe "borrow" the nix binary and re-distribute it via brew.

For this to work, you have to rewrite the dynamically linked C++ library location:

```
$ xattr -c ./bbnixm1
$ chmod +x ./bbnixm1
$ install_name_tool -change /nix/store/sg09c88mzmgrnb7n9xxpc6vp33i7m8mh-libcxx-11.1.0/lib/libc++.1.0.dylib /usr/lib/libc++.1.dylib  ./bbnixm1
$ codesign --force -s - ./bbnixm1
```

After these patches, the binary worked on my M1 system with all tests passing.

**Comment by borkdude** [comment]
It seems our problems will soon be over!

https://github.com/actions/runner/issues/805#issuecomment-1132097056

**Comment by borkdude** [comment]
Solved now.

If you upgrade via brew, it should now run natively on Apple Silicon.

The `install` script still needs to be updated though.

**Comment by ericdallo** [comment]
Thanks for the help!
I should work on the install script soon
