### ISSUE TITLE
function signatures in the Emacs minibuffer do not reflect cursor position or are misleading

### ISSUE THREAD

**Issue by genmeblog** [clojure-lsp/clojure-lsp#995]
**Describe the bug**
There is something odd with what is displayed in the Emacs minibuffer regarding to cursor position. Taking a Cider as a reference there should be (mostly) a current function signature.

Discussion on Slack: https://app.slack.com/client/T03RZGPFR/C099W16KZ

**To Reproduce**

- commented out LSP configuration in my [init.el](https://gist.github.com/genmeblog/fbec9d790ffd46aafdbf0cef7c69471d) (lines 315-327) open any clj file and call `cider-jack-in-clj`

Comments below describe minibuffer content:

```clojure
(map|) ;; map doc
(map |) ;; map doc
(map identity|) ;; map doc with `f` argument highlighted
(map identity |) ;; map doc with `coll` argument highlighted
(map identity (repeatedly|)) ;; repeatedly doc
(map identity (repeatedly 10|)) ;; repeatedly doc, first arg highlighted
(map identity (repeatedly 10 rand|)) ;; repeatedly doc, second arg highlighted
(map identity (repeatedly 10 rand)|) ;; map doc, second arg highlighted
(map identity|) ;; map doc with `f` argument highlighted (need to move a cursor left/right to have doc visible)
(map|) ;; as above
(|) ;; nothing
```

- LSP turned on

```clojure
(map|) ;; map doc
(map |) ;; map doc
(map identity|) ;; identity doc (?)
(map identity |) ;; identity doc (?)
(map identity (repeatedly|)) ;; repeatedly doc
(map identity (repeatedly 10|)) ;; repeatedly doc, no highlight
(map identity (repeatedly 10 rand|)) ;; rand doc (?)
(map identity (repeatedly 10 rand)|) ;; still rand doc (?)
(map identity|) ;; identity doc (?)
(map|) ;; map doc
(|) ;; map doc (?)
```

Additionally, when you repeat above a couple of times, below things happen sometimes:
- cider's doc appears, replaced by lsp (or not)
- corrected typo (eg. writing `identy` and corrected to `identity`) displays only symbol before correction (eg. `identy`)
- `map` -> `mapv` -> `map`, `mapv` docs persist
- when moving a cursor around existing code, docs is shown or not, eg:
    - `(let| [...])` - no `let` docs
	- `(let |[...])` - `let` docs is displayed
- other things like `(/ var 2.|7)` - `var` is displayed, depending what was visited by cursor

Seems like some caching issue, which is really visible after some time of coding and when heavy (and fast) editing is performed.

**Expected behavior**
Cider behavior as much as possible, ie. the doc context should be current sexp not current symbol

**User details (please complete the following information):**
 - OS: Ubuntu 22.04 on WSL2 (Windows 11)
 - Editor: Emacs 29.0.50 with native compilation (custom build), newest Cider
 - Version: clojure-lsp 2022.05.23-13.18.11, clj-kondo 2022.04.26-SNAPSHOT
 - init.el: https://gist.github.com/genmeblog/fbec9d790ffd46aafdbf0cef7c69471d

**Comment by ericdallo** [comment]
Last time I took a quick look on that issue it was not easy to understand exactly what was happening, but I think it was related with the hover request being sent before we process the changes of clj-kondo when a file is changed.
I'll take a look again on the weekend, thanks for the report

**Comment by ericdallo** [comment]
I think the main issue is that we walk backwards until we find a valid function/var, that's why we show docs about `identity` but not for `10` because it's not a valid var.
We should walk until we find the function being called I think, like `(map`
